Adding CUP button and CUP mode.
mixxxdj/mixxx pull request #1010
Opened 2016-09-13 22:15 UTC by williamlemus

https://bugs.launchpad.net/mixxx/+bug/1535468

The CUP mode has been added. It works the following way:

- Press, pause at the cue point
- release, play

It is available as a Cue mode, or as a button that can be learned.

This is a fixed version of PR https://github.com/mixxxdj/mixxx/pull/1001

2016-09-14 22:57 UTC, daschuer commented on src/engine/cuecontrol.cpp
> +		}
In the Block above, you have still tabs.

2016-09-14 22:58 UTC, daschuer commented on src/engine/cuecontrol.cpp
> +	} else {
Here is a tab as well

2016-09-14 23:02 UTC, daschuer requested changes
For now I have added only some style nits. The rest looks good to me.  
I will test this soon.

2016-09-15 19:42 UTC, williamlemus commented
I removed the tabs. Let me know if you find any issues testing!

2016-09-16 21:47 UTC, daschuer approved these changes

2016-09-16 22:08 UTC, daschuer commented
Works great, Thank you very much! LGTM,

For testing, I have used the CUP song: 
https://www.youtube.com/watch?v=yhECTE2-Oqc
:-D

2016-09-16 22:08 UTC, merged

2016-09-24 10:15 UTC, esbrandt commented
Thank for the feature.
May have found a bug with CUP mode when Quantization is enabled.

Stop the track and right-click on the PLAY button to place a cue point. Hit the CUE button. Playback starts on release.

Now enable Quantization, and again, stop the track and right-click on the PLAY button to place a cue point. Hit the CUE button. Nothing happens.

2016-10-02 00:29 UTC, williamlemus commented
How do I go about enabling Quantization? I want to try and reproduce it and see if I can fix it.

2016-10-02 08:57 UTC, esbrandt commented
> How do I go about enabling Quantization?

Click the ``Magnet`` icon in the decks button grid to enable quantization on a deck, see http://mixxx.org/manual/latest/chapters/user_interface.html#deck-options-button-grid