Support HotCue clear with Pad.
mixxxdj/mixxx pull request #10841
Opened 2022-08-30 09:21 UTC by doteya

push "Pad" in "CUES" mode, activate hotcue, and
push "Pad" holding "PAD MODE" in "CUES" mode, clear hotcue.

2022-08-30 09:31 UTC, doteya commented on res/controllers/Numark_DJ2GO2_Touch.midi.xml
> +      <control>
DJ2GO2/DJ2GO2 Touch does not support "shift" button, but send another control (control + 8) when push "Pad" holding "PAD MODE" in "CUES" mode.  
Other DJ software assigns it to clear hotcue.  
In other modes, holding "PAD MODE" is ignored. DJ2GO2/DJ2GO2 Touch sends same control holding "PAD MODE" or not.

2022-08-30 09:32 UTC, doteya commented on res/controllers/Numark_DJ2GO2_Touch_scripts.js
> +            input: function(channel, control, value, status, _group) {
If the received control is smaller than or equal to 8, send _activate to hotcue.
If the received control is greater than 8, send _clear to hotcue.

2022-08-30 09:41 UTC, ronso0 commented
Thank you for this contribution!
For your work to be included in Mixxx we need you to sign the contributor agreement:
Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allows Mixxx to include your changes.
Please give a headsup if you did so.

Updates/fixes to controller mappings that do not rely on new features should go to the current stable branch, which is `2.3` atm.
Please change the base branch here, rebase your branch locally and force-push.

In order to make CI happy (without too many fixup commits), please also set up `pre-commit` locally, see https://github.com/mixxxdj/mixxx/wiki/Using-git#set-up-automatic-code-checking

2022-08-30 11:13 UTC, Swiftb0y requested changes
Thanks for your contribution. Can you also take care of updating the manual with this new feature?

2022-08-30 11:13 UTC, Swiftb0y commented on res/controllers/Numark_DJ2GO2_Touch_scripts.js
> +                if (control <= 8) {
From your comment above
```suggestion 
                // DJ2GO2/DJ2GO2 Touch does not have a "shift" button, 
                // but when in CUES Pad Mode, holding the PAD MODE button will 
                // cause the controller to send messages where the originating midi
                // control is offset by 8.
                // this "feature" only applies to the CUES PAD MODE. Holding the button
                // in other modes does nothing.
                if (control <= 8) {
```

2022-08-30 19:33 UTC, doteya commented
Thank you for comments.

ronso0,

I sent my sign.
But I don't know the name is my account name or my real name.
I sent the sign of my real name and my account name with same mail address.

I have branced form 2.3, cherry-pick my commit and push force to my local repositry.

And DJ2Go is not compatible with DJ2Go2/DJ2Go2 Touch.
So I changed commit title DJ2Go to DJ2Go2.
DJ2Go2 and DJ2Go2 Touch are compatible.
Difference of them is "without Touch" or "with Touch" only.

Swiftb0y,

Thank you.

I will try to update manual.

I add comment.

2022-08-30 19:44 UTC, Swiftb0y commented
Thanks. If you take care of the manual, I'll can take care of the failing pre-commit hook before merging.

2022-08-30 21:24 UTC, ronso0 commented
> But I don't know the name is my account name or my real name.
> I sent the sign of my real name and my account name with same mail address.

Well, depends on with which name/nick you want to be mentioned in the contributor list in the About dialog and on the website? 
I'd simply delete the other one.

2022-08-30 21:45 UTC, doteya commented
> > But I don't know the name is my account name or my real name.
> > I sent the sign of my real name and my account name with same mail address.
> 
> Well, depends on with which name/nick you want to be mentioned in the contributor list in the About dialog and on the website? I'd simply delete the other one.

I want to use my account name 'doteya'.
Thank you.

2022-08-30 21:47 UTC, doteya commented
> Thanks. If you take care of the manual, I'll can take care of the failing pre-commit hook before merging.

I make PR for the manual.
https://github.com/mixxxdj/manual/pull/506

And I have fixed pre-commit code style issue.
I'm always using windows environment. I'm sorry late to setup the pre-commit chek environment.

2022-08-30 21:49 UTC, Swiftb0y commented
No Problem.
You seem to be proficient with git. Can you squash all the changes into a single commit and force push?

2022-08-30 21:59 UTC, doteya commented
> No Problem. You seem to be proficient with git. Can you squash all the changes into a single commit and force push?

I squash all commits in a single commit and push it.

2022-08-30 22:34 UTC, ronso0 commented
> I want to use my account name 'doteya'.

Done. Thank you!

2022-08-31 14:48 UTC, Swiftb0y approved these changes
LGTM. thank you very much.

2022-08-31 14:48 UTC, merged