PitchShiftEffect: add description comments
mixxxdj/mixxx pull request #10858
Opened 2022-09-02 07:08 UTC by davidchocholaty

This PR adds the comments, primarily for the usage
of the RubberBand API, for the Pitch shift effect processing.

2022-09-02 11:45 UTC, daschuer commented on src/effects/backends/builtin/pitchshifteffect.cpp
> +        // Set the RubberBand option for the formant preserving.
This comment just repeats the code.

2022-09-02 11:47 UTC, daschuer commented on src/effects/backends/builtin/pitchshifteffect.cpp
> +    // based on the current setting of the Range knob.
This comment does also not add any value. 
You may explain that one of from 0...X and the other from -x to +y ... and describe the implications.

2022-09-02 11:48 UTC, daschuer commented on src/effects/backends/builtin/pitchshifteffect.cpp
> +    // Calculate the result pitch setting for the RubberBand.
Here also no value. You may tell us why std::pow(2.0 is required.

2022-09-02 11:54 UTC, daschuer requested changes
I have left some comments.  Sorry if they look rude, that was not meant like that. 
I am happy about such Document PRs, Thank you.  

It is just, that I share the opinion that comments are only a last resort to explain difficult code parts in cases it was not possible to put the information into the code itself.

That helps that the reader does not waste time reading it and limit the risk that the code comment is rotting after refactoring.  

In this case, think about the pitfalls you have managed and write about them.

2022-09-02 13:30 UTC, davidchocholaty commented
Absolutely no problem, thank you very much for the advice and proposals. I will do it this way.

2022-09-04 11:21 UTC, daschuer approved these changes
Thank you for all the additional details :-)

2022-09-04 11:23 UTC, merged

2022-09-04 18:53 UTC, davidchocholaty commented
Thank you for merging. :+1: