Changelog: remove stray )
mixxxdj/mixxx pull request #10906
Opened 2022-09-18 11:12 UTC by daschuer

This should fix a build error with the manual: 
https://github.com/mixxxdj/manual/actions/runs/3072969204/jobs/4965120078

2022-09-18 11:15 UTC, daschuer commented
The annoying pre-commit issue will be solved after merging:
https://github.com/mixxxdj/mixxx/pull/10882

2022-09-18 11:17 UTC, daschuer commented
Th Ubunutu 22.4 failure is fixed after merging https://github.com/mixxxdj/mixxx/pull/10904

2022-09-18 21:39 UTC, ronso0 requested changes

2022-09-18 21:39 UTC, ronso0 commented on CHANGELOG.md
> +* LateNight: Add toggles to show loop and beatjump controls [#4713](<https://github.com/mixxxdj/mixxx/pull/>[#4713](https://github.com/mixxxdj/mixxx/pull/4713)
```suggestion
* LateNight: Add toggles to show loop and beatjump controls [#4713](https://github.com/mixxxdj/mixxx/pull/4713)
```
and metainfo.xml will be fixed automatically

2022-09-19 05:08 UTC, daschuer commented
Done

2022-09-19 11:55 UTC, ronso0 commented
Thank you!

2022-09-19 11:55 UTC, merged