Library Scanner: sort files before adding
mixxxdj/mixxx pull request #10919
Opened 2022-09-26 23:43 UTC by poelzi

Sort files in each scanned directory alphabetically before adding. This causes folders which contain track numbered files to be added in it's natural order, so sorting after date added also sorts for track numbers. Since the tracks will have slightly different timestamps, using a second sorting does not work.

2022-09-26 23:48 UTC, poelzi commented
An alternative aproach would be, to add a date(datetime_added) column to the temporary view and use this for sorting, but this would likely require larger changes.

2022-09-27 07:04 UTC, daschuer requested changes
Good idea. Just added some C++11 ideas.

2022-09-27 07:04 UTC, daschuer commented on src/library/scanner/recursivescandirectorytask.cpp
> +    for (auto it = children.begin(); it != children.end(); ++it) {
This can become a range based loop
```suggestion
    for (const auto& child : children) {
```

2022-09-27 07:04 UTC, daschuer commented on src/library/scanner/recursivescandirectorytask.cpp
> +    QFileInfoList children = dir.entryInfoList();
```suggestion
    const QFileInfoList children = dir.entryInfoList();
```

2022-09-30 05:45 UTC, daschuer approved these changes
LGTM, Thank you.

2022-09-30 05:45 UTC, merged