enable search in Browse & Recording views
mixxxdj/mixxx pull request #11014
Opened 2022-10-27 23:55 UTC by ronso0

This enables a simple text filter for the Browse-based features.
All columns are considered, incl. invisible.
Query is saved per feature only (not for individual folders).

closes #11012

2022-10-31 22:55 UTC, ronso0 commented
The last commit allows searching for individual words or quoted word groups.
Feels a bit like reinveting the wheel (sql column query) so this basic implementation is all I will do here.

2022-11-01 06:43 UTC, daschuer requested changes
Thank you for this first version. I have not yet tested it only some C++ suggestions.

How does the tokenizing compare to our normal search? I think it fails for things like "gimme gimme gimme" ... probably expected

2022-11-01 06:43 UTC, daschuer commented on src/library/proxytrackmodel.cpp
> +            m_currentSearch.trimmed());
We already trim above. Please re-use the result.

2022-11-01 06:43 UTC, daschuer commented on src/library/proxytrackmodel.cpp
> +    for (QString token : tokens) {
```suggestion
    for (const auto& token : std::as_const(tokens)) {
```
Not sure if std::as_const() is strictly required though...

2022-11-01 06:43 UTC, daschuer commented on src/library/proxytrackmodel.cpp
> +        while (iter.hasNext() && !tokenMatch) {
This can also become a range based loop with a break statement below for early abbort.

2022-11-01 19:54 UTC, ronso0 commented
> How does the tokenizing compare to our normal search? I think it fails for things like "gimme gimme gimme" ... probably expected

Sorry, I don't understand the question, it's the same tokenizer used by `WTrackTableView::onSearch` > `SearchQueryParser::queryIsLessSpecific`.
And I don't know how to compare the basic text filter here and the sql filter in [`BaseTrackCache::filterAndSort`](https://github.com/mixxxdj/mixxx/blob/963f2ce9fce08ea10d40cbbbd1a8ac82a82d0a52/src/library/basetrackcache.cpp#L457) performance-wise if that's what you mean.

2022-11-01 22:04 UTC, daschuer commented
Never mind, I have just tested it and it works like a charm. Thank you very much.

2022-11-01 22:04 UTC, daschuer approved these changes

2022-11-01 22:04 UTC, merged