Scalers: Replace the unneded flushing code with silence passing
mixxxdj/mixxx pull request #11152
Opened 2022-12-23 09:30 UTC by daschuer

This is a leftover form an earlier version of the engine, that is no longer needed. If this assumption is wrong the engine would have used old samples left in the buffer In. We now assert for this condition and clear the buffer if the assumption is wrong.

2022-12-23 09:32 UTC, daschuer commented
This does not fix a bug, but is a foundation for another pending bug with different offsets of different sound touch versions.

2023-03-17 14:38 UTC, daschuer commented on src/engine/bufferscalers/enginebufferscalelinear.cpp
>                      } else {
Yes

2023-03-17 14:45 UTC, daschuer commented on src/engine/bufferscalers/enginebufferscalelinear.cpp
>                      } else {
This seems to be a bug, because ++read_failed_count is applied before the check. So the condition will always false.

2023-03-19 10:10 UTC, daschuer commented
Done

2023-04-09 19:51 UTC, Swiftb0y commented
I'm sorry, I currently don't have the time to dig into the code enough to confidently reason about the changes. Someone else has to take over.

2023-05-16 11:09 UTC, ronso0 requested changes
Note this is not a code review, I just wanted to know if this PR maybe fixes #11381

2023-05-16 11:09 UTC, ronso0 commented on src/engine/bufferscalers/enginebufferscalelinear.cpp
> +                    m_bufferIntSize = getOutputSignal().samples2frames(samples_to_read);
for example 
> when moving a loop causes the play position to be moved along

samples_to_read may be odd and thus hit
https://github.com/mixxxdj/mixxx/blob/5f5cd28b3f8b471f5f2ca271e1ecacf8f2b1a659/src/audio/signalinfo.h#L40-L44

SampleUtil::roundPlayPosToFrameStart ?

2023-05-16 12:11 UTC, ronso0 commented on src/engine/bufferscalers/enginebufferscalelinear.cpp
> +                VERIFY_OR_DEBUG_ASSERT(m_bufferIntSize != 0) {
FYI if I remove this debug assert altogether, i.e. just continue, #11381 is fixed!

2023-05-16 12:15 UTC, ronso0 commented on src/engine/bufferscalers/enginebufferscalelinear.cpp
> +                    m_bufferIntSize = getOutputSignal().samples2frames(samples_to_read);
Tbh I don't understand why you used `samples2frames` here.
FWIW if I just do
```
if (m_bufferIntSize == 0) {
    // getNextSamples() must never fail,
    // using silence as a last resort
    SampleUtil::clear(m_bufferInt, samples_to_read);
    m_bufferIntSize = samples_to_read;
}
```
that's probably what you had in mind, but it causes #11381.

Though, if I remove this debug assert altogether, i.e. just continue, the loop move use case is covered and #11381 is fixed!

2023-05-16 19:05 UTC, ronso0 commented
I made cca23969b78 on top of this, which fixes #11381.

2023-05-25 09:31 UTC, ronso0 commented
> I made https://github.com/mixxxdj/mixxx/commit/cca23969b78c94f910ef70be86aa3dee645004e7 on top of this, which fixes https://github.com/mixxxdj/mixxx/issues/11381.

I polished that commit and opened https://github.com/daschuer/mixxx/pull/88
Please take a look.

2023-05-29 19:05 UTC, daschuer commented
It took me a while to find time to verify your findings. It looks very good now. Thank you. 
I think it is read to merge.

2023-05-30 09:11 UTC, ronso0 commented
Adjusting a comment faa1f6cfc2

2023-06-01 21:45 UTC, daschuer commented on src/engine/bufferscalers/enginebufferscalerubberband.cpp
> +                    deinterleaveAndProcess(m_buffer_back, iLenFramesRequired);
No break, because we nee to continue the loop until we have received all samples.

2023-06-01 21:47 UTC, daschuer commented
Done

2023-06-02 22:19 UTC, ronso0 commented
Code LGTM, no regressions spotted, test pass, a bug fixed.
If no one objects I'll merge this in a few days @mixxxdj/developers

2023-06-06 20:21 UTC, ronso0 commented
Alright then... Thanks @daschuer!

2023-06-06 20:21 UTC, merged