Set minimumWidth of th lable according to the maximum possible lable
mixxxdj/mixxx pull request #11194
Opened 2023-01-10 00:33 UTC by daschuer

This fixes the wiggling off the knob position during adjusting the value.

A regression caused by the switch between value and label.

2023-01-10 12:41 UTC, ronso0 requested changes
LGTM, thanks for the fixup!

Just a question, and please remove the debug output (--amend)

2023-01-10 12:41 UTC, ronso0 commented on src/widget/weffectparameternamebase.cpp
> +    setMinimumWidth(optimumWidth + 6);
Why +6 ?
I tested with Tango & LateNight and it looks good without it, even with crammed effect slots, +6 only shifts the 'elide' threshold a bit. Is that it?

2023-01-10 12:52 UTC, ronso0 commented
This screws up the label alignment in Tango and LateNight, though by looking at the Shade knobs xml I discovered how to simplify the Tango/LateNight knob templates.
fix: d639dad6fc

2023-01-16 00:06 UTC, daschuer commented
Re-implementing the sizeHint() Function did finally the trick. Please test again.

2023-02-02 18:36 UTC, ronso0 commented on src/widget/weffectparameternamebase.cpp
> +    m_widthHint = optimumWidth;
let's rename `optimumWidth` to `valueWidth` and 
```suggestion
    m_widthHint = math_max(
            valueWidth,
            metrics.size(0, m_text).width());
```
and remove the debug ouput below

2023-02-02 22:34 UTC, ronso0 commented
I guess the minimumSizeHint doesn't consider the padding.
If I remove the padding the label is static
```
           padding-left: 3px;
           padding-right: 3px;
```
https://github.com/mixxxdj/mixxx/pull/11194/files#diff-e1924755bc957e48039a69bcc6c083ed94ae7d4570ef7f317595d370fd3ba5fbR26-R27

However, this is what happens:
* start Mixxx with Shade, fx section is hidden, Graphic EQ is unit1, slot2
* show fx
![Screenshot_2023-02-02_23-30-18](https://user-images.githubusercontent.com/5934199/216464662-251b69cc-c7be-43a4-a6ba-5246326d558c.png)
* start to drag a parameter label, or reload the effect:
the entire knob container shrinks in width:
![Screenshot_2023-02-02_23-30-27](https://user-images.githubusercontent.com/5934199/216464786-08ff0e52-bb0b-4e0d-b42a-d7f6a491830d.png)

2023-02-03 00:43 UTC, ronso0 requested changes

2023-02-03 00:43 UTC, ronso0 commented on src/widget/wlabel.cpp
> +        QString elidedText = metrics.elidedText(m_longText, m_elideMode, width() - frameWidth());
```suggestion
        m_widthHint = metrics.size(0, m_longText).width() + 2 * frameWidth();
        QString elidedText = metrics.elidedText(m_longText, m_elideMode, width() - 2 * frameWidth());
```

2023-02-03 00:43 UTC, ronso0 commented on src/widget/wlabel.cpp
> +        QString elidedText = metrics.elidedText(m_longText, m_elideMode, width() - frameWidth());
I think that was it.
At least now the size doesn't change anymore...

Though I think we should try to figure why the label shrinks when parameters are swapped.

2023-02-03 16:02 UTC, ronso0 requested changes

2023-02-03 16:02 UTC, ronso0 commented on src/widget/weffectparameternamebase.cpp
> +    m_widthHint = optimumWidth;
let's rename `optimumWidth` to `valueWidth` and 
```suggestion
    int optimumWidth = math_max(
            valueWidth,
            metrics.size(0, m_text).width());
    m_widthHint = optimumWidth + 2 * frameWidth();
```
and remove the debug ouput below

2023-02-03 16:03 UTC, ronso0 commented on src/widget/weffectparameternamebase.cpp
> +    m_widthHint = optimumWidth;
with this the labels are okay, besides the fact that they are initially (before swapping parameters) expanded compared to 2.4

2023-02-04 18:20 UTC, daschuer commented
Thank you for the good testing. For me it is working now. Also after parameter swapping.

2023-02-06 00:35 UTC, ronso0 commented
Yes, it works now.

It's just that something 'broke' the initial view in Shade, compared to 2.4:
initial view:
![Screenshot_2023-02-06_01-18-38](https://user-images.githubusercontent.com/5934199/216855023-d46150b0-d534-4df2-8cfb-b1431da70c5d.png)
swapped parameters:
![Screenshot_2023-02-06_01-18-57](https://user-images.githubusercontent.com/5934199/216855045-9f70f527-f913-40fd-9fb7-8760763de949.png)

I this actually looks better, but users may be confused / disappointed by the condensed view after the swap.
Though tbh I don't care too much about it. Since the other skins still work great this is ready.
If you're motivated to debug this we can wait, otherwise I'll merge it. Just let me know how you prefer it.

2023-02-06 00:35 UTC, ronso0 approved these changes

2023-02-10 12:20 UTC, ronso0 commented
@daschuer Ignore this "good"/harmless regression, or investiagte once more?

2023-02-17 23:43 UTC, daschuer commented
Let's just merge this. It is IMHO good enough.

2023-02-17 23:46 UTC, merged