Fix a rounding issue is BpmControl::getBeatContext
mixxxdj/mixxx pull request #11263
Opened 2023-02-10 18:37 UTC by daschuer

This causes a DEBUG_ASSERT in Beats::iteratorFrom()

2023-02-10 20:38 UTC, JoergAtGithub requested changes

2023-02-10 20:38 UTC, JoergAtGithub commented on src/engine/controls/bpmcontrol.cpp
> +    // This original version has double precision issues (we kept it for documentation):
Instead of leaving the old code as comment, src/test/bpmcontrol_test.cpp should be extended by a testcase that detects the precision issue.

2023-02-11 11:00 UTC, daschuer commented
The test took me way more time than the fix because it was really hard to artificially trigger the asserts because it is really a LSB double issue. But OK now the test is in place.

2023-02-11 11:12 UTC, JoergAtGithub approved these changes
LGTM! Waiting for CI.

2023-02-11 11:44 UTC, merged

2023-02-11 11:45 UTC, JoergAtGithub commented
Thank you!