Mapping files for Hercules DJControl MIX
mixxxdj/mixxx pull request #11279
Opened 2023-02-15 18:08 UTC by DJPhatso

Based on Hercules DJControl Starlight mapping released with Mixxx v2.3.0: -Remapped LOOP and SAMPLER section according to DJControl MIX layout; -Added Master Volume and Headphone Volume; 
-Removed superfluous LED configuration (not present on DJControl MIX).

2023-02-15 18:31 UTC, JoergAtGithub commented
The Pre-Commit check fails. You can fix this by using pre-commit.patch artifact from the CI build:
git apply pre-commit.patch
or you install pre-commit locally on your system: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

2023-02-15 19:41 UTC, DJPhatso commented
>  You can fix this by using pre-commit.patch artifact from the CI build: git apply pre-commit.patch 

Not quite sure how to go about doing that.
Tried installing pre-commit locally, but it looks to be difficult with the workplace restrictions.

2023-02-15 19:44 UTC, JoergAtGithub commented
Than download this file:
![grafik](https://user-images.githubusercontent.com/64457745/219135938-a346a8c7-b086-410b-8564-5aadcc94edd3.png)
and execute
`git apply pre-commit.patch`

2023-02-15 20:18 UTC, DJPhatso commented
Done.

2023-02-15 22:27 UTC, JoergAtGithub commented
Please try again, this wasn't successful

2023-02-16 18:14 UTC, DJPhatso commented
I re-applied the patch. Now trying to resync to commit again, but that doesn't seem to work.

2023-02-24 19:18 UTC, JoergAtGithub commented
Please set up automaic code checking: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

2023-02-24 19:37 UTC, DJPhatso commented
As mentioned before, I tried these steps before, but I'm doing this on my work computer, and the admin restrictions are not allowing me to install everything properly. Planning on eventually starting anew on another personal pc, but this is not possible currently.

Is there any work around ? This seems complicated just to submit a mapping.

2023-03-06 20:35 UTC, JoergAtGithub commented
You don't need to install anything except git. Than download the `pre-commit.patch` from the failing GitHub build and call `git apply pre-commit.patch`

2023-03-06 20:46 UTC, DJPhatso commented
If that would have worked, we wouldn't be here...

I'm in the process of installing and configuring everything as best as I can on a Linux system, and use that only for submission, but that in itself is something I could do without ATM.

2023-03-29 22:13 UTC, Swiftb0y commented
Hey there @DJPhatso. Have you seen my PR https://github.com/DJPhatso/mixxx/pull/7 that fixes the pre-commit issues? If you merge that, we can start looking a more closer look at this PR. what do you think?

2023-08-08 19:48 UTC, DJPhatso commented
Just checking if this is in-line to be included in the next release or if there is anything left to do.

2023-08-13 08:21 UTC, JoergAtGithub commented
We need also the documentation page for the manual, see: https://github.com/mixxxdj/mixxx/wiki/Contributing-Mappings#user-content-documenting-the-mapping

2023-12-29 18:43 UTC, JoergAtGithub requested changes
Overall it's looking good, but I listed some minor findings, which should be corrected before merging this.

2023-12-29 18:43 UTC, JoergAtGithub commented on res/controllers/Hercules-DJControl-MIX-scripts.js
> +    };
```suggestion
    }
```
Please delete this semicolon

2023-12-29 18:43 UTC, JoergAtGithub commented on res/controllers/Hercules-DJControl-MIX-scripts.js
> +        // * Wiki: https://mixxx.org/wiki/doku.php/
```suggestion
```
Please delete this dead link

2024-01-03 19:37 UTC, JoergAtGithub approved these changes

2024-01-03 19:44 UTC, JoergAtGithub commented
LGTM! Thank you!

2024-01-03 19:45 UTC, merged

2024-01-17 21:39 UTC, daschuer commented
Hi @DJPhatso, thank you for your contribution.
It looks like we have missed to ask for your permission to distribute your code before merge. Can you catch that up, sign https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ and comment here when done? I will then put you the Mixxx 2.4 contributor list in the about box. May I use your real name?

2024-01-18 15:56 UTC, DJPhatso commented
Filled the form, and yes, you use my name.