Pioneer-DDJ-SB3: Fixes slip mode and adds missing knob controls
mixxxdj/mixxx pull request #11307
Opened 2023-02-25 20:18 UTC by llaver

The Pioneer DDJ SB3 controller script would crash on the dev snapshot and a number of knobs did not do anything so I have updated the script and midi file to fix those problems. They are detailed below, but please view individual commits to see each fix in isolation. This is my first contribution to the mixxx repo, my apologies if I missed anything. 

Note: please see the master gain and headGain section, there is some inconsistency there I would like to discuss with someone more familiar with the topic.

**Slip Mode**
> Invalid property name `slipEnabled`
 * Replaced all occurrences of `slipEnabled` with `slip_enabled`
 * Moved property declaration to `controlsToFunctions` 

**Invalid callback**
> A function was being called instead of passed as a callback
* Now passing function as a callback

**Master gain and headGain control**
> Knobs did nothing
Note: the [Mixxx manual](https://github.com/mixxxdj/manual/blob/main/source/hardware/controllers/pioneer_ddj_sb3.rst) for this controller states:
> This changes the master/headphones output level directly on the controller's audio interface. The MAIN/HEAD knob on the Mixxx UI will not change.
However, I have not found this to be the case. I have had trouble with the onboard sound card though, so I want to see if anyone else knows.
* Added `[Master] gain` and `[Master] headGain` MSB/LSB controls to the midi file

**Missing shifted FX Level knob control**
> FX Level Knob did nothing when pressing shift
Note: Different midino control values are sent when shifted, so a new `Pot` must be created
* Adds `shiftKnob` Pot using same knob value logic from the unshifted variant to set the Super Knob value
* Fixes midino control values for the shifted FX Level knob

2023-02-25 20:33 UTC, JoergAtGithub commented
Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

2023-02-25 20:36 UTC, llaver commented
Signed

2023-02-25 20:37 UTC, JoergAtGithub commented
This should PR should be merged to branch 2.3, not Main.

2023-02-25 20:38 UTC, llaver commented
Got it, I'll fix that.

2023-02-26 10:07 UTC, uklotzde commented
Both master and head level seem to be hardware controls that should not control the levels in the software:

https://www.virtualdj.com/manuals/hardware/pioneer/ddjsb3/layout/mixer.html

Otherwise the levels add up, which is probably unwanted.

2023-02-27 04:25 UTC, llaver commented
@uklotzde Have you tested this on the controller? This has not been the case for me. 

I will test more locally and see if I can get that to work. 

Aside from that, if you have Mixxx outputting through another output (External sound card for example) then the knobs will do nothing. This does not seem to be the desired behavior. Is there something that could be done to detect if outputting through the built in sound card or not?

2023-02-27 06:37 UTC, JoergAtGithub commented
@llaver Do Master and Headphone knobs change the volume, using the original mapping, where they are not mapped?

2023-02-27 11:54 UTC, uklotzde commented
> @uklotzde Have you tested this on the controller? This has not been the case for me.

I don't own this device. I was just curious to understand how it works.

2023-02-27 14:12 UTC, Swiftb0y commented
> Aside from that, if you have Mixxx outputting through another output (External sound card for example) then the knobs will do nothing. This does not seem to be the desired behavior. Is there something that could be done to detect if outputting through the built in sound card or not?

I think we should keep it as that. Simply stating in the manual that the knobs control the controllers built-in DAC will be easiest to understand for most users. If people output through another DAC, they should use the volume control on that. Adding conditional logic on detecting what output is used will not only be hard to implement but also hard to understand. "Critical" software such as Mixxx needs to be predictable, altering behavior conditionally invisibly will accomplish the opposite.

2023-02-27 14:55 UTC, Swiftb0y requested changes
Rest looks good, though we still need to resolve the hardware DAC volume issue.

2023-02-27 14:55 UTC, Swiftb0y commented on res/controllers/Pioneer-DDJ-SB3-scripts.js
> +        },
This is sufficient, the rest is already implement in the `components.Pot`
```suggestion
        inKey: "super1",
        group: eu.group
```

2023-03-01 05:04 UTC, llaver commented
I tested further and the Master/Headphone knobs do indeed control volume when outputting sound through the controller. 
They do not change the volume if outputting through any other sound card. I understand the reasoning though, and will remove those changes.

2025-02-05 18:47 UTC, acolombier commented
Do you still have interest in completing this work @llaver ? Looks like there is just that one change request from @Swiftb0y and we could merge this fix. As I understand, the DAC issue is unrelated to this change and can be addressed separately.

2025-02-05 22:32 UTC, llaver commented
My SB3 broke shortly after submitting this so I can no longer test on the controller. I will not be continuing development, but am happy to answer any questions to the best of my ability.

2025-02-06 00:52 UTC, acolombier commented
Ah this is a bummer, sorry to hear! @Swiftb0y do you think we can merge that with just the code suggestion you raised?

2025-02-06 14:49 UTC, Swiftb0y approved these changes
Yeah sure, if there turn out to be issues, someone else that has working device can address them.

2025-02-12 21:11 UTC, merged