Excluding ELAN touch screen
mixxxdj/mixxx pull request #11324
Opened 2023-03-03 16:29 UTC by acolombier

Excluding ELAN touch screen, which fits XPS 15 laptops.

This should also exclude other touch screens, but unfortunately, the ELAN device exposes other HID usages through vendor specific and reserved usage pages (`01ff`, `ff00` and `ff01`) so it cannot be excluded using the global rule. 

This fixes #11323.

2023-03-03 18:00 UTC, JoergAtGithub commented
Is this an USB HID device? If it's an I2C HID or SPI HID device, we could also filter by bus type. Than all internal laptop devices would be hidden.
The bus type information is new in hidapi 0.13.0 https://github.com/libusb/hidapi/releases/tag/hidapi-0.13.0 and would require an update of hidapi in the ./lib folder first.

2023-03-03 18:10 UTC, acolombier commented
This particular device doesn't seem to be an USB HID, so this would work too.
Happy to give the update a spin and see how much work it would need to work if you think we should go this way instead.

2023-03-03 18:13 UTC, JoergAtGithub commented
This would be additional, because your change covers also the case of an HID touchpads on USB keyboards etc.

2023-03-04 11:49 UTC, JoergAtGithub requested changes

2023-03-04 11:49 UTC, JoergAtGithub commented on src/controllers/hid/hidenumerator.cpp
> +        if (device_info.product_id && device_info.product_id != denylisted.product_id) {
```suggestion
        if (denylisted.product_id && device_info.product_id != denylisted.product_id) {
```

2023-03-04 11:56 UTC, JoergAtGithub commented
An HID touchpad/screen could be mapped for effects control like here: https://youtu.be/vVfmMevmxxs?t=99
But maybe this is not of practical relevance.

2023-03-06 18:11 UTC, acolombier commented
I have added an other exclusion for Logitech G Pro mouse which also appears to be detected as a valid controller unfortunately. The reason behind this is that this mouse expose bunch of other HID interface which can be use to tweak the mouse setting (colors, DPIs) as well as accessing status (battery level)

2 cents thought as this issue likely impact many other devices - could we have a whitelist instead of a blacklist? This whitelist could be a little bit more flexible (e.g no devices are shown by default if not present on distributed whitelist -> user is able to to bypass the whitelist and select their device from the list of all HID device -> whitelist gets updated so next user find their device right away)

2023-03-25 20:03 UTC, JoergAtGithub commented
I head a second thought about it. When we have a controller with touch input, it should most likely mapped to a future QML instance which renders the screen content and not to the normal HID mapping. Therefore it fits to ignore the usage touch here.

2023-03-25 20:07 UTC, merged

2023-03-25 20:07 UTC, JoergAtGithub commented
Thank you!