fullscreen: rebuild & reconnect menu only on desktops with global menu
mixxxdj/mixxx pull request #11350
Opened 2023-03-09 22:20 UTC by ronso0

follow-up for #11328:
keep the menubar on all Linux desktops that **don't** use global menubars to avoid pointless operations.

2023-03-12 09:46 UTC, daschuer commented
For my understanding Qt::AA_DontUseNativeMenuBar is always false.
 
This change has been introduced in Qt 5.7.1 (Ubuntu Bionic has 5.9): 
https://github.com/qt/qtbase/commit/8cd28ea8850c5365c47dd65de16f528e2e223835

According to the comment we can check whether the menu bar is already non-native before chaining to full screen using MenuBar::isNativeMenuBar().

2023-03-12 09:49 UTC, daschuer requested changes
Is there a Linux distro that has no native menu bar (DBus)? 
If not we can just close this?

2023-03-12 21:51 UTC, ronso0 commented
Oh, you got me there, I didn't investigat thoroughly.

What I'm after is actually the unchangeable 'supports global menu' property, like `qt5ct` reports it when Mixxx is started.
I changed the approach and adopted the way `qt5ct` detects it:
https://github.com/desktop-app/qt5ct/blob/9f60cd2352a4dcc55c8ca267f29bd8fff5c6a659/src/qt5ct-qtplugin/qt5ctplatformtheme.cpp#L102-L105
```
QDBusConnection conn = QDBusConnection::sessionBus();
m_dbusGlobalMenuAvailable = conn.interface()->isServiceRegistered("com.canonical.AppMenu.Registrar");
qCDebug(lqt5ct) << "D-Bus global menu:" << (m_dbusGlobalMenuAvailable ? "yes" : "no");
```
Is this okay in your opinion?

2023-03-12 22:35 UTC, daschuer commented on src/mixxx.cpp
> +    return conn.interface()->isServiceRegistered("com.canonical.AppMenu.Registrar");
The Qt Implementation has also a null check. 
https://github.com/qt/qtbase/blob/6e2963200642fa0171b247cb986726ca124795b0/src/gui/platform/unix/qgenericunixthemes.cpp#L108

2023-03-12 22:42 UTC, daschuer commented on src/mixxx.cpp
> +    return conn.interface()->isServiceRegistered("com.canonical.AppMenu.Registrar");
For completeness you may also check the QT_NO_DBUS macro.

2023-03-12 22:43 UTC, daschuer commented
> Is this okay in your opinion? 

Yes.

2023-03-13 00:08 UTC, ronso0 commented
Yep, implemented as you suggested. Thanks for you help!

2023-03-13 10:47 UTC, daschuer approved these changes
LGTM, Thank you.

2023-03-13 10:47 UTC, merged