Add 2.4.5 changes to CHANGELOG.md
mixxxdj/mixxx pull request #11403
Opened 2023-03-23 23:43 UTC by daschuer

This is a first step towards a 2.3.5 release.
Due to some regressions in 2.3.4, we should release it soon. 

The milestone can be watched here:
https://github.com/mixxxdj/mixxx/milestone/39

This is the link to the pending 2.3 PRs: 
https://github.com/mixxxdj/mixxx/pulls?q=is%3Apr+is%3Aopen+base%3A2.3

2023-04-02 21:38 UTC, ronso0 requested changes
Thank you!

I proposed some small improvements.
Would you mind sticking to the one-line style we used previously? Like
`AutoDJ: fix horrible crash [#1098] [#1024]`
and use the multiple-lines list only if there's a significant amount of PRs for a certain topic/issue?
Trailing dots are also not neessary IMHO

2023-04-02 21:38 UTC, ronso0 commented on CHANGELOG.md
> +* Playlist export: Fix chained file extensions after changing the playlist type.
```suggestion
* Playlist export: Adopt new extension after changing the playlist type
```

2023-04-02 21:38 UTC, ronso0 commented on CHANGELOG.md
> +  since [#11162](https://github.com/mixxxdj/mixxx/pull/11162).
```suggestion
* Fix empty waveform overview after loading a track (Mixxx 2.3.4 regression)
```

2023-04-06 08:46 UTC, ronso0 commented
LGTM. What do you think about

> Would you mind sticking to the one-line style we used previously? Like
AutoDJ: fix horrible crash [#1098] [#1024]
and use the multiple-lines list only if there's a significant amount of PRs for a certain topic/issue?
Trailing dots are also not neessary IMHO

2023-04-06 11:35 UTC, daschuer commented
A, the rendered version is just one line and scales with the available space. So it should be Ok. 

For the source I like to follow the habit to break around 80 columns to have an easy review.

2023-04-06 14:29 UTC, daschuer commented
Here: https://github.com/mixxxdj/mixxx/blob/7fa38b05cd0a4138ee21744c1673af159163d1ec/CHANGELOG.md

Oh I fergot that many users will read it as txt. 
In that case we need a reasonable line length. Can we draft a rule for that?

2023-04-06 14:33 UTC, Swiftb0y commented
shouldn't be hard to enforce. We're currently disabling it anyways.

https://github.com/mixxxdj/mixxx/blob/45eb0bbddf02187c8ac591bc646680874bf0e822/.markdownlint-cli2.yaml#L18-L20

2023-04-06 15:00 UTC, ronso0 commented
Oh the changelog.md, of course. I was referring to the metainfo.xml
Anyway, done. Thanks!

2023-04-06 15:00 UTC, merged

2023-04-06 15:23 UTC, Swiftb0y commented
Ah sorry, should've payed closer attention, I assumed you mean the markdown file in the context of being viewed by texteditors. I don't think we have much control over how the contents of the metainfo.xml will be displayed anyways.