Windows buildenv: Fix 7-Zip quoting
mixxxdj/mixxx pull request #11510
Opened 2023-04-25 17:46 UTC by fwcd

Due to quoting, the `7z` invocation ended up being expanded as

```
""7z.exe"" x -o"C:\Users\<user>\git\mixxx\buildenv" "C:\Users\<user>\git\mixxx\buildenv\mixxx-deps-2.4-x64-windows-db02b82.zip"
```

which led to 'command not found' errors while running the script. This fixes the quoting by stripping one level of quotes around `7z.exe` and moving `-o` into quotes too (otherwise [PowerShell will complain](https://stackoverflow.com/questions/66162957/7zip-in-powershell-keeps-saying-too-long-switch-or-too-short-switch))

2023-04-25 18:27 UTC, Swiftb0y commented
The CI seems to pass, so no regressions there I guess, but I don't understand under which circumstances this breaks since it didn't break on CI afaik.

2023-04-25 18:31 UTC, fwcd commented
Perhaps CI doesn't use the 7-zip extractor, so it never went down that code path?

2023-04-25 18:50 UTC, JoergAtGithub commented
This needs to be tested with cmd.exe and Powershell. And especially with "x64 Native Tools Command Prompt for VS 2019" which is required by our Readme.md.

2023-04-25 18:54 UTC, fwcd commented
I agree, though this is arguably unrelated to the Visual Studio tools since this is just about the 7-Zip invocation. Since it's a Batchfile, it shouldn't make a difference since the script will execute in `cmd.exe` anyway (at least that is my understanding).

2023-04-25 20:38 UTC, daschuer commented
How about simplify the script by using: 
```
cmake -E tar xzf ...
```
This can handle zip files and is mandatory anyway. So we don't need to probe for any other unzip tool.

2023-04-26 00:10 UTC, fwcd commented
Done

2023-04-26 02:21 UTC, JoergAtGithub commented
The different ZIP tools are probed for performance reasons. There are several minutes difference in unzipping with Windows buildin ZIP tool and 7Zip. The Powershell version is somewhere inbetween, but not available in any Powershell version. Removing this requires benchmarking the CMake version against 7Zip.

2023-04-26 08:38 UTC, fwcd commented
Perhaps we should then fix the quoting issue first, so people can use the 7z extractor again, and move the CMake version to a separate PR where it can be tested more extensively?

2023-04-27 18:16 UTC, JoergAtGithub commented
This does not work for me:
![grafik](https://user-images.githubusercontent.com/64457745/234955500-5bc2c400-1b1d-4788-aea4-14eaf35ef84e.png)

2023-05-01 02:15 UTC, fwcd commented
Since we probably want to take our time to get the CMake extraction right, especially to make sure that we don't regress on performance, I've moved it to #11524 for further discussion.

I have also retargeted this PR to 2.4 and reset it to the original fix, so users can at least use the 7-Zip extractor again (which is broken in its current state).

2023-05-01 08:59 UTC, JoergAtGithub requested changes
Unfortunately, this doesn't work for me. The default path for 7z `C:\Program Files\7-Zip\7z.exe` contains a space, which is only considered, if the path is in quotes:
![grafik](https://user-images.githubusercontent.com/64457745/235432145-174e9de1-691d-44c2-abd9-e5b0a2f2e4b8.png)

2023-05-01 09:05 UTC, JoergAtGithub commented
Could you give us more details, with which setup the original issue occured?

2023-05-02 01:49 UTC, fwcd commented
Ah I think the issue is that we get different levels of quoting depending on whether `7z` is on the user's PATH:

https://github.com/mixxxdj/mixxx/blob/1dfd1dc85d78d9d7ee53a09d91a3b526db5076f4/tools/windows_buildenv.bat#L117-L124

On my dev machine that's the case, which is likely why we got different results. Batch files aren't 'smart' about their quotes (like in Unix shell scripts), making this easy to overlook.

2023-05-07 21:43 UTC, fwcd commented
I've updated `DETECT_SEVENZIP` to use consistent quoting. @JoergAtGithub, could you check whether that fixes the issue for you?

2023-05-08 19:20 UTC, JoergAtGithub commented
This works for me now. Tested with:
-7z started by double click from Explorer
-Powershell by double click from Explorer
-7z started from "x64 Native Tools Command Prompt for VS 2022" 

The later failed during bitsadmin download, but this is unrelated to this change.
Also unrelated is the Clazy fail in CI.

Thank you!

2023-05-08 19:20 UTC, merged