Changelog for 2.3.6
mixxxdj/mixxx pull request #11633
Opened 2023-06-06 21:00 UTC by daschuer

2023-06-06 22:56 UTC, ronso0 requested changes

2023-06-06 22:56 UTC, ronso0 commented on CHANGELOG.md
> +* No longer stopping a track with an active loop at the very end.
```suggestion
* No longer stop a track with an active loop at the very end.
```

2023-06-06 22:56 UTC, ronso0 commented on CHANGELOG.md
> +* Fixed resyncing when beat-jumping in an active loop
```suggestion
* Fixed resyncing when moving an active loop
```

2023-06-07 19:21 UTC, daschuer commented
Done

2023-06-08 06:25 UTC, ronso0 commented
Thank you!

2023-06-08 06:25 UTC, merged