Scroll bar position fix
mixxxdj/mixxx pull request #1169
Opened 2017-02-03 11:20 UTC by dodler

Fixed scroll bar position via adding map for keeping values of scroll bar for different models.

2017-02-03 11:23 UTC, dodler commented
https://bugs.launchpad.net/mixxx/+bug/1450391

Bug on launchpad.

2017-02-03 15:36 UTC, Be-ing commented
I tried to test and got a compile error:
```
src/widget/wanalysislibrarytableview.cpp: In constructor ‘WAnalysisLibraryTableView::WAnalysisLibraryTableView(QWidget*, UserSettingsPointer, TrackCollection*)’:
src/widget/wanalysislibrarytableview.cpp:7:86: error: no matching function for call to ‘WTrackTableView::WTrackTableView(QWidget*&, UserSettingsPointer&, TrackCollection*&, QString)’
         : WTrackTableView(parent, pConfig, pTrackCollection, QString::number(qrand())) {
                                                                                      ^
In file included from src/widget/wanalysislibrarytableview.h:7:0,
                 from src/widget/wanalysislibrarytableview.cpp:2:
src/widget/wtracktableview.h:30:5: note: candidate: WTrackTableView::WTrackTableView(QWidget*, UserSettingsPointer, TrackCollection*, bool)
     WTrackTableView(QWidget* parent, UserSettingsPointer pConfig,
     ^~~~~~~~~~~~~~~
src/widget/wtracktableview.h:30:5: note:   no known conversion for argument 4 from ‘QString’ to ‘bool’
scons: *** [lin64_build/widget/wanalysislibrarytableview.o] Error 1
scons: building terminated because of errors.
```

2017-02-05 19:44 UTC, uklotzde commented on src/widget/wlibrarytableview.cpp
> +    //loadVScrollBarPosState();
Don't comment out code. Either delete or keep it. The next one reading this code will not know why it has been commented out and why it is still here.

2017-02-05 19:47 UTC, uklotzde commented on src/widget/wtracktableview.cpp
> +        newModelAddr = reinterpret_cast<unsigned long>(trackModel);
This is extremely dangerous code. And it is not portable. You don't even check if a unsigned long has the same size as a pointer.

2017-02-05 19:48 UTC, uklotzde commented on src/widget/wtracktableview.cpp
> +    //restoreVScrollBarPos();
Again, what does this comment try to explain? ;)

2017-02-05 19:53 UTC, uklotzde commented on src/widget/wlibrarytableview.h
> +    QMap<QString, int> m_vScrollBarPosValues;
Why do you use QString instead of TrackModel* as your key? Pointers are valid key values.

2017-02-05 20:17 UTC, Be-ing commented
This works when I switch between track tables and when I enter a search query then clear it, but when I switch to one of the placeholders that are shown when a library feature is selected by itself (like clicking the "Crates" header without clicking a specific crate) the scroll bar position is lost.

2017-02-05 20:56 UTC, Be-ing commented
Thanks for taking care of this long standing issue. :)

2017-02-06 06:40 UTC, dodler commented on src/widget/wlibrarytableview.h
> +    QMap<QString, int> m_vScrollBarPosValues;
I'm quite new to C++, so I wasn't sure about that. Initially I wanted to in that way. I can still change it if needed.

2017-03-23 14:49 UTC, Be-ing commented
@dodler do you think you'll be able to address the issues in the above comments soon? I'd like to have this fix in 2.1. Even if the position still gets lost when viewing one of the feature placeholder panels, this is still a good improvement.

2017-03-24 16:04 UTC, dodler commented
@Be-ing yes, I will try to handle it next week.

2017-03-29 15:41 UTC, Be-ing commented
@uklotzde, ready for merge?

2017-04-05 15:33 UTC, daschuer commented
There are some change requests pending.

2017-06-02 04:05 UTC, Be-ing commented
Hi @dodler, could you finish this PR?

2017-06-05 11:42 UTC, dodler commented
Close it? I thought there are some things that should be validated. If not I'm ready.

2017-06-05 22:04 UTC, daschuer requested changes
@dodler here some comments. There are also some pending commenst of @uklotzde. 
Are you able to do the requested changes? If not, ask for help. 
Thank you very much.

2017-06-05 22:04 UTC, daschuer commented on src/widget/wlibrarytableview.cpp
> +        verticalScrollBar()->setValue(m_vScrollBarPosValues[key]);
this is a double map lookup. use find() and check for end() like here: 
https://github.com/mixxxdj/mixxx/blob/a944d1f224788e8efb41ad41bd487210766ddb11/src/control/control.cpp#L88

2017-06-05 22:06 UTC, daschuer commented
Or did you just forget to "git push"

2017-06-07 07:04 UTC, dodler commented
Okay, I'll finish it asap

2017-11-18 19:01 UTC, foss- commented
@dodler Just thought this would be a useful improvement and @Be-ing pointed me to this PR. Any chance of finishing the requested changes? daschur asked to ask if help is needed.

Just a friendly ping for this PR and if you are still on this.

2017-11-20 14:01 UTC, dodler commented
@foss- 
Hi, 
I've done some changes.

2017-11-27 05:45 UTC, Be-ing commented
It looks like review comments have been addressed other than commenting out some debugging output. @uklotzde and/or @daschuer could you take another look at this?

2017-12-03 22:29 UTC, daschuer commented
@dodler: I would like to merge this soon, any chance to comment the debug lines as requested? 

We need also your permission, please sign 
https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done. 

Thank you very much

2017-12-04 05:15 UTC, dodler commented
@daschuer 
done

2017-12-04 22:07 UTC, daschuer approved these changes

2017-12-04 22:08 UTC, daschuer commented
Thank you very much. It works nicely now. LGTM

2017-12-04 22:08 UTC, merged

2017-12-04 22:20 UTC, daschuer commented
I like to add you to the contributor list in the about box inside Mixxx.
Which name and which character encoding do you like? Normally we use our real names there.

2017-12-05 09:07 UTC, dodler commented
Artyom Lyan
any encoding