WTrackProperty: show simple editor on delayed double-click
mixxxdj/mixxx pull request #11755
Opened 2023-07-22 12:05 UTC by ronso0

show a simple QLineEdit after selected-click (delayed double click) onto track property labels

a coffee break project to help with my tag editing workflow (quick in-deck tag editing), i.e. create a fast alternative to double-click -> Track Properties -> click desired property line edit -> edit  -> hit Apply:

- [ ] styles for line edit
- [ ] use timer, reset 'selected' state automatically
- [ ] visual feedback for 'selected' state (while widget expects second click)

Gonna share this early, but Draft until it's polished.
Quick alternative

2023-07-25 21:50 UTC, ronso0 commented
I'll probably keep polishing this, but it has already proven useful & usable in real life.

2023-07-26 20:52 UTC, ronso0 commented
This is very inviting, I edit and tag my tracks much more often now, and more spontaneously than before, when editing was rather clunky with Track Info or with the library.
(#11764 definitely helps, but this is way easier. )

Need to fix:
It's confusing that everytime an editor is closed the searchbar is focused. It should be the (library) widget that had focus before. Sending focus to tracks table is likely desired in the majority of cases, or a true re-focus.

2023-08-16 12:34 UTC, ronso0 commented
Ready to roll!

There's a new tr string for the respective tooltip.

2023-09-20 10:13 UTC, ronso0 commented
I added a workaround a Qt bug that became obvious with the new `hover` styles:
`hover` gets stuck when the track menu is opened which is kind of irritating. The hover state can only be reset by hovering the widget again after closing the menu.

Workaround is to post a QLeaveEvent when the menu is shown.

2023-10-15 23:07 UTC, ronso0 commented
rebased onto main

2023-10-20 08:27 UTC, ronso0 commented
> I added a workaround a Qt bug that became obvious with the new `hover` styles: `hover` gets stuck when the track menu is opened which is kind of irritating. The hover state can only be reset by hovering the widget again after closing the menu.
> 
> Workaround is to post a QLeaveEvent when the menu is shown.
> 
> Need to test whether this is still required with Qt6.

Yes, it is.

I also improved some comments. Ready for review.

2023-12-25 19:27 UTC, ronso0 commented
this is now based on #12004

2024-03-29 13:40 UTC, ronso0 commented
This works great, except: clicking outside the editor ('blank' area) doesn't close it. 
Related: https://github.com/mixxxdj/mixxx/issues/12966#issuecomment-1997106667)

2024-03-31 15:05 UTC, ronso0 commented
Very strange: after rebasing (main with new drag'n'drop threshold) hovering a WTrackProperty initiates a drag. THOUGH this is not caused by c++ changes but by qss selector `WTrackProperty:hover`.
🤷

2024-04-01 21:18 UTC, daschuer requested changes
Works good. I have only two minor comments

2024-04-01 21:18 UTC, daschuer commented on src/widget/wtrackproperty.cpp
> +constexpr int selectedClickTimeout = 2000;
```suggestion
constexpr int kSelectedClickTimeoutMs = 2000;
```

2024-04-01 21:18 UTC, daschuer commented on src/widget/wtrackproperty.cpp
> +        m_pSelectedClickTimer = new QTimer(this);
This can also become a parented pointer.

2024-04-02 19:48 UTC, daschuer approved these changes
LGTM, Thank you.

2024-04-02 23:47 UTC, ronso0 commented
I squashed the fixup.

2024-04-03 09:43 UTC, merged

2024-04-03 09:43 UTC, daschuer commented
Thank you.

2024-04-03 09:56 UTC, ronso0 commented
Wooohoo :tada: 
Thanks for reviewing @daschuer

2024-04-16 08:14 UTC, ronso0 commented
Review after having used this for a few months:
quite often I expected the editor to open after the first click (select), probably due to the hover effect.
I'll check if I can make it act on first click and while leaving drag'n'drop as is.