Update changelog for Mixxx 2.3.6
mixxxdj/mixxx pull request #11784
Opened 2023-08-03 06:20 UTC by daschuer

2023-08-03 11:02 UTC, Swiftb0y requested changes

2023-08-03 11:02 UTC, Swiftb0y commented on CHANGELOG.md
> +  [#11751](https://github.com/mixxxdj/mixxx/pull/11751)
```suggestion
* Protobuf: Fixed building with v23.4
  [#11751](https://github.com/mixxxdj/mixxx/pull/11751)
```

2023-08-03 17:40 UTC, daschuer commented
Fixed and integrated latest merge.

The 2.3.6 release and "closing" of the 2.3 branch is a prerequisite for a 2.4 release.

I think we should follow a deadline driven, but "no regression" strategy. 
From that point of view 
Theses Issues are blocking the release:
https://github.com/mixxxdj/mixxx/issues/11545
https://github.com/mixxxdj/mixxx/issues/11785

There are some more PRs targeted the 2.3 branch, nice to have but they can go to 2.4.1 in favor of not stretching the deadline. 

Does that sound reasonable? 

(Will cosponsor that on Zulip)

2023-08-05 21:13 UTC, Holzhaus commented on CHANGELOG.md
> +* Handle setting loop_in and loop_out at the same position
```suggestion
* Handle setting `loop_in` and `loop_out` to the same position
```

2023-08-05 21:13 UTC, Holzhaus commented on CHANGELOG.md
> +* Fixed build issues with Protobuf v23.4 and with clang 32
I think the other points are in present tense
```suggestion
* Fix build issues with Protobuf v23.4 and with clang 32
```

2023-08-06 05:26 UTC, daschuer commented
Done.

2023-08-06 10:18 UTC, Holzhaus commented on CHANGELOG.md
> +* Disable GL VU-Meters on windows by default. They can be re-enabled via the command line option: `--enableVuMeterGL`.
```suggestion
* Disable GL VU-Meters on Windows by default. They can be re-enabled via the command line option `--enableVuMeterGL`.
```

2023-08-06 10:18 UTC, Holzhaus commented on CHANGELOG.md
> +* Library preferences: Uncheck serato metadata export when file metadata export is unchecked
```suggestion
* Library preferences: Uncheck Serato metadata export when file metadata export is unchecked
```

2023-08-06 21:59 UTC, daschuer commented
Done + new entry recently merged.

2023-08-07 09:05 UTC, Holzhaus approved these changes
LGTM, thanks.

2023-08-07 11:38 UTC, Swiftb0y approved these changes
LGTM thank you for the PR and for the review

2023-08-07 11:38 UTC, merged