Fix for randomly not loaded CoverArt in Spinnies
mixxxdj/mixxx pull request #11827
Opened 2023-08-13 20:01 UTC by JoergAtGithub

Im not sure if this fix is the appropriated solution, but it fixes the issue #11131 for me. 
The problem is, that the requestor of cached CoverArt is not always WSpinnyBase - it can also be WCoverArt.

2023-08-13 21:28 UTC, daschuer requested changes
Every widget is running it's own request, because of size constrains. 
There must be a race-codition that the cover is not requested of the responds is lost. 
Is WSpinnyBase::slotTrackCoverArtUpdated always called?

2023-08-13 21:37 UTC, JoergAtGithub commented
I set a breakpoint in `WSpinnyBase::slotTrackCoverArtUpdated()` and it's was never called.

2023-08-13 22:33 UTC, ronso0 commented
I agree with daschuer, now the spinny will receive signals meant for other widgets, so it will receive more unneeded updates.

@JoergAtGithub You found out https://github.com/mixxxdj/mixxx/issues/11131#issuecomment-1676401662
> The following function is executed three times, when a track is loaded into a deck. The first two times pixmap is alway NULL and it returns early. The third call differs in failure case, when the Coverart is not loaded, pixmap is NULL as well.
> 
> https://github.com/mixxxdj/mixxx/blob/4a51c393eb8820a5728f4b2b53dce8ef203d2b8c/src/widget/wspinnybase.cpp#L377-L386

I wonder why it's called 3 times in the first place.

2023-08-24 19:49 UTC, JoergAtGithub commented
Unfortunately this bug is not fixed by #11840

2023-08-24 19:51 UTC, ronso0 commented
Sorry, I confused it with the slip indicator bug.

2023-09-06 05:51 UTC, closed without merging

2023-09-06 05:51 UTC, JoergAtGithub commented
Closing this PR - I agree, that this is not the correct fix for this bug.