CMakeLists: Always default `CMAKE_BUILD_TYPE` to `RelWithDebInfo`
mixxxdj/mixxx pull request #11952
Opened 2023-09-09 14:19 UTC by fwcd

As discussed in https://github.com/mixxxdj/mixxx/pull/11871#issuecomment-1694760590, we should default to release builds on all platforms since debug builds of Qt (especially Qt 6) are too slow even for development. Currently this is only done on Windows.

cc @daschuer

2023-09-09 19:18 UTC, Swiftb0y commented
From what I can tell, this only sets build mode of mixxx to release, the build mode of Qt is decided by the packager (which is us in the case of vcpkg, but not on linux)...

2023-09-09 19:55 UTC, fwcd commented
True, though at least for the platforms where vcpkg is used, it would be convenient to have a reasonable default. IMO #11871 would be nice-to-have too, but that might be a rather specialized use-case (mixing debug Mixxx with release Qt)

2023-09-09 20:22 UTC, Swiftb0y commented
I'm not an expert, but IMO using a release version of a library (especially if its big and slow in debug as Qt) with a debug version of the application is not that uncommon...

2023-09-10 01:09 UTC, fwcd commented
Yeah, that's why I advocated for #11871 (and still do). This PR was mostly due to @daschuer's suggestion that we should default to release builds for everything. `RelWithDebInfo` should cover the debug symbols too.

2023-10-12 09:06 UTC, daschuer requested changes
What is the goal for this change? On Linux it works good because the system libraries are optimized and Mixxx is optimized in Debug as well. This means that contributors have debug assertions and so one enabled by default. 

Is there a risk that package maintainer has a .git folder?  

We may adjust our concept a bit, but we need a clear picture what we want to achieve. 

What is puzzling me current is also build time. 
https://github.com/mixxxdj/mixxx/issues/12081

With the default configuration I am now suffering almost full build time after switching branches. I have a workaround, but casual contributors wont even know that there is an option to reduce build time after branch switching by a magnitude.

2023-12-03 22:59 UTC, fwcd commented
I will close this for now. Building Mixxx itself in debug mode is not really the issue, using debug builds of Qt is. Since we plan on shipping release-only build environments (see #12370) that would make it easy to build debug Mixxx with release Qt, there should not really be a need for building everything in release mode.

2023-12-03 22:59 UTC, closed without merging