add Rate Tap button
mixxxdj/mixxx pull request #12104
Opened 2023-10-14 11:33 UTC by ronso0

and replace BPM tap button (BPM display overlay).

quoting myself from #12086
> Admittedly, I never understood why this a track edit tool [BPM tap button] was placed in the rate control section in the first place.

> double-clicking any track (text) label opens the Track Properties editor where the (track) BPM can be set (type or tap)
Use case

Reasoning
BPM tap edits a track property (permanently) while the rate section is solely about controlling the playback speed (+, -, sync). Hence, IMO BPM tap doesn't belong there.
IIUC the intention for putting it there was to allow _setting_ the track BPM, i.e. set initial value or correct BPM analysis. I assume it was helpful in the early days of Mixxx but with the improved beats analyzer nowadays I suppose it's not needed (that much) anymore. Manual correction can be done in Track Properties > BPM tab.

My use case
Infrequently I need to "Sync" to external players (vinyl via Aux, other DJ in b2b sessions), i.e. at least estimate the target BPM. Until now I was using a Python BPM counter [1], activated with a global hotkey, which gives very accurate results. However, it'd be much more convenient to do this within Mixxx.
Either I apply the guessed target BPM (e.g. 128) to loaded tracks, or I do a bpm search `bpm:125-130`.
Rate Tap is a good step forward.

- 1 https://github.com/m13253/bpm-counter/blob/master/trunk/bpm-counter.py

2023-10-14 21:44 UTC, deejay-girl commented
Where can we download nightly build of Mixxx?
The 2.6 alpha development version on the website is never updated so for me it's impossible to test the latest changes :(
I can't compile Mixxx myself.

2023-10-14 21:54 UTC, ronso0 commented
Getting alpha builds and testing Pull Requests is described on the wiki
https://github.com/mixxxdj/mixxx/wiki/Testing

2023-10-14 23:16 UTC, ronso0 commented
Very weird: I built this locally and it works as expected.
Though, it was built with Qt5 because I forgot to set the Qt6 switch.
So with Qt6 [`slotUpdateRateSlider(double bpm)`](https://github.com/mixxxdj/mixxx/blob/0c2faf06a89e5aca14d1aa7df8e90f9c5b50c69c/src/engine/controls/bpmcontrol.cpp#L939) is not called when BPM are tapped, even though it should
https://github.com/mixxxdj/mixxx/blob/0c2faf06a89e5aca14d1aa7df8e90f9c5b50c69c/src/engine/controls/bpmcontrol.cpp#L101-L111

When I change `bpm` from dev tools it works, it just doesn't when `bpm` is set in `slotRateTapFilter` :shrug: 
It also works if I make `bpm` read-only and use `connectValueChangeRequest` and copy all required calls there.

Also, I have no idea why unrelated tests fail n all OS except ARM 64, for example https://github.com/mixxxdj/mixxx/actions/runs/6517384471/job/17707390983?pr=12104

I'd appreciate if someone could give me some hints what's wrong here.

2023-10-15 20:48 UTC, ronso0 commented
I pushed a different (working) version with my findings added inline.

2023-11-02 13:54 UTC, ronso0 commented
> Very weird: I built this locally and it works as expected. Though, it was built with Qt5 because I forgot to set the Qt6 switch. So with Qt6 [`slotUpdateRateSlider(double bpm)`](https://github.com/mixxxdj/mixxx/blob/0c2faf06a89e5aca14d1aa7df8e90f9c5b50c69c/src/engine/controls/bpmcontrol.cpp#L939) is not called when BPM are tapped, even though it should
...

Seems this is a known issue? Just stumbled upon https://github.com/mixxxdj/mixxx/blob/558253682acc5c07452f829209fefca91bd8ba8b/src/broadcast/broadcastmanager.cpp#L71-L78
Still wondering why the comment was written for Qt5 whereas it worked here with Qt5 and fails with Qt6 :shrug: 
I changed it to call the slot manually.

2023-11-02 13:55 UTC, ronso0 commented
I changed all skin buttons to tap the tempo on left click and tap the BPM on right click.

2023-11-03 16:46 UTC, ronso0 commented
I changed it to `tempo_tap` to make it more clear what it does.

Ready to roll!

2023-12-02 20:59 UTC, ronso0 commented on src/engine/controls/bpmcontrol.h
> +    std::unique_ptr<ControlProxy> m_pReverseButton;
note: can be PollingControlProxy

2024-02-18 23:25 UTC, fwcd commented
> I assume it was helpful in the early days of Mixxx but with the improved beats analyzer nowadays I suppose it's not needed (that much) anymore

I use the BPM tap pretty frequently on tracks where the analyzer still struggles (acapellas or tracks with complex polyrhythms, e.g. Salsa music). Would appreciate to at least keep the option to keep having BPM tap available in the UI, having to dig into the track properties makes this too inconvenient to really be useful IMHO.

2024-02-18 23:37 UTC, ronso0 commented
> Moving the BPM tap to the beatgrid editing sections seems reasonable too, to untangle the BPM editing controls from rate changing.

Good idea!
Feasible in Tango and LateNight, not so nice in Deere but the BPM control section is already interfering anyway with the track dsiplays.

> perhaps a switch in the skin settings to toggle left/right-click behavior?

Hmm, the skin settings menu is growing and growing, in LateNight we already had to squeeze so it fits at minimum height.
At some point we need to wrap it into a WScrollable #3890 (still unused in official skins)

2024-02-19 07:46 UTC, daschuer commented
Can you move the first commit to a separate PR? 
This way we see here better the proposed functional changes.

2024-02-19 08:10 UTC, ronso0 commented
Why not view by commit?

2024-05-08 06:09 UTC, daschuer commented
Now a conflict has developed.

2024-05-08 09:29 UTC, ronso0 commented
> > Moving the BPM tap to the beatgrid editing sections seems reasonable too, to untangle the BPM editing controls from rate changing.

Just filed a feature request to track this.

> > perhaps a switch in the skin settings to toggle left/right-click behavior?
> 
> Hmm, the skin settings menu is growing and growing, in LateNight we already had to squeeze so it fits at minimum height. At some point we need to wrap it into a WScrollable #3890 (still unused in official skins)

I'll look into this during beta.

2024-05-08 09:29 UTC, ronso0 commented
Conflicts are resolved.

2024-05-14 18:37 UTC, daschuer commented
Now the unit-test are failing.

2024-05-14 18:50 UTC, daschuer requested changes

2024-05-14 18:50 UTC, daschuer commented on src/engine/controls/bpmcontrol.cpp
> -    m_pBpmLock->connectValueChangeRequest(
because of this change m_pBpmLock is left null and crashes when used in trackBpmLockChanged

2024-05-14 18:51 UTC, daschuer commented
Oh sorry, and new conflicts have developed.

2024-05-14 23:26 UTC, ronso0 commented
> Oh sorry, and new conflicts have developed.

Yeah, a lot has happend in BpmControl since I started this.
I rebased and it looks & works good now, let's see what CI says.

2024-05-14 23:36 UTC, ronso0 commented
small TODO:
highlight the tap button also on right-click. Not sure how to do that, though.

2024-05-16 13:35 UTC, Swiftb0y approved these changes
Only nitpick. rest LGTM

2024-05-16 13:35 UTC, Swiftb0y commented on src/engine/controls/bpmcontrol.cpp
please update the name `value` to reflect the fact that its now the `rate`.

2024-05-20 13:05 UTC, daschuer approved these changes

2024-05-20 13:05 UTC, daschuer commented
Thank you.

2024-05-20 13:05 UTC, merged