Addes the test SoftTakeoverTest.CatchOutOfBounds
mixxxdj/mixxx pull request #12114
Opened 2023-10-15 05:50 UTC by daschuer

This proves that the slider is able to snap an out of bounds position. 
https://github.com/mixxxdj/mixxx/issues/12011

2023-10-15 20:23 UTC, ronso0 requested changes
Just typos for now, I'll take a closer look during the next week.

2023-10-15 20:23 UTC, ronso0 commented on src/test/softtakeover_test.cpp
> +    // actions in the same edirection shall be ignored
here and below
```suggestion
    // actions in the same direction shall be ignored
```

2023-11-11 19:03 UTC, daschuer commented
Done

2023-11-12 21:15 UTC, ronso0 approved these changes
LGTM, thanks!

2023-11-12 21:15 UTC, merged