avoid overlapping marks
mixxxdj/mixxx pull request #12273
Opened 2023-11-08 09:33 UTC by m0dB

draw overlapping marks at increasing/decreasing y position in the waveform viewer

TODO: i haven't figured out yet how to get signalled when the loop mark changes. moving/adding/removing any of the other marks updates the y position as expected.

2023-11-08 12:26 UTC, ronso0 commented
> TODO: i haven't figured out yet how to get signalled when the loop mark changes.

What about `WaveformMarkSet::connectSamplePositionChanged`?

2023-11-08 12:32 UTC, Swiftb0y commented
The ideas in this PR are pretty good (I like the priority concept) but I feel like just stacking marks with the exact same sampleposition on top of each other is not the best solution. For example, cues set carelessly and without quantize might have slightly different samplepositions, but are still essentially on top of each other. Also, the labels of different cues still fight with each other as well (as seen in your screenshot). If instead comparing cues by sampleposition, we just avoided the collision of the boxes in general, the special cases where markers are on top of each other or very near would be solved automatically. How feasible do you think this is?

2023-11-08 22:28 UTC, m0dB commented
Certainly feasible, definitely more complicated to implement, and potentially resulting in undesired situations with markers jumping up and down when changing the zoom level.

In any case, I would only consider doing that after a more thorough refactoring of the related code. With the current code, these are minor changes that bring a very noticable improvement. My proposal is to start here and implement further improvements like you are suggestion down the road.

2023-11-09 06:13 UTC, Swiftb0y commented
Sounds good as well, let me know when this PR is ready.

2023-11-15 17:58 UTC, ywwg commented
I agree this is a good first start, and that in the longer term a generalized box-avoidance solution is preferable.  I think it's ok if things move around as the zoom changes, that's like a web page reflowing when the size changes.

2023-11-16 01:33 UTC, m0dB commented
> > TODO: i haven't figured out yet how to get signalled when the loop mark changes.
> 
> What about `WaveformMarkSet::connectSamplePositionChanged`?

Yes, I am using this, and this works for all markers excepts for the loop markers.

2023-11-18 11:35 UTC, m0dB commented
> > TODO: i haven't figured out yet how to get signalled when the loop mark changes.
> 
> What about `WaveformMarkSet::connectSamplePositionChanged`?

Works like a charm!

I have reduced code duplication between the legacy and allshader waveformmarkrenderer.cpp (with a shared intermediate baseclass) and everything is working as expected, so this is now ready for review.

2023-11-19 20:32 UTC, ronso0 commented
When I build this I get 
```
/src/waveform/renderers/allshader/waveformrendermark.cpp: In member function ‘void allshader::WaveformRenderMark::drawMark(const QRectF&, QColor)’:
/src/waveform/renderers/allshader/waveformrendermark.cpp:118:5: error: ‘getRgbF’ was not declared in this scope
  118 |     getRgbF(color, &r, &g, &b, &a);
      |     ^~~~~~~

```
I reconfigured to make sure precompiled headers are off, though same reasult.

2023-11-20 07:00 UTC, JoergAtGithub commented
On Windows it builds - and works as intended!

2023-11-20 10:00 UTC, ronso0 commented on src/waveform/renderers/allshader/waveformrendermark.cpp
> -#include "util/colorcomponents.h"
It builds when I restore this include

2023-11-20 10:53 UTC, ronso0 commented on src/waveform/renderers/allshader/waveformrendermark.cpp
> -#include "util/colorcomponents.h"
This is on Ubuntu 20.04, and it seems this and #12303 slip through because we don't have a 20.04 runner anymore even though we support it?

2023-11-20 12:34 UTC, ronso0 commented
It works as desired, thanks.

Though there's a small UX issue with the hover threshold:
* create two cues in one place (1 +5)
* hover 1: is highlighted
* move slightly to the left: while the pointer is technically still above [1] the mark line is hovered and highlights [5]
* move slightly to the right: now the pointer is definitely above [1] but [5] remains highlighted
![Screenshot_2023-11-20_11-22-30](https://github.com/mixxxdj/mixxx/assets/5934199/1857cf72-fe84-46a0-a41c-78a5d3ef38b8)

I doub't anyone would do this while the waveform is moving, so there is no real (live) performance problem, also the cues are ultimately in the same place, but with a hotcue and a loop cue this might result in some confusion.
Anyhow, with 2.4 this situation would much more unclear, so it's not a real issue.

2023-11-26 10:37 UTC, m0dB commented
@ronso0 I added the missing include and I slightly improved the hovering detection. It is still not idea, but certainly better, and good enough for now. I think that with these last changes this PR is ready for merge.

2023-11-27 00:32 UTC, ywwg commented
> I feel like just stacking marks with the exact same sampleposition on top of each other is not the best solution.

It think even if this is not the best solution, it's an improvement and does not go down a road that would be hard to reverse.  I am in favor of merging this for 2.4

2023-11-28 02:02 UTC, ronso0 commented
> @ronso0 I added the missing include and I slightly improved the hovering detection. It is still not perfect, but certainly better, and good enough for now. I think that with these last changes this PR is ready for merge.

Okay, great! I'll test this soonish, but I'll the code review to others ;) I'm still no good at fully understanding / judging class inheritance, ownership, basic oop rules ..

2023-11-28 21:00 UTC, daschuer requested changes
Thank you for the PR. 
Here some code and comment improvement comments.

2023-11-30 00:47 UTC, ronso0 commented
> @ronso0 I added the missing include and I slightly improved the hovering detection. It is still not perfect, but certainly better, and good enough for now.

Indeed its much better now! Thanks!

2023-12-08 21:36 UTC, m0dB commented on src/waveform/renderers/waveformmark.cpp
> +    return m_linePosition >= point.x() - lineHoverPadding &&
done

2023-12-08 21:38 UTC, m0dB commented on src/waveform/renderers/waveformmark.cpp
> +        point = QPoint(point.y(), static_cast<int>(m_breadth) - point.x());
The terminology used elsewhere is length & breadth, instead of width & height, and for a good reason. I leave a comment.

2023-12-08 21:41 UTC, m0dB commented on src/waveform/renderers/waveformmark.cpp
> +    const MarkerGeometry markerGeometry(label, useIcon, m_align, m_breadth, m_level);
done

2023-12-08 21:47 UTC, m0dB commented on src/waveform/renderers/waveformmark.h
> +    int m_level;
done

2023-12-08 21:48 UTC, m0dB commented on src/waveform/renderers/waveformmark.h
> +        Graphics() {
done

2023-12-08 21:50 UTC, m0dB commented on src/waveform/renderers/allshader/waveformrendermark.cpp
> +    updateMarkImages();
yes, to indicate that the image has to be regenerated. I leave a comment.

2023-12-08 21:53 UTC, m0dB commented on src/waveform/renderers/waveformrendermarkbase.cpp
> +    for (auto& pMark : m_marks) {
done

2023-12-08 21:55 UTC, m0dB commented on src/waveform/renderers/waveformmarkset.cpp
> +        if (pMark->getSamplePosition() != prevSamplePosition) {
> do we need to consider a certain distance here?

Ideally yes, but that goes beyond this PR. This deals only with marks set at quantised positions, which IMO covers the primary use case.

2023-12-08 21:56 UTC, m0dB commented on src/waveform/renderers/waveformmarkset.cpp
> +        if (pMark->getSamplePosition() != prevSamplePosition) {
> Which values of https://doc.qt.io/qt-6/qt.html#AlignmentFlag-enumf are considered?

I'll leave a comment

2023-12-08 22:00 UTC, m0dB commented on src/waveform/renderers/waveformrendermarkbase.cpp
> +        WaveformWidgetRenderer* waveformWidgetRenderer,
done

2023-12-08 22:03 UTC, m0dB commented
Sorry for the delay, @daschuer , this fell of my radar (I was convinced it was already merged). I addressed all your comments.

2023-12-18 17:03 UTC, daschuer approved these changes

2023-12-18 17:56 UTC, JoergAtGithub commented
Ok, let's merge this! Thank you!

2023-12-18 17:56 UTC, merged

2024-01-02 18:39 UTC, fwcd commented
Hm, after playing with this I've encountered a number of cases where it makes the waveform harder to read.

There are a lot of tracks where the main cue overlaps with the intro marker and thus obscures the waveform (at least when viewed at a small-ish height):

<p><img width="193" alt="Screenshot 2024-01-02 at 18 51 05" src="https://github.com/mixxxdj/mixxx/assets/30873659/8dad94ad-069f-4ab4-8dc9-f85c5f054c96"></p>

<p><img width="198" alt="Screenshot 2024-01-02 at 18 54 04" src="https://github.com/mixxxdj/mixxx/assets/30873659/828f922d-fe0b-4530-8bf2-d69d05264a1f"></p>

Any ideas?

2024-01-02 18:53 UTC, m0dB commented
Yeah, that is really very small, I never do that, as my eyesight is quite bad 😅 

Do you really mean "the amplitude of the waveform", or do you mean the height of the waveform viewer? I think the first is a bad idea, the second might work and should be easy to implement. Like limiting the total space occupied by the markers from either top or bottom to a third of the total height. In your example that would mean (almost) fully overlapping I guess. Alternatively we could scale the markers to a smaller size. I guess that if you are okay with staring at small waveforms you are also okay with staring at small markers ;-)

2024-01-02 19:01 UTC, JoergAtGithub commented
Why not scale the markers below a certain height limit - e.g. no marker must be higher than 20% of the waveform viewer height.
Another approach would be transparenc, but I fear, that can impact readability.

BTW: The feature itself helped me removing saved loop from Serato, where I wasn't ware of before, because hotcues/loops >8 have no pads.

2024-01-02 19:02 UTC, fwcd commented
> Yeah, that is really very small, I never do that

On laptops where screen real estate is limited, it's quite useful to have small waveforms IMO, especially when browsing the library and even more when playing with 4 decks.

> Do you really mean "the amplitude of the waveform", or do you mean the height of the waveform viewer?

I was thinking of the actual waveform, though admittedly that might be too complex to implement/might have surprising semantics e.g. when adjusting gain etc.

> Like limiting the total space occupied by the markers from either top or bottom to a third of the total height.

I like that idea!

> In your example that would mean (almost) fully overlapping I guess

Yeah, I guess that would be hard to avoid, though I think it would be fine if they overlap like in previous versions in that case. Ideally perhaps even in a deterministic order (i.e. always rendering the CUE marker above the intro/outro markers)

> Alternatively we could scale the markers to a smaller size. I guess that if you are okay with staring at small waveforms you are also okay with staring at small markers

Interesting idea, though I'd probably still consider overlapping markers the best tradeoff for readability.

2024-01-02 19:08 UTC, fwcd commented
> Why not scale the markers below a certain height limit - e.g. no marker must be higher than 20% of the waveform viewer height.

I feel like scaling the markers non-uniformly could potentially look a bit off. But perhaps we could just make the marker scale configurable?

In any case, we should make sure that the default works well.

2024-01-02 23:17 UTC, m0dB commented
How about this? (and let's move the conversation there) https://github.com/mixxxdj/mixxx/pull/12501