Fix/gh12369
mixxxdj/mixxx pull request #12401
Opened 2023-12-05 21:27 UTC by Swiftb0y

Based on #12400. Alternative to #12396. Fixes #12384. Fixes #12369 apart from https://github.com/mixxxdj/mixxx/issues/12369#issuecomment-1835700452.

@ywwg can you take a quick look at the changes to the Reloop-Beatpad script? I did some refactorings that seemed sensible, but you probably know the code better than me.

I'd highly appreciate if anyone that still has access to any of these controllers can give these changes a quick test and see if they broke anything in their respective mappings.

2023-12-05 21:41 UTC, Swiftb0y commented
yikes, still suffering from eslint issues, though this time they're valid and only related to the actually changed lines. I think we should ignore those for now too since some of them just require too many changes (eg renaming an entire controller because its named `DeFOrmEd_SnakE_CAsE`)...

2023-12-06 00:18 UTC, Swiftb0y commented
I wouldn't mind but I don't have any. I went through it manually. My initial regex attempts failed, this was faster and gave me more confidence that I'm not accidentally breaking anything.

2023-12-07 00:48 UTC, ywwg commented
> @ywwg can you take a quick look at the changes to the Reloop-Beatpad script? I did some refactorings that seemed sensible, but you probably know the code better than me.

hmm I don't actually know that code.  I used to maintain the Hercules DJControls so I know those better and those look fine.

2023-12-07 16:33 UTC, JoergAtGithub requested changes
The code change itself is as far as I can see correct ES7 code, that should work.
But unfortunatly, we are not only in the JavaScript domain here. We evaluate the code from the C++ domain and I doubt, that an arrow function can resolves 'this' correct.
I think we should not merge this code unless we have a working unit test for each of these pattern:
-beginTimer with arrow-function
-beginTimer with external function name
-beginTimer with function() {}.bind(this)
-beginTimer with function body in exclamation marks

The last might fail, but I think it is fixable, because we pass it as string in https://github.com/mixxxdj/mixxx/blob/dabca58d22a45e71500e1f141826c4017287ca7e/src/controllers/scripting/legacy/controllerscriptinterfacelegacy.cpp#L472-L473 anyway.

2023-12-07 16:34 UTC, JoergAtGithub commented
BTW: I wonder if this `this` bug is related: https://doc.qt.io/qt-6/qtqml-cppintegration-exposecppattributes.html#c-methods-and-the-this-object

2023-12-07 18:38 UTC, Swiftb0y commented
>  But unfortunatly, we are not only in the JavaScript domain here. We evaluate the code from the C++ domain and I doubt, that an arrow function can resolves 'this' correct.

Can you elaborate? I don't understand your concern. 

>  I think we should not merge this code unless we have a working unit test for each of these pattern:

I'll see how feasible it is to implement those. I don't know how testable our JS Api is. 

> BTW: I wonder if this this bug is related:

Yes, but its QML- and Qt6-only and requires an even bigger API change, so I ruled it out as a potential solution.

2023-12-07 19:04 UTC, JoergAtGithub commented
> > But unfortunatly, we are not only in the JavaScript domain here. We evaluate the code from the C++ domain and I doubt, that an arrow function can resolves 'this' correct.
> 
> Can you elaborate? I don't understand your concern.

I have some code that looks like this:
```
class MyClass {
    constructor() {
         this.myVar = 1;
    }
    buttonHandler(field) {
         this.shiftPressedTimer = engine.beginTimer(200, ()=> {
              this.myVar = 0;
        }, true);
    }
}
```
and the timer code never sets the member var of the class.

But what works is:
```
class MyClass {
    constructor() {
         this.myVar = 1;
    }
    buttonHandler(field) {
         this.shiftPressedTimer = engine.beginTimer(200, function() {
              this.myVar = 0;
        }.bind(this), true);
    }
}
```

This lead me think, that the arrow function doesn't get the relation to it's parent JS class.

But honestly I'm not sure about this.

2023-12-07 20:00 UTC, Swiftb0y commented
> The example I posted above is taken from a real mapping, that doesn't work with arrow function.

which one exactly? I'll look into it.

> Maybe I'm thinking to simple, but I thought removing exclamation marks around a code snippet to evaluate, should be an easy regex before 

Yes, of course the most robust solution would be to not pass as a string. That's why this PR eliminates that for all mappings we have. But we can't do anything about mappings that have not been contributed. The arrow function on the C++ side is there because otherwise the code was evaluated immediately instead of after the timer, which is obviously a bug.

2023-12-07 20:05 UTC, JoergAtGithub commented
> > The example I posted above is taken from a real mapping, that doesn't work with arrow function.
> 
> which one exactly? I'll look into it.

A version of my Z2 mapping under development: https://github.com/mixxxdj/mixxx/blob/8796b3cc5145f399daed76ae6870215bbcf0567f/res/controllers/Traktor-Kontrol-Z2-hid-scripts.js#L1396-L1405

2023-12-07 21:08 UTC, Swiftb0y commented
I don't have access to a Z2, so I can't test this in context of your mapping. I created a little QJSEngine playground outside of Qt, but I can't reproduce the issue there. I'll try reproducing it in Mixxx.

2023-12-07 21:21 UTC, Swiftb0y commented
Can't even reproduce within mixxx with a test script. Please double check your mapping then. I don't know what the culprit could be.

2023-12-08 03:19 UTC, ywwg commented
this is hard to test on the Traktor S3 because a bunch of other controlobjects are broken, some of which should be fixed by #12208 but others need to be fixed too.

2023-12-08 03:25 UTC, ywwg commented
(https://github.com/mixxxdj/mixxx/pull/12409

2023-12-08 14:01 UTC, Swiftb0y commented
Testing the mappings is not a requirement IMO. the only thing that worries me slightly is the issue reported by @JoergAtGithub previously. Speaking of which, if you can still reproduce the issue, what Qt version is this on? I'm compiling with 5.15.11, maybe yours is older?

2023-12-08 17:46 UTC, Swiftb0y commented
Yup, I remember that PR, but I think it would make more sense to try to integrate [Qt Quick test](https://doc.qt.io/qt-6/qtquicktest-index.html) into our current test runner instead (which would allow us to test Qt quick and by extension Qml and Js code on its own).

2023-12-08 19:17 UTC, Swiftb0y commented
I agree, your concerns are valid. I'm quite short on time due to university, so if you want to do me a favor and get this merged, I would really appreciate if you could take care of the unit test implementation.

2023-12-11 19:46 UTC, ywwg commented
This is not the first time we have to choose between "PR without test" or "No PR" -- if this were a merge to main then I'd feel better about just getting it in. 

Lacking a test, what I'd prefer to do is only fix those mappings that we know have problems, and save the mass search-and-replace for `main`. That way we have less risk of breaking the imminent release.

2023-12-11 21:12 UTC, ronso0 commented
We could also only fix those mappings where the pattern matches the mappings that were reported to be broken (and fixed by this), namely the DDJ-SB3 and Mixtrack Pro 3, #12384 and #12369, and merge the rest to main.
Didn't check what would be left then x)

2023-12-16 16:19 UTC, JoergAtGithub approved these changes
I created testcases for engine.beginTimer myself in #12437 and all tested code pattern work as intended.
o.t.: I couldn't reproduce the issue, that I see with my Z2 mapping with these testcase. So there might still be a latent error in the code of the beginTimer implementation.

2023-12-16 16:20 UTC, merged

2023-12-16 16:20 UTC, JoergAtGithub commented
Thank you!

2023-12-17 08:49 UTC, Swiftb0y commented
Thank you.