Skins: add `skins:` path alias
mixxxdj/mixxx pull request #12463
Opened 2023-12-23 23:58 UTC by ronso0

This fixes an inconvenience noticed by @mxmilkiib in https://github.com/mixxxdj/mixxx/issues/10123#issuecomment-1859008968

If you want to mod a skin that uses template urls like `skin:../Deere/some_template.xml` by copying it to the user skins directory and rename it so it's easy to identify in the skins combobox, this would break the template url scheme (requiring to alter all template urls to fix).

This PR adds the system skins directory as `skins` to the QDir searchpaths for all `src` attributes. For the plain `LaunchImageStyle` string `skins:[skin name]` is resolved to the actual path.
Now it's possible to locate templates via `src="skins:Deere/some_template.xml`, which in turn simplifies the process of creating simple skin mods:
* create user skin directory **LateNight (bright waveforms)**
* copy/paste only `skin.xml` and adjust the waveform color variables for example
* (loads all templates and stylesheets from original LateNight)
* (benefit from all LateNight updates, except those in skin.xml)

The other commits adjust Deere, LateNight and Tango to use `skins:`, and simplifies the 64-sampler templates a bit.

2023-12-24 14:54 UTC, daschuer commented on src/skin/legacy/legacyskinparser.cpp
> +    // don't because unfirtunatey there is no reliable way to apply equivalent
```suggestion
    // don't because unfortunately there is no reliable way to apply equivalent
```

2023-12-24 14:55 UTC, daschuer requested changes
Just a typo, the rest LGTM Thank you.

2023-12-27 00:10 UTC, JoergAtGithub commented
LGTM and works on my Windows11 system as before! Thank you!

2023-12-27 00:10 UTC, merged

2023-12-27 00:15 UTC, ronso0 commented
Thanks for testing this!

2023-12-28 17:56 UTC, Russe commented
I don't get this to run with a modded skin. Is there any further description how to use this feature?
What do I need to do when I want to change LateNight toolbar.xml only?

These are my steps trying to get a modded skin to run:
- create user skin folder "LateNight (Test)" at .mixxx/skins/
- copy toolbar.xml from /usr/share/mixxx/skins/LateNight to .mixxx/skins/LateNight (Test)/
- change some content of this copied toolbar.xml
- restart Mixxx and choose skin "LateNight (Test)"

Now the "original" skin will be loaded instead my adapted toolbar.xml
When also copying skin.xml and adapt the path to my modded toolbar.xml the toolbar will not be displayed anymore.

2023-12-28 21:51 UTC, ronso0 commented
If you want a skin mod you need to copy only skin.xml and the (top-level) files the files to be modded.
For templates in subdirectories you'd need that subdirectory and mod the respective skins.

So, in your case
* copy skin.xml and toolbar.xml
* change `<Template src="skins:LateNight/toolbar.xml"/>` to
`<Template src="skin:toolbar.xml"/>` so Mixxx looks for it in the parent skin directory
* change `toolbar.xml` to your liking
* load "LateNight (Test)"

I agree, all in all this is still no optimal solution but IMO it's better than before.

2023-12-30 09:46 UTC, Russe commented
This is what I did.
Today, I did an update of Mixxx to most recent version 2.4-beta-314-g71dceb27ba
Again, with the same steps of your description the toolbar will not be displayed any more.
Am I using the wrong version of Mixxx?

My System: Ubuntu 22.04.3 LTS

2023-12-30 11:03 UTC, ronso0 commented
Hmm, works nicely for me.
Note the difference `skin:` vs. `skins:` (plural).
 I created `LateNight---toolbar` in the user skins dir, with just `skin.xml` and `toolbar.xml`, and in `skin.xml` I'm using
`<Template src="skin:toolbar.xml"/>` (which loads `LateNight---toolbar/toolbar.xml`) and I see the changes I made.

However, there seems to be a double `/` when adding the system skin path, I'll push a fix.

2023-12-30 11:05 UTC, ronso0 commented
With more debug output I now see the QDir searchPaths persist, i.e. `skins` is added repeatedly when reloading a skin.
I'll fix that, too.