Tag fetcher: allow to apply cover and tags separately // var.1 checkboxes
mixxxdj/mixxx pull request #12543
Opened 2024-01-10 00:21 UTC by ronso0

Fixes #12532 

Solution with two checkboxes = two new tr strings
![image](https://github.com/mixxxdj/mixxx/assets/5934199/0b053e02-263a-452a-af40-e936bbf1b0a4)

With this new tr strings are inevitable. With #12542 not necessarily.

2024-01-10 08:00 UTC, daschuer requested changes
Thank you. This one matches my use case more. 
Did you consider to make the checkboxes persistent?

2024-01-10 09:44 UTC, ronso0 commented on src/library/dlgtagfetcher.cpp
> +        statusMessage->setText(tr("Metadata applied"));
Sure, I'd also prefer "Tags" and can change that, too, than it's consistent at least in this dialog.
(the track menu and the preferences use "Metadata")

And, no, we can not have them "here" literaly, see the comment below.

2024-01-11 06:22 UTC, daschuer commented
It work good enough for a first merge. Thank you. 
During test I had the expectation that the cover is cleared when I try to apply a not found cover. Probably not a use case. 
Do we want to ray out the box in this case or remove the cover.

2024-01-11 14:26 UTC, ronso0 commented
> During test I had the expectation that the cover is cleared when I try to apply a not found cover. Probably not a use case.
Do we want to ray out the box in this case or remove the cover.

I considered that first but I'm not 100% sure the disabled checkbox clearly communicates there's no cover. But that's just my opinion.
I see that Search/Replace dialogs like in Eclipse use the same pattern, e.g. in Eclispe "whole word" is greyed out if "Regex" is checked, so we may implement it that way. Hopefully it will reassure users not to remove the existing cover when there was not cover found for the selected release.

2024-01-12 07:28 UTC, daschuer commented
> Hopefully it will reassure users not to remove the existing cover when there was not cover found for the selected release.

Ah yes. So let's do it that way around. If the selected row has no cover, gray out the checkbox + the label. If they want to remove cover they can do it in the track property dialog.

2024-01-12 10:24 UTC, ronso0 commented
Alright.
> gray out the checkbox + the label.

Which label do you refer to?
The 'Found Cover' image is already the placeholder in that case (and it has no menu).

2024-01-12 10:43 UTC, daschuer commented
Oh sorry, I just mean the checkbox label which is grayed out anyway.

Do we need in addition a few lines that also unchecks the greyed out checkbox and restores the previous value after a line with a cover is selected?

2024-01-12 11:07 UTC, ronso0 commented
Yes, unchecking the inactive box makes sense. I didn't do that previously to not make this quick fix more complex, but not that we agreed on that I'll implement it.

2024-01-15 01:05 UTC, ronso0 commented
Okay, done. Checkboxes are now disabled when there are no tags / cover to be applied.

'Apply' is **not** disabled when both are unchecked, tracking this to not falsely enable Apply is overkill.
For the same reason I did not implement un/checking the boxes when they're enabled/disabled.

This is good enough now. Please take a look.

2024-01-15 01:16 UTC, ronso0 commented
OT: we may consier to move the 'preferred size' combobox from the preferences to the TagFetcher.

2024-01-15 06:50 UTC, daschuer approved these changes
LGTM. 
Yes I agree, it works good. 
We can improve that any time later.

2024-01-15 06:50 UTC, merged