fix glitch in Star rating
mixxxdj/mixxx pull request #12582
Opened 2024-01-15 23:45 UTC by ronso0

* don't set 0 on leave event (like when the track menu is opened, or some dialog pops up)
* set confirmed value when pointer position exceeds max. star count

Fixes #12576

2024-01-16 07:59 UTC, daschuer requested changes
Thank you for taking care for this long standing bug. I need to do also manual tests.

2024-01-16 13:21 UTC, ronso0 commented
Back to draft, I discovered other small issues.

2024-01-16 14:29 UTC, ronso0 commented
Okay, this is now a roundhouse kick as it fixes the mentioned issues for all star ratings (decks, Track Info, library).

And it's horizontally centered if the parent is wider that the rating.
Though I can revert that if its not desired.

And, no need to rush, this can easily go to 2.4.1

2024-01-16 14:34 UTC, ronso0 commented
For WStarRating testing purpose I amend a **TEST commit** that makes the deck rating in LateNight a bit wider.

2024-01-16 19:46 UTC, ronso0 commented on src/library/stardelegate.cpp
> +    int stars = index.model()->data(index, Qt::ToolTipRole).toInt();
Hmm, so i didn't fully understand the StarRating class. `index.model()->data(Qt::EditRole | Qt::TooltipRol | Qt::UserRole + 2)` should all return the QVariant(rawValue.toInt()). But it's always 0.

Anyway, you're right, `starCount()` is it.

2024-01-17 12:11 UTC, ronso0 commented
> on leave event and **when the track menu is opened**
(even though it works for other editors, **the latter requires a hack if the editor is also selected**)

That's not working reliably, probably due varying order events. Like, on right click, sometimes the editor receives a LeaveEvent, sometimes it doesn't (for the same cell, tracks view unchanged).
I'll do a brief test if `eventFilter()` does the trick, else I'll just revert it and we may look into fixing it later on.

2024-01-19 01:27 UTC, ronso0 commented
Yup, with `eventFilter()` I couldn't make it fail anymore, but it remains a mystery to me, because it should work the same (the event is not consumed by eventFilter).
Works now  :man_shrugging: and with eventFilter() it's a bit easier to maintain IMO.

2024-01-19 07:10 UTC, daschuer approved these changes
Works perfectly and LGTM. Thank you very much for fixing alsohttps://github.com/mixxxdj/mixxx/issues/7304 form 2014

2024-01-19 07:11 UTC, merged

2024-01-19 07:15 UTC, daschuer commented
Ups, the TEST commit went again in. Sorry.

2024-01-19 08:42 UTC, ronso0 commented
Great, thanks for testing!

The test commit, forgot to request changes myself, I'll probably go with the Draft state next time.

2024-01-20 18:00 UTC, ronso0 commented
FYI I pushed three fix/polish commits directly to 2.4
5401f6bee775c773447c555be02ee4a4fab5c1a1
ab2d9b6ce757bcb19b5f24023d5bb2cd75589ad5
923abdf15b7b238cf1d1f1f8961d2a3ca2d11ad8

now trying to merge 2.4 into main