Hotcue: allow setting hotcue inside active, saved loop
mixxxdj/mixxx pull request #12623
Opened 2024-01-22 12:01 UTC by ronso0

Fixes #12618 

* activate a loop
* seek inside the loop
* trigger `hotcue_A_activate` or `hotcue_A_set`
   * new loop cue at loop start position
* trigger `hotcue_B_activate` or `hotcue_B_set`
   * new hotcue at current position

2024-01-24 23:37 UTC, daschuer requested changes
Thank you, need to test.

2024-01-24 23:37 UTC, daschuer commented on src/engine/controls/cuecontrol.cpp
> +            auto pSavedLoopControl = m_pCurrentSavedLoopControl.loadAcquire();
```suggestion
            auto* pSavedLoopControl = m_pCurrentSavedLoopControl.loadAcquire();
```

2024-01-24 23:40 UTC, daschuer commented
I can confirm the issue and that it is fixed with this PR.

2024-01-25 19:36 UTC, Holzhaus commented
Should there be a way to disable this magic? I sometimes use this to clone loop cues and then clear the original one.

2024-01-25 20:01 UTC, ronso0 commented
> I sometimes use this to move loop cues

You mean store the loop in another cue?
If so, you can do it the other way around:
* activate the saved loop `4`
* clear the cue (loop still active)
* hit hotcue `2`, done

Related: #9968

2024-01-26 00:52 UTC, ronso0 commented
Wouldn't hurt to add a test for this.

2024-01-27 15:35 UTC, ronso0 commented
Okay, this is ready.

2024-01-27 15:55 UTC, daschuer approved these changes
LGTM, Thank you

2024-01-27 15:55 UTC, merged