fix mainwindow and preferences window positioning
mixxxdj/mixxx pull request #1270
Opened 2017-05-28 20:33 UTC by JosepMaJAZ

fix positioning when reloading skin from developer menu. Also fixed Preferences window positioning

2017-05-29 07:24 UTC, sblaisot commented
I assigned bug https://bugs.launchpad.net/mixxx/+bug/1533575 to you.

2017-05-29 07:35 UTC, JosepMaJAZ commented
Ok. I will also fix that later today.

2017-05-29 07:46 UTC, sblaisot commented
I thought i was fixed by this PR already.
I will try your PR and let you know.

2017-05-29 08:43 UTC, JosepMaJAZ commented
I fixed what was causing it to go outside of the screen, but I haven't
added yet a "move it back if it is already outside". But that is
implemented in the other correction in mixxx.cpp, so it is simply a
copy&paste missing.

2017-05-29 08:47 UTC, sblaisot commented
I just tested using Appveyor artifact and moving outside of screen doesn't seems to be fixed.
Each time I show preference window, it moves up&left by a (probably) fixed amount of pixel. Showing preference window several times finally move it outside of screen.

2017-05-29 08:49 UTC, JosepMaJAZ commented
On which OS? I tested it on linux.

2017-05-29 09:03 UTC, sblaisot commented
On windows

2017-05-29 20:15 UTC, JosepMaJAZ commented
Ok, so far, I can confirm that on windows the solution didn't work, and at some point, it stopped working on linux too, but now I've got both mostly working, although with a different code path for each one. I'll commit it after a couple more tests

2017-05-30 04:17 UTC, Be-ing commented on src/preferences/dialog/dlgpreferences.cpp
> +    newX+=offsetX;
nitpick: please use spaces around the operator.

2017-05-30 06:55 UTC, sblaisot requested changes
Thank you so much for taking care of this ! I tested this version and it works well. No more preference window moving outside of screen, fixed and predictible position.
I left you somme minor comments.
Other than that, LGTM.

2017-05-30 06:55 UTC, sblaisot commented on src/preferences/dialog/dlgpreferences.cpp
> +#if defined(Q_OS_WIN)
You should probably use `#ifdef __WINDOWS__` for code consistency

2017-05-30 06:55 UTC, sblaisot commented on src/preferences/dialog/dlgpreferences.cpp
> +#if defined(Q_OS_WIN)
You should probably use `#ifdef __WINDOWS__` for code consistency

2017-05-30 06:55 UTC, sblaisot commented on src/mixxx.cpp
> +//    m_pPrefDlg->setHidden(false);
Remove dead code

2017-05-30 06:55 UTC, sblaisot commented on src/mixxx.cpp
> +//        qDebug() << "new x/y target:" << newX << "," << newY;
Remove debugging code before merge

2017-05-30 06:55 UTC, sblaisot commented on src/preferences/dialog/dlgpreferences.cpp
> +//    qDebug() << "ONSHOW  newxy" << newX << " " << newY;
Remove debugging code before merge

2017-05-30 06:55 UTC, sblaisot commented on src/preferences/dialog/dlgpreferences.cpp
> +//        qDebug() << "MOVEEVENT offsets " << offsetX << " " << offsetY;
Remove debugging code before merge

2017-05-30 06:55 UTC, sblaisot commented on src/preferences/dialog/dlgpreferences.cpp
> +        m_geometry[0] = QString::number(frameGeometry().left());
sapce vs tab identation mismatch with previous line ?

2017-06-01 20:57 UTC, daschuer commented
Thank you very much for fixing this one! :-)

2017-06-01 20:57 UTC, merged

2017-06-01 21:06 UTC, daschuer commented
Just noticed one remaining thing: 
On Linux the Mixxx window is still moving slowly right after every restart. This PR fixes th case that the window is moving out of the visible area. Thats good.
Do you have an idea why the moving happens in the first place?

2017-06-01 22:24 UTC, JosepMaJAZ commented
That has to do with the way X window and the windows manager works. I added
a way to compensate for the possibility of it being erroneous at first
open, but if it isn't working for you, it might not be generic enough.