Set text elide mode to left in WTrackTableView
mixxxdj/mixxx pull request #1288
Opened 2017-06-20 10:58 UTC by aalex

I think that the location column looks better with elide mode to the left. Maybe the other columns should stay with it set to the right.

![mixxx_elidemode_left](https://user-images.githubusercontent.com/293677/27330029-db1262f0-5585-11e7-97c5-a77846769524.png)

2017-06-20 11:08 UTC, aalex commented
I think that elide mode to the left doesn't make much sense for the BPM, Title, Artist, Album, etc. Either we could set it only for the Location column, or simply allow one to display only the base name of the file in the Location column. (the file name, without the directory in which it is)

2017-06-20 15:09 UTC, daschuer commented
Thank you very much fo the pull request. It works now better for me in most situations. 

Did you thought about making it even better? 
Here some thought directly from my head:
IMHO the most significant info is the subfolder where the file is stored. In my case showing the filename is redundant because it is build of artist and Title which is shown anyway. If the file is part of a single music folder the first part is useless as long as I see that it is in The music folder. If it is on a jump drive, this info is also significant.

Can we generate an elude rule from this?

2017-06-20 16:42 UTC, aalex commented
Hi!
I am glad ypu like my contribution/proposal.

I think the ideal would be, for the Location column, to provide these options:

- elude left full path (this patch)
- elude right full path (the current)
- only folder name
- only basename

For me, I need the basename (file name) since I use the BPM as a prefix, and I move my files around a lot, so using the BPM entry in Mixxx might be too much work, so I use a prefix.

Maybe there could be three columns: 

- absolute full path
- basename (file name
- directory name

2017-06-21 19:44 UTC, daschuer commented
You copied my typo corrected by my cell phone "elude" -> "elide", sorry :-D

> Maybe there could be three columns:

Yes that will work, but probably a bit overdone, because I normal have not enough space to show the location column in a reasonable size. So I have most likely not the space for tree columns. And no user will actually enable these columns. 

How about this: 
Keep the left elide and add an artificial elide after 8 chars of the file name. We have already the artist, title and type column, so this might be a good trade. In my case it will look like this: 

…e_Musik/1704/Marteria…
…e_Musik/1704/Bilderbu…
…ik/Recordings/7qfsLIHL…
…ecordings/Ska/El Bosso…
…Cadillac Blood/03-volbe…

It is much better then the released: 

/home/daniel/Musik/Volum…
/home/daniel/Musik/Volum…
/home/daniel/Musik/Volum…
/home/daniel/Musik/Volum…
/home/daniel/Musik/Volum…

And does not display redundant informations only, for user like me with this PR.

This solves my use case perfectly and should fit to yours as well, right? 
For more, we have always the hoover tool-tip. 

What do you think?

2017-06-22 15:46 UTC, aalex commented
Hi Daniel,
This is a great idea! Very practical.
Now, we simply need to clip the file name at 8 chars after the beginning of the basename. Easy.

There is one downside to that approach: we won't be able to have the full path (including the removed part) when we mouse over it.

There is one thing that needs to be sorted out: As I mentioned before, I think the elide left should be only for that specific column. (the other columns should have the regular elide right)

2017-06-22 16:26 UTC, daschuer commented
To see the full path in the tooltips is IMHO mandatory. I will look into it tonight. Without further investigations I think this can be done by a simple text box delegate. We use this already to display the star rating coloum.

2017-06-22 19:37 UTC, daschuer commented
OK, here a receipt. I hope it is not to coarse to implement it.If that is the case, please ask.  
* create a new cpp and h file "src/library/locationdelegate*
* add the cpp fie to build/depends.py
* create a new QStyledItemDelegate child class by coping most of StarDelegate
* user your new delegate in BaseSqlTableModel::delegateForColumn() 
* rewrite the painting code like here: 
http://www.qtcentre.org/threads/46580-QStyledItemDelegate-draw-an-items-with-a-different-size-text-and-heights
https://forum.qt.io/topic/11891/delegate-multi-line-text/2
https://forum.qt.io/topic/41463/solved-qstyleditemdelegate-set-text-color-when-row-is-selected
* the first version should just implement the right alide. 
* now do all fancy stuff you like ;-)

2017-10-09 18:56 UTC, poelzi commented
I would like the location reduced a bit like fish shell does.
Example:
pwd: /media/poelzi/zgike-pa-poelzi/Music/chillgressive/Beatfarmer/Cosmic_Playground
becomes: poelzi@horas /m/p/z/M/c/B/Cosmic_Playground (master)> 

But i would prefer more something like:
.../chil/Beat/Cosmic_Playground/01 - Cosmic_Playground_cosmic_Mix.flac

The library root hidden or squashed or so. At least in case of a single library root.

2017-10-09 19:37 UTC, daschuer commented
to you prefer to see the whole file name.
In my case it will occupy the whole column width without showing me where it is in my folder structure.

2019-01-10 19:04 UTC, ferranpujolcamins commented
I think we should merge this. It's already an improvement!

2019-01-11 12:03 UTC, aalex commented
That might be a good idea, yes.

Le jeu. 10 janv. 2019 14 h 04, Ferran Pujol Camins <notifications@github.com>
a écrit :

> I think we should merge this. It's already an improvement!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mixxxdj/mixxx/pull/1288#issuecomment-453214418>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAR7LWAU4Wi06lDEBPEGnKgq4v1DtPnHks5vB46tgaJpZM4N_au6>
> .
>

2019-01-11 13:21 UTC, daschuer requested changes
Ok, unfortunately this one changes the elite mode for all cloums.
This and the merge conflicts should me merged first.

2019-01-20 17:35 UTC, benis commented
> OK, here a receipt. I hope it is not to coarse to implement it.If that is the case, please ask.
> 
>     * create a new cpp and h file "src/library/locationdelegate*
> 
>     * add the cpp fie to build/depends.py
> 
>     * create a new QStyledItemDelegate child class by coping most of StarDelegate
> 
>     * user your new delegate in BaseSqlTableModel::delegateForColumn()
> 
>     * rewrite the painting code like here:
>       http://www.qtcentre.org/threads/46580-QStyledItemDelegate-draw-an-items-with-a-different-size-text-and-heights
>       https://forum.qt.io/topic/11891/delegate-multi-line-text/2
>       https://forum.qt.io/topic/41463/solved-qstyleditemdelegate-set-text-color-when-row-is-selected
> 
>     * the first version should just implement the right alide.

This is the thing I am trying to work on currently but I just don't really know how to do it. Any help would be appreciated.

2019-01-20 20:14 UTC, benis commented
Progress...

<img width="426" alt="screenshot 2019-01-20 at 20 14 15" src="https://user-images.githubusercontent.com/36423450/51444480-fb46e680-1cef-11e9-899f-fe463e8a7e87.png">

2019-01-20 20:59 UTC, benis commented
@aalex I think I'm pretty close to getting this working. Are you happy for me to make a new PR? Otherwise I have to PR everything to you and then you have to merge it etc.

2019-01-21 18:04 UTC, Be-ing commented
@benis if the original author of this PR doesn't respond by the time your code is ready for review, go ahead and make a new PR.

2019-01-21 18:10 UTC, aalex commented
@benis Yes! Don't worry: you should do another PR. I am happy that someone is taking care of this, indeed.

2019-01-21 18:12 UTC, aalex commented
Simply create another PR, paste its link as a comment here, and feel free to close this one.

2019-01-21 19:12 UTC, benis commented
Cool.. see #2002. Thanks guys

2019-02-17 19:50 UTC, benis commented
This can be closed as #2002 replaced it and has been merged.

2019-02-18 00:02 UTC, closed without merging