Computer feature: add sidebar action "Refresh directory tree"
mixxxdj/mixxx pull request #12908
Opened 2024-03-03 22:22 UTC by ronso0

This allows to show newly added directories when the parent had no directories when it was first added to the tree.

based on #12893

2024-05-01 20:13 UTC, daschuer requested changes
I did the following: 
* Opened a folder with Mixxx
* Added a file using a file manager. 
* Select Refresh form the context menu. 
Expected: File is shown 
Actual: nothing happens.

2024-05-01 20:19 UTC, daschuer commented
I have also intuitive pressed F5, but that has a different meaning.

2024-05-02 12:35 UTC, ronso0 commented
> The menu is missing for "Quick access" folders

I added that.

2024-05-02 12:45 UTC, ronso0 commented
Yeah, F5 in the tracks view would also be cool.

2024-05-13 23:35 UTC, daschuer approved these changes
Thank you. Works good

2024-05-13 23:35 UTC, merged