[PreviewDeckN],LoadSelectedTrackAndPlay toggles play/pause if the track is already loaded
mixxxdj/mixxx pull request #12920
Opened 2024-03-04 17:34 UTC by ronso0

Fixes #9819 

Due to limited unused hotkeys (in the default mapping) and to allow controlling the preview deck with a few hotkeys only I propose to extend/override the behaviour of `[PreviewDeckN], LoadSelectedTrackAndPlay`:
if the track is already loaded, toggle play/pause.

This is mapped to `P`
`Shift`+`P` does `start_stop` (stop and seek to start) (could as well be `cue_gotoandstop`?)

**TODO**
- [ ] update mappings
- [ ] update [manual](https://manual.mixxx.org/2.5/en/chapters/appendix/mixxx_controls.html#control-[ChannelN]-LoadSelectedTrackAndPlay)

2024-03-04 20:03 UTC, daschuer commented
Good idea.

2024-03-04 20:09 UTC, daschuer commented on src/mixer/playermanager.cpp
> +        auto pPlayer = getPlayer(group);
We have pPlayer and the null check already above.

2024-03-04 20:12 UTC, daschuer requested changes
Thank you

2024-03-04 20:12 UTC, daschuer commented on src/mixer/playermanager.cpp
> +                    isPlaying ? 0.0 : 1.0);
Please avoid to look up the control object twice.

2024-03-04 23:17 UTC, ronso0 commented
The corresponding manual PR is https://github.com/mixxxdj/manual/pull/625

2024-03-05 06:29 UTC, daschuer requested changes
Just one minor.
Why is this still in n draft?

2024-03-05 06:29 UTC, daschuer commented on src/mixer/playermanager.cpp
> +            double newPlay = pPlay->get() > 0.0 ? 0.0 : 1.0;
```suggestion
            double newPlay = pPlay->toBool() ? 0.0 : 1.0;
```

2024-03-05 09:05 UTC, ronso0 commented
> Why is this still in n draft?

I noticed a glitch in the keyboard sheet preview (:heavy_check_mark:  seemst to be an issue with the GH preview) and I didn't check if this affects the Preview delegate (:heavy_check_mark: ).

So this is ready to roll.
Thanks for your prompt review!

2024-03-05 09:23 UTC, ronso0 commented
I noticed an incosistency:
* the preview Play button right-click is mapped to `start` (and stops, so this is the same as `start_stop`?)
* the tooltip says `cue_gotoandplay` (LateNight only)
* `Shift`+`P` is mapped to `start_stop`
* the Preview delegate always does `cue_gotoandplay` and `play` (pause)

I think we should map the Play button right-click and `Shift`+`P` to `cue_gotoandplay`, too.
If the user wants to go back to the the start this can be done by dragging the playhead on the overview, while otoh jumping to Cue requires to click the C icon (which is rather small in the preview deck).
For unprepared tracks Cue = start, and for prepared tracks we may assume Cue has been set to a different position on purpose.

Not going to fix this here, let's discuss it in #12925

2024-03-05 09:24 UTC, ronso0 commented on src/mixer/playermanager.cpp
> +            double newPlay = pPlay->get() > 0.0 ? 0.0 : 1.0;
fixed

2024-03-09 00:24 UTC, ronso0 commented
FWIW, with 2.4 I managed to get a mismatch of the preview deck's play button (not lit) and Preview delegate (lit). I continued clicking the delegate so I can't tell whether the deck was actually playing (shouldn't since the Play button CO is reliable IMO).

2024-03-19 03:03 UTC, ronso0 commented
The manual PR has been merged already, let's merge this, too.
Any objections?

2024-03-19 07:37 UTC, daschuer approved these changes
LGTM, Thank you.

2024-03-19 07:37 UTC, merged