(fix) Library: allow adding new dirs while we have missing watched dir(s)
mixxxdj/mixxx pull request #12937
Opened 2024-03-08 12:05 UTC by ronso0

Fixes #10481

I don't understand how the "inconsistencies" mentioned in the comment can be so serious that we have to prevent adding a new directory.
After a rescan, everything should be fine.

2024-03-09 00:40 UTC, ronso0 commented on src/library/dao/directorydao.cpp
> +    for (auto&& oldDir : loadAllDirectories(true)) {
Alternatively, use the current implemantation but don't return if the old dir is missing. Instead, do the QString equivalent of `mixxx::FileInfo::isRootSubCanonicalLocation(new, old)` in that case.
This requires refactirng here, i.e. use `DirectoryDAO::getRootDirStrings()` added in #12878 and construct the mixxx::FileInfo here.

2024-04-14 19:46 UTC, daschuer requested changes

2024-04-14 19:46 UTC, daschuer commented on src/library/dao/directorydao.cpp
> +    // Ignore invalid or missing directories in order to aloow adding new dirs
```suggestion
    // Ignore invalid or missing directories in order to allow adding new dirs
```

2024-04-14 22:26 UTC, ronso0 commented on src/library/dao/directorydao.cpp
> +    // Ignore invalid or missing directories in order to aloow adding new dirs
yup, fixed.

2024-04-15 16:40 UTC, daschuer approved these changes
LGTM, thank you

2024-04-15 16:40 UTC, merged