increase keylock disable limit to 250%, apply only for SoundTouch
mixxxdj/mixxx pull request #12946
Opened 2024-03-10 12:02 UTC by ronso0

see https://mixxx.zulipchat.com/#narrow/stream/109122-general/topic/keylock.20for.20more.20than.20.2B100.25.20speed.20change.20possible.3F

### We need to test for regressions with
* speeds up to 250%
* all keylock engines.
* scratching with Rubberband v2/v3
* seeking

Draft until we have confirmed no / minimal regressions.

2024-03-10 12:04 UTC, ronso0 commented
In case of doubts or issues, we may create a minimal fix (SoundTouch only, 100%) for 2.4

2024-04-14 08:48 UTC, daschuer commented
How is the state here? Do we have any test results? We may just merge this to 2.5 and collect test data during 2.5-beta.

2024-04-15 15:17 UTC, ronso0 commented
Nope, I did only a brief test with rate +100%.

Targetting main now.

2024-05-01 19:50 UTC, daschuer requested changes
Just did a test, Rubberband and Soundtouch are sounding terrible at 250. But it works. It also sounds terrible when you pass the threshold and it goes to chipmunk without a warning. 

So it is OK to raise the threshold. But how about removing the speed threshold entirely?

The other issue it that cueing by scratching for a first beat, sound now totally different with key-lock enabled. My first impulse was, that it is broken. After a bit testing I think one can get used to, but auto-disabling key lock during scratching is IMHO a good feature for that use case. 

Is there a real use case for scratching with key lock?

2025-05-02 01:44 UTC, closed without merging