Update Changelog for 2..5-alpha
mixxxdj/mixxx pull request #12960
Opened 2024-03-13 04:05 UTC by daschuer

2024-03-17 14:43 UTC, JoergAtGithub commented
https://github.com/mixxxdj/mixxx/pull/4637 and https://github.com/mixxxdj/mixxx/pull/11035 were backported to 2.4 (see #11264). Please remove them from the 2.5 changelog therefore.

2024-03-18 07:44 UTC, daschuer commented
Done and up to date.

2024-03-18 19:51 UTC, JoergAtGithub requested changes

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* Playlists: Uupdate of playlist labels after adding tracks [#12866](https://github.com/mixxxdj/mixxx/pull/12866) [#12761](https://github.com/mixxxdj/mixxx/issues/12761)
```suggestion
* Playlists: Update of playlist labels after adding tracks [#12866](https://github.com/mixxxdj/mixxx/pull/12866) [#12761](https://github.com/mixxxdj/mixxx/issues/12761)
```

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* Tracks: custom text color for played tracks (qss) [#12744](https://github.com/mixxxdj/mixxx/pull/12744) [#5911](https://github.com/mixxxdj/mixxx/issues/5911) [#12912](https://github.com/mixxxdj/mix
```suggestion
* Tracks: Custom text color for played tracks (qss) [#12744](https://github.com/mixxxdj/mixxx/pull/12744) [#5911](https://github.com/mixxxdj/mixxx/issues/5911) [#12912](https://github.com/mixxxdj/mixxx/pull/12912)
```

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* History: show track count and duration in sidebar [#12811](https://github.com/mixxxdj/mixxx/pull/12811) [#12788](https://github.com/mixxxdj/mixxx/issues/12788)
```suggestion
* History: Show track count and duration in sidebar [#12811](https://github.com/mixxxdj/mixxx/pull/12811) [#12788](https://github.com/mixxxdj/mixxx/issues/12788)
```

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* Track menu: rephrase "Reset" to "Clear" [#12955](https://github.com/mixxxdj/mixxx/pull/12955)
```suggestion
* Track menu: Rephrase "Reset" to "Clear" [#12955](https://github.com/mixxxdj/mixxx/pull/12955)
```

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* refactor: avoid temporary qlist allocation on midi sysex receive [#12843](https://github.com/mixxxdj/mixxx/pull/12843)
```suggestion
* refactor: Avoid temporary qlist allocation on midi sysex receive [#12843](https://github.com/mixxxdj/mixxx/pull/12843)
```

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* feat(ci): add eslint rule prefer-template [#12889](https://github.com/mixxxdj/mixxx/pull/12889)
```suggestion
* feat(ci): Add eslint rule prefer-template [#12889](https://github.com/mixxxdj/mixxx/pull/12889)
```

2024-03-18 19:51 UTC, JoergAtGithub commented on CHANGELOG.md
> +* src/library: sort files into sub-directories [#12956](https://github.com/mixxxdj/mixxx/pull/12956)
```suggestion
* src/library: Sort files into sub-directories [#12956](https://github.com/mixxxdj/mixxx/pull/12956)
```

2024-03-19 07:42 UTC, daschuer commented
Done

2024-03-19 08:06 UTC, JoergAtGithub commented
LGTM! Thank you!

2024-03-19 08:06 UTC, merged