Add needed error handling
mixxxdj/mixxx pull request #12964
Opened 2024-03-13 18:48 UTC by yatigautam

Fixes: #11903 

Have written these lines with my understanding, do let me know about any further changes required!

2024-03-13 19:28 UTC, JoergAtGithub commented
Welcome at Mixxx!
As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

2024-03-13 21:59 UTC, ronso0 commented
Thanks for working on this.

However I should note that I obviously filed #11903 with too little details.
The fix is just logging the error (rather useless for regular users) but providing meaningful information in the GUI, like 
[`TagFetcher::networkError`](https://github.com/mixxxdj/mixxx/blob/32ee9ed246cf34182dd6dbbd8dd12d4a4a290f55/src/musicbrainz/tagfetcher.h#L55-L59) is used to print the error message in the status/progress bar of Tag Fetcher.

2024-03-15 02:02 UTC, yatigautam commented
I have signed to the Mixxx Contributor Agreement. 
I also understand that the issue needs some more fix as you have stated, currently working on it and will let you know about the fix very soon.
Thank you for the guidance.

2024-03-21 16:46 UTC, yatigautam commented
hello,
I have made some changes in the code for printing the meaningful error message in the GUI.
Do let me know that is this the kind of error message and code you were expecting?
While building the project, some errors aroused please help me a bit in that.

2024-03-22 00:43 UTC, ronso0 submitted a review, later dismissed
Just a few hints after taking a brief look:
* don't add "private" stuff to the Mixxx .gitignore, these belong into your local/global .gitignore
* avoid moving functions around for no reason
* keep blank lines around functions

I'll take a closer look soonish, i.e. after you have updated/reverted the details I mentioned above.

I think here it's okay to ammend to / fixup commits, rebase and force-push because no in-depth code review was done.

2024-03-22 17:28 UTC, yatigautam commented
Sorry for the silly mistakes.
I have reverted the changes.

2024-03-24 08:09 UTC, yatigautam commented
Hey, @ronso0   may I know which class handles the main UI where statuBar is handled?

2024-03-24 15:15 UTC, daschuer commented
We don't have a status bar in the main GUI yet. The status bar we use for tag fetcher issues is this one: 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/c6238bd2-818f-4580-9d29-497d22c54b0d)

2024-03-24 15:19 UTC, daschuer commented
it is either displayed on `DlgTagFetcher::loadingProgressBar` or directly as `DlgTagFetcher::statusMessage`

2024-03-27 19:49 UTC, yatigautam commented
hey, i have almost solved the issue and made changes to the code, i just need some help with it's testing, see when i am uploading any track and going to the "import metadata from musicbrainz" option i am unable to see any suggested tags for it rather it's displaying the error "can't connect to Acoustid:: TLS initialization failed", i have also switched the local branch to the main and pulled the changes if any, still i am encountering the same issue. Although the same music track has some suggested tags in the desktop application when i checked.
kindly help me out a bit on how to execute further.

2024-03-28 13:58 UTC, ronso0 commented
Do you expereince that issue also with plain `main`?

2024-03-29 05:58 UTC, yatigautam commented
> Do you expereince that issue also with plain `main`?

Yes

2024-03-29 08:27 UTC, daschuer requested changes

2024-03-29 12:12 UTC, yatigautam commented on src/musicbrainz/tagfetcher.cpp
> -    m_pCoverArtArchiveLinksTask = make_parented<mixxx::CoverArtArchiveLinksTask>(
I was previously facing this particular error, so I went through the code and removed these particular lines of codes, 
ERROR:: `'mixxx::CoverArtArchiveLinksTask::CoverArtArchiveLinksTask': no overloaded function could convert all the argument types`	
sorry, for removing this rather I should have commented this out and asked you regarding the error.

2024-03-29 12:52 UTC, daschuer commented on src/musicbrainz/tagfetcher.cpp
> -    m_pCoverArtArchiveLinksTask = make_parented<mixxx::CoverArtArchiveLinksTask>(
Does this error still happen? I don't see an obvious reason for that. 
You may just undo this change and we can look into the CI output.

2024-03-29 12:54 UTC, daschuer commented
pre-commit is failing. Please make sure you have installed pre-commit locally. 
You find instructions here: https://github.com/mixxxdj/mixxx/wiki/using-git#set-up-automatic-code-checking

2024-03-30 17:23 UTC, yatigautam commented
I squashed all the commits into one to ease up the process of review .. If more changes needed from my side then do comment, thanks in advance!

2024-03-30 19:15 UTC, ronso0 requested changes

2024-03-30 19:15 UTC, ronso0 commented on src/musicbrainz/tagfetcher.cpp
> +            this);
I don't understand the purpose of this.

In this function we should actually only need to interpret the errorCode as you do below, then pass the user string to DlgTagfetcher.

2024-03-30 19:15 UTC, ronso0 commented on src/musicbrainz/tagfetcher.h
> +    void coverArtArchiveLinksTaskNetworkError(const QString& errorMessage);
Why do we need two signals with the exact same content?

2024-04-10 13:27 UTC, yatigautam commented
hey, sorry to respond so late to the changes required, been sick lately.
I had made the changes and I think it must work fine. Although, I am unable to test it as I told you earlier that while  uploading any track and going to the "import metadata from musicbrainz" option I am unable to see any suggested tags for it rather it's displaying the error "can't connect to Acoustid:: TLS initialization failed", but the same isn't happening in the mixxx desktop application.

2024-06-09 18:44 UTC, acolombier requested changes
> I have made the changes and I think it must work fine. Although, I am unable to test it as I told you earlier that while uploading any track and going to the "import metadata from musicbrainz" option I am unable to see any suggested tags for it rather it's displaying the error "can't connect to Acoustid:: TLS initialization failed", but the same isn't happening in the mixxx desktop application.

This is odd. It could have been a temporary outage on their end. Perhaps share the log  if it still occurs? (you might need to run Mixxx with `--log-level debug`)

2024-06-09 18:44 UTC, acolombier commented on .gitignore
> +
Looks like this change is unneeded

2024-06-09 18:44 UTC, acolombier commented on cpp.hint
> +// Hint files help the Visual Studio IDE interpret Visual C++ identifiers
To be confirmed by the Mixxx Core Team, but I believe we are trying not to put any IDE specific config file in the repo. Perhaps you may add this in your [global git ignore](https://stackoverflow.com/a/7335487)?

2024-06-09 18:44 UTC, acolombier commented on src/musicbrainz/tagfetcher.cpp
> +#include <qmainwindow.h>
Doesn't seem to be used

2024-06-09 18:55 UTC, ronso0 commented
FWIW I think this PR has been abandoned after the decision for current year's GSoC participants, but I might be wrong.

2025-02-26 00:27 UTC, ronso0 commented
8+ months without response, closing this now.

2025-02-26 00:27 UTC, closed without merging