feat: Add CLI option to auto start Auto DJ
mixxxdj/mixxx pull request #13017
Opened 2024-03-28 12:07 UTC by danferns

This PR resolves #10189.

The CLI flag `--start-autodj` was added. When this flag is set, Mixxx enables Auto DJ mode on startup.

2024-03-28 12:48 UTC, daschuer requested changes
Thank you for your first PR. 

To shop it with Mixxx, we need your permission. Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so.

2024-03-28 12:48 UTC, daschuer commented on src/mixxxmainwindow.cpp
> +        pAutoDjEnabled->set(1.0);
`new` without `delete` is a memory leak in C++. We avoid this pair in new code by using smart pointer.
In this case you can set the CO directly via: 
```suggestion
        ControlObject::set(ConfigKey("[AutoDJ]", "enabled"), 1.0);
```

2024-03-28 13:54 UTC, ronso0 reviewed
LGTM, thank you!

In order to keep this feature PR comapct I'd prefer if you could git squash the second commit, then force-push.

2024-03-28 13:56 UTC, ronso0 commented
(agreement signed, thank you!)

2024-03-28 14:09 UTC, danferns commented
Thank you @daschuer and @ronso0 for your feedback and advice! 
Also yes I have signed the agreement! Happy to be a part of this :)

2024-03-29 13:14 UTC, daschuer approved these changes
Thank you very much. Works and looks good. 

I have just noticed one unrelated issue. Adding any of the command line option enables colorful console output. The must be an issue with the --color option.

2024-03-29 13:14 UTC, merged