feat: enable controller setting on MIDI
mixxxdj/mixxx pull request #13045
Opened 2024-04-03 22:33 UTC by acolombier

The original plan was to also support settings when parsing the XML mapping definition, thus why a follow up PR was dedicated for this feature.

As the latter is likely not happening, this PR exposes the settings in the JS engine only.

I don't have a MIDI controller available for testing yet, can anyone give it a go please?

2024-04-03 22:59 UTC, ronso0 commented
How exactly can we test?

2024-04-03 23:24 UTC, acolombier commented
It can be tested by adding settings definition and querying them from the engine like for the [S4 MK3](https://github.com/mixxxdj/mixxx/pull/12995#event-12304815386)

2024-04-03 23:42 UTC, ronso0 commented
So they **do** go to the xml? (to create the settings GUI)

2024-04-04 09:02 UTC, acolombier commented
Yes, that's right. The setting definition still goes in XML. The thing that was dropped is conditional mapping definition in XML

2024-04-04 09:09 UTC, ronso0 commented
Haha, easy one : )
Will give it a go soonish.

2024-04-04 10:36 UTC, ronso0 commented
I added the S4 Mk3 snip to a VirMIDI mapping and there seems to be an issue with the checkbox labal and rich text:
the inline style is not recognized, thus the string is looooooong and makes the settings page expand that much I don't get a full view with FHD.

Seems this is not based on main?

2024-04-04 10:41 UTC, ronso0 commented
Yeah, putting this commit on top of main fixes the string issue.

But the checkbox wrapper has a margin now.
before (broken, pure checkbox):
![image](https://github.com/mixxxdj/mixxx/assets/5934199/c40c353c-15d6-496b-ad72-9864983b87dd)


on top of main:
![image](https://github.com/mixxxdj/mixxx/assets/5934199/9ff607b3-c256-4cf7-ba08-6ec3708d7af6)

2024-04-04 10:46 UTC, ronso0 commented
Btw I think we should add a 'button' style for the label strings, so that the mapping only contains
`This will light up the :btn:SYNC:/btn:` (or whatever syntax fits)
and c++ creates the style depending on the GUI's dark/light flag (Qt theme).

Any other style templates that would simplify the xml strings?
italic?
bold?

2024-04-04 10:47 UTC, ronso0 commented
I.e. I consider this ready to go if rebased onto main for easy testing.

2024-04-04 11:32 UTC, Swiftb0y approved these changes
Code LGTM ;) 
Didn't do any testing. I may find some time to test this out with some of my mappings.

2024-04-04 14:09 UTC, ronso0 commented
> Btw I think we should add a 'button' style for the label strings, so that the mapping only contains `This will light up the :btn:SYNC:/btn:` (or whatever syntax fits) 

:hwbtn:`LABEL`?
#13046

2024-04-12 18:33 UTC, acolombier commented
Merge?

2024-04-13 01:39 UTC, ronso0 commented
Sorry, I only checked the GUI so far, not the actual settings (I expect that to work, though someone should check it).

2024-04-13 05:30 UTC, JoergAtGithub commented
I will check this on Monday. I need to set up a MIDI device first.

2024-04-15 21:11 UTC, JoergAtGithub requested changes
I just tested this with a MIDI device. The settings functionality itself works as expected, but not the Restore Defaults button. It unloads the whole mapping instead of resetting the setting values.

2024-04-15 21:18 UTC, acolombier commented
![image](https://github.com/mixxxdj/mixxx/assets/7086688/49ef76df-9eaa-4309-912d-c722d469e73f)

Could you share a video of the behaviour? It sound like the expected behaviour if there is [no exact mapping match](https://github.com/acolombier/mixxx/blob/c5e34806eb79d9a49151fc514d429351905e2f02/src/controllers/dlgprefcontroller.cpp#L433)

2024-04-15 21:37 UTC, JoergAtGithub commented
https://github.com/mixxxdj/mixxx/assets/64457745/2b6cb6c7-a6cc-4d95-b688-d1270e1cf8c3

2024-04-16 10:19 UTC, acolombier commented
This looks like expected behaviour when the device doesn't match 100% the mapping definition. Could you confirm the mapping combobox reset to `No mapping` too?

The custom settings of the current mapping are staged for reset, but when you re-select it in the combobox, you undo the reset (as per intended). If you want to reset the setting, you should:
- Click the `Restore Defaults`
- Click `Ok`/`Apply`

Then reselecting the mapping will use the default values

2024-04-16 17:08 UTC, JoergAtGithub commented
> This looks like expected behaviour when the device doesn't match 100% the mapping definition. Could you confirm the mapping combobox reset to `No mapping` too?

Yes, can confirm it's exactly the behavior you described for a device that doesn't match 100% the mapping definition.

But matching can't be true for a MIDI device due to:
https://github.com/mixxxdj/mixxx/blob/435da25fa8f361f94c8abb24aa770857a3dce7e9/src/controllers/midi/midicontroller.cpp#L73-L78

Therefor this PR is correct and the controller ettings code will work as soon as MidiController::matchMapping get implemented. The behavior without MidiController::matchMapping implemented is safe and just a UI glitch.

2024-04-16 17:09 UTC, JoergAtGithub approved these changes

2024-04-16 17:09 UTC, merged

2024-04-16 17:09 UTC, JoergAtGithub commented
Thank you!