feat: refactor FFmpeg soundsource to allow other soundsource to inherit it
mixxxdj/mixxx pull request #13042
Opened 2024-04-03 10:37 UTC by acolombier

This is requirement for the STEM sound source

2024-04-12 22:42 UTC, daschuer requested changes

2024-04-13 11:18 UTC, acolombier commented on src/sources/soundsourceffmpeg.h
> +    // The following static functions are used by children classes
I had to make it public so the STEM class, which doesn't inherit FFmpeg directly, but has composition(with the inheritance) can also [open the file](soundsourcestem.cpp:289) to check the the content. I guess I could also make it a friend? What's your thought?

2024-04-13 11:31 UTC, daschuer commented on src/sources/soundsourceffmpeg.h
> +    // The following static functions are used by children classes
No need to become pedantic with it. 
Tha just adjust the comments.

2024-04-13 11:31 UTC, daschuer commented on src/sources/soundsourceffmpeg.h
> +    // The following static functions are used by children classes
No need to become pedantic with it. 
Tha just adjust the comments.

2024-04-13 22:07 UTC, daschuer approved these changes
LGTM, Thank you.

2024-04-13 22:07 UTC, merged

2024-04-13 22:07 UTC, daschuer commented
Which one is the next?

2024-04-14 12:10 UTC, acolombier commented
That would be [this one](https://github.com/mixxxdj/mixxx/pull/13044)