Changelog update for 2.4 branch
mixxxdj/mixxx pull request #13096
Opened 2024-04-13 13:21 UTC by daschuer

2024-04-15 15:13 UTC, ronso0 commented
Thanks, just some ideas for rephrasing

2024-04-15 18:37 UTC, ronso0 approved these changes

2024-04-15 18:38 UTC, ronso0 commented
(just waiting for CI to be all green, anyone passing by may press merge)

2024-04-15 18:49 UTC, daschuer commented
I have added some more entries since your review.

2024-04-16 08:39 UTC, ronso0 requested changes

2024-04-16 08:39 UTC, ronso0 commented on CHANGELOG.md
> +* Library: allow adding new dirs while we have missing watched dir(s)
```suggestion
* Library: allow adding new directories while watched directories are missing
```

2024-04-16 08:39 UTC, ronso0 commented on CHANGELOG.md
> +* Library sidebar: fix History label update [#12882](https://github.com/mixxxdj/mixxx/pull/12882) [#12880](https://github.com/mixxxdj/mixxx/issues/12880)
```suggestion
* Library sidebar: show track count and duration of History playlists
  [#12811](https://github.com/mixxxdj/mixxx/pull/12811)
  [#13020](https://github.com/mixxxdj/mixxx/pull/13020)
  [#13019](https://github.com/mixxxdj/mixxx/issues/13019)
  [#12788](https://github.com/mixxxdj/mixxx/issues/12788)
  [#12880](https://github.com/mixxxdj/mixxx/issues/12880)
  [#12882](https://github.com/mixxxdj/mixxx/pull/12882)
```

2024-04-19 21:23 UTC, ronso0 approved these changes

2024-04-19 21:23 UTC, ronso0 commented
Thanks!

2024-04-20 13:39 UTC, merged