Playlists: move tracks Alt + Up/Down
mixxxdj/mixxx pull request #13092
Opened 2024-04-11 23:10 UTC by ronso0

Finally.
This was rather easy only due the new Cut, Copy & Paste feature #12020. Thanks @m0dB !!

Applicable only in (unlocked) playlists.
(sort by #)

* continuous selections are moved right away
* non-continuous selections are first consolidated at first/last row, then moved on next keypress
* wrap-around is suppressed to avoid undesirable overshoot with longpress (keyrepeat)

- [ ] remove trace output (normalized to 1-based rows)

2024-04-12 10:21 UTC, ronso0 commented
FWIW I think the `event->source() == this` part of `WTrackTableView::dropEvent()` can be replaced with cut/paste.
@m0dB wdyt?

2024-04-12 14:30 UTC, ronso0 commented
Works, but draft again because I'll look into redoing moveTrack() -> moveTracks(QModelIndexList indices, int insertPos), moving all tracks at once.

2024-04-13 09:40 UTC, nlw0 commented
That's great, I've tried out and it seems to work. I noticed that 'del' seems to have stopped working for me, though. Could it be related to this patch?

What would be a good way to implement library commands for this now, using `emitKeyEvent`?

2024-04-13 12:30 UTC, ronso0 commented
> ...but I'll check if a wrapper could work, i.e. a function that can be called by dragDropEvent() and moveTracks()

Yup, that works!
Will pick that to get around the (presumably) costly cut/paste ops

2024-04-14 22:21 UTC, ronso0 commented
> > ...but I'll check if a wrapper could work, i.e. a function that can be called by dragDropEvent() and moveTracks()
> 
> Yup, that works! Will pick that to get around the (presumably) costly cut/paste ops

Done. Works like a charm, espcially consolidating non-continuous selections.

2024-04-14 22:23 UTC, ronso0 commented
And it avoids running into bug #13100 (or limitation once that is fixed) with tracks whose files are currently missing.

2024-04-14 22:24 UTC, ronso0 commented
In case someone experiences issues, I can make a debu commit from the trace output I have in my stash.

2024-04-15 11:29 UTC, daschuer requested changes
Some finding. A manual test is pending.

2024-04-15 11:29 UTC, daschuer commented on src/widget/wtracktableview.cpp
> +    std::sort(selectedRows.begin(), selectedRows.end());
Can we move this into getSelectedRowNumbers()? It looks like it is required in all cases.

2024-04-15 11:29 UTC, daschuer commented on src/widget/wtracktableview.cpp
> +    }
This is redundant, but you may keep it if you like. 
```suggestion
```

2024-04-15 11:29 UTC, daschuer commented on src/widget/wtracktableview.cpp
> +    const QModelIndexList indices = pSelectionModel->selectedRows();
```suggestion
    const QModelIndexList indices = getSelectedRows();
```

2024-04-15 13:20 UTC, ronso0 commented on src/widget/wtracktableview.cpp
> +    const QModelIndexList indices = pSelectionModel->selectedRows();
of course ...

2024-04-15 18:27 UTC, daschuer approved these changes
Works like a charm. You may rebase it now. Thank you.

2024-04-15 20:21 UTC, daschuer commented
All green. Thank you.

2024-04-15 20:21 UTC, merged