Playlists: keep correct track selection (position) when sorting
mixxxdj/mixxx pull request #13103
Opened 2024-04-15 11:06 UTC by ronso0

Previously, tracks were reselected by TrackId after sorting which would add wrong tracks to the selection in case the playlist contains tracks multiple times.

I also considered adding an equivalent to [`m_trackIdToRows`](https://github.com/mixxxdj/mixxx/blob/74cee25c54d0f282fcadc42a8a93bec355e3ef39/src/library/basesqltablemodel.h#L153) and repopulate that on every select, but tbh I didn't want to mess with `BaseSqlTableModel` and potentially introduce a performance regression in `select()`.
Though I may try that and check if it is acceptable.

2024-04-17 08:39 UTC, ronso0 commented
I went with the position->row hash.
Works nicely, didn't noticew any performance regression in select().

2024-04-17 08:41 UTC, ronso0 commented
This is actually a bugfix for 2.4, though it's low prio and I was to lazy to resolve the conflicts when applying this to 2.4 (since I worked off a main-based branch with lots of changes).

2024-04-20 16:36 UTC, m0dB commented
LGTM with a minor nitpick.

2024-04-20 17:04 UTC, JoergAtGithub commented
What you mean with nitpick?

2024-04-20 21:23 UTC, m0dB commented
I mean my being "pingelig" about comparing with <=0 instead of -1

2024-04-20 21:29 UTC, JoergAtGithub commented
Did you miss to Submit your review? I don't see anything.

2024-04-20 21:47 UTC, m0dB commented
> Did you miss to Submit your review? I don't see anything.

Oops!

2024-05-01 06:13 UTC, JoergAtGithub commented
There's a merge conflict now

2024-05-01 09:51 UTC, ronso0 commented
I have rebased this onto 2.4 and dropped the 'p' prefix commit in order to hopefully reduce merge conflicts with main.

2024-05-26 22:11 UTC, ronso0 commented
@m0dB I think I addressed your comments, wanna check it once more?

2024-08-14 08:43 UTC, ronso0 commented
_ping_
I resolved the conflicts, all green now.

2024-08-16 08:12 UTC, daschuer requested changes
Its works like a charm. The position look up can be simplified see my comments.

2024-08-16 08:12 UTC, daschuer commented on src/library/playlisttablemodel.cpp
> +    // TODO Transpose m_trackPosToRow ?? Would it be faster?
This would be slightly faster here but comes with a penalty on every select call so probably not worth the effort IMHO. Remove the comment?

2024-08-17 12:37 UTC, ronso0 commented on src/library/basesqltablemodel.h
> +        int position; // used by playlist models only
True. I copied the trackId implementation, but the position is needed (explicitly) only once to populate TrackPos2Row, so this change makes sense. Thanks!

2024-08-17 12:40 UTC, ronso0 commented on src/library/basesqltablemodel.cpp
>          // current position defines the ordering
yup, removed and renamed order -> row

2024-09-15 18:59 UTC, daschuer approved these changes
LGTM. Thank you. Con you sqash the fixup and resolve the conflicts? 
Than we can merge this.

2024-09-20 06:05 UTC, daschuer commented
Thank you.

2024-09-20 06:05 UTC, merged