[DRAFT] resolve-from-urls
mixxxdj/mixxx pull request #13146
Opened 2024-04-20 21:14 UTC by m0dB

resolveTrackIdsFromUrls directly, without going through DragAndDropeHlper::supportedTracksFromUrls

2024-04-29 07:02 UTC, daschuer requested changes

2024-04-29 07:02 UTC, daschuer commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
A minor issue is that because if that, the QString is allocated twice. Maybe we find a workaround for that.

2024-04-29 07:02 UTC, daschuer commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
What happens if it is no local file? We should avoid "()"

2024-05-01 15:15 UTC, daschuer commented
This is still draft, move form 2.5-beta milestone?

2024-05-03 21:57 UTC, m0dB commented
> Could this eventually lead to the possibility of pasting YouTube URLs into Mixxx to pull, convert and load audio into the next available deck? (an aspect of #6277)

I don't think so...

2024-05-03 22:04 UTC, m0dB commented
> This is still draft, move form 2.5-beta milestone?

It is draft because I find it the surrounding code hard to understand. The sole purpose of this change is to fix https://github.com/mixxxdj/mixxx/issues/13100 , and it looks to me that it does, but I find it hard to say if it is the right solution (also because @ronso0 suggested other approaches) and to predict if this can have negative side effects.

I don't think we want to revert the tracklist shortkey handling for 2.5, as it is a very nice and very "announcable" improvement, but @ronso0 considers a https://github.com/mixxxdj/mixxx/issues/13100 a blocker (I think I agree), so it should be fixed.

I am not quite sure how to proceed... Who would be the most familiar with the surrounding code?

2024-05-03 23:00 UTC, ronso0 commented
gonna take a in-detail look soonish.
think this could slip in during beta IMOH (regression fix etc.)

2024-06-01 00:43 UTC, m0dB commented
Did you have a change to look at this @ronso0 ? Or do you think there is a better way to fix https://github.com/mixxxdj/mixxx/issues/13100 ?

2024-06-02 00:11 UTC, ronso0 commented
Well, it works as desired now, thanks!

I also have a hard time double-checking all callers, and I didn't spent time on an alternative fix.
Changes LGTM from what I can tell, but @daschuer's review is still open?

2024-06-02 00:11 UTC, ronso0 commented
I changed the base branch to 2.5, now that 2.6 has been split off.

2024-06-08 00:15 UTC, ronso0 commented
Yes, LGTM.
I propose to remove the Draft state and get this into 2.5-beta.

@daschuer What do you think?

2024-09-28 15:43 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
_friendly ping_ @m0dB

2024-09-28 15:44 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
@daschuer do you have a fix in mind?

2024-09-28 15:58 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
> What happens if it is no local file? We should avoid "()"

What about this? Like in DragAndDropHelper::supportedTracksFromUrls
```suggestion
        QString urlStr = url.isLocalFile() ? url.toLocalFile() : url.toString()
        pathList << "(" + SqlStringFormatter::format(m_database, urlStr) + ")";
```

2024-10-01 07:12 UTC, daschuer commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
Yes, that looks good.

2024-11-21 13:26 UTC, ronso0 commented
@m0dB @daschuer How shall we proceed here?
Can we still get this into 2.5, with [the fixup I proposed](https://github.com/mixxxdj/mixxx/pull/13146#discussion_r1779664436)?
Or should we add the 'bug' to the "Known issues" for 2.5.0 and try to get in into 2.5.1?

2024-11-22 06:49 UTC, daschuer commented
I consider this is as "ready for merge" with your fix in place. @m0dB will you have time to prepare that for  merge?

2024-12-01 18:44 UTC, m0dB commented on src/library/dao/trackdao.cpp
> +        pathList << "(" + SqlStringFormatter::format(m_database, url.toLocalFile()) + ")";
done

2024-12-01 18:46 UTC, m0dB commented
Added the change suggested by @daschuer and rebased on 2.5.

2024-12-01 18:52 UTC, m0dB commented
Sorry, having issues pushing...

2024-12-01 19:01 UTC, m0dB commented
https://github.com/mixxxdj/mixxx/pull/13958

2024-12-01 22:18 UTC, daschuer commented
Close in favor of https://github.com/mixxxdj/mixxx/pull/13958

2024-12-01 22:18 UTC, closed without merging