remove flanger mapping with quickeffect toggle
mixxxdj/mixxx pull request #13196
Opened 2024-05-01 19:41 UTC by Swiftb0y

Fixes #13134

Tbh. this is just an idea. I don't know how much sense it makes. I would appreciate alternative suggestions.

2024-05-10 13:44 UTC, Swiftb0y commented
@Phr3d13 is this solution okay for you? @JoergAtGithub do you have time to review and merge this?

2024-05-13 16:31 UTC, JoergAtGithub requested changes

2024-05-13 16:31 UTC, JoergAtGithub commented on res/controllers/Novation Dicer.midi.xml
> +                <group>[QuickEffectRack1_[ChannelI]_Effect1]</group>
```suggestion
                <group>[QuickEffectRack1_[Channel2]_Effect1]</group>
```

2024-05-13 16:31 UTC, JoergAtGithub commented on res/controllers/Novation Dicer.midi.xml
> +                <group>[QuickEffectRack1_[ChannelI]_Effect1]</group>
```suggestion
                <group>[QuickEffectRack1_[Channel1]_Effect1]</group>
```

2024-05-13 16:31 UTC, JoergAtGithub commented on res/controllers/Novation Dicer.midi.xml
>                  <key>NovationDicer.flangeEffect</key>
```suggestion
                <key>NovationDicer.enableEffect</key>
```
The function name is not matching to the functionality anymore.

2024-05-13 16:44 UTC, Swiftb0y commented
whoops, embarrasing, see fixup

2024-05-13 17:30 UTC, JoergAtGithub approved these changes
LGTM now!

2024-05-17 15:42 UTC, merged

2024-05-17 15:57 UTC, Swiftb0y commented
Thank you for the review ;)

2024-06-06 22:44 UTC, ronso0 commented
> Also, if it's removed, why is it still an option?

This doesn't remove the Flanger effect (why?), only the deprecated direct effect control from the time when Mixxx only had a handful of effects, and only for this particular mapping.