(fix) Effects: show newly added effects, read/write HiddenEffects
mixxxdj/mixxx pull request #13326
Opened 2024-06-04 17:34 UTC by ronso0

Fixes #11343

Add `HiddenEffects` to effects.xml

Small one-time issue after upgrade:
(new) effects that users have set visible and then set hidden again will now be set visible again :man_shrugging:

2024-06-04 17:45 UTC, ronso0 commented
About the inline TODO:
Currently manifests are split into visible/hidden by DlgPrefEffects only ([here](https://github.com/mixxxdj/mixxx/blob/ac37870c428cc50b0586293844ccbc2b2e1516d1/src/preferences/dialog/dlgprefeffects.cpp#L110-L114)). And this PR adds similiar actions to `EffectsManager::saveEffectsXml()`.
We may keep it that way, or refactor/split VisibleEffectsList in order to have member pointers to both lists in `EffectsManager` and simply call `getList()` when saving to xml.
Wdyt?

2024-06-04 18:22 UTC, Swiftb0y commented
> refactor/split VisibleEffectsList in order to have member pointers to both lists in EffectsManager and simply call getList() when saving to xml.


What do you think about refactoring the `VisibleEffectsList`, so its just `EffectsList` which then manages the hidden vs visible effects internally (enforcing the constraint that the visible and hidden effectslists are disjunct). That would allow keeping EffectsManager simpler. Alternatively, having `VisibleEffectsList` and `HiddenEffectsList` would also be an option, though I'm skeptical that that would introduce a lot of boilerplate.

2024-06-04 19:35 UTC, ronso0 commented
Yeah that could work but I can't promise to work on that soonish.

> Alternatively, having `VisibleEffectsList` and `HiddenEffectsList` would also be an option, though I'm skeptical that that would introduce a lot of boilerplate.

 Well, the difference is only the xml node name for read/write and one else branch when reading. So both could be derived from a common EffectsList.
Though, we actually need HiddenEffectsList only for read/write, no unit is accessing that list otherwise (via at(), next() etc.)

2024-06-05 09:57 UTC, Swiftb0y commented
Yeah, idk. I can't decide on the best solution either.

2024-06-05 12:07 UTC, ronso0 commented
After all, this is a _TO DO_ ; p
I'll add some more..

As long as the current solution works we should merge it to make the new effects visible.
I'll definitely take another look during beta.

2024-06-05 14:30 UTC, daschuer requested changes
The solution looks good. I have added some suggestions for readability.

2024-06-05 14:30 UTC, daschuer commented on src/effects/effectsmanager.cpp
> +    VisibleEffectsList pHiddenEffectsList;
```suggestion
    VisibleEffectsList hiddenEffectsList;
```

2024-06-05 14:30 UTC, daschuer commented on src/effects/effectsmanager.cpp
> +    }
This can be also, integrated into VisibleEffectsList

2024-06-05 14:30 UTC, daschuer commented on src/effects/visibleeffectslist.cpp
>          setList(pBackendManager->getManifestsForBackend(EffectBackendType::BuiltIn));
Is this condition still relevant? We will add  new effects anyway in the outside code.

2024-06-05 21:27 UTC, ronso0 commented
Thanks for your review @daschuer.
Your comments pretty much point to the refactoring we discussed above.

I'll see what I can do with minimal effort.

2024-06-09 17:07 UTC, daschuer approved these changes
LGTM, please sqash the fixup and merge. Thank you.

2024-06-09 20:10 UTC, daschuer commented
Since this is a bug fix it can go to the 2.5 branch at any time. I move that to the 2.5.0 milestone and proceed with the 2.5-beta release.

2024-06-09 20:34 UTC, ronso0 commented
Well, it's ready. Merge whenever it fits.

2024-06-29 11:36 UTC, JoergAtGithub commented
Since 2.5 beta is out now, lets merge this into 2.5.

2024-06-29 11:36 UTC, merged