[WIP] Windows installer improvements
mixxxdj/mixxx pull request #1336
Opened 2017-08-29 07:34 UTC by sblaisot

[x] Improve warning messages dialogs
[ ] Improve update path : automatically launch older version uninstaller and explain user what to do

2017-08-29 08:37 UTC, daschuer requested changes

2017-08-29 08:37 UTC, daschuer commented on build/wix/Localization/mixxx_de-DE.wxl
> +  <String Id="x86VersionWarning">Sie sind dabei, die 32-Bit-Version auf einem 64-Bit-Betriebssystem zu installieren. Wir empfehlen mit der 64-Bit-Version für bessere Performance. Sie können das der 6
Sie installieren gerade die 32-Bit-Version auf einem 64-Bit-Betriebssystem. Wir empfehlen stattdessen die 64-Bit-Version für eine bessere Performance zu installieren. Sie können ...

2017-08-29 08:39 UTC, daschuer commented
Are all translations auto generated? This It is probably a good idea to hold them back until a native speaker has prove read them.

2017-08-29 10:27 UTC, sblaisot commented
Nope, these are translations from transifex. I only fond a way  to remove special chars from the text to make translation easier. Please update translations from transifex if needed.

2017-08-29 19:35 UTC, daschuer commented
I cannot edit the transiflex translation. Do I need to get permission?

2017-08-30 07:04 UTC, sblaisot commented
The transifex account daschuer2 is authorized to translate to the de and de_DE languages.
If you have any other request (other account or language), you can request it directly on the transifex website and I will be happy to add you to whatever language you need.

You will then be able to translate the windows installer strings to de_DE at this url: https://www.transifex.com/mixxx-dj-software/mixxxdj-windows-installer/translate/#de_DE/

2017-09-10 15:38 UTC, daschuer commented
I can only add my text as a suggestion. 
I have just done it.

2017-09-10 15:38 UTC, daschuer commented
So this PR can be merged now. Thank you.

2017-09-10 15:38 UTC, merged

2017-09-10 16:28 UTC, sblaisot commented
oops, I didn't finished improving upgrade path ("WIP" in the subject, unchecked boxes in the description).
nevermind, I'll open a new PR for the next work ;)
Thanks for merging @daschuer

2017-09-26 05:40 UTC, Be-ing commented
Any progress on automatically running the old uninstaller?

2017-09-26 14:54 UTC, Be-ing commented
Great, thank you.