fix(engine-prime): build-failure
mixxxdj/mixxx pull request #13397
Opened 2024-06-24 09:39 UTC by Swiftb0y

Explicitly instantiate default destructor in out-of-line (in .cpp) because destructing a `std::unique_ptr<Waveform>` needs `Waveform` to be complete at the point of destruction.

2024-06-24 09:44 UTC, Swiftb0y commented
Interestingly, this only surfaced because of f031f51393c5ae2bb923fc331408330878285617

2024-06-24 11:54 UTC, daschuer requested changes
Please add also the override keyword. 
It is a good practice to make the destructor virtual when the class had virtual functions. A virtual function can not be inlined btw.

2024-06-24 12:26 UTC, Swiftb0y commented
right, but `~EnginePrimeExportJob` doesn't need to be virtual as the class is not designed to be inherited from technically, but I'll add it anyways.

2024-06-25 15:47 UTC, daschuer approved these changes
Thank you. LGTM

2024-06-25 15:47 UTC, merged