Paintable cleanup
mixxxdj/mixxx pull request #13435
Opened 2024-07-03 05:24 UTC by JoergAtGithub

Removed 2 unused methods
Changed code to return early style
Implemented missing SVG branch for Paintable::toImage()
Replaced hardcoded transparency color by Qt::transparent
Use std::move instead reset/release

2024-07-03 07:26 UTC, daschuer requested changes
LGTM, only a minor comment. 

Reading the code I notice that we render the SVG over and over again when for example called here:

https://github.com/mixxxdj/mixxx/blob/c0b4f50082b27767305357551c4c8f18b4db95cc/src/widget/wbattery.cpp#L168

Does it make sense to keep a copy of the QImage, and skip all the logic in draw, if the size did not change? I am not sure if this works, because I don't know when the SVG is exactly rendered and if there is already a caching involved.

2024-07-03 07:26 UTC, daschuer commented on src/widget/paintable.cpp
> +        image.fill(Qt::transparent);
Why is this required? Please add a source code comment.

2024-07-03 08:33 UTC, Swiftb0y commented on src/widget/paintable.cpp
> +        QImage image(m_pSvg->defaultSize(), QImage::Format_ARGB32);
```suggestion
        QImage image(m_pSvg->defaultSize(), QImage::Format_ARGB32_Premultiplied);
```
![image](https://github.com/mixxxdj/mixxx/assets/12380386/4fe47653-4df6-40d0-9e30-0dca4c1027a0)

2024-07-04 07:04 UTC, JoergAtGithub commented
> Reading the code I notice that we render the SVG over and over again when for example called here:
> 
> https://github.com/mixxxdj/mixxx/blob/c0b4f50082b27767305357551c4c8f18b4db95cc/src/widget/wbattery.cpp#L168

Yes we do, this is addressed in #12904 for 2.4 and not in this PR.

2024-07-04 16:22 UTC, Swiftb0y approved these changes
LGTM. waiting for @daschuer

2024-07-05 15:22 UTC, daschuer approved these changes
Thank you

2024-07-05 15:23 UTC, merged