Updating m_hotcuePosition to readonly
mixxxdj/mixxx pull request #13446
Opened 2024-07-05 17:56 UTC by LuccaPaiva

Updating m_hotcuePosition to readonly
Creating slotPositionChangeRequest to check if the hotcue is set
Fixes #10409

2024-07-06 11:46 UTC, daschuer requested changes
Thank you for taking care. 
 
In addition you need to replace all 
m_hotcuePosition->set() calls by setAndConfirm() 
You should also move all code from the valueChanged() to valueChangeRequest().

2024-07-06 11:46 UTC, daschuer commented on src/engine/controls/cuecontrol.cpp
> +    if (!m_hotcuePosition->get()) {
```suggestion
    if (m_hotcuePosition->get() != Cue::kNoPosition) {
```

2025-01-22 15:19 UTC, ronso0 commented
@LuccaPaiva Any chance you pick this up again and address the review comments?

2026-02-21 23:24 UTC, ronso0 commented
There hasn't been any activity for a year, unfortunately, so I'm closing this now to clean up our PR list.
@LuccaPaiva  please let us know when you like to continue your work here. Would be a pity to throw it away..

2026-02-21 23:24 UTC, closed without merging