scrolling qml waveformdisplay working
mixxxdj/mixxx pull request #13470
Opened 2024-07-14 13:24 UTC by acolombier

This PR is a rebase of @m0dB's `qml_scrolling_waveform` on the latest main

The waveform rendering approach should provided better result in the long run and should integrate with the new `allshader` approach.

Currently, the waveform rendering logic which happen in `QmlWaveformDisplay::updatePaintNode` is duplicated (or rather strongly inspired) from the RGB allshader rendering. A "definition of ready" for this PR would be to have some kind of compatibility layer/integration to reuse the rendering logic define in `allshader` and should support at least one waveform type logic (e.g `RGB`)

2024-10-16 22:36 UTC, acolombier commented
Note that this is still being actively worked on with @m0dB and myself!

2025-01-17 21:14 UTC, Holzhaus commented
Unfortunately, there are merge conflicts now.

2025-01-17 21:24 UTC, Holzhaus commented
FYI, the PR is still broken :(

```
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


endoftrack.frag -> endoftrack.frag.qsb exposed as :/shaders/rendergraph/endoftrack.frag.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


endoftrack.vert -> endoftrack.vert.qsb exposed as :/shaders/rendergraph/endoftrack.vert.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


pattern.frag -> pattern.frag.qsb exposed as :/shaders/rendergraph/pattern.frag.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


pattern.vert -> pattern.vert.qsb exposed as :/shaders/rendergraph/pattern.vert.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


rgb.frag -> rgb.frag.qsb exposed as :/shaders/rendergraph/rgb.frag.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


rgb.vert -> rgb.vert.qsb exposed as :/shaders/rendergraph/rgb.vert.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


rgba.frag -> rgba.frag.qsb exposed as :/shaders/rendergraph/rgba.frag.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


rgba.vert -> rgba.vert.qsb exposed as :/shaders/rendergraph/rgba.vert.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


texture.frag -> texture.frag.qsb exposed as :/shaders/rendergraph/texture.frag.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


texture.vert -> texture.vert.qsb exposed as :/shaders/rendergraph/texture.vert.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)


unicolor.frag -> unicolor.frag.qsb exposed as :/shaders/rendergraph/unicolor.frag.qsb
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2127 (get_target_property):
  get_target_property() called with non-existent target "rendergraph_sg".
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:103 (_qt_internal_expose_source_file_to_ide)
  /usr/lib/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake:354 (_qt_internal_add_shaders_impl)
  res/shaders/rendergraph/CMakeLists.txt:16 (qt6_add_shaders)
```

2025-01-19 02:37 UTC, acolombier commented
@Holzhaus this should now be ready for some very early testing!

2025-01-19 23:50 UTC, JoergAtGithub commented
@m0dB @acolombier I wonder if a clearer seperation between QML and QtQuick would be of benefit here, as we could use a QQuickWindow instead of the QOpenGLWindow in the existing QWidget GUI: https://doc.qt.io/qt-6/qtquick-embeddedinwidgets-example.html
Wouldn't this provide us the use of native graphic APIs, instead of OpenGL - for all builds with recent Qt? And we are just in the process to update the VCPKG buildenv for macOS and Windows builds to Qt6.8.1.

2025-01-20 23:18 UTC, Holzhaus commented
Hi, configuring works now. I'm getting the following build error now:

```cpp
[ 25%] Building CXX object CMakeFiles/mixxx-qml-lib.dir/src/qml/qmlstemsmodel.cpp.o
In file included from src/rendergraph/scenegraph/../common/rendergraph/assert.h:4,
                 from src/rendergraph/scenegraph/../common/rendergraph/material.h:6,
                 from src/rendergraph/scenegraph/../common/rendergraph/geometrynode.h:5,
                 from src/waveform/renderers/allshader/waveformrendermark.h:5,
                 from src/waveform/renderers/allshader/waveformrendermark.cpp:1:
src/waveform/renderers/allshader/waveformrendermark.cpp: In member function ‘void {anonymous}::WaveformMarkNode::update(float, float, float)’:
src/waveform/renderers/allshader/waveformrendermark.cpp:50:35: error: ‘RoundToPixel’ was not declared in this scope
   50 |         DEBUG_ASSERT(std::abs(x - RoundToPixel(devicePixelRatio)(x)) < epsilon);
      |                                   ^~~~~~~~~~~~
src/rendergraph/scenegraph/../common/rendergraph/../../../util/assert.h:59:32: note: in definition of macro ‘DEBUG_ASSERT’
   59 |         if (!static_cast<bool>(cond)) [[unlikely]] {                        \
      |                                ^~~~
src/waveform/renderers/allshader/waveformrendermark.cpp:51:35: error: ‘RoundToPixel’ was not declared in this scope
   51 |         DEBUG_ASSERT(std::abs(y - RoundToPixel(devicePixelRatio)(y)) < epsilon);
      |                                   ^~~~~~~~~~~~
src/rendergraph/scenegraph/../common/rendergraph/../../../util/assert.h:59:32: note: in definition of macro ‘DEBUG_ASSERT’
   59 |         if (!static_cast<bool>(cond)) [[unlikely]] {                        \
      |                                ^~~~
make[2]: *** [CMakeFiles/mixxx-qml-lib.dir/build.make:666: CMakeFiles/mixxx-qml-lib.dir/src/waveform/renderers/allshader/waveformrendermark.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:803: CMakeFiles/mixxx-qml-lib.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

2025-01-21 13:13 UTC, m0dB commented
I fixed this in the rg-wr-… PR, so if @acolombier merges the latest commits of my branches it will be fixed here too.

2025-02-03 14:02 UTC, acolombier commented
@Swiftb0y I assume you are currently looking into this - you reacted with the :eye: on the PR - thank you!

There is still a lot to work on, but I'd been keen to hear your feedback on how to propagate properties for each renderers.

Currently, there is two clashing design, and I will need to unify it into one, but I'm having a hard time to take a decision.

- **Design 1**: The renderer gets initialised (the `setup` method) and holds properties statically. This means that the `LegacySkinParser` will need to extract these property from the XMLs and inject it, in the same way that the QML proxy will do it with its property. Pro: contained, no lifecycle issue, easy to maintain. Con: No dynamic propagation - property update requires to rebuild the renderer stack (slow!)
- **Design 2**: The renderer gets initialised with a reference to the a "provider", which holds properties. This means that the `LegacySkinParser` (or some object in between) will need to extract and hold these properties from the XMLs and will provide them ondemand over few getters, in the same way that the QML proxy will do it with its property. Pro: generic interface, dynamic update, quick feedback. Con: lifecycle (no parenting between QML object and renderer, possible hierarchy on Legacy)

It feels like there is no perfect answers. Also QML is still quite unstable (note the number of changes made in this PR to consolidate it - happy to move some in other PR btw) so I don't think we should overly concern on stability yet with QML, as long as we don't introduce risks on legacy.

2025-02-03 15:40 UTC, Swiftb0y commented
> I assume you are currently looking into this - you reacted with the 👁️ on the PR - thank you!

I'm actually not atm, I'm sorry my reaction gave that impression. I'll try to once the preliminary PRs have been merged. 

I have not looked enough into this PR to even understand the problem you're describing, so I can't provide any opinion.

2025-02-03 21:28 UTC, Holzhaus commented
Ok, I applied to following patch to work around the build error:

```udiff
diff --git a/src/qml/qmlwaveformrenderer.cpp b/src/qml/qmlwaveformrenderer.cpp
index 3095243945..1d368ebfd4 100644
--- a/src/qml/qmlwaveformrenderer.cpp
+++ b/src/qml/qmlwaveformrenderer.cpp
@@ -89,7 +89,7 @@ QmlWaveformRendererFactory::Renderer QmlWaveformRendererPreroll::create(
 QmlWaveformRendererFactory::Renderer QmlWaveformRendererRGB::create(
         WaveformWidgetRenderer* waveformWidget) const {
     auto* renderer = new WaveformRendererRGB(waveformWidget, m_position, m_options, this);
-    renderer->setup(
+    renderer->setupColors(
             m_axesColor,
             m_lowColor,
             m_midColor,
diff --git a/src/waveform/renderers/allshader/waveformrendererrgb.cpp b/src/waveform/renderers/allshader/waveformrendererrgb.cpp
index 40b92d28e5..409232a66a 100644
--- a/src/waveform/renderers/allshader/waveformrendererrgb.cpp
+++ b/src/waveform/renderers/allshader/waveformrendererrgb.cpp
@@ -29,7 +29,7 @@ WaveformRendererRGB::WaveformRendererRGB(WaveformWidgetRenderer* waveformWidget,
     setUsePreprocess(true);
 }

-void WaveformRendererRGB::setup(const QColor& axesColor,
+void WaveformRendererRGB::setupColors(const QColor& axesColor,
         const QColor& lowColor,
         const QColor& midColor,
         const QColor& highColor) {
diff --git a/src/waveform/renderers/allshader/waveformrendererrgb.h b/src/waveform/renderers/allshader/waveformrendererrgb.h
index acd06ec50f..47833edd0d 100644
--- a/src/waveform/renderers/allshader/waveformrendererrgb.h
+++ b/src/waveform/renderers/allshader/waveformrendererrgb.h
@@ -21,7 +21,7 @@ class allshader::WaveformRendererRGB final
     // Pure virtual from WaveformRendererSignalBase, not used
     void onSetup(const QDomNode& node) override;

-    void setup(const QColor& axesColor,
+    void setupColors(const QColor& axesColor,
             const QColor& lowColor,
             const QColor& midColor,
             const QColor& highColor);
```


Now it crashes with a segfault:

```
Core was generated by `./mixxx --qml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ControlDoublePrivate::getKey (this=<optimized out>) at /home/jan/Projects/mixxx/src/control/control.h:143
143	        return m_key;
[Current thread is 1 (Thread 0x7ed96b7fe6c0 (LWP 176578))]
>>> bt
#0  ControlDoublePrivate::getKey (this=<optimized out>) at /home/jan/Projects/mixxx/src/control/control.h:143
#1  ControlProxy::getKey (this=0x0) at /home/jan/Projects/mixxx/src/control/controlproxy.cpp:25
#2  0x000062b631380b8d in allshader_sg::WaveformRendererStem::init (this=0x7ed95c366280)
    at /home/jan/Projects/mixxx/src/waveform/renderers/allshader/waveformrendererstem.cpp:35
#3  0x000062b630e2ec04 in WaveformWidgetRenderer::init (this=this@entry=0x62b65a1149c8)
    at /usr/include/qt6/QtCore/qarraydatapointer.h:119
#4  0x000062b63135c21e in mixxx::qml::QmlWaveformDisplay::updatePaintNode
    (this=0x62b65a1149a0, node=<optimized out>) at /home/jan/Projects/mixxx/src/qml/qmlwaveformdisplay.cpp:132
#5  0x00007edac7a6e984 in QQuickWindowPrivate::updateDirtyNode (this=0x62b661806220, item=0x62b65a1149a0)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:2271
#6  0x00007edac7a61e1d in QQuickWindowPrivate::updateDirtyNodes (this=this@entry=0x62b661806220)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:2013
#7  0x00007edac7a629c6 in QQuickWindowPrivate::syncSceneGraph (this=<optimized out>)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:566
#8  0x00007edac7c465db in QSGRenderThread::sync (this=<optimized out>, inExpose=true)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/scenegraph/qsgthreadedrenderloop.cpp:553
#9  QSGRenderThread::syncAndRender (this=<optimized out>)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/scenegraph/qsgthreadedrenderloop.cpp:716
#10 QSGRenderThread::run (this=0x62b664890830)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/scenegraph/qsgthreadedrenderloop.cpp:975
#11 0x00007edac22d831b in operator() (__closure=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread_unix.cpp:375
#12 (anonymous namespace)::terminate_on_exception<QThreadPrivate::start(void*)::<lambda()> > (t=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread_unix.cpp:311
#13 QThreadPrivate::start (arg=0x62b664890830)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/thread/qthread_unix.cpp:339
#14 0x00007edac1aa32ce in ??? () at /usr/lib/libc.so.6
#15 0x00007edac1b2829c in ??? () at /usr/lib/libc.so.6
```

2025-02-03 21:54 UTC, Holzhaus commented
@acolombier Kudos, looks great! And the annoying flickering that we saw with the previous waveforms is also gone.

Some minor issues I found:
1. Something is wrong with the clipping - if i turn up the Hi/Mids using the EQ, the waveforms overlap the rest of the UI.
2. The waveform marks wiggle around a bit when scratching.


https://github.com/user-attachments/assets/74708116-7b91-4dc1-b57e-607e69b347b9

2025-02-04 01:15 UTC, acolombier commented
Thanks for you feedback @Holzhaus! Kudos to @m0dB to make that possible with the rendergraph!
 
> Some minor issues I found:
> 
>     1. Something is wrong with the clipping - if i turn up the Hi/Mids using the EQ, the waveforms overlap the rest of the UI.
I'm actually still not completely sure how to use the scene graph clipping - Any pointer or fix for this @m0dB ?
>     2. The waveform marks wiggle around a bit when scratching.
Indeed, I can also reproduce it locally - it feels like the renderer are not synched for some reason (beats are responding faster than signal, itself responding faster than marker). I must say here again, I have no idea where to start and could definitely use some help @m0dB :smile:

2025-02-12 00:50 UTC, acolombier commented
> 2. The waveform marks wiggle around a bit when scratching. 

This seems to be better now, I would appreciate if you could give this another go 

Regarding [this comment](https://github.com/mixxxdj/mixxx/pull/13470#issuecomment-2631091530), I went with a 3rd option, using signal/slots between the QML element and the rendergraph instances

2025-02-12 02:32 UTC, acolombier commented
I'm getting `Target "rendergraph_sg" links to target "Qt6::Quick" but the target was not` on Windows - any idea how this can be solved? I believe QtQuick should already be included in VCPKG, as it builds fine on Mac

2025-02-12 12:04 UTC, Swiftb0y reviewed
couple surface-level things I noticed

2025-02-12 12:04 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.h
> +    Q_PROPERTY(QColor color READ color WRITE setColor)
IIRC properties also need a `NOTIFY` to properly work in Qml. At least if they're supposed to support reactive bindings.

2025-02-12 12:04 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.h
> +    QList<QmlWaveformMarkRange*> m_ranges;
what are the lifetime requirements on the `QmlWaveformMarkRange*`? Is it possible to get a use after free if Qml holds on to this list after a new track has been loaded?

2025-02-12 14:07 UTC, acolombier commented on src/qml/qmlwaveformrenderer.h
> +    }
Yup, makes sense!

2025-02-12 14:08 UTC, acolombier commented on src/qml/qmlwaveformrenderer.h
> +    Q_PROPERTY(QColor color READ color WRITE setColor)
Yeah, it's missing on few since the property/binding was not used previously, but with my yesterday commit, it should be possible to allow runtime update of those so I'll had the missing one

2025-02-12 19:12 UTC, acolombier commented on src/qml/qmlwaveformrenderer.h
> +    }
Changed and removed unused accessor, reduce file from 587 lines to 430

2025-02-14 02:38 UTC, acolombier commented
@Holzhaus the two issues you raised should be fixed now, could you please give it another go?

2025-02-17 20:42 UTC, Holzhaus reviewed
Hey, didn't really review the whole thing, just some minor comments.

2025-02-17 20:42 UTC, Holzhaus commented on res/controllers/DummyDeviceDefaultScreen.qml
> +                            // <!-- Loop -->
```suggestion
                            // Loop
```
And elsewhere

2025-02-17 20:42 UTC, Holzhaus commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
What do you think about this?

```suggestion
                text: '◢'
```

2025-02-17 20:42 UTC, Holzhaus commented on res/qml/WaveformDisplay.qml
> +            // <!-- Loop -->
```suggestion
            // Loop
```
And elsewhere

2025-02-17 20:42 UTC, Holzhaus commented on res/qml/WaveformDisplay.qml
> +            Mixxx.WaveformMark {
Btw, in the long term I'd like to be able to define a mark delegate from QML. That would allow different skins to have a way to define a custom look (not just custom colors) for waveform marks.

Maybe by defining a QML item here, which is then rendered to a pixmap and then copied to the waveform. Nothing for this PR, but this would be a long term goal.

2025-02-17 20:42 UTC, Holzhaus commented on src/qml/qmlwaveformrenderer.cpp
> +    for (auto* pMark : m_ranges) {
Shouldn't this be const?

2025-02-17 20:42 UTC, Holzhaus commented on src/qml/qmlwaveformrenderer.cpp
> +    renderer->setBgPlayColor(m_playMarkerBackground);
I'd suggest to name these consistently and expressive:

```suggestion
    renderer->setPlayMarkerForegroundColor(m_playMarkerForegroundColor);
    renderer->setPlayMarkerBackgroundColor(m_playMarkerBackgroundColor);
```

2025-02-17 20:42 UTC, Holzhaus commented on src/qml/qmlwaveformrenderer.cpp
> +    for (auto* pMark : m_marks) {
Const?

2025-02-17 20:42 UTC, Holzhaus commented on src/qml/qmlwaveformrenderer.cpp
> +                --priority)));
Is this really supposed to go 0, -1, -2, ...?

Also, I would be in favor of splitting the increment/decrement step onto a separate line for readability.

2025-02-17 20:42 UTC, Holzhaus commented on src/waveform/renderers/allshader/waveformrendererstem.cpp
> +    // applyCompensation = false, as we scale to match filtered.all
I have no idea about this but why did the value change but the comment text did not?

2025-02-17 21:21 UTC, acolombier commented on src/qml/qmlwaveformrenderer.cpp
> +    renderer->setBgPlayColor(m_playMarkerBackground);
This was auto-generated from the members name, but I think we can rename it as well

2025-02-17 21:22 UTC, acolombier commented on src/qml/qmlwaveformrenderer.cpp
> +                --priority)));
This was copied from the renderer setup logic used by the legacy skin parser so I cannot do much on what is expected there. Sure, happy to make that on two lines

2025-02-17 21:26 UTC, acolombier commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
I started with this and it didn't render so well in the UI. Overall, the whole QML design probably needs a good rework anyway (see Zulip) so I thought I'll go with the more explicit now but happy to keep this char if we think it's better

2025-02-17 21:43 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.cpp
> +    for (auto* pMark : m_ranges) {
use `std::as_const` too. Otherwise it may still detach the container.

2025-02-17 23:24 UTC, acolombier commented on src/qml/qmlwaveformrenderer.cpp
> +                --priority)));
Added a comment above to explain where this logic comes from

2025-02-17 23:27 UTC, acolombier commented on src/waveform/renderers/allshader/waveformrendererstem.cpp
> +    // applyCompensation = false, as we scale to match filtered.all
The comment was incorrect (see line above, using `applyCompensation = false`). It was copy from [here](https://github.com/mixxxdj/mixxx/blob/7b75517639fa1d9cfcc1905291ed2bd25122cc6a/src/waveform/renderers/allshader/waveformrendererrgb.cpp#L110) so looks like I must have messed up by accident when I implemented this renderer

2025-02-17 23:29 UTC, acolombier commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
Hmmm not a big fan
![image](https://github.com/user-attachments/assets/0b05464b-a8ac-475d-a1db-225e72e06b77)

Wdyt? Shall I keep with text till we can to properly design this?

2025-02-17 23:41 UTC, Holzhaus commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
I think the icon looks weird, but better than the text ;-) but I leave it up to you, we need to improve the UI later on anyway (Maybe have a frame around both buttons, put the intro icon as the group label, and then have something like `|-` and `-|` as button labels or something like that).

2025-02-18 01:26 UTC, acolombier commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
Yeah, for now I've been only focusing on feature, since I'm also working on a whole design project for QML so didn't want to waste time with temporary measure for this

2025-02-18 18:50 UTC, Holzhaus commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
Yup. I think the waveforms and the library are the two major issues that prevent me from using in in a set. Most other stuff is working from my controller anyway 😁

2025-02-18 19:37 UTC, Holzhaus commented on res/qml/Deck.qml
> +                text: "Intro\nStart"
Yup. I think the waveforms and the library are the two major issues that prevent me from making qml actually usable in a set. Most other stuff is working from my controller anyway 😁

2025-02-23 11:11 UTC, JoergAtGithub commented
I could build this PR locally now, the build passed, but there are obviously errors during the build, which are not detected as build fail:
```
  [22/941] Generating .qsb/unicolor.frag.qsb
  Failed to run spirv-opt -O C:\Users\Joerg.WORLDWARTWEB\AppData\Local\Temp\qsb-NkwHbf\qsb_spv_temp -o C:\Users\Joerg.WORLDWARTWEB\AppData\Local\Temp\qsb-NkwHbf\qsb_spv_temp_out: Process failed to start: Das System kann die angegebene Datei nicht finden.
```

2025-02-23 11:39 UTC, JoergAtGithub commented
At the start I get always asserts, because renderer.renderer is NULL:
```
Program: D:\mixxx\build\x64__off\Qt6Cored.dll
Module: 6.5.3
File: D:\mixxx\src\util\logging.cpp
Line: 372

DEBUG ASSERT: "renderer.renderer" in function class QSGNode *__cdecl mixxx::qml::QmlWaveformDisplay::updatePaintNode(class QSGNode *,struct QQuickItem::UpdatePaintNodeData *) at D:\mixxx\src\qml\qmlwaveformdisplay.cpp:123
```
If I ignore these asserts, it starts up and work somehow. With much lower CPU usage than the normal OpenGL version.

2025-02-23 12:40 UTC, acolombier commented
> It seems spirv-tools is not specified in our VCPKG buildenv. But the configuration seems also be wrong, as it runs this build step in %temp% instead of the configured build directory.

I'll try to look into this - I've also spotted the problem, but not entirely sure how to approach it

> At the start I get always asserts, because renderer.renderer is NULL:

Ah yes, this is likely because you are running with `STEM=OFF`, leading to a [null renderer](https://github.com/mixxxdj/mixxx/blob/7b6888943a4119054d42dd5007352d24773a7487/src/qml/qmlwaveformrenderer.h#L357). I'll add some kind of `isSupported` logic to silence this correctly.

> Mixxx starts up and waveforms work. With much lower CPU usage than the normal OpenGL version.

That is great to hear!

2025-02-23 14:05 UTC, acolombier commented
> > It seems spirv-tools is not specified in our VCPKG buildenv. But the configuration seems also be wrong, as it runs this build step in %temp% instead of the configured build directory.
> 
> I'll try to look into this - I've also spotted the problem, but not entirely sure how to approach it

After investigation, this is coming from [this rendergraph command](https://github.com/mixxxdj/mixxx/blob/84f8966f79389d0f87573f20be23b7bd4f34d9fa/src/rendergraph/shaders/CMakeLists.txt#L35). I will see if I can fix it within a given time, but I'd like this not to block this feature to go in 2.6. Note the byproduct if this failure, is only to lack some shader optimisation, which didn't exist prior rendergraph so no regression there.

2025-02-23 22:35 UTC, acolombier commented
> > It seems spirv-tools is not specified in our VCPKG buildenv. But the configuration seems also be wrong, as it runs this build step in %temp% instead of the configured build directory.
> 
> I'll try to look into this - I've also spotted the problem, but not entirely sure how to approach it

Sadly, this is no easy fix, so I have disabled the broken optimisation of the shader. This will need to be looked at separately

2025-02-24 11:30 UTC, acolombier commented
@JoergAtGithub all the issues reported should be fixed now - I have squashed my commits so this is ready to go for 2.6!

2025-02-24 19:14 UTC, JoergAtGithub requested changes
Please fix the remaining 10 Clazy warnings: https://github.com/mixxxdj/mixxx/actions/runs/13497007080?pr=13470

2025-02-24 19:14 UTC, JoergAtGithub commented on src/waveform/renderers/allshader/waveformrendererstem.cpp
> +    const int reserved = numVerticesPerLine * (8 * stripLength + 1);
```suggestion
    const int reserved = numVerticesPerLine * (mixxx::audio::ChannelCount::stem() * stripLength + 1);
```
Did I guess right, where 8 comes from?

2025-02-24 19:14 UTC, JoergAtGithub commented on src/waveform/renderers/waveformrenderersignalbase.cpp
> +            highGain *= m_highVisualGain;
```suggestion
            lowVisualGain *= m_lowVisualGain;
            midVisualGain *= m_midVisualGain;
            highVisualGain *= m_highVisualGain;
```
Left hand side is also a visual gain

2025-02-25 00:52 UTC, acolombier commented on src/waveform/waveform.h
> +    FilterCount = 4 };
Makes sense - since the enum will create a symbol on the global scope, I kept `All` and `Count` prefixed with enum type. This could probably use a cleanup but this is out of scope for this PR.

2025-02-25 02:09 UTC, JoergAtGithub approved these changes
Code LGTM! Works flawless on Windows, with and without --qml!

2025-02-25 10:15 UTC, Swiftb0y reviewed
couple high level thoughts

2025-02-25 10:15 UTC, Swiftb0y commented on src/rendergraph/scenegraph/backend/baseattributeset.cpp
> +        throw std::runtime_error("not implemented");
two nits: 
1. exceptions in Mixxx are a touchy subject. 
2. this essentially silences `-Wswitch` which is usually undesirable. If you need to add a return value or throw (because the compiler complains otherwise), just do it after the switch/outside.

2025-02-25 10:15 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrenderbeat.h
>              ::WaveformRendererAbstract::PositionSource type =
I don't get why this needs to be a Q_OBJECT. You don't need to declare a member function as slot in order to bind it to a signal. Any member function is automatically a slot. Only the object that emits the signal needs to be the QObject afaik.

2025-02-25 10:15 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendererstem.cpp
> +} // namespace
file an issue after merge so we don't forget?

2025-02-25 14:58 UTC, acolombier commented on src/mixxxmainwindow.cpp
> +    qDebug() << t.elapsed(false).debugMillisWithUnit() << "deleting ControllerManager";
I've used this to keep it consistent with the other debug message above, but definitely could use a clean up. Happy for this going in follow up work? There is more job to do around timer cleanup and standardisation around `chrono`. I have tried to keep the new code more align with this, but it was hard to draw the line somewhere to not add up an additional batch of changes in this piece of work (see 8ece65b5fcedc93587708fae2cc394c5f352a54d).

2025-02-25 15:04 UTC, acolombier commented on src/rendergraph/scenegraph/backend/baseattributeset.cpp
> +        throw std::runtime_error("not implemented");
Yeah, I'm definitely keen to control the proliferation of pesky exception. I've added this one to align with the code style of the rendergraph (see [here](https://github.com/mixxxdj/mixxx/blob/89bf0a23bfa795cb4b002f5443a8079ea0797de4/src/rendergraph/opengl/backend/basegeometrynode.cpp#L21), [here](https://github.com/mixxxdj/mixxx/blob/89bf0a23bfa795cb4b002f5443a8079ea0797de4/src/rendergraph/scenegraph/geometry.cpp#L17) or [here](https://github.com/mixxxdj/mixxx/blob/89bf0a23bfa795cb4b002f5443a8079ea0797de4/src/rendergraph/scenegraph/geometry.cpp#L28)). I'm almost tempted to replace these with a `VERIFY_OR_DEBUG_ASSERT` but felt like potential cleanup task to keep out of this PR scope.

Happy to "break" the rendergraph style already here tho if you think this is sensible

2025-02-25 15:11 UTC, acolombier commented on src/waveform/renderers/allshader/waveformrendererstem.cpp
> +} // namespace
Yep, good call - created as #14407

2025-02-25 15:27 UTC, acolombier commented on src/waveform/renderers/allshader/waveformrenderbeat.h
>              ::WaveformRendererAbstract::PositionSource type =
It's not a warning, it prevents compiling entirely. Or is this a "warning as error" case?

> is not related to any other changes in the class?

Kinda  - this class was never build with `allshader=allshader_sg` and `rendergraph=rendergraph_sg` before so these are the "major changes" here

2025-02-25 15:29 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrenderbeat.h
>              ::WaveformRendererAbstract::PositionSource type =
Ah I see. Yeah makes sense. Thanks for the explanation.

2025-02-25 16:09 UTC, Swiftb0y commented on src/rendergraph/scenegraph/backend/baseattributeset.cpp
> +        throw std::runtime_error("not implemented");
Oh, I'm sorry. I had lost context and thought we were switching on our our own sg `enum`. The discussion is void then.

2025-02-25 18:38 UTC, Holzhaus commented
Thanks, looks and works great. 🎉

Once we get this PR in, the only big remaining issue with the QML interface is the library IMHO.

2025-02-25 18:45 UTC, acolombier commented on src/waveform/renderers/waveformmarkset.h
> +    };
Sure - the renderer has the concept of "default marker" (<DefaultMarker>` in skin I believe) which is used to put styles on hotcue. QML has a custom object to allow define this, but since it is in the `mixxx-qml-lib`, this couldn't be directly referenced or used. Since there will be soon the concept of "delegate", meaning that it didn't feel worth spending too much effort on refactoring this too much, so I just wanted to add a quick container - does that make sense? It does feel like the name `Seed`, what should I name it? Just `DefaulMarker`?

2025-02-25 18:56 UTC, Swiftb0y commented on src/waveform/renderers/waveformmarkset.h
> +    };
Yeah, just rename it to something like `DefaultMarkerStyle`. Potentially add the slated replacement plan/idea as a comment near the type.

2025-02-25 23:05 UTC, acolombier commented
Glad you like it! Most of the credit goes to @m0dB tho

Agreed on the library, and the settings, as well as a good revamp of the deck controls, but I'm on it! :D (cf Zulip)

2025-02-25 23:46 UTC, acolombier commented
Addressed the last comments and squashed the fixups - ready to go :rocket:

2025-03-01 18:45 UTC, acolombier commented
@mixxxdj/developers merge?

2025-03-01 19:51 UTC, Swiftb0y reviewed
Did another sanity check. Most of the comments are nits, though the missing initialization and the endOfTrackWarning need some discussion.

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendermark.cpp
>      DEBUG_ASSERT(false);
codestyle regression technically

https://github.com/mixxxdj/mixxx/wiki/Coding%20Guidelines#unused-parameters

2025-03-01 19:51 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
`parented_ptr`?

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendererendoftrack.cpp
> +            m_remainingTimeTriggerSeconds;
Isn't this configurable from the user preferences? This would ignore that user preference. Should the skin designer have to wire that up?

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendererendoftrack.h
> +    int m_remainingTimeTriggerSeconds;
I don't see this getting initialized anywhere. Am I missing something?

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendererstem.cpp
> +            std::floor(static_cast<float>(pixelLength) / kPixelPerStrip));
NIT: unnecessary call to `std::floor` afaict. Also [not something the compiler optimizes out](https://compiler-explorer.com/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TA3cAGQImbAA5PwAjbFIQC3IAB3QlYhcmL19/A2TU5yEQsMi2GLiEh2wndJEiFlIiTL8AnntsR3ymGrqiQojo2Pj7WvrG7JalYZ7QvpKBiwBKe3QfUlROLksAZlDUXxwAajNNjwA3SpJSI9wzLQBBG9uT9AJMfcx0AH0ldA4PgHcyABrCChIjzI42O4PJ4vfaJUjoNZKJQfYjYNhKCAYJgTfYTTAgEBnJxkI4eUFXSwANn2xPmhwA7JDbvtWfsWD4SHiAF6HTYAEVplQAdKludgIODNsy2ftBKQIPjCWLsB8iPsCHzBVoIRq%2BR4ebqCLZbPSzEyHrLZe8vj9VQDSMDiWYAKxWY0u/lSmVs838h5%2Bh5cRb0bgu/gBLg6cjobgeE3WPHLVbYQ4WTZ8chEbTBxaAkAurSGbjSfhsAtFyPR2NcfhKEBF7NR4PkOCwFAYHD4YhkSjUOiMVgcbiZwTCMQSTgyOTCZRqTTN8j6BJGExoBN2CpVVwQdyjAIWFrBabFUogBlJFJpIT7%2BItXLXpi9U8DC9bjpdEbeJp31rtaqTM%2B/RxG%2Bky3oeQzdEBswgYs3wrGs3BbDseypmSxIXJSUJ3DCrw2t8vwOsCoLegGOHPK88KItgyKokQ6KYtiuJKkS5ykscFKbNcFg0nSjI%2Bqy8oQByXJomw%2BwgEKqBmhadxWmy%2BF2v8QIgvRbCkXJvoMv6ULaUGIZhhGOYxnGG5JghaHphY/BNjo8yLEg2AsDgcSSsWXCluQ5aFuQVb8DWdYNlmOb2eQ%2BbSC6wpUgAnDw0VaFSWhaC6FiHtFmzuZsRmLgFwXNosbbIGgPyJAwsR9liJVlXEuzGMAPCbFoLQDvRpD1hAUTGVEoR1AAniO/AYGwHDCAA8kw9D9YuOBsHVkjTQQpDnAQZz1ou2DqJUnLrJmoJtMZ9AEFEpB9V4ODGUQpAEOWvAtjQRjAEoABqBDYH8o2JMwA0zqI4iSNOY6KCoGjGfoLSrqYG6GEd9aQIs6CJB0a0ALSjVlf7LTue7fmM5DHkUwE5FeHS3vexPpNBZ7jG0mOdGBOPNBj2501BJ6E%2BM9NZIzEyswTMFSHByaIS0l3YDtLahlw4a%2BcZNbqAAHFSyNUtI%2By1SY%2BwNcKWjCjw%2BwQPG1i2OQ%2BzdhcaYZibXhsKVjCkBbPDzDZIWth2VV2xVQ22wM6v1Y1zUMK17WdYu3WsKQU2ZkNI1EONk3GTNc3rNGhBLVUq3GRtW30d9e2S9Gh3HadWDJzZV03Xwiz3Swj0vW9H1fbdP0Tv9siA3OIOLsuhh1euRvWNDUSw25CNI9wqPo%2B%2B6RuEwngM4Es%2BUwMZN5OkpOXqvBRs/z1P/kIn4NPPu%2B0wfS9xBz3Trzz9RnwLSwWYMoviwZUvZdW3AK0rKtqxDmubNrut9aGxsAPU2hBzZbASPsa23t7aQKdnlOyrsQCEBoDQCqgMW5TjbvIDuC4C5IHrODQhqCaBEF6p9IKpBCGDGoUoUh5DKFaBftLPyJkuD8gIGg/Ydc/ixH2J/ZWqtfZ/wAXrE4SgBGKyET/OqoidaZlsrmcgjlnIDDcvmF00hhSNXllodK0VorSAZAyPRDIqTuU8uWHgSUZY5W4IFBISjQqS2snY9%2BtZEHKLOG1ae0ggA)

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendererstem.h
> +    bool m_splitStemTracks;
initialization?

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/waveformmark.cpp
> +        typeControl = "hotcue_" + QString::number(hotCue + 1) + "_type";
NIT: save the `QString::number` call in a local var. Seems unnecessary to call this often.

2025-03-01 19:51 UTC, Swiftb0y commented on src/waveform/renderers/waveformmarkrange.cpp
> +        }
NIT: expensive string operations just for debug logging

2025-03-02 00:23 UTC, acolombier commented on src/waveform/renderers/waveformmarkrange.cpp
> +        }
This operation is only ran at init time. Also, I always assumed that `qDebug` would no-op the rest of the stream of the operation if it is not enabled, isn't that right?

2025-03-02 00:23 UTC, acolombier commented on src/waveform/renderers/allshader/waveformrendererendoftrack.h
> +    int m_remainingTimeTriggerSeconds;
Nope, it's missing indeed

2025-03-02 00:23 UTC, acolombier commented on src/waveform/renderers/allshader/waveformrendererendoftrack.cpp
> +            m_remainingTimeTriggerSeconds;
Yes, that's right. The reason for doing so is to allow renderer to be used in some other context (e.g S4 screen rendering), where different setting may be taken into account

2025-03-02 00:23 UTC, acolombier commented on src/waveform/renderers/waveformmarkrange.cpp
> +        }
Anyway, I would argue the value of this message is important as it would help indicating user that the specify color was somehow not working (e.g missing, typo, ...). Do you think I should increase the level?

2025-03-02 00:23 UTC, acolombier commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
Unfortunately, `WaveformWidgetRenderer` doesn't inherit `QObject` so `parented_ptr` cannot be used. Note that the ptr is eventually encapsulated inside a `unique_ptr` [here](https://github.com/mixxxdj/mixxx/blob/5a7e04b80ee6a1c8c54f06ba37193fd975123171/src/qml/qmlwaveformdisplay.cpp#L129) to ensure proper de-allocation.

2025-03-02 11:56 UTC, Swiftb0y commented on src/waveform/renderers/waveformmarkrange.cpp
> +        }
> Also, I always assumed that qDebug would no-op the rest of the stream of the operation if it is not enabled, isn't that right?

not really as far as I can tell. `rangeSuffix` and `rangeName` are still created and constructed, no matter how `qDebug` actually behaves. Also even if `qDebug` doesn't do anything, the arguments to the `operator<<` still need to be evaluated. Anyways, as I said, just a nit. I think we can achieve the same without the allocation overhead if you just implement it in terms of `QStringView`

2025-03-02 12:07 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
Oh, I just assumed it was a QObject and thus managed by the QObject tree. So this is actually a raw owning pointer? In that case we should definitely work a little on this. You can easily convert a `std::unique_ptr<Derived>` to a `std::unique_ptr<Base>` (the types are just not covariant compared to raw pointers). I'm fairly certain you can `std::make_unique` from the start and then also move that into the `QmlWaveformRendererFactory::Renderer`.

2025-03-02 12:15 UTC, Swiftb0y commented on src/waveform/renderers/allshader/waveformrendererendoftrack.cpp
> +            m_remainingTimeTriggerSeconds;
Right, but that means the user preference is being ignored by default. So this seems like a regression to me.

2025-03-02 12:49 UTC, acolombier commented on src/waveform/renderers/allshader/waveformrendererendoftrack.cpp
> +            m_remainingTimeTriggerSeconds;
Good catch - I fixed it in bffc6f335389d4131233ca8fba4e29d1393e97f5. I tested that it would dynamically update when editing the settings (since the singleton wouldn't be used in place) and it works well. This allows not needing references to that bloated singleton on the QML code (for which this renderer code is also used)

2025-03-02 13:50 UTC, acolombier commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
No, unfortunately I can't because I have to pass that pointer twice inside the Render struct. This is because I need to keep track of the two base classes of the renderers (WaveformRenderer and Rendergraph node, unrelated together). I'm sure this is very hacky but unfortunately I cannot think of any other ways to wrap that elegantly, without adding some bloating on allshader and rendergraph.
Happy to try an alternative if you have ideas. Note that I cannot use a shared_ptr since one of its usage (inside rendergraph) will be downcasted to unique_ptr

2025-03-02 22:21 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
I think its fairly straightforward if adapt something like this:

```cpp

class A {};
class B {};
class C : public A, public B {};

struct Renderer {
    // ensure owning ptr is before the borrowing one
    // to ensure the borrow doesn't outlive the owner.
    std::unique_ptr<A> node{nullptr};
    B* renderer{nullptr};
};

Renderer create() {
    auto c = std::make_unique<C>();
    // local temporary is needed so we don't call `.get` on `c` after it may have been moved from
    B* b = c.get();
    return Renderer{std::move(c), b};
}

```

wdyt?

2025-03-02 22:29 UTC, Swiftb0y commented on src/waveform/renderers/waveformmarkrange.cpp
> +        }
```suggestion
            QStringView rangeName = rangeSuffix; 
            constexpr static QStringView rangeSuffix = "_start_position";
            if (startControl.endsWith(rangeSuffix)) {
                rangeName.chop(rangeSuffix.length);
            }
            int gray = qGray(m_activeColor.rgb());
            m_disabledColor = QColor(gray, gray, gray);
            qDebug() << "Didn't get DisabledColor for mark range" << rangeName
                     << "- using desaturated Color:" << m_disabledColor;
        }
```

2025-03-02 23:48 UTC, acolombier commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
Yep, works with me. I thought it was a bit strange to use a mixture of both, but happy to do so if you think it's the best tradeoff

2025-03-03 15:20 UTC, Swiftb0y commented on src/qml/qmlwaveformrenderer.cpp
> +    auto* pRenderer = new allshader::WaveformRendererEndOfTrack(waveformWidget);
I think so, yes. Lets try our best to adhere to [`ES.60: Avoid new and delete outside resource management functions`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es60-avoid-new-and-delete-outside-resource-management-functions)

2025-03-04 00:14 UTC, acolombier commented on src/waveform/renderers/waveformmarkrange.cpp
> +        }
Ah sorry, I just realised you weren't talking just about this `qDebug`, but the whole `else` block. I only copied this code and didn't realise that

2025-03-05 11:39 UTC, Swiftb0y approved these changes
LGTM. Thank you.

2025-03-05 23:10 UTC, acolombier commented
Thanks @Swiftb0y - all squashed and ready to go now!

2025-03-05 23:16 UTC, Holzhaus commented
There a still a bunch of fixup commits

2025-03-05 23:22 UTC, acolombier commented
Indeed, I didn't notice that the push failed for some unrelated git hooks checks. We should be good to go now!

2025-03-06 12:14 UTC, merged

2025-03-06 14:04 UTC, PPN-SD commented on CMakeLists.txt
> +target_compile_definitions(mixxx-test PRIVATE allshader=allshader_gl)
missing if(BUILD_TESTING)/endif()

```
CMake Error at CMakeLists.txt:4727 (target_compile_definitions):
  Cannot specify compile definitions for target "mixxx-test" which is not
  built by this project.

```

2025-03-06 14:57 UTC, Swiftb0y commented on CMakeLists.txt
> +target_compile_definitions(mixxx-test PRIVATE allshader=allshader_gl)
Is there a CI run for this or how does this happen?

2025-03-06 15:00 UTC, PPN-SD commented on CMakeLists.txt
> +target_compile_definitions(mixxx-test PRIVATE allshader=allshader_gl)
checked with live ebuild from gentoo. But I think base/test and SHARED_LIBS (https://github.com/mixxxdj/mixxx/pull/14021#issuecomment-2630601087) should be integrated in CI.

2025-03-06 15:27 UTC, Swiftb0y commented on CMakeLists.txt
> +target_compile_definitions(mixxx-test PRIVATE allshader=allshader_gl)
@acolombier is it feasible for you to look into this?

2025-03-06 20:38 UTC, PPN-SD commented on CMakeLists.txt
> +target_compile_definitions(mixxx-test PRIVATE allshader=allshader_gl)
> how can I reproduce this?

BUILD_TESTING=OFF

2025-03-10 22:56 UTC, acolombier commented on CMakeLists.txt
> +target_compile_definitions(mixxx-test PRIVATE allshader=allshader_gl)
This should be fixed now. Thanks for reporting!