RFC: Alternative non-floating stem controls for LateNight
mixxxdj/mixxx pull request #13537
Opened 2024-08-04 21:42 UTC by JoergAtGithub

This is an alternative to the UI PR #13515 by @acolombier . It use classic widget groups instead of the floating widget.
![grafik](https://github.com/user-attachments/assets/52473831-11fc-4dbc-b6e3-0239bea29ebb)

The functionality is the same, but the widget positioning differs. Both PRs are in prove of concept state and not visually fine tuned.

The benefit of the floating widgets is that the waveform is only hidden by the stem widgets for the tracks that are stem files, while here, the stem widgets are either shown for all tracks or for none.

Please test both PRs #13515 and this one. (Build with FFMPEG and STEM enabled in CMake) and load a .stem file. And review the code of the second commit here. Which approach should we follow?

If you need STEM files for test, you can download the reference files here: https://www.native-instruments.com/fileadmin/ni_media/downloads/stems/free_stems_for_traktor_pro_2.zip

2024-08-04 22:01 UTC, acolombier commented
That's looking very promising! :rocket:

2024-08-05 10:13 UTC, Swiftb0y reviewed
had a quick look. in pretty good shape. I just wish the `*Manager` classes wouldn't get bloated so much.

2024-08-05 10:16 UTC, acolombier commented
Thanks for the review @Swiftb0y !

Looks like most of those comments are meant for #13123, on which this PR is based. I will address them, but feel free to continue the review there, in case you have more feedback!

2024-08-05 16:05 UTC, JoergAtGithub commented on src/skin/legacy/legacyskinparser.cpp
>      QDomDocument tmpl("template");
That is a wrong resolved merge conflict

2024-08-08 12:16 UTC, Eve00000 commented
I really appreciate the work/time your investing in this matter, so I did a thorough test and I wanted to write a profound report.
due to some errors on my behalve I had a rather strange effect that made it on the other side very clear to compair (see image).

I want to start with a +/- list
subject / design 1 / design 2
**  indicating clearly a stem is loaded
-> design 1 only shows stem controls when a stem is loaded, design 2 shows them stem controls fora all decks even when there is no (stem) file loaded. the floating widget seems to be more scalable than the fixed. if you don't need the guicontrols to manipulate the stems they take a lot of space in design 2. Having 4 decks + samplers (even mini view) leaves no space for library.
-> this can / is confusing. A possible solution can be to have little rectangles (same design as Daniel uses in the Keys) in the stemcontrols that show the trackcolor as wel. (maybe the stars can be that color to)

** clarity of the stemcontrols
->the coloring of the tracks in design 1 was/is a little too 'invasive', the colors blinded the readability of the information (loaded effect, volume/fx potmeter level) especially when stems are loaded in all decks. The opacity of the controls when a stem-track is muted is clear. design 2 has the mute buttons as well.
-> design 2 is more 'relaxing" for the eyes, but a stem-track-color would clearify the view from a distance. 

** floating or fixed
-> in the floating design the controls cover all views that are not showing the complete waveform (big library, 4-> 2 decks with stems loaded in 3/4) can be confusing. In the fixed design the controls are always there (unless hidden with the button) witch has an influence on the waverforms window as well. (4 decks = huge)
-> I find the fixed design more relaxing

Resumé
Both designs have + and - , so the optimal design must be somewhere in the middle (the truth is out there),
- stem-track-colored rectangles indicating a stem is loaded, can the opacity be combined?
- can the effectname be smaller?
- can there be a different design for "only info" / "info + manipulate", the controls in the first could be smaller 
- can there be an indication in the deck that a stem is loaded?
- floating design is scalable and leaves place for library , samplers and fx, the fixed design doesn't.

So there should be thought about diffeent user types:
- using the gui as info ->smaller (hidable) stemcontrols
- using the gui to control Mixxx -> bigger clear controls
 

PS: The track in the image remembered me of the early 90's, for a couple of weeks I was overwelmed with "Bells of NY', I got a white label and played (parts of) it maybe 5 times a night. Thanks for remembering me.

![afbeelding](https://github.com/user-attachments/assets/6544dec4-5efd-459e-a248-bd7d4abbf440)

2024-08-29 11:56 UTC, daschuer commented
Here my 2 ct: 
* The floating version was too colorfull. 
* The uncovered area in the floating type was useless
* The changing size was more anoying than helpfull.
* Requrement: Alignment of deck waveforms 
* The colored texts may not work well / are readable with all Skin Color schemes and stem colors -> extra area or border
* The combined waveforms sometimes hide details in single stems. Idea: Side by side version. 
* Nice: Show/Hide controls per deck. Waform chopped on the left, not scaled to always match non stem decks.
* Force a minimm wavform size that all controls have the normal size
* I have no demand to show and hide the waveforms, but a demand to switch back to stereo mode and let the track flow without a high CPU load. Maybe an extra small widget that is shown in stereo mode and allows to switch back to stem mode showing the full controlls.

2024-09-08 21:44 UTC, ronso0 commented
Just a quick feedback / idea, let me know what you think:
the play/mute controls could be buttons with a label (not labels + small buttons)
Ie. I'd prefer larger controls as GUI equivalent for pads on (stem-ready) controllers.

I'll provide a commit fixing the indentation soonish, then take a look at the UX and the c++ part.

2024-09-08 21:56 UTC, acolombier approved these changes
LGTM!

@ronso0's suggestion sounds great, but also conscious than working on the legacy UI is not very easy/rewarding so happy with the current look!

2024-09-08 22:15 UTC, JoergAtGithub commented
Yes, a WStemButton would also make sense, an saves some space. I derived WStemLabel from WLabel, but I guess it should be easy to do the same with WPushButton instead.

2024-09-09 10:54 UTC, Swiftb0y approved these changes
can't comment on the qss and xml changes (@ronso0 could you have a look?) Cpp changes LGTM.

2024-09-09 11:06 UTC, ronso0 commented
Yes, working on it right now.

2024-09-09 12:40 UTC, ronso0 commented
Fixup is here 3975eddd2e
I fixed the knobs, adjusted the layout a bit, etc.

FWIW the action buttons in LateNight indicate what happens when you push them (not the current state, eg. `| |` icon when a track is playing), so I changed the stem mute icons, too.
![image](https://github.com/user-attachments/assets/30776cd0-ca07-4bce-a4ca-9726716d219d)

2024-09-09 12:49 UTC, ronso0 commented
> Fixup is here https://github.com/mixxxdj/mixxx/commit/3975eddd2e786c18aeabae4d04dedf6ee586fb4c

whoops, this had some residues in the SVG.
here's the clean one 709da44e6c, please pick that instead.

2024-09-09 19:59 UTC, JoergAtGithub commented
@ronso0 Is it intended, that the Effect-Name is no longer left alligned?
![grafik](https://github.com/user-attachments/assets/10146223-7e55-4092-a7a3-62af0757361f)

2024-09-09 20:07 UTC, JoergAtGithub commented
@ronso0 In your patch the changed SVG for LateNight Classic seems to be missing

2024-09-09 20:16 UTC, ronso0 commented
> @ronso0 Is it intended, that the Effect-Name is no longer left alligned?

Whoops, only tested with long names. Will fix it.

I didn't change the Classic icon. Will take a look.

2024-09-10 11:16 UTC, ronso0 commented
Done. Polished commit is b08fe0e7a2

2024-09-10 11:44 UTC, JoergAtGithub commented
I noticed two visual issues, which are independent of the last commit:
![grafik](https://github.com/user-attachments/assets/2e9d68eb-3541-4c0c-9948-d3871c3dbebb)

1.) With very long stem labels, only the  channel section with this label becomes wider. This is an issue because the waveform shrinks and is no longer aligned to the other waveforms. I think we will need an additional invisible container around all channels
2.) The default quick effect can be "---" or ""

Than we have also a build issue. We have the CMake setting STEM to enable the feature, but this does not affect the skin, only the C++ code. AFAIK an #ifdef like command in the skins is not available?

2024-09-10 13:14 UTC, ronso0 commented
> We have the CMake setting STEM to enable the feature, but this does not affect the skin, only the C++ code. AFAIK an #ifdef like command in the skins is not available?

Some ideas:
1. abuse new ControlObjects to hide the widgets
= cumbersome
2. add a wrapper class for WidgetGroup, eg. StemWidgetGroup, that is only parsed if STEM is enabled
(+) safe IMO
(-) we'd need to implement this for every widget class used for stems that is placed in regular widget groups, eg. some stem control in the mixer where wrapping in an extra StemWidgetGroup would be overkill
3. add a `<RequiresStem>` node to WidgetGroups in question, and only parse the WidgetGroup if STEM is enabled
(+) should be easy to implement in [`LegacySkinParser::parseWidgetGroup`](https://github.com/mixxxdj/mixxx/blob/8790b5fbf2eb555da740a16ae39cf08215868031/src/skin/legacy/legacyskinparser.cpp#L733)
(+) could also be a helper function called by **any widget parser**

3 is my favourite.

2024-09-10 13:26 UTC, ronso0 requested changes
LGTM, except we need to add assertions when accessing the steminfo list.

2024-09-10 13:26 UTC, ronso0 commented on src/widget/wstemlabel.cpp
> +void WStemLabel::slotTrackUnloaded(TrackPointer track) {
here and elsewhere
```suggestion
void WStemLabel::slotTrackUnloaded(TrackPointer pTrack) {
```

2024-09-10 13:26 UTC, ronso0 commented on src/widget/wstemlabel.cpp
> +    m_stemNo = context.selectInt(node, "StemNum");
assert that num is >= 0 and < N (what's the upper limit?)
otherwise we'd get `ASSERT failure in QList::operator[]: "index out of range"`

2024-09-10 13:26 UTC, ronso0 commented on src/widget/wstemlabel.cpp
> +    m_stemInfo = stemInfo[m_stemNo - 1];
assert that m_stemNo <= m_stemInfo.size()
otherwise we'd get `ASSERT failure in QList::operator[]: "index out of range"`

2024-09-18 21:18 UTC, ronso0 commented
@JoergAtGithub I'm currently travelling and i'll review as soon as I'm back home.

2024-09-18 21:38 UTC, Eve00000 commented
@ronso0 : enjoy your holiday, have a good time

2024-09-19 22:29 UTC, ronso0 commented on src/widget/wstemlabel.cpp
> +                          << mixxx::kMaxSupportedStems;
A mixxx::logger is nice, but here we'd actually use the `SKIN_WARNING` macro IMO

2024-09-19 22:41 UTC, ronso0 commented
https://github.com/ronso0/mixxx/commit/b9da04dd3f2eb45ae87fccf96303575e2647a299 fixes the tabs in waveform_container.xml

2024-09-19 22:48 UTC, ronso0 commented on src/skin/legacy/legacyskinparser.cpp
> +}
`WStemLabel` is a `WLabel`, so why not use `LegacySkinParser::setupLabelWidget()`? 

If there's a reason _not_ to use that, why put this into an extra function that's used only for WStemLabel? (vs. put it in `parseStemLabelWidget)`

2024-09-19 22:54 UTC, ronso0 commented on src/skin/legacy/legacyskinparser.cpp
> +}
`LegacySkinParser::setupLabelWidget()` works just fine.
74a1c863e1

2024-09-20 08:18 UTC, ronso0 commented
> Than we have also a build issue. We have the CMake setting STEM to enable the feature, but this does not affect the skin, only the C++ code. AFAIK an #ifdef like command in the skins is not available?

What about not ifdef'ing the stem label parser itself (which gives us a skin warning "Invalid node name in skin: .."), but use the ifdef in `parseStemLabelWidget` to log a note saying that WStemLabel requires building with STEM enabled?

2024-09-21 13:13 UTC, ronso0 commented
LGTM, but the indentations of the xml files are screwed up again. I think you need to adjust your editor to use spaces instead of tabs like in c++ code. Fixup or append a commit, as you like.

2024-09-22 19:17 UTC, JoergAtGithub commented
Done!

2024-09-23 08:18 UTC, ronso0 approved these changes
LGTM, thank you very much!

2024-09-23 08:18 UTC, merged