(fix) Tracks: apply played/missing text color also to selected tracks
mixxxdj/mixxx pull request #13583
Opened 2024-08-20 09:56 UTC by ronso0

During performance I find it quite confusing that when selecting played tracks they are marked like unplayed tracks.

Fixing this required to add a DefaultDelegate (picked from #11644) and tweak some paint methods.
Works great, also for the star editor.

As a bycatch I managed to simplify some of them (see StarEditor for example, and removed QColorGroup setting).

Note: the stylesheet fixes are only in LateNight PaleMoon for now.
The color blend ratio needs to be tested, but so far I find it okay (dark enough to see 'played', bright enough to read the text).

Let me know what you think.

2024-10-06 15:05 UTC, ronso0 commented
Okay, looks as expected in all skins.

I wonder: are the existing 'played' colors okay in all skins?

2024-10-06 19:28 UTC, ronso0 commented
This is ready IMO.

A general issue remains however:
with bright track colors, the dim 'played' color might be unreadable.
**Possible fixes:**
1. make text brighter until a certain contrast is reached, try to keep it darker than the regular text color?
not sure if this is even possible to get a color that is still distinct enough to recognise the tracks as 'played'...
2. switch to dark color that provides enough contrast
   * use a fixed secondary `trackPlayedColor`
   * determine the color based on the background to provide just enough contrast

2025-01-19 15:19 UTC, daschuer commented
Unfortunately you cannot read the text anymore in Deere and Shade: 
![grafik](https://github.com/user-attachments/assets/56f2671e-c98a-47bc-81aa-48fd4409f90c)
![grafik](https://github.com/user-attachments/assets/a92fe033-271b-4d64-a839-3d78487ce801)
Tango is at the edge IMHO: 
![grafik](https://github.com/user-attachments/assets/1f2c82e2-31da-40f3-9a75-5cee8b3f923f)

2025-01-19 15:20 UTC, daschuer requested changes
The colors need to be tweaked.

2025-01-22 13:50 UTC, ronso0 commented
Right, colors are not suitable. Will try to fix them.
With new `DefaultDelegate` this might be a candidate for 2.6 anyway?

2025-01-22 15:26 UTC, ronso0 commented
I'll try a different approach:
for played + selected: blend selected font color and background color
That should get us enough contrast for
* selected bg / selected text (unplayed) as well as
* selected text / selected text (played)

2025-01-22 15:27 UTC, ronso0 commented
TODO:
fix text for 'inactive' palette, i.e. another window is in front (e.g. Track Info)

2025-04-15 22:04 UTC, ronso0 commented
The played/selected colors are now blended 50/50.
Looks good in all skins IMO
![image](https://github.com/user-attachments/assets/965d821a-ce8f-4f79-8495-a7710dde1915) 
![image](https://github.com/user-attachments/assets/5577aeb5-0800-4a1e-9a40-1e48662246f7)
![image](https://github.com/user-attachments/assets/33dc4bed-c24a-4d30-9a7d-99ddec242ae2)
![image](https://github.com/user-attachments/assets/9732c9c7-3abd-430e-beda-c33426508e57)
![image](https://github.com/user-attachments/assets/4caa8bdf-b3bb-40f0-8ded-1977fb17d327)
We could also allow skins/schemes to set their own custom ratio :shrug:

2025-04-25 06:25 UTC, daschuer approved these changes
LGTM and the visibility issue is fixed. Thank you.

2025-04-25 06:25 UTC, merged

2025-04-25 15:54 UTC, ronso0 commented
Thanks for your review.

I think this still needs some tweaking, but that doesn't have to happen for 2.5.1 to not hold that up.
The font/bg contrasts should be increased
* in Deere: brighter selected text, white as in other skins
* in Shade Classic: dim selected bg a bit