Fix some minor code issue
mixxxdj/mixxx pull request #13586
Opened 2024-08-21 22:14 UTC by daschuer

2024-08-22 08:09 UTC, Swiftb0y requested changes

2024-08-22 08:09 UTC, Swiftb0y commented on src/engine/controls/loopingcontrol.h
> +        }
this makes LoopInfo not an aggregate anymore. This makes it less convenient to use. Please remove.

2024-08-22 22:17 UTC, Swiftb0y approved these changes
LGTM. Thank you.

2024-08-22 22:59 UTC, Holzhaus commented on src/engine/controls/loopingcontrol.h
> +        mixxx::audio::FramePos endPosition;
What's the benefit of this change? The previous version made the default value explicit.

2024-08-26 10:06 UTC, Holzhaus approved these changes

2024-08-26 10:06 UTC, merged