Tape echo
mixxxdj/mixxx pull request #1359
Opened 2017-10-08 20:50 UTC by daschuer

This fixes the silent gaps when changing the time parameter of the echo effect, by changing the implementation on the delay buffer. Now we use always the full ring, like a tape delay. 

When changing time, the new time is faded into the old time. During the delvelopment, I have also implemented a pitched fade, but this results into a row of unnatural high pitched sounds. 
I assume that this is due to the unregular and slow sampling of the parameter knob, and due the wide pitch range.   

I have also removed the fixed -6 dB offset of the send signal. This allows to have finally a natural -3 dB echo sound by default.

2017-10-08 21:27 UTC, Be-ing requested changes
Thank you for fixing this. I tested the changes and it sounds good to me. I have left a few nitpicky comments to improve the readability of the code.

2017-10-08 21:27 UTC, Be-ing commented on src/effects/native/echoeffect.cpp
> +#define DECREMENT_RING(index, decrement, length) index = (index + length - decrement) % length
Why are preprocessor macros used for this? IMO it makes it harder to read. I'd rather read the math directly in the code where it is used or make functions.

2017-10-08 21:27 UTC, Be-ing commented on src/effects/native/echoeffect.cpp
> +    int delay_samples = delay_frames * gs.kChannelCount;
Why is the channel count a property of the GroupState?

2017-10-08 21:27 UTC, Be-ing commented on src/effects/native/echoeffect.cpp
> +        CSAMPLE bufferedSample1 = gs.delay_buf[read_position + 1];
I think using "Left" and "Right" in the variable names would be more readable than "0" and "1".

2017-10-08 21:27 UTC, Be-ing commented on src/effects/native/echoeffect.cpp
> +            bufferedSample1 += gs.delay_buf[prev_read_position + 1] * (1 -frac);
Please put a space on both sides of the operator: `(1 - frac)`

2017-10-08 21:27 UTC, Be-ing commented on src/effects/native/echoeffect.cpp
> +        if (++gs.ping_pong >= delay_samples) {
I think combining variable assignment and condition testing on the same line is unnecessarily hard to read. Please split into two lines like:
```
++gs.ping_pong;
if (gs.ping_pong >= delay_samples) {
```

2017-10-08 22:33 UTC, daschuer commented
Notes addressed.

2017-10-08 22:58 UTC, Be-ing commented
LGTM, thanks! 👍

2017-10-09 11:27 UTC, daschuer commented
Thank you for review.

2017-10-09 11:28 UTC, merged