HID: Avoid repeated error messages from hid_write()/hid_read()
mixxxdj/mixxx pull request #13692
Opened 2024-09-24 05:54 UTC by daschuer

This is fixed the huge log file issue with #13660 for log spam in any disconnect case, without fixing the root cause in that particular case.

2024-09-24 07:14 UTC, acolombier approved these changes
LGTM! Thanks

Do we think this is a sufficient mitigation for the log file size till we have a proper limiter in place?

2024-09-25 22:42 UTC, JoergAtGithub requested changes

2024-09-25 22:42 UTC, JoergAtGithub commented on src/controllers/hid/hidiooutputreport.cpp
> +            m_hidWriteErrorLogged = true; // Don't log the same error again
This will not wor as the comment describe. To ensure that only identical errors are inhibited, you must compare the error message string.

2024-09-25 22:42 UTC, JoergAtGithub commented on src/controllers/hid/hidiothread.cpp
> +                m_hidReadErrorLogged = true; // Don't log the same error again
Same here

2024-09-26 05:46 UTC, daschuer commented
I have adjusted the error message. We want also stop log spam in the unlikely case that there are altering different error messages, because this would still fill the log file.

2024-09-26 05:49 UTC, daschuer commented
> Do we think this is a sufficient mitigation for the log file size till we have a proper limiter in place?

I consider this a permanent solution, because we also want to avoid the performance impact, until the 100 MB log limit is from https://github.com/mixxxdj/mixxx/pull/13684 is reached.

2024-09-28 07:39 UTC, JoergAtGithub reviewed
hid_write is also used here: https://github.com/mixxxdj/mixxx/blob/d6eeb45ceeaa5878b06d1b3b86a9facdad08ac81/src/controllers/hid/hidioglobaloutputreportfifo.cpp#L68-L76

2024-09-28 07:50 UTC, JoergAtGithub commented on src/controllers/hid/hidiothread.cpp
> +                                                  kMaxHidErrorMessageSize);
```suggestion
                qCWarning(m_logOutput) << "Unable to read buffered HID InputReports from"
                                       << m_deviceInfo.formatName() << ":"
                                       << mixxx::convertWCStringToQString(
                                                  hid_error(m_pHidDevice),
                                                  kMaxHidErrorMessageSize)
                                       << "Note that, this message is only logged once and may not appear again until all hid_read errors have disappeared.";
```

2024-10-06 20:23 UTC, daschuer commented
Done

2024-11-03 07:24 UTC, JoergAtGithub commented
Works as expected. Thank you!

2024-11-03 07:24 UTC, merged