Fix loading the wrong track via drag and drop and fix wrong DEBUG_ASSERT
mixxxdj/mixxx pull request #13708
Opened 2024-09-29 09:58 UTC by daschuer

This fixes handling with duplicated tracks. Now an attempt for caching two tracks with different locations referencing the same file are reliably detected and rejected the situation is reported as warning, and does no longer violates assertions. 

This has been tested on Ubuntu focal using a symlink 
`ln -s track.mp3 symlink.mp3`

The related issues showing the empty property page and overwriting thee symlink https://github.com/mixxxdj/mixxx/issues/13707 are still pending, work is in progress.

2024-09-29 11:58 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +        // Reject requests that would otherwise cause a caching caching conflict
```suggestion
        // Reject requests that would otherwise cause a caching conflict
```

2024-09-29 11:59 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +                << "because tack"
```suggestion
                << "because track"
```

2024-09-29 12:20 UTC, ronso0 commented
Looks like this fixes #13540 (and #13140)

2024-09-29 12:27 UTC, ronso0 commented
Just an idea how to allow users fixing the situation in Mixxx:
* in case we manage to display an error dialog, we could allow showing both tracks in the tracks view via an OR search for both track ids (or more, maybe a file has already been added a third or forth time) with `Library::searchTracksInCollection(QStringLiteral("id:trackId1 | id:trackId2"));`
* users can now merge metadata and purge the obsolete track
* maybe allow replacing the obsolete track with the original in playlists and crates, incl. history

2024-10-01 21:28 UTC, daschuer commented
Sounds good. Can we merge this now since this is IMHO a 2.4.2 bug fix.

2024-10-06 19:56 UTC, daschuer commented
I consider this ready for merge.

2024-12-15 23:59 UTC, JoergAtGithub commented
@ronso0 How do you rate the risk here? Should we postpone this to 2.5.1 ?

2024-12-20 12:18 UTC, acolombier approved these changes
LGTM - haven't had a chance to run manual testing tho

2024-12-20 13:00 UTC, ronso0 commented
> @ronso0 How do you rate the risk here? Should we postpone this to 2.5.1 ?

Oh sorry, I missed that!
I'm still having a hard time understanding some of the Track/Trackrecord/db relations, I don't feel competent to judge the changes.

If the manual tests¹ succeed this is good for 2.5 IMO. Question is how to easily (easy for reviewers) get this into 2.5 since 2.4 is frozen IIUC.

Tests:
* all new tracks must be discovered, of course
* all new tracks must be discovered after moving a base music directory via preferences
* what about old/new symlinked tracks @daschuer ?

2025-01-08 14:12 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +        const TrackId oldTrackId = pTrack->getId();
_ping_ @daschuer ?

2025-01-08 14:14 UTC, ronso0 commented
@daschuer can you please rebase onto 2.5? (or just chnage the target branch, idk)

2025-02-08 16:32 UTC, ronso0 commented
Will do a manual test soon!

2025-02-12 14:27 UTC, cr7pt0gr4ph7 requested changes

2025-02-12 14:27 UTC, cr7pt0gr4ph7 commented on src/library/dao/trackdao.cpp
> +                    << "because tack"
```suggestion
                    << "because track"
```

2025-02-12 14:27 UTC, cr7pt0gr4ph7 commented on src/track/globaltrackcache.cpp
> +    return {};
```suggestion
    // Lookup failed, either because the TrackRef did not specify an id or canonical location,
    // or because the database contains multiple tracks with that canonical location.
    return {};
```

2025-02-12 14:27 UTC, cr7pt0gr4ph7 commented on src/library/dao/trackdao.cpp
> +        const TrackId oldTrackId = pTrack->getId();
Just for context, does the `"File not found"` message previously present here mean `"File not found in the database"` or `"File not found on the filesystem"`?

2025-02-18 13:37 UTC, daschuer commented on src/library/dao/trackdao.cpp
> +        const TrackId oldTrackId = pTrack->getId();
Kind of file not found on the file system. If the file is not in the database it is anyhow added to the cache to prevent writing the file metadata while playing. The cache uses the canonical location of the file which requires file system access. The file is however later opened which still may fail. 

Null check is now back.

2025-02-18 16:17 UTC, daschuer commented
Done

2025-02-28 07:45 UTC, daschuer commented
Can one take a final look an merge?

2025-02-28 07:53 UTC, cr7pt0gr4ph7 approved these changes
LGTM

2025-03-15 10:23 UTC, JoergAtGithub commented
> Will do a manual test soon!

It seems this code is reviewed, but no one tested it yet. Can someone test with Unix symbolic links?

2025-03-20 09:18 UTC, ronso0 commented
So, finally, here are my test results with this branch.
Strangely I can not make it hit the assert mentioned in #13706 with 2.5
(track paths are truncated)

* I created one symlink of a track which is already in the db
track1.mp3 + symlink.mp3
* track1.mp3 has been added to the library
* do a Library rescan

```
debug [LibraryScanner 1] LibraryScanner - slotStartScan()
... (scanner info)
debug [Thread (pooled)] Importing track "/music/symlink.mp3"
debug [LibraryScanner 1] isFileSupported "mp3"
debug [LibraryScanner 1] GlobalTrackCache - Resolving track by canonical location "/music/track1.mp3"
debug [LibraryScanner 1] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/music/symlink.mp3","/music/track1.mp3",-1}
debug [LibraryScanner 1] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/music/symlink.mp3","/music/track1.mp3",-1} QObject(0x0)
... (SoundSource, Serato, TagLib)
debug [LibraryScanner 1] TrackDAO - TrackDAO: Adding track "/music/symlink.mp3"
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/music/symlink.mp3","/music/track1.mp3",2} Track(0x7fa7a80b2f40)
debug [LibraryScanner 1] LibraryScanner - slotFinishHashedScan
debug [LibraryScanner 1] LibraryScanner - slotFinishUnhashedScan
debug [Main] GlobalTrackCache - Deleting Track(0x7fa7a80b2f40)
... (scanner info)
debug [LibraryScanner 1] LibraryScanner - Scan finished cleanly
debug [LibraryScanner 1] Scan took: 83671775 ns. 0 unchanged directories. 1 changed/added directories. 1 tracks verified from changed/added directories. 1 new tracks.
```

* get this info once when I press Down in the Tracks to select symlink.mp3.
* get this 5 times more when I press Ctrl+Enter to open Track Info (then hit the dbg assert in dlgtrackinfo.cpp)
```
debug [Main] GlobalTrackCache - Resolving track by id 2
debug [Main] GlobalTrackCache - Resolving track by canonical location "/music/track1.mp3"
debug [Main] GlobalTrackCache - Cache Conflict - found a different track for the same canonical location: requested =  TrackRef {"/music/symlink.mp3","/music/track1.mp3",2} cached =  TrackRef {"/music/track1.mp3","/music/track1.mp3",1}
warning [Main] TrackDAO - Failed to load track "/music/symlink.mp3" with id 2 because track "/music/track1.mp3" with id 1 referencing the same file at "/music/track1.mp3" is already loaded.
```

2025-03-20 09:19 UTC, ronso0 commented
Had to merge this branch into 2.5 for testing.
Please rebase.

2025-03-20 21:43 UTC, daschuer commented
Done

2025-04-15 09:11 UTC, ronso0 commented
Looks like the rebase went wrong, now the only change is the new comment?

2025-04-25 06:21 UTC, daschuer commented
The major part of this PR has been merged via: 
https://github.com/mixxxdj/mixxx/pul.githubl/13719
Now we have only the comment, which was not part in that.

2025-05-14 10:30 UTC, ronso0 commented
LGTM :man_shrugging:

2025-05-14 10:31 UTC, merged