Fix unnecessary painting in CoverArtDelegate
mixxxdj/mixxx pull request #13715
Opened 2024-10-01 21:14 UTC by daschuer

I have created this during my my first attempt to fix the priority inversion when scrolling with cover arts column enabled. 
This is a bit of a speed up, but does not fix the actual problem. This will be part of the next PR.

2024-10-04 17:56 UTC, ronso0 commented
FWIW I'm not noticing a difference in performance between 2.4 and this.
With both branches, for covers that are skipped while scrolling fast (only the color is painted) the images are loaded only when I scroll back to the skipped rows. Ie. I don't see any effect of c36e5661d8ddfea072f3d190a26db6383ddfca01/6c841bd4b2320f6dd4ebf0599c4f3d6697caf9e4 (IIUC how those are supposed to work).

2024-10-04 18:09 UTC, ronso0 requested changes
Just some small findings, I'll take a closer look soonish.

2024-10-04 21:55 UTC, daschuer commented
The actual but small speed up happens once you stop scrolling. In this case the cover pictures appears faster. In the original version the uni-color replacements are first painted again after scroll stop and than the original covers are fetched and pained.

The other optimizations has only a negligible speed up. In 2.4 the chache grows up to 1000 and more, which requires repeated memory allocations. This branch reuses the memory once it is allocated for the number of all visible rows.

2024-10-04 21:58 UTC, daschuer commented on src/library/coverartdelegate.cpp
> +    if (m_inhibitLazyLoading) {
I will restore it. It was no longer required in an intermediate version

2024-10-04 22:03 UTC, daschuer commented
Done

2024-10-05 13:19 UTC, ronso0 commented on src/library/coverartdelegate.cpp
> +        QRect rect = m_pTableView->visualRect(index);
Only that one is open.

2024-10-06 06:04 UTC, daschuer commented
Done

2024-10-28 11:39 UTC, ronso0 requested changes
LGTM, but let's polish that comment

2024-11-03 15:43 UTC, daschuer commented
Done

2024-11-03 17:22 UTC, ronso0 commented
Thank you!

2024-11-03 17:22 UTC, merged