Fix scrolling issue with coverart columns visible
mixxxdj/mixxx pull request #13719
Opened 2024-10-04 18:12 UTC by daschuer

This finally fixing a long standing and puzzling bug that momentary locks up Mixxx during scrolling the library with cover art enabled. #11128

The issue happens due to a priory inversion on the track cache mutex. During cover art reading the cache is locked to protect this incomplete track, which prevents the main thread checking for pending modifications on cached tracks. Scrolling continues when all covers are read even it is don in worker threads.  

The solution implemented here is to allow to bypass the lock in case the current track populated, yet still incomplete track is not of interest. It is implemented by limiting that actual look for the track cache only for aching actions and use a wait condition in case a thread is waiting for completing an incomplete track. 

Now scrolling is smooth all the time and together with removing unnecessary painting #13715 also quite fast. 

This PR is on top of https://github.com/mixxxdj/mixxx/pull/13708 which should be merged first.

2024-10-28 11:58 UTC, ronso0 commented
This seems to fix a long-standing performance issue, does one of @mixxxdj/developers have time to take a look?

2024-10-28 14:06 UTC, ywwg commented
what is the status of the beta / release? While this is annoying, it has been around forever without causing harm so it seems better to fixing in the main branch (just in case there is an unforeseen regression)

2024-10-28 17:20 UTC, JoergAtGithub commented
I did a short test on Windows. I had not the described issue before, therefore I can not say if this PR fixes the bug. I've no delay, with and without this PR.

But what I noticed, is that the caching does not work properly, if I scroll up and down in my track list, it starts reloading coverart of tracks that should be in the cache. It can't be the cache size, which is set to 20MByte and I've only a few hundereds tracks with tiny coverart pixmaps where I estimate the overall size (assuming uncompressd pixmaps) with 1.4MByte.

2024-10-28 18:40 UTC, ywwg commented
@daschuer can you repoint to main?

2024-10-29 07:14 UTC, daschuer commented
main is for new features. This is a bug fix, I am affected on. I have my tracks on an external spinning HDD. 

So the 2.4 target is correct. Please note that this is not on the 2.4.2 milestone, because it shall not block the release in case of pending issues. 

@JoergAtGithub, how do you test exctly. 
How do you know hat the covers are reloaded during scrolling? I cannot confirm. 

I can confirm, that covers are only loaded and cached after stopping for the inhibit timeout. Caching requests for not visible rows are deleted. This means that you can easily scroll to the library several times and find uncashed covers. 

This behaviour did not change by this PR. Or is it an other regression by this PR. 

I have double checked that by searching for covers that are loaded twice via mixxx.log and addition debug messages. No issue found.

2024-10-29 07:24 UTC, JoergAtGithub commented
> 
> @JoergAtGithub, how do you test exctly. How do you know hat the covers are reloaded during scrolling? I cannot confirm.

I scrolled up and down multiple times, and are pretty sure that the same covers were shown with the preview-color before the image appeared.

2024-10-29 07:29 UTC, daschuer commented
That is the desired behavior, not changed in this PR. Columns are only cache if they are shown with stopped scrolling. The caching request is discarded if they are no longer visible, but the inhibit delay is not over.

Can you confirm with plain 2.4 or any other branch you have at hand?

2024-11-03 21:51 UTC, JoergAtGithub commented
I can confirm that this behaviour is already in plain 2.4, therefore it's not a regression of this PR.

2025-01-08 14:13 UTC, ronso0 commented
@daschuer can you please rebase onto 2.5?

@mixxxdj/developers who can review this when #13708 is merged?

2025-02-12 16:09 UTC, cr7pt0gr4ph7 requested changes
_Correct_ concurrency is always complicated :sweat_smile: 

I took a deep dive into the proposed changes and tried to understand them. Here are a few suggested changes plus some questions.

2025-02-18 16:41 UTC, daschuer commented on src/library/dao/trackdao.cpp
> +    auto cacheResolver = GlobalTrackCacheResolver(fileAccess);
We don't have a strict rule about copy initialization vs direct initialization, but we had the discussion with the conclusion that the first reads more naturally and is therefore more often used in Mixxx. The original looks like a function call because of our naming rule of lower case functions and upper case class names when skimming over the code. 
I don't get the relation to scoped-RAII.

2025-02-18 16:51 UTC, daschuer commented on src/library/dao/trackdao.cpp
> +    const auto fileAccess = mixxx::FileAccess(mixxx::FileInfo(filePath));
The change is a result form inlining an unused overload of `addTracksAddFile()` see here: 
https://github.com/mixxxdj/mixxx/pull/13719/commits/0a25713dae575fa013c14685de7e5f5530964fa4
The `QString& filePath` overload was always there.

2025-02-18 16:52 UTC, daschuer commented on src/sources/soundsourceproxy.cpp
> +    auto cacheResolver = GlobalTrackCacheResolver(trackFileAccess, temporary);
We prefer copy initialization,

2025-02-18 17:05 UTC, daschuer commented on src/sources/soundsourceproxy.cpp
> +    auto cacheResolver = GlobalTrackCacheResolver(trackFileAccess, temporary);
I have added a block to visualize the scoped-RAII.

2025-02-18 17:30 UTC, daschuer commented on src/track/globaltrackcache.cpp
> +    m_pInstance->m_mutex.unlock();
I agree that there is room for improvements. But let's not do this in this PR.

2025-02-18 18:46 UTC, daschuer commented on src/track/globaltrackcache.cpp
> +        m_pInstance->discardIncompleteTrack();
The GlobalTrackCache allows only one GlobalTrackCacheResolver using the m_incompleteTrack all others are suspended in the constructor using m_isTrackCompleted QWaitCondition. 
I will add a comment.

2025-02-18 19:05 UTC, daschuer commented
Done.

2025-02-25 20:23 UTC, daschuer commented
This is now open since a while. It is an important fix for me. I really like to have it in 2.5.1. 
Who can take care for merging?

2025-02-25 21:17 UTC, ronso0 commented
@cr7pt0gr4ph7 Can you check if you're okay with the review resolves?

Anyone else of @mixxxdj/developers can take a look please?

2025-02-26 00:15 UTC, acolombier requested changes

2025-02-26 00:15 UTC, acolombier commented on src/library/dao/trackdao.cpp
> +        Q_UNUSED(future)
nit: Is there value in storing the future in an unsed variable droped in the same scope? It feels a bit bloated to me
```suggestion
        // Don't wait for the result and keep running in the background
        guessTrackCoverInfoConcurrently(pAddedTrack);
```

2025-02-26 00:15 UTC, acolombier commented on src/library/scanner/libraryscanner.cpp
>          // TODO(XXX): Is it really intended to acknowledge a failed
Out of curiosity, did you get a chance to answer this `TODO` your exploration?

2025-02-26 00:15 UTC, acolombier commented on src/sources/soundsourceproxy.cpp
> +        TrackPointer pTrack = cacheResolver.getTrack();
This could fail and return a `nullptr` (due to the early return safety to be restored), an y chance we can protect that?

2025-02-26 00:15 UTC, acolombier commented on src/test/globaltrackcache_test.cpp
> +        // track, GlobalTrackCacheResolver::m_strongPtr and GlobalTrackCache::m_incompletTrack
Is this comment cruft useful? If not, remove?

2025-02-26 00:15 UTC, acolombier commented on src/track/globaltrackcache.cpp
> +                if (debugLogEnabled()) {
This condition feels redundant - it seems to check whether debug logs are enable to then send logs to debug anyway. AFAIK, there is no value in doing so ass debug logging would translate to no-op anyway, so this looks like unnecessary optimisation.

Note that `debugLogEnabled` seems to also check for `kLogEnabled` but this is not used anywhere, meaning that it duplicate what you would already get with `log-level=debug` anway, without needed recompilation

2025-02-26 00:15 UTC, acolombier commented on src/track/globaltrackcache.cpp
> +    m_mutex.lock();
Where is mutex being unlocked? Is this done in a nested call?

2025-02-26 00:32 UTC, ronso0 commented on src/library/dao/trackdao.cpp
> +            qDebug() << "TrackDAO::addTracksAddFile:"
One benefit of Logger is that we can set the prefix and don't have to do so for each call.
(didn't check if it set here)

2025-02-26 23:08 UTC, cr7pt0gr4ph7 requested changes

2025-02-26 23:08 UTC, cr7pt0gr4ph7 commented on src/track/globaltrackcache.cpp
> +    m_mutex.lock();
> Where is mutex being unlocked? Is this done in a nested call?

The `m_mutex.lock()` should be removed here, and moved to [L206](https://github.com/mixxxdj/mixxx/blob/0f633489f77f8624c96ac64c88b8ad0ff8f8017f/src/track/globaltrackcache.cpp#L206) (`GlobalTrackCacheResolver::initTrackIdAndUnlockCache()`) instead.

2025-02-26 23:09 UTC, cr7pt0gr4ph7 commented on src/library/dao/trackdao.cpp
> +        Q_UNUSED(future)
`guessTrackCoverInfoConcurrently` is marked as `[[nodiscard]]` - which is usually the right call when returning futures, as discarding them is usually indicative of an oversight. So the `Q_UNUSED` is required.

I wouldn't consider this bloat, as I find the current code nice & self-documenting.

2025-02-27 07:36 UTC, daschuer commented on src/test/globaltrackcache_test.cpp
> +            auto resolver = GlobalTrackCacheResolver(testFileAccess);
I prefer the assignment via = because it reads more naturally

2025-02-27 08:17 UTC, daschuer commented on src/library/dao/trackdao.h
> +            bool unremove);
The change just happens because of incoming a function. See my other comment.

2025-02-27 12:38 UTC, daschuer commented on src/sources/soundsourceproxy.cpp
> +        TrackPointer pTrack = cacheResolver.getTrack();
I have added a source code comment.

2025-02-27 12:53 UTC, daschuer commented on src/track/globaltrackcache.cpp
> +                if (debugLogEnabled()) {
This debug message is disable by default. In other place this message is just left as a comment. In this class the original author has coded around this. I have no intererst to change it here. 

When debugging. I actually prefere to enable/disable debug messages via //. I have normally no overview what I will see if after I bulk enable debugging with such a feature.

2025-02-28 08:16 UTC, daschuer commented
I think I have addressed everything and it is still working as desired. 
Thank you for review.

2025-03-16 19:58 UTC, daschuer commented
@acolombier Is this ready to merge now. I really like to see this merged to 2.5.1 after half a year.

2025-03-17 00:19 UTC, acolombier approved these changes
LGTM, thanks

2025-03-17 00:20 UTC, merged