[POC] Overview: abort play pos dragging if cursor is relased outside the valid area
mixxxdj/mixxx pull request #13741
Opened 2024-10-08 22:39 UTC by ronso0

If the cursor leaves the valid area while dragging
* show a warning cursor
* remove the time ruler, restore regular play pos painting

![overview-drag-abort](https://github.com/user-attachments/assets/cbbe184a-1473-4d29-b19a-8c34674a4bce)

The margin is 50px curently.
I didn't yet look into how devicePixeRatio is relevant here.
And I'm not 100% sure that the cursor is reset in all situations it should be.

2024-10-09 09:38 UTC, ronso0 commented
Btw I'd prefer the regular cursor with the usual 'Drop not allowed' icon attached, but that only works for QDrag cursors.
Turning the overview drag into a QDrag is overkill IMO (and I'm not motivated to do that).

Besides that I'm pretty satisfied with how this works.
I think in order to get this mergable we need to discuss
* the margin: is a threshold of 50px vertically and 100px horizontally okay? (swapped for vertical overviews)
* the 'Drag not allowed' icon

2024-10-09 10:27 UTC, spotlesscoder commented
looks great :) I will test it later

2024-10-09 16:14 UTC, spotlesscoder commented
can you please guide me where to click to download the macOS arm64 build?

2024-10-09 16:31 UTC, ronso0 commented
Testing instructions are in the wiki
https://github.com/mixxxdj/mixxx/wiki/Testing

2024-10-09 16:37 UTC, spotlesscoder commented
Thank you :)

2024-10-09 16:44 UTC, spotlesscoder commented
I get this error message

One of the files this plug-in needs cannot be found, please reinstall or contact technical support for assistance.

But nothing is written to the logfile

2024-10-09 16:50 UTC, ronso0 commented
Sounds like a macOS error message. Does it print more details?

Did you try to remove Mixxx, then install the CI build again?

2024-10-09 16:55 UTC, spotlesscoder commented
This is what the error looks like on the screen - not sure wether from macOS or mixxx
![image](https://github.com/user-attachments/assets/6f1e41df-98f5-4a9a-ae3a-eaa6e50277dc)

2024-10-09 16:56 UTC, spotlesscoder commented
Do I also have to remove all my local config data when trying again?

2024-10-09 17:14 UTC, ronso0 commented
Let's first check the log file.
But actually this going off-topic, so let's move this discussion to a issue/bug.
Please file a report at https://github.com/mixxxdj/mixxx/issues attach the log file ([here's how to find it](https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file)).

Thank you!

> Do I also have to remove all my local config data when trying again?

You can try, sure, we'll see if that makes a difference. The Testing page also has info wrt backups https://github.com/mixxxdj/mixxx/wiki/Testing#backup-settings-and-database, in case you don't want to throw away all you data.

2024-10-09 18:33 UTC, spotlesscoder commented
https://github.com/mixxxdj/mixxx/issues/13746

2024-10-10 22:27 UTC, spotlesscoder commented
The error still occurs with mixxx-2.6-alpha-106-g26e7afc968.dmg even after deleting the old Mixxx folder

2024-10-10 22:31 UTC, ronso0 commented
Okay (not). I have no clue how this relates to this PR tbh. These are only changes to the drag behavior, no new modules or plugins are added.

2024-10-28 12:46 UTC, ronso0 commented
I rebased onto 2.5 since I consider this a UX fix.
(so actually 2.4 but since 2.4.2 and 2.5 will be released roughly at the same time :man_shrugging: )

I need some help with the TODOs
1) check if devicePixeRatio is relevant here
testing on HiDPI screens
2) make 100% sure that the cursor is reset in all possible situations
I tested with track load and passthrough toggle while dragging. Anything else?

2024-11-06 16:50 UTC, spotlesscoder commented
I'll also test this once I find the time

2025-01-16 22:23 UTC, daschuer requested changes

2025-01-17 16:19 UTC, ronso0 commented on res/images/cross_circle_red.svg
Yes, that works! Thank you, didn't consider these cursors.

2025-01-25 23:11 UTC, daschuer approved these changes
LGTM. Please squash fixup. And than we can merge. Thank you.

2025-01-26 13:21 UTC, ronso0 commented
Cool, done!

2025-01-26 15:16 UTC, Holzhaus commented
Merging, as this was approved by @daschuer and CI passes.

2025-01-26 15:16 UTC, merged