Track menu, purge: allow to hide further success popups in the current session
mixxxdj/mixxx pull request #13807
Opened 2024-10-28 12:54 UTC by ronso0

adds a checkbox to the success popup
"Don't show again during this session"

Same method as for "Don't ask again" in the mapping overwrite dialog.

2024-11-02 13:23 UTC, cr7pt0gr4ph7 requested changes
I'd suggest renaming the variable to `s_showPurgeSuccessPopup`, and also removing the Qt5 workarounds while already at it. Otherwise LGTM.

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.h
> +    static bool s_showPurgesuccessPopup;
```suggestion
    static bool s_showPurgeSuccessPopup;
```

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.cpp
> +        if (s_showPurgesuccessPopup) {
```suggestion
        if (s_showPurgeSuccessPopup) {
```

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.cpp
> +bool WTrackMenu::s_showPurgesuccessPopup = true;
```suggestion
bool WTrackMenu::s_showPurgeSuccessPopup = true;
```

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.cpp
>  #endif
The `#if` for Qt5 can be removed, now that we have fully migrated to Qt6 (at least to my knowledge, correct me if I'm wrong)

```suggestion
                msgTitle = tr("Track Files Moved To Trash");
```

Also, the `#if` condition was already wrong/exactly backwards - compare with:
https://github.com/mixxxdj/mixxx/blob/edae0ca3b2fc36c51d9f310f341fb2e4bbea7d26/src/widget/wtrackmenu.cpp#L341-L345

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.cpp
>  #endif
The `#if` for Qt5 can be removed here, too (though at least the `#if` condition is correct here):
```suggestion
                        tr("%1 track files were moved to trash and purged "
                           "from the Mixxx database.")
```
 
 https://github.com/mixxxdj/mixxx/blob/dbb9610fabf78b5957194ad89867f4896eff2743/src/widget/wtrackmenu.cpp#L2375C2-L2379C7

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.cpp
>  #endif
```suggestion
                msgTitle = tr("Track File Moved To Trash");
                msgText = tr(
                        "Track file was moved to trash and purged "
                        "from the Mixxx database.");
```

2024-11-02 13:23 UTC, cr7pt0gr4ph7 commented on src/widget/wtrackmenu.cpp
> +                s_showPurgesuccessPopup = false;
```suggestion
                s_showPurgeSuccessPopup = false;
```

2024-11-02 14:02 UTC, ronso0 commented
Thanks. I fixed the static's name.

Also, I unified the Qt version switches.
Though, IMO this is not the place/time to remove Qt5 paths. Let's do this in one flush as soon as the core team agrees to drop Qt5 support entirely.

2024-11-02 14:51 UTC, cr7pt0gr4ph7 approved these changes
Looks good to me :+1:

2024-11-03 09:50 UTC, daschuer approved these changes
Thank you.

2024-11-03 09:50 UTC, merged