Changelog for 2.4.2
mixxxdj/mixxx pull request #13823
Opened 2024-11-02 14:23 UTC by daschuer

Here a step towards overdue 2.4.2 release.

2024-11-03 20:56 UTC, daschuer commented
Updated with latest merges.

2024-11-05 22:25 UTC, ronso0 requested changes
Thank you!
Found some nits, didn't yet check the PR/issue links

2024-11-05 22:25 UTC, ronso0 commented on CHANGELOG.md
> +  [#13463](https://github.com/mixxxdj/mixxx/pull/13463)
Duplicate, it's already listed above
```suggestion
```

2024-11-05 22:25 UTC, ronso0 commented on CHANGELOG.md
> +* Denon MC7000: Fix star up/down logic by only handling button down events [#13588](https://github.com/mixxxdj/mixxx/pull/1358)
```suggestion
* Denon MC7000: Fix star up/down logic by only handling button down events [#13588](https://github.com/mixxxdj/mixxx/pull/13588)
```

2024-11-05 22:25 UTC, ronso0 commented on CHANGELOG.md
> +* Fix quantization in the effect engine (mentronome effect)
```suggestion
* Fix quantization in the effect engine (metronome effect)
```

2024-11-08 13:43 UTC, daschuer commented
I have amend the fix. Once this is merged we can proceed with the release. 

Does one want to take care of the remaining bugs before: 
https://github.com/mixxxdj/mixxx/milestones/2.4.2

2024-11-08 14:15 UTC, Swiftb0y reviewed
whoops. left this one pending.

2024-11-10 14:43 UTC, daschuer commented
@ronso0 Can this be merged now?

2024-11-10 16:01 UTC, Swiftb0y approved these changes
LGTM. Thank you.

2024-11-10 19:34 UTC, merged