Fix sampler sync functionality for Mixxx skins
mixxxdj/mixxx pull request #13820
Opened 2024-11-01 21:11 UTC by urek69mazino

This PR addresses an issue with the sampler sync functionality across several Mixxx skins, updating the sync control to improve usability and ensure consistency in behavior.

Changes Made:
Updated XML Configuration Files for Skins:

Replaced beatsync_beatsync_tempo with sync_enabled in the following XML files to align with the updated sync functionality:
Deere: res/skins/Deere/sampler_controls_row.xml (Line 88)
Shade: res/skins/Shade/sampler.xml (Line 301)
LateNight: res/skins/LateNight/samplers/sampler.xml (Line 370)
Tango: res/skins/Tango/mic_aux_sampler/sampler.xml (Lines 128 and 340)
Updated Tooltip and Connection Attributes:

Modified the TooltipId and left_connection_control attributes as required to use sync_enabled for improved control and readability.
Testing:
Verified each skin to ensure that pressing the sync button behaves as expected.
Held the sync button to confirm that the "lock sync" feature engages as described.
No issues or regressions observed after these changes.
Additional Notes:
This PR focuses solely on improving sync consistency across the mentioned skins and should not affect other skin functionality.
Please review and test the sync button behavior, especially for the lock sync feature, to confirm these changes work across various setups.

2024-11-01 21:26 UTC, ronso0 commented
Thank you for this PR!
Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

2024-11-01 21:27 UTC, ronso0 commented
Since this is a fix it should target the stable branch 2.4
Please rebase and force-push. Thank you!

If you need help with git just let us know.

2024-11-02 07:14 UTC, urek69mazino commented
when i try to rebase and do a pull request the following error is being shown "Pull request creation failed. Validation failed: must be a collaborator"

2024-11-02 07:19 UTC, urek69mazino commented
fixed it, and now I have committed the changes in the 2.4 branch

2024-11-02 10:53 UTC, cr7pt0gr4ph7 commented
> fixed it, and now I have committed the changes in the 2.4 branch

@urek696969mazino It looks like your new PR #13821 contains a lot more than just your changes.

I think what @ronso0 meant was to rebase this single commit onto the `2.4` branch, force push to the PR branch of this, and change the target branch of this PR:

```bash
# (Assuming "origin" points to your GitHub repository)
git remote add upstream git@github.com:mixxxdj/mixxx.git
git fetch upstream
git checkout fix-sampler-sync
git rebase --onto upstream/2.4 upstream/main
git push origin --force-with-lease
```

# Changing the target branch of this PR:
## Step 1: Click on `Edit`
![Bildschirmfoto vom 2024-11-02 11-49-35](https://github.com/user-attachments/assets/776aef25-2555-4fc6-a496-fe908693ce87)
## Step 2: Select `base: main` combobox
![Bildschirmfoto vom 2024-11-02 11-50-15](https://github.com/user-attachments/assets/0dfadac8-6fd2-4eb7-a8ec-e1b8e653ecac)
## Step 3: Choose `2.4` as new base branch
![Bildschirmfoto vom 2024-11-02 11-50-28](https://github.com/user-attachments/assets/4a2863c5-26bf-4872-8467-4b8084e41874)

2024-11-02 11:03 UTC, urek69mazino commented
@cr7pt0gr4ph7 i have made the changes as directed by you , kindly see if any other changes need to be made

2024-11-02 11:30 UTC, cr7pt0gr4ph7 requested changes
Thank you for this PR! It seems that this has slipped through the cracks for _at least_ ~10 years, going by the fact that the new `sync_enabled` tooltips where introduced by #298 in July of 2014...

While you're at it, could you also update the `Shade` skin` at `res/skins/Shade/sampler.xml`?https://github.com/mixxxdj/mixxx/blob/edae0ca3b2fc36c51d9f310f341fb2e4bbea7d26/res/skins/Shade/sampler.xml#L300-L319

There's also a general discussion to be had (probably independent of this PR) on how (and whether) to handle `beatsync_tempo` in the new `sync_enabled` model, see comments below for further discussion.

2024-11-02 11:30 UTC, cr7pt0gr4ph7 commented on res/skins/Deere/sampler_controls_row.xml
> +            <SetVariable name="TooltipId">sync_enabled</SetVariable>
You are only changing the tooltip here. To replace the functionality of the button, you also have to replace `left_connection` below.
```xml
            <SetVariable name="left_connection_control"><Variable name="group"/>,sync_enabled</SetVariable>
```
 Note that there is corresponding replacement for `beatsync_tempo`, so the `right_connection` should be removed. See issue comments for further discussion.

2024-11-02 11:30 UTC, cr7pt0gr4ph7 commented on res/skins/LateNight/samplers/sampler.xml
> +                <SetVariable name="TooltipId">sync_enabled</SetVariable>
Same applies here: You are currently only changing the tooltip.

2024-11-02 11:30 UTC, cr7pt0gr4ph7 commented on res/skins/Tango/mic_aux_sampler/sampler.xml
> +                <SetVariable name="TooltipId">sync_enabled</SetVariable>
And also here: You are only changing the tooltip.

2024-11-02 12:05 UTC, cr7pt0gr4ph7 commented
As mentioned in [my review comment](https://github.com/mixxxdj/mixxx/pull/13820#pullrequestreview-2411235913), there are some behavioral mismatches between the old and new sync behavior that we may have to think about. Behavior was verified using the source code and a pretty current build of Mixxx's main branch.

# Old behavior with `beatsync`/`beatsync_tempo`
The old `beatsync` behavior was like this:

* Left-click: Instanteanously sync tempo and phase to what I will call _temporary sync target_, for the lack of a better term.
* Right-click: Instanteanously sync tempo to the _temporary sync target_

Where the _temporary sync target_ is picked by `EngineSync::pickNonSyncSyncTarget` according to the rules explained in its comments:

https://github.com/mixxxdj/mixxx/blob/edae0ca3b2fc36c51d9f310f341fb2e4bbea7d26/src/engine/sync/enginesync.h#L57-L65

Main points:
- Works even if no deck is currently the sync leader, and just makes a "best guess" in that case.
- We do not care about the `quantize` setting for the sampler.

# New behavior with `sync_enabled`
While the new behavior for `sync_enabled` is currently like this:

* Left-click (short press when button is not toggled on): Instanteanously sync tempo (and phase, **if quantize is enabled**) to the _temporary sync target_.
* Left-click (long press): Enable sync tempo (and phase, **if quantize is enabled** for **both the current and the target deck**) to the _temporary sync target_.
* Left-click (short press when button is toggled on): Disable sync tempo (and phase)
* Independent of `sync_enabled` setting: Pressing play on a deck, changing its position via seek etc. automatically snap phase  to the *temporary sync target* so that the first beat is aligned with the current beat of the *temporary sync target* **if quantize is enabled** for **the current deck/sampler** (so we do _not_ care about the `quantize` setting of the target deck).

Main points:
- There is currently no way to control the `quantize` setting for samplers, but we probably want one because otherwise it is not possible to sync tempo and phase, only tempo.
- One option might be to set `quantize` to `1` for all samplers (which automatically aligns the phase when the sampler play button is pressed, even when sync is disabled), but there are probably cases where the users wants this phase lock behavior, and others where the user wants to play the sampler immediately/without phase alignment.

2024-11-02 12:26 UTC, cr7pt0gr4ph7 commented
> @cr7pt0gr4ph7 i have made the changes as directed by you , kindly see if any other changes need to be made

Thank you! Though it seems that you haven't done the rebase as described. The output should look like this:

```bash
❯ git checkout fix-sampler-sync
Already on 'fix-sampler-sync'
Your branch is up to date with 'origin/fix-sampler-sync'.

❯ git rebase --onto upstream/2.4 upstream/main
Successfully rebased and updated refs/heads/fix-sampler-sync.

❯ git push origin --force-with-lease
Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Delta compression using up to 8 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (12/12), 1016 bytes | 1016.00 KiB/s, done.
Total 12 (delta 11), reused 3 (delta 3), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (11/11), completed with 11 local objects.
To github.com:urek69mazino/mixxx.git
 + b301ccac64...19b608363d fix-sampler-sync -> fix-sampler-sync (forced update)
```

When viewing your version history via `gitk`, the state before the rebase should look like this:
![Bildschirmfoto vom 2024-11-02 13-19-39](https://github.com/user-attachments/assets/10c425fe-622d-4df6-8e4d-580a4c853f33)

And afterwards, it should look like this:
![Bildschirmfoto vom 2024-11-02 13-20-16](https://github.com/user-attachments/assets/f24814d6-b485-4444-8b91-b664c760e5fb)

2024-11-02 12:31 UTC, cr7pt0gr4ph7 commented
@urek69mazino Sorry, posted the wrong screenshots. Fixed now.

2024-11-02 12:32 UTC, cr7pt0gr4ph7 commented
@urek69mazino Could you send me the output of `git remote -v`?

2024-11-03 14:02 UTC, cr7pt0gr4ph7 commented
@urek69mazino For your convenience, you can find a rebased version of your changes at [`cr7pt0gr4ph7/mixxx:fix-sampler-sync`](https://github.com/cr7pt0gr4ph7/mixxx/tree/fix-sampler-sync), so you can force push the commits in that branch to your own `fix-sampler-sync` branch.

2025-09-23 12:12 UTC, ronso0 commented
Continued in #15399
Thanks @urek69mazino and @cr7pt0gr4ph7

2025-09-23 12:12 UTC, closed without merging