Add Sample-Based Play Position Control (m_playposition_samples)
mixxxdj/mixxx pull request #13822
Opened 2024-11-02 11:39 UTC by urek69mazino

This PR introduces a new sample-based control for tracking the play position in samples (m_playposition_samples) within the EngineBuffer class. This enhancement provides more granular access to the play position, simplifying position-based comparisons and calculations in scripts and plugins.

Key Changes
New Sample-Based Control:

Added ControlObject<double> m_playposition_samples in EngineBuffer.
This control provides the play position in samples, facilitating precise playback and position tracking in scripts.
Integration with updateIndicators:

The updateIndicators method now updates m_playposition_samples with the exact play position in samples. This ensures m_playposition_samples is always synchronized with the play position, improving accuracy in playback tracking.
Script Simplification:

This new control simplifies script calculations that previously required manual conversions from fractional play positions to sample positions, streamlining position comparisons and enhancing usability for developers.
Benefits
Improved Accuracy: The new sample-based control provides a finer level of detail than the fractional play position.
Ease of Use for Scripts: Developers can directly access the play position in samples, reducing the need for conversions in scripts.
Backward Compatibility: This change does not affect existing fractional play position controls, maintaining compatibility with prior functionality.
Testing
Verified that m_playposition_samples accurately reflects the play position in samples during playback and seek operations.
Confirmed that m_playposition_samples updates consistently in sync with updateIndicators.

2024-11-02 12:36 UTC, cr7pt0gr4ph7 commented
I'd kindly suggest formating your PR messages with [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Especially:
- `code formatting` for identifiers like `ControlObject` or `EngineBuffer`
- **bold headings**, and
- list items

would improve readability :)

2024-11-02 12:41 UTC, cr7pt0gr4ph7 commented
Just as an example (feel free to copy):
----
This PR introduces a new sample-based control for tracking the play position in samples (`m_playposition_samples`) within the `EngineBuffer` class. This enhancement provides more granular access to the play position, simplifying position-based comparisons and calculations in scripts and plugins.

# Key Changes
- **New Sample-Based Control**

  Added `ControlObject m_playposition_samples` in `EngineBuffer`. This control provides the play position in samples, facilitating precise playback and position tracking in scripts.
  
- **Integration with updateIndicators**

The `updateIndicators` method now updates `m_playposition_samples` with the exact play position in samples. This ensures `m_playposition_samples` is always synchronized with the play position, improving accuracy in playback tracking.

- **Script Simplification:**

This new control simplifies script calculations that previously required manual conversions from fractional play positions to sample positions, streamlining position comparisons and enhancing usability for developers.

# Benefits
- Improved Accuracy: The new sample-based control provides a finer level of detail than the fractional play position.
- Ease of Use for Scripts: Developers can directly access the play position in samples, reducing the need for conversions in scripts.
- Backward Compatibility: This change does not affect existing fractional play position controls, maintaining compatibility with prior functionality.
- Testing: Verified that `m_playposition_samples` accurately reflects the play position in samples during playback and seek operations. Confirmed that `m_playposition_samples` updates consistently in sync with `updateIndicators`.

2024-11-02 13:01 UTC, cr7pt0gr4ph7 requested changes
It seems like you're missing the changes to `enginebuffer.h` in this commit.

2024-11-02 13:07 UTC, cr7pt0gr4ph7 commented
In general, what is the exact use case of exposing the sample-level play position to controller scripts?
There's a reason why the play position indicators is only updated 15 times/second instead of thousands of times per second. In general, the sample-level position you obtain in a controller script will probably be outdated before you even have a chance to send it to a controler device...

https://github.com/mixxxdj/mixxx/blob/edae0ca3b2fc36c51d9f310f341fb2e4bbea7d26/src/engine/enginebuffer.cpp#L50-L51

2024-11-03 00:10 UTC, urek69mazino commented
thankyou for suggesting the changes , i will improve my pull request for the upcoming commits

2024-11-03 00:39 UTC, urek69mazino commented
I have made the changes suggested by you, but I don't know why when i commit the changes i have made to specific files, other commits also get added , kindly help me

2024-11-03 14:03 UTC, cr7pt0gr4ph7 commented
> I have made the changes suggested by you, but I don't know why when i commit the changes i have made to specific files, other commits also get added , kindly help me

I'll try :) Push your changes as they are to some branch in your GitHub repository and I'll help & try investigate.

2026-04-18 22:51 UTC, closed without merging