Optimized tooltip generation in WBaseWidget
mixxxdj/mixxx pull request #13952
Opened 2024-11-30 15:49 UTC by JoergAtGithub

Code cleanup. Main change is that empty lines at the end of the tooltips are no longer printed.

2024-12-01 12:53 UTC, daschuer commented on src/widget/wbasewidget.cpp
> +        m_pWidget->setToolTip(debug.join(QStringLiteral("\n")));
```suggestion
        m_pWidget->setToolTip(debug.join(QChar('\n')));
```

2024-12-01 17:02 UTC, daschuer commented on src/widget/wbasewidget.cpp
> +    *debug << QStringLiteral("ClassName: %1")
The QStringBuilder does it implicit for us, if we replace the %1 placeholder by normal string concat using +. 
However is it worth the efforts in this PR?

2024-12-01 17:55 UTC, Swiftb0y commented on src/widget/wbasewidget.cpp
> +    *debug << QStringLiteral("ClassName: %1")
`debug` is a `QList<QString>`. I don't see how QStringBuilder is relevant here.

2024-12-01 22:24 UTC, daschuer commented on src/widget/wbasewidget.cpp
> +    *debug << QStringLiteral("ClassName: %1")
I mean 
`QStringLiteral("ObjectName: %1").arg(m_pWidget->objectName())` 
-> 
`QStringLiteral("ObjectName: ") + m_pWidget->objectName()`

2024-12-02 10:16 UTC, Swiftb0y commented on src/widget/wbasewidget.cpp
> +    *debug << QStringLiteral("ClassName: %1")
I don't think that makes a meaningful difference for a single argument

2025-02-02 22:24 UTC, JoergAtGithub commented on src/widget/wbasewidget.cpp
> +    *debug << QStringLiteral("ClassName: %1")
I will not touch this, because it's seldom executed code only active in developer mode - and there is obviously no consensus on the correct solution either.

2025-02-02 22:37 UTC, Swiftb0y approved these changes
Loads of more stuff that could be done, but this suffices for now. LGTM. Thank you.

2025-02-03 00:35 UTC, ronso0 commented on src/widget/wbasewidget.cpp
> +    }
this does the trick, just without the boilerplate
`return QVariant::fromValue(policy).toString();`

2025-02-03 00:45 UTC, ronso0 requested changes

2025-02-03 00:45 UTC, ronso0 commented on src/widget/wbasewidget.cpp
> +        m_pWidget->setToolTip(base);
This means QWidget::setTooltip() is now called on every tooltip event which is redundant.
Please move it back into the CmdLine..dev parantheses

2025-02-09 14:32 UTC, ronso0 commented on src/widget/wbasewidget.cpp
> +    }
naa,  meant as replacement for the entire switch.

2025-02-09 14:34 UTC, ronso0 commented on src/widget/wbasewidget.cpp
> +    }
I did test it earlier, works beautifully

2025-02-09 17:32 UTC, JoergAtGithub commented on src/widget/wbasewidget.cpp
> +    }
Done!

2025-02-12 01:30 UTC, ronso0 commented
Thank you, LGTM!

2025-02-12 01:31 UTC, merged

2025-05-08 09:08 UTC, ronso0 commented
Whoopsy, this appends the shortcut tooltips without the leading linebreak.
[QString::trimmed() removes both leading and trailing whitespace, this includes the ASCII characters '\t', '\n', '\v', '\f', '\r'](https://doc.qt.io/qt-6/qstring.html#trimmed)

We should use `mixxx::removeTrailingWhitespaces()`
Will provide a PR

2025-05-08 10:03 UTC, ronso0 commented
#14757