(fix) Traktor Kontrol S4 Mk3: revert QuickEffect preset offset
mixxxdj/mixxx pull request #13997
Opened 2024-12-06 15:08 UTC by ronso0

0 is now the empty item ---
1 is the first item etc.

2024-12-06 15:39 UTC, acolombier requested changes
The reason why `0` was removed is because, as per [the doc](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[EffectRack1_EffectUnitN]-loaded_chain_preset), `0` will unselect the quick FX, so when assigning `FX 1` to a deck (or a stem starting from #13653), which made a very poor user experience. 
If you think this should still be possible, please make that a configurable setting.

2024-12-06 15:44 UTC, ronso0 commented
Yeah, I thinks it's fixed now.
@acolombier please take a look.

2024-12-06 15:46 UTC, ronso0 commented
> The reason why `0` was removed is because, as per [the doc](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-%5BEffectRack1_EffectUnitN%5D-loaded_chain_preset), `0` will unselect the quick FX, so when assigning `FX 1` to a deck (or a stem starting from #13653), which made a very poor user experience. If you think this should still be possible, please make that a configurable setting.

Umm, without this fix [1] would select the 3rd item (preset 2).
I just tested it again: [1] now selects the 1st preset, 0 can't be selected.

2024-12-06 15:50 UTC, acolombier commented
Right, looking at `FXSelect`, it looks like the computation always return 1 indeed. I'm AFK now, but I will test that later. I cannot remember why I added that offset, but it could also have been the initial Be's mapping definition.

2024-12-16 18:26 UTC, acolombier approved these changes
Tested and work as expected! Thank you

2024-12-16 18:26 UTC, merged