Devcontainer support
mixxxdj/mixxx pull request #14018
Opened 2024-12-14 13:08 UTC by acolombier

<details>
 <summary>Some context from the author</summary>
 
As I have started trying new distro to replace my unsupported PopOS22.04, I have stopped on Fedora 41 SilverBlue. While I love the concept of immutable system, and everything is a container, it does bring a chjalenge of how to develop Mixxx.

This is my attempt to provide a compressive solution. Note that I have been using a patched version of devpod to get this to work locally, but I haven't yet shared my patch for it.

</details>

TODO:

- [ ] Support commit signing
- [ ] Support git+SSH

This fixes  #13914

2025-01-18 22:18 UTC, acolombier commented
It's not perfect, but I'd like to get this initial version merged and iterate on it

2025-01-19 09:59 UTC, daschuer reviewed
In general there is nothing particular against this, except the maintenance task. So let's consider who will used this. 

If a user on an older machine wants to develop a new Mixxx version, but don't want to used it later? That sounds as an exception. 

A way more streamlined approach is to use appImage/snap/flatpak this has an equal maintenance effort, but is also usable for others and I consider this a better benefit for our users. 

Do I miss something? So I vote for not merging this.

2025-01-19 09:59 UTC, daschuer commented on tools/debian_buildenv.sh
> +            libboost-dev \
this is not required

2025-01-19 09:59 UTC, daschuer commented on tools/debian_buildenv.sh
> +            qt6-wayland \
This pulls Wayland in. We don't want this. Mixxx does not depend on wayland.

2025-01-19 11:57 UTC, acolombier commented on tools/debian_buildenv.sh
> +            qt6-wayland \
This is required if you are running with `QT_QPA_PLATFORM=wayland`. Since our minimal system requirement is Wayland by default (Ubuntu 24.04), I think it would make sense to have it, but happy to move that in the Dockerfile otherwise

2025-01-19 12:18 UTC, acolombier commented
Thanks for your review @daschuer , I think you are missing the point of what [DevContainers](https://containers.dev/) are about. DevContainer (!= container) are stricly used in develpment to ensure:
- System immutability (a must if you are developing on an immutable system or a system without superuser access)
- Reproducibility - it allows to always have a prisitine copy of the dev environment, without any external factors, which can be very useful to align with our CI env
- Cloud/Ephemeral - it is the foundation of CDE (Cloud Dev Env) such as Codespaces or DevPod in the OpenSource
![image](https://github.com/user-attachments/assets/e708b0e0-bd1b-446d-a620-613c6829b9c6)

DevContainer are completely unrelated to installable user artifact such as Snap, AppImage or Flatpak and are not meant in any ways to replace them. 

Regarding maintainability, this is similar to our [NixOS dev setup](https://github.com/mixxxdj/mixxx/blob/main/shell.nix) - it may fall unmaintained, but we are expecting developer using it to take it of it themselves

Finally, regarding your vote against, I find it puzzling since you voted for it in the [related issue](https://github.com/mixxxdj/mixxx/issues/13914) when I asked if I should bring this in 2 months ago. With the amount of time I spent on this, I'm going to assume your statement was made in confusion.
![image](https://github.com/user-attachments/assets/fec2409c-db56-4d46-bdb3-8529c913f464)

2025-01-19 12:23 UTC, jarey commented
I personally consider this really useful, speciallly for people like me, that are considering to co tribute to some issues. It would minimise friction a lot and will make it way easier to new contributors to just start checking the code and do things on it without necessarily setting up any local dev environment.

Great job on this, by the way @acolombier .

2025-01-19 12:55 UTC, acolombier commented on tools/debian_buildenv.sh
> +            qt6-wayland \
Moved the Dockerfile

2025-01-19 13:04 UTC, acolombier commented
Thanks for your feedback @jarey, greatly appreciated! 

Since no other active contributors use devconatiners to my knowledge, would you be interested in giving the setup a go? No need to do too much in there, just running the devcontainer and try [the suggested command to get Mixxx running](https://github.com/mixxxdj/mixxx/blob/b55319f5b1663b7fecbf366c517fb7a5e807efbb/README.md#using-dev-container). I mainly expect issues with X.org/Wayland connectivity and it would be great if I could at least document them

2025-01-19 18:02 UTC, JoergAtGithub commented
> Finally, regarding your vote against, I find it puzzling since you voted for it in the [related issue](https://github.com/mixxxdj/mixxx/issues/13914) when I asked if I should bring this in 2 months ago. With the amount of time I spent on this, I'm going to assume your statement was made in confusion.

We need a certain level of commitment when a core-dev makes such a vote. If no unexpected aspects arise during implementation, the contributor must assume that this work is wanted by the person who made the vote, and that this person will not oppose a merging, if the implementation is clean.

2025-01-19 21:17 UTC, daschuer commented
Sorry for the confusion. I should have made more clear that I am not blocking this PR. I have just reconsidered the pro and cons with a different result. I was under the expression that this no longer a need for it after @acolombier has moved to Fedora.

2025-01-20 21:00 UTC, acolombier commented
I have moved to Fedore Silverblue, which is immutable. I can build and run Mixxx from [toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/), but it is not possible to run an IDE insided these since apps are all flatpak based. This means devcontainer is the only viable approach 

That being said, I think allowing anybody to work on the project without having to install random dependencies is very valuable, so beside my case and immutable OSes, I think we should still allow such a setup to allow easy plug-n-dev

2025-02-02 16:41 UTC, acolombier reviewed
I have squashed the fixups and removed SELinux support as it is quite unstable. With the latest version, it possible to get a true plug-n-dev or plug-n-play experience with your own controller or audio card without tinkering. 

It'd be great if we could look at merging this as it is and fix forward if we find better optimisation.

2025-02-02 16:56 UTC, JoergAtGithub commented on .devcontainer/Dockerfile
> +    vim && \
Are all these packages developer tools, or do some belong to debian_buildenv.sh instead?

2025-02-02 18:14 UTC, acolombier commented on .devcontainer/Dockerfile
> +    vim && \
Good question - most of these packages are expected to already be installed on the machine (git, udev for example), some others provide an opinionated out of the box experience (vim, clangd, gdb).

I think it makes sense to keep it separated but open to move some of these packages in the script.

2025-02-14 20:02 UTC, acolombier commented
Friendly ping @jarey :)
Have you had a chance to give this a spin?

2025-02-25 06:29 UTC, daschuer commented
For my understanding the devcontainer.json file is missing: https://containers.dev/implementors/json_reference/

2025-02-25 07:35 UTC, daschuer requested changes
I have added some comments an questions.

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/Dockerfile
> +    sudo \
Do we need sudo? For my understanding you are already superuser in a devcontainer. 
I am afraid there are some more command line tools missing. Isn't there not a different base container of a devcontainer feature that comes with all this?

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/Dockerfile
> +    pulseaudio-utils \
Do we need all this? How is it supposed to work?

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/Dockerfile
> +COPY tools/debian_buildenv.sh /tmp/
Why we need a copy?

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/Dockerfile
> +RUN userdel -f -r ubuntu && \
What is the reason to for this change of user name? Is there an issue with the defaults?

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/Dockerfile
> +    mkdir /home/developer && echo "developer ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/developer && \
Why && all commands?

2025-02-25 07:35 UTC, daschuer commented on README.md
> +> Dev container has recently been introduced and it is likely incomplete! Currently, it's been tested with `devpod` on Zed and Codium exclusively
This will be outdated soon. Please change it that it is valid for long.

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/devcontainer.json
> +    "QT_QPA_PLATFORM": "${localEnv:QT_QPA_PLATFORM:wayland}" // Default to Wayland session, can also use 'xcb' to use X.org instead
Is this required at all?

2025-02-25 07:35 UTC, daschuer commented on .devcontainer/devcontainer.json
> +    "PATH": "/usr/lib/qt6/bin/:${containerEnv:PATH}",
Is this required?

2025-02-25 07:35 UTC, daschuer commented on .github/workflows/devcontainer.yml
> +      - name: Build and push Docker image
How does this work?

2025-02-25 07:35 UTC, daschuer commented on README.md
> +mkdir build
Following this, we build locally, right?

2025-02-25 07:39 UTC, daschuer commented on README.md
> +Similar to Fedora Toolbox's, the default configuration provide a comprehensive definition of mounts which will allow use to use Mixxx seamlessly in the container. (UI, audio, ...)
Why reference  "Fedora Toolbox's"

2025-02-25 14:04 UTC, acolombier reviewed
Thanks for looking into this @daschuer !

2025-02-25 14:04 UTC, acolombier commented on README.md
> +Similar to Fedora Toolbox's, the default configuration provide a comprehensive definition of mounts which will allow use to use Mixxx seamlessly in the container. (UI, audio, ...)
Because this is the other big initiative around dev containerisation. It's less mature, supported and popular (yet), but I know we discuss about it as well so I thought it was worth to make the parallel for user that my have heard only of Fedora Toolbox (e.g Silverblue user) since it literally equivalent and work as a drop-in replacement

2025-02-26 10:37 UTC, acolombier commented on .devcontainer/Dockerfile
> +    qt6-wayland \
It is needed - without this, Mixxx cannot start
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimalegl, offscreen, eglfs, xcb, vkkhrdisplay, minimal, linuxfb, vnc.
```

2025-03-04 00:12 UTC, daschuer commented
Thank you for changes. Can you squash the fixup. 
The readme is missing a step by step guide how to use the container. I think that is required.

2025-03-04 00:24 UTC, acolombier commented
Thanks for the follow up - I have added a small tip here, let me known if something more hands on should be provided there.

2025-03-04 16:27 UTC, daschuer requested changes
I have suggested some text tweaks

2025-03-04 16:27 UTC, daschuer commented on README.md
> +> New to devcontainer? If you use VSCode, the IDE should offer you to use devcontainer when you open the Mixxx project. If you are not using VSCode,
Spelled "VS Code" 
```suggestion
> If you use VS Code, the IDE should offer you to use Dev Container when you open the mixxx working copy folder. Otherwise, 
```

2025-03-04 16:27 UTC, daschuer commented on README.md
> +Similar to Fedora Toolbox's, the default configuration provide a comprehensive definition of mounts which will allow use to use Mixxx seamlessly in the container. (UI, audio, ...)
```suggestion
The default configuration provide a comprehensive definition of mounts which will allow you to use Mixxx seamlessly in the container. (UI, audio, ...)
```

2025-03-04 16:27 UTC, daschuer commented on README.md
> +#### Using your device in DevContainer
```suggestion
#### Using your device in Dev Container
```

2025-03-04 16:27 UTC, daschuer commented on README.md
> +Devices be supported by default, thanks to the provided binds. Note that if you are encountering permission issue, check that you are not using SELinux, as this is currently not well supported in Dev
```suggestion
Devices be supported by default, thanks to the provided binds. Note that if you are encountering permission issue, check that you are not using SELinux, as this is currently not well supported in Dev Container
```

2025-03-04 16:27 UTC, daschuer commented on README.md
> +Devices be supported by default, thanks to the provided binds. Note that if you are encountering permission issue, check that you are not using SELinux, as this is currently not well supported in Dev
Or remove the paragraph and move the note after "the container. (UI, audio, ...)" above.

2025-03-06 12:13 UTC, daschuer commented on README.md
> +Similar to Fedora Toolbox's, the default configuration provide a comprehensive definition of mounts which will allow use to use Mixxx seamlessly in the container. (UI, audio, ...)
OK, in that case I would add an additional sentences that explains it the rationals and implications ... or link external resources.

2025-03-06 12:16 UTC, daschuer commented on README.md
> +If you are not comfortable with this, you may want to remove some or all of the binding before starting the container.
Ok, than put it in the additional sentences about security concerns.

2025-03-06 12:19 UTC, daschuer commented on README.md
> +> New to [dev container](https://containers.dev/)? If you use VS Code, the IDE should offer you to use Dev Container when you open the Mixxx working copy folder. Otherwise,
OK, but use the right spelling: 
```suggestion
> New to [Development Containers](https://containers.dev/)? If you use VS Code, the IDE should offer you to use Dev Container when you open the Mixxx working copy folder. Otherwise,
```

2025-03-06 12:24 UTC, daschuer commented on README.md
> +If you are not comfortable with this, you may want to remove some or all of the binding before starting the container.
Maybe a paragraph unter "Using your device in Dev Container" ? 

I have been original stumbled over it, because we start with concerns. That apply in the same way to the alternative of native install anyway. Instead it would be better to start with the benefits compared to that. 

The point which is missing is the additional disk space it needs compare to a native build environment. Can you give an estimate?

2025-03-09 07:55 UTC, daschuer commented on README.md
> +> Dev container has recently been introduced and it is likely incomplete! Currently, it's been tested with `devpod` on Zed and Codium exclusively
Did you gain more experience with this meanwhile? 
This note is very prominent compared to the rest of the Readme. Can we remove it?

2025-03-09 07:57 UTC, daschuer commented
How about moving the whole Dev Container paragraph out of the main repository readme to the wiki?

2025-03-09 08:03 UTC, daschuer requested changes
After merging, every VS-Code user is urged to use UbuntuDev containers instead of native builds which is not recommended. I think it is required to make it not the defaul for VS-Code.

I consider this a blocker for merging. Can we move the .devcontainer folder to the tools subfolder for VS-Code?

2025-03-09 10:52 UTC, acolombier commented
> How about moving the whole Dev Container paragraph out of the main repository readme to the wiki?

What is the point of this? I can only see drawbacks:
1. Non core member won't be able to contribute (comment, update accordingly)
2. Information will only be harder to reach

> every VS-Code user is urged to use UbuntuDev containers instead of native builds

Sorry, but that's not true. You are only "suggested" to open in Dev Container if:
1. You have the dev container extension installed (meaning you use dev container)
2. You have't disabled that tip (clicked the `Don't Show Again` button, or set the setting key accordingly)
 
(I assuming the urge you are referring to is this popup)
![image](https://github.com/user-attachments/assets/53307e34-0e7d-4676-9e7d-7bafbdcb73d4)

> which is not recommended

What is the rational for that statement? This sounds like an opinion rather than objective fact? Could you please elaborate?

> Can we move the .devcontainer folder to the tools subfolder for VS-Code?

No you cannot, please read [the spec](https://containers.dev/implementors/templates-distribution/#packaging). This is that same as moving the `.github` or the `README.md` out of the project root, this will simply break the feature.

2025-03-09 11:21 UTC, daschuer commented
>> How about moving the whole Dev Container paragraph out of the main repository readme to the wiki?

> What is the point of this?

This gives the chance to give more explanations, without clutter the main Readme.md. But I don't mind which way you prefer.

2025-03-09 11:25 UTC, daschuer commented
>> every VS-Code user is urged to use UbuntuDev containers instead of native builds

> Sorry, but that's not true. You are only "suggested" to open in Dev Container if:
>  You have the dev container extension installed (meaning you use dev container)
> You have't disabled that tip (clicked the Don't Show Again button, or set the setting key accordingly)

I cannot confirm. In my case VS-Code installed automatically all requirements when you except all proposals. That is what new contributors do. 
This must not happen.

2025-03-09 11:28 UTC, daschuer commented
>> which is not recommended

> What is the rational for that statement? This sounds like an opinion rather than objective fact? Could you please elaborate?

Ins't it obvious that windows users want a windows build? Please describe why you want that windows and macOS users should use Mixxx in a Ubuntu docker cintainer?

2025-03-09 11:32 UTC, daschuer commented
>> Can we move the .devcontainer folder to the tools subfolder for VS-Code?

> No you cannot, please read the spec. This is that same as moving the .github or the README.md out of the project root, this will simply

Sorry that I am not expert in dev containers. I think it is up to you to propose a solution. 

For me it works flawlessly to open a subfolder with a `. devcontainer` folder. What issue do you expect?

2025-03-09 15:58 UTC, acolombier commented
> This gives the chance to give more explanations, without clutter the main Readme.md. But I don't mind which way you prefer.

Fair enough. As a middle ground, I could trim the content from the `README.md` and move additional details (e.g bindings etc) inside a `docs/devcontainer.md` file. Wdyt? 

> Ins't it obvious that windows users want a windows build? Please describe why you want that windows and macOS users should use Mixxx in a Ubuntu docker cintainer?

My experience with developing Mixxx on Windows and Mac (disclaimer - in VM, but I think my point stands) is that working with VCPKG is quite complicated, compare to the embedded build environment. Of course, depending of what you want to do, building with VPCKG may be required, but since we ship build artifacts as part of[ the pipeline ](https://github.com/mixxxdj/mixxx/actions/runs/13687241124), users needing to build Mixxx locally to test new feature has gone down, meaning new contributor could benefit from having a fully-fledge dev environment not specific to their OS (also, note that having that `build` volume allow user to actually do both) and would help with for example, pre-commits, which is still something we have with many new contributors, or less experimented developers.) 

> For me it works flawlessly to open a subfolder with a `.devcontainer` folder. What issue do you expect?

The problem comes with the workspace - say you move `.devcontainer` inside `tools`, Dev Container would bind the workspace as `tools` instead of the root of the repo, making the devcontainer spec unusable. There is some tinkering you can do with your VSCode extenssion or `devpod up` setup, but this requires a significant amount of tinkering

2025-03-09 16:11 UTC, acolombier commented on README.md
> +If you are not comfortable with this, you may want to remove some or all of the binding before starting the container.
Fair, I moved it there.

> Can you give an estimate?

The [base image](https://hub.docker.com/_/ubuntu/tags?name=24.04) is about 30M, the dev container apt deps appears to require about 1.3 GB of additional disk space (as mentioned via APT, haven't confirmed the measure). It is hard to compare with native build environment tho because these are dependencies you would have to install on your native machine anyway (build-essential or ninja-build for example). For full disclosure, here is the current footprint of my dev container environment, including volumes (so not part of the container or image), in case you want to compare it with your native env:

```
localhost/vsc-mixxx-0637a   2.485GB
mixxx-bashistory            22.09kB
mixxx-ccache                0B
mixxx-config                255.5MB
mixxx-precommit             1.361GB
mixxx-build                 3.739GB
```

2025-05-12 21:49 UTC, JoergAtGithub commented
@daschuer This does not affect the build of Mixxx itself. This PR can therefore be targeted to a stable release without any risk! Please set the tzarget to 2.6 therefore!

2025-05-13 05:20 UTC, daschuer commented
Our stable branch is the 2.5 branch. If you like we can rebase it to that. Since this is independent from any release. I will remove the milestone for now. Set it again If you like.

2025-08-19 23:13 UTC, acolombier commented
Rebased against `2.5` and fixed conflict. @daschuer could you point me to what is remaining to address?

2025-08-20 10:04 UTC, daschuer commented
I have double checked again, this comment still applies: 
https://github.com/mixxxdj/mixxx/pull/14018#pullrequestreview-2669342570

After merging, every VS-Code user is urged to use UbuntuDev containers instead of native builds which is not recommended. 

No MacOS or Window user should ever build in a Linux Dev container. Also Linux user should not build in a dev container unless they have a strong reason for it. It is a high value for our project to have a high testing coverage of a the systems out there. After merging this it will become more unified which is not desired. The build done in a dev container is not the same than the final build we release.  

So please move the `.devcontainer` folder out of the root. Users who want to use it can use a symlink instead.

2025-08-20 18:27 UTC, closed without merging

2025-08-20 18:48 UTC, JoergAtGithub commented
What is the problem with using a symlink here? Isn't that a one-time operation on the local file system that remains in place after a git checkout/switch?

2025-08-20 19:06 UTC, acolombier commented
No problem with creating a symlink. 

The problem that this is supposed to solve however doesn't exist and I am not interested in supporting a non-compliant hacky dev-container setup, dictated by members that don't even use them.

2025-08-20 19:42 UTC, ywwg commented
> After merging, every VS-Code user is urged to use UbuntuDev containers instead of native builds which is not recommended.

@daschuer have you confirmed that this is actually the case? You have been asserting that there would be a specific non-desirable workflow for mac or windows developers but I do not see evidence to confirm it.  Have you tested on windows or mac and confirm that this situation is true? If I understand, specifically you're saying that mac or windows developers would be encouraged to create ubuntu devcontainer builds instead of native builds.  Without confirmation of this problem, there is no basis for your requests for changes.

2025-08-20 19:58 UTC, acolombier commented
Just to clarify @ywwg, it is correct that opening a project with a devcontainer configuration will ask you if you want to open it into a devcontainer (popup at bottom right)

<img width="2552" height="1376" alt="image" src="https://github.com/user-attachments/assets/e0efeac5-3b24-493c-b6b1-fc25d6eeae5e" />

I'm arguing this isn't an urge to use it, simply an option.

Furthermore, this implies that users have installed [the addon](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers). IMO, this suggests that they would be informed of what DevContainer are, and wouldn't be trapped into using a Linux emulation against their will, when running another OS

2025-08-20 20:09 UTC, ywwg commented
This seems like a bug with VSCode, not Mixxx.

2025-08-20 20:11 UTC, ywwg commented
could we provide a little cmake command like `cmake devcontainer` (or whatever) that creates the .devcontainer folder if people want it?  Then it would not be a hacky symlink and would not exist unless someone follows specific directions to initialize it.

2025-08-20 20:33 UTC, daschuer commented
@ywwg 

> @daschuer have you confirmed that this is actually the case? You have been asserting that there would be a specific non-desirable workflow for mac or windows developers but I do not see evidence to confirm it. 

Yes. I have tested this on Ubuntu and a Windows 10 PC. https://github.com/mixxxdj/mixxx/pull/14018#issuecomment-2708808933

2025-08-20 21:53 UTC, ywwg commented
> In my case VS-Code installed automatically all requirements when you except all proposals.

I do not feel Mixxx is responsible for the user selecting an option presented to them by a third party software.  We could at the very least provide information on the wiki about whether a windows/mac developer would want this.

Regardless, what do you think of my suggestion to only create the devcontainer infrastructure if the user follows specific instructions? That would seem to address both your desire not to expose this option to users and @acolombier 's desire to have devcontainer usable without hacks.

2025-08-20 22:02 UTC, acolombier commented
The reasons why I am reluctant to go with this option is that it would require user to install `cmake`, which would prevent the use case of immutable distros  (which the reason I adopted devcontainer on Mixxx) and/or usage within integrated IDE installed via Snap or Flatpak

2025-08-21 02:00 UTC, ywwg commented
even a shell script could accomplish the task of creating the proper directory / putting files in it, etc.  doesn't have to be cmake

2025-08-21 07:20 UTC, acolombier commented
Sure, I would even say a single one-liner command like `cp -r ./tools/devcontainer .devcontainer` would get that likely working.

However, this measure is being put in place because we assume our average contributor just blindly click CTAs when they pop in non-blocking notification. 

Again, this is another case of solutionising and in this case by breaking away from an established spec. 

Instead we could have got that in 6 months ago, and if indeed we had user raising issues, we could have moved that in another folder, or even better, we could have engaged on the [spec repo](https://github.com/devcontainers/spec), with actual prove on this limit, and get Mixxx to help the spec to progress.