(fix) DlgTrackInfo/~Multi: use configured notation for key display
mixxxdj/mixxx pull request #14011
Opened 2024-12-12 00:29 UTC by ronso0

Previously, Track Properties did show the key text stored in the track, not the corresponding key of the notation selected in Key preferences. Furthermore, when selecting such a key literal text of  a different notation in DlgTrackInfoMulti, that string was always converted to 'Traditional' notation (select 5A, get Cm).

This fixes Track Properties and uses the new helper function in Key preferences.

2024-12-13 14:47 UTC, daschuer requested changes
I can confirm the issue. The fix can be improved.

2024-12-13 14:47 UTC, daschuer commented on src/library/dlgtrackinfo.cpp
> +                    m_notation);
The issue is probably caused of hard to used code. We have here a hint:
https://github.com/mixxxdj/mixxx/blob/9817e5eab23ce907f8e49bfdb0050fef9549257d/src/track/track.cpp#L1453
but not here: 
https://github.com/mixxxdj/mixxx/blob/24a84b9d64607bb2b2cdcfc270bf9cb885074f3a/src/track/trackinfo.h#L35

The later seems to ba a container fr the key text stored in track metadata. Do we want to rename (again) it or at least add a comment? 

I think here we want exactly what found in the metadata, right?  
https://github.com/mixxxdj/mixxx/blob/9817e5eab23ce907f8e49bfdb0050fef9549257d/src/library/browse/browsethread.cpp#L239

2024-12-13 14:47 UTC, daschuer commented on src/library/dlgtrackinfo.cpp
> +                    m_notation);
I think it is better to use the same string the track object will return for display purpose: 
```suggestion
    const QString keyText = KeyUtils::keyToString(m_record.getKeys().getGlobalKey());
```
this should work without `m_notation` which can be probably be removed, (not tested)

2024-12-13 14:47 UTC, daschuer commented on src/track/keyutils.cpp
> +KeyUtils::KeyNotation KeyUtils::keyNotationFromString(const QString& notationName) {
Please keep this nice refactoring.

2024-12-14 01:47 UTC, ronso0 commented
You're right, that code ishard to use : P
I overlooked `KeyUtils::setNotation()` which makes `keyToString()` use the selected notation.

Here are my observations:
Throwing Snow - Iridis
| | |
|---|---|
|Tracks  | 1A |
Deck |    1A
Track Properties dialog |     G#m
-> Re-import from file |1A
| | | 
database |  G#m
file metadat|     G#m

2024-12-14 02:18 UTC, ronso0 commented
Yes, it does work without `m_notation`

2024-12-14 02:24 UTC, ronso0 commented
I have no energy to look into the [inconsistency described above](https://github.com/mixxxdj/mixxx/pull/14011#issuecomment-2542653733), though we should fix that IMO.

(btw I don' consider this here a blocker, it's probably been like this for quite some time, 2.4 and earlier I think)

2024-12-15 22:46 UTC, daschuer approved these changes
LGTM, thank you.

2024-12-15 22:46 UTC, merged

2024-12-15 23:35 UTC, ronso0 commented
Thanks @daschuer for your hints!