Update CHANGELOG.md for 2.5.0
mixxxdj/mixxx pull request #14033
Opened 2024-12-18 07:11 UTC by daschuer

The next step is to polish it a bit and remove uninteresting entries.

2024-12-20 09:22 UTC, daschuer commented
This is now up to date. Does one have a look? Next I will prepare a polish PR.

2024-12-20 16:32 UTC, JoergAtGithub requested changes

2024-12-20 16:32 UTC, JoergAtGithub commented on CHANGELOG.md
> +  [#13958](https://github.com/mixxxdj/mixxx/issues/13100)
```suggestion
  [#13100](https://github.com/mixxxdj/mixxx/issues/13100)
```

2024-12-20 16:32 UTC, JoergAtGithub commented on CHANGELOG.md
> +  [#13899](https://github.com/mixxxdj/mixxx/pull/13899)
```suggestion
  [#13899](https://github.com/mixxxdj/mixxx/pull/13899)
```
Duplicate

2024-12-21 16:24 UTC, daschuer commented
Fixed the issues. I will merge this now and open a new one with the reorganization.

2024-12-21 16:24 UTC, merged