Update skin preview images
mixxxdj/mixxx pull request #14044
Opened 2024-12-20 12:39 UTC by daschuer

2024-12-20 18:32 UTC, ronso0 commented
unfortunately we can't use these screens: colors are not correct, library font is custom
See https://mixxx.zulipchat.com/#narrow/channel/109171-development/topic/2.2E5.2E0.20release.20deadline/near/490199318

2024-12-22 21:49 UTC, ronso0 commented
These are still the images with the screen calibration by @Eve00000 , ie. wrong colors.
See this diff for example
![image](https://github.com/user-attachments/assets/5c83e34e-f96d-43b2-874f-1a80543bc441)

2024-12-22 21:53 UTC, ronso0 commented
Actually, the only difference 2.4 --> 2.5 I can spot at a glance in the **previews** are
* the new effect unit menu button
* no menubar anymore

Layout / features shown in the old screens is much better than the new ones.
After all the previews shoud give users an idea of the layout and colors, this is not a feature showcase like the press screenshots on the website.

= I'd rather keep the old previews than waiting for new polished ones.

(formally "requesting changes" so we don't merge the current state)

2024-12-22 21:53 UTC, ronso0 requested changes
.

2024-12-22 22:46 UTC, daschuer commented
OK, works for me. I have just issued the version bump PR. https://github.com/mixxxdj/mixxx/pull/14049

2025-04-25 06:01 UTC, daschuer commented
We need to start over if we wish. closing this.

2025-04-25 06:01 UTC, closed without merging