Playlists: add 'Delete all' and 'Delet all unlocked' menu actions
mixxxdj/mixxx pull request #14091
Opened 2024-12-31 16:19 UTC by ronso0

Another coffee break feature I found in my git stash.

This add two actions to the **Playlists** context menu (sidebar):
* Delete all playlists
* Delete all unlocked playlists

Both need to be confirmed twice.

Will do the same for crates soonish.

2025-01-03 23:13 UTC, daschuer reviewed
The Code Looks good. The workflow can be improved. 

I don't like the two popups in a row. It feels as if we don't take user decisions serious. 

I would also expect to "allways" respect the Lock.

Let's repeat the pattern of single delete: 
* Only delete unlocked playlists with "one" confirmation.
* Add a feature to unlock all playlists. If we add a confirm dialog as well. We have still a double safety net. 

If you are still concerned about unwanted mass delete. We may add a text input where users need to type "y"  for deletion. We may even make it a math challenge "type the result of 4+2"

2025-01-06 09:42 UTC, ronso0 commented
In History we have two dialogs as well to avoid accidenst. IIRC think you proposed the second one to be a 'summary' so it doesn't come across as "we don't take user decisions serious", which works for me.

![image](https://github.com/user-attachments/assets/fae1fcc6-1330-4c59-812e-c6e2e49354f0)
![image](https://github.com/user-attachments/assets/053bbb43-fb87-4bdf-a737-9358bd8804ec)

2025-01-06 09:45 UTC, ronso0 commented
> I would also expect to "allways" respect the Lock.
Add a feature to unlock all playlists.

Hmmyeah, that would work for me.
I'll add the 'Unlock all' action and add a "Also delete locked playlists" checkbox.

2025-01-06 09:52 UTC, ronso0 commented
Otoh, with an 'Unlock all" we can keep "Delete all unlocked playlists" and don't need the "Also delete locked" checkbox.

2025-04-26 08:28 UTC, daschuer commented
This has a conflict.

2025-05-07 05:23 UTC, daschuer requested changes

2025-05-07 14:23 UTC, daschuer reviewed
The fix looks good. You may squash it. Than I can merge after a final test.

2025-05-07 19:34 UTC, daschuer commented
You can squash. 

However I have found another issue. Deleting does not happen when only one Playlist is deleted. 
It does not matter if there are sibling locked playlists or not.

2025-05-08 08:47 UTC, ronso0 commented
Pff, stupid typo.
all..working..now

2025-05-08 08:47 UTC, ronso0 commented
..and sqashed

2025-05-08 22:19 UTC, daschuer approved these changes
Works like a charm now. LGTM

2025-05-08 22:20 UTC, merged

2025-05-08 22:22 UTC, ronso0 commented
Cool. Thanks for taking the time to test it!