Mixxx 2.1 updates for DJ console 4-Mx
mixxxdj/mixxx pull request #1419
Opened 2017-12-16 17:13 UTC by JosepMaJAZ

2.1 effect racks
2.1 softTakeover fix for setParameter.
xml mapping fixes
sampler mapping fixes
single jog mode hack

2017-12-16 18:09 UTC, Be-ing commented
Thanks for submitting this. I won't take a detailed look until after 2.1 beta is released, but at first glance I see a lot of legacy code for 2.0. Mixxx 2.0 was already released with a mapping for this controller and this PR will be modifying it for 2.1, so I don't think there's any need to maintain backwards compatibility with 2.0.

2017-12-23 18:56 UTC, Be-ing commented
I will get to reviewing this soon, but for now I will be taking a break from development and code review for a few days.

2018-03-26 01:48 UTC, Be-ing requested changes
Thank you for updating this and sorry for the delay reviewing it. I noted just a few minor nitpicks in the code. Could you remove the legacy code for 2.0? I don't think there's any point keeping it in 2.1.

2018-03-26 01:48 UTC, Be-ing commented on res/controllers/Hercules-DJ-Console-4-Mx-scripts.js
> +    'useSingleJogWeelHack': false
typo: useSingleJogW**h**eelHack

2018-03-26 01:48 UTC, Be-ing commented on res/controllers/Hercules-DJ-Console-4-Mx-scripts.js
> +    Hercules4Mx.noActionButtonMap.buttonPressAction=Hercules4Mx.FxActionNoOp;
spaces around `=` operator

2018-03-26 01:48 UTC, Be-ing commented
Also, can you rebase this on the 2.1 branch?

2018-03-27 19:17 UTC, JosepMaJAZ commented
Glups.... I believe I made a mistake with the rebase... Can you simply get the latest changes and commit them as they should?

2018-03-28 22:04 UTC, Be-ing commented
I rebased this branch and directly pushed it to 2.1. Thank you @JosepMaJAZ.

2018-03-28 22:04 UTC, closed without merging

2018-03-28 22:06 UTC, Be-ing commented
Could you checkout the 2.1 branch and confirm that I didn't mess anything up with the rebasing?

2018-03-29 10:11 UTC, JosepMaJAZ commented
I can confirm that the files have the expected changes.