Kontrol s4 mappings LED updates and autoslip mode
mixxxdj/mixxx pull request #1653
Opened 2018-04-29 22:24 UTC by fayaaz

Summary:

- Auto Slip Mode added:
  - Press Shift + Flux
  - Remix LED lights up
  - Jog wheel scratches will start slip mode on wheel press and exit on touch up
  - Entering a loop will start slip mode, on loop exit slip mode also exits
  - Hotcues on touchdown will start slip mode, on touchup exit

- LED colours slightly changed to match LateNight
- Minor code changes

2018-05-12 18:08 UTC, Be-ing requested changes
The UX changes seem fine. Please document them on the [wiki page](https://mixxx.org/wiki/doku.php/native_instruments_traktor_kontrol_s4_mk2). I have made some comments below to help make the code easier to read.

The slip auto mode [should be handled in Mixxx instead](https://bugs.launchpad.net/mixxx/+bug/1475303). It is okay to have it implemented in this mapping for now to work around that, but it should be easy to map with any controller. Would you be interested in working on that?

Have you made any progress figuring out why this mapping is not working on Windows?

2018-05-12 18:08 UTC, Be-ing commented on res/controllers/Traktor-Kontrol-S4-MK2-hid-scripts.js
> +        engine.setValue(field.group, "rateRange", range_value);
The variable names in this function are confusing like the `TraktorS4Mk2.slipHandler` function above.

2018-05-13 21:49 UTC, daschuer commented
Can we move this to 2.1.x and release 2.1.1 this week?

2018-05-13 23:15 UTC, Be-ing commented
This is already assigned to the 2.1.1 milestone.

2018-05-14 06:02 UTC, daschuer commented
This is not ready. I like to shift it to the next point release.

2018-06-11 21:55 UTC, Be-ing commented
ping @fayaaz, could you take care of the review comments above?

2019-11-12 07:28 UTC, Holzhaus commented
Ping @fayaaz

2020-11-17 03:53 UTC, closed without merging