Lib redesign skin fixes
mixxxdj/mixxx pull request #1671
Opened 2018-05-19 13:02 UTC by ronso0

Tango: fix minor issues

Deere: move Lib maximize toggle above WButtonbar, push it next to Searchbox if sidebar gets to small/is collapsed

LateNight:
- fix buttonbar appearance
- remove feature label in sidebar
- fix feature buttons, feature backgrounds & AutoDJ spinbox
- add translucent scrollbar handles
- redesign toolbar divider to differ from splitter handle

Please test!
Do inactive Library buttons look okay? (for example Purge, Unhide buttons when no track is selected)

2018-05-19 16:04 UTC, Be-ing commented
screenshots?

2018-05-19 16:31 UTC, ronso0 commented
screens added

2018-05-19 22:21 UTC, Be-ing requested changes
The text above the control pane in LateNight is cut off for me with Qt5 and a scale factor of 2.5.
![screenshot from 2018-05-19 17-08-58](https://user-images.githubusercontent.com/9455094/40273618-dc5c2920-5b88-11e8-8b45-ba43cba680ee.png)

Interestingly the feature name text above the track table does not show at all in Tango:
![screenshot from 2018-05-19 17-18-01](https://user-images.githubusercontent.com/9455094/40273621-f608ef52-5b88-11e8-874d-6966b78577f6.png)
While we have only one feature showing, I think this is preferable. If you could make the other skins do this, that would be nice.

Aside from that I noticed some minor code quality nitpicks.

2018-05-20 18:55 UTC, ronso0 commented on res/skins/Deere/library.xml
> +              <Template src="skin:library_sidebar_tester.xml"/>
I can name it `library_sidebar_width_detector.xml`

2018-05-21 00:05 UTC, ronso0 commented on res/skins/Deere/library.xml
> +              <Template src="skin:library_sidebar_tester.xml"/>
or we move the button bar outside the splitter, then this SizeAwareStack can be removed as well

2018-05-21 00:12 UTC, ronso0 commented
> The text above the control pane in LateNight is cut off for me with Qt5 and a scale factor of 2.5.

yep, I used a different hack to hide it. works @100% but scaling doesn't respect all sizes declared in css. Changed it so it works like in Tango now.

> While we have only one feature showing, I think this is preferable. If you could make the other skins do this, that would be nice.

Sure. Also applied some basic fixes in Shade.
@daschuer Do you plan to update the Shade library styling? Apart from the feature icons it looks like qt default.

2018-05-24 11:17 UTC, ronso0 commented
Done.
Please test

2018-06-12 14:39 UTC, Be-ing commented
The jmigual-library-redesign branch has been merged with the latest updates from master. @ronso0 can you fix the merge conflicts with this branch again?

2018-06-13 17:02 UTC, ronso0 commented
I'm about to do so, but it's a bit messy now

2018-06-14 11:40 UTC, ronso0 commented
Though I'm wondering why the Library preview button in LateNight has some kind of minimum width defined: the preview column can be resized but the button itself occupies 65px anyway, so the icon is shifted and only partially visible if the preview column is too small

2018-06-16 11:43 UTC, nopeppermint commented
in latenight if you disable "show text in sidebar icon" it doesn't rescale automatically, you need to change the window size for this..


![latenight](https://user-images.githubusercontent.com/3403218/41498302-4fb4ebf4-716a-11e8-8d04-6d7fcb069be3.png)

the bpm "locked" is somehow broken:

![bpm](https://user-images.githubusercontent.com/3403218/41498328-e0b144a4-716a-11e8-962f-23a64d6a47c6.png)

2018-06-16 11:44 UTC, nopeppermint commented
Shade Autodj Fade time is almost invisible
![shade](https://user-images.githubusercontent.com/3403218/41498340-614326a0-716b-11e8-8a9b-bbb7d545c54b.png)

2018-06-16 11:51 UTC, nopeppermint commented
library styling for latenight is somehow broken:
![latenight_hover](https://user-images.githubusercontent.com/3403218/41498354-bef8fc70-716b-11e8-9a10-ca432411859f.png) compared to 2.1
![latenight_2 1](https://user-images.githubusercontent.com/3403218/41498368-1faa938a-716c-11e8-9e4b-f18513e45493.png)

- hover for preview button is extended over his colon and the played checkbox locks better in 2.1

2018-06-16 12:00 UTC, nopeppermint commented
Deere preview button is broken
![deere](https://user-images.githubusercontent.com/3403218/41498409-56d32894-716d-11e8-85a4-1c84b30fe26c.png)

2018-06-17 15:55 UTC, ronso0 commented
> Deere preview button is broken

Strange, didn't touch it. Fixed.

> I'm wondering why the Library preview button in LateNight has some kind of minimum width

Got it! It was a leftover/merge conflict:
```
WBaseLibrary QPushButton {
  min-width: 65px;
  min-height: 22px;
  max-height: 22px;
```

> in latenight if you disable "show text in sidebar icon" it doesn't rescale automatically

Can't confirm, behaves basicallly the same in all skins.
Though I can't test with most recent lib-redesign branch because I messd up my qt souces somehow..

> Shade Autodj Fade time is almost invisible

Those special library features are still unstyled as I was waiting for some feedback from @daschuer 
So it's the OS them issue again. I'll take care of that and the feature buttons soonish

2018-06-19 11:39 UTC, ronso0 commented
Now Shade library is styled as well.
Please test

2018-06-19 20:15 UTC, nopeppermint commented
it seems that there are now "Conflicting files"

2018-06-19 20:31 UTC, nopeppermint commented
latenight:
fixed:
- played checkbox

still open:
- hover for preview button is extended over his column

And I got a crash while I was trying to load a random track to autodj

```
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Warning [Main]: Could not load random track.
Segmentation fault
```
as Autodj source I had an empty crate, but I was not able to reproduce this crash..

2018-06-19 20:36 UTC, nopeppermint commented
fixed:
- Deere preview button

> Though I can't test with most recent lib-redesign branch because I messd up my qt souces somehow..

I just compiled your branch, or should I compile the lib-redesign branch and copy only the skin folder from your branch?

2018-06-20 09:21 UTC, ronso0 commented
> it seems that there are now "Conflicting files"

Fixed..again. @Be-ing @daschuer Please review and merge this so I don't need to fix the merge conflicts again. Any further issues can be fixed in a follow-up PR

2018-06-20 09:22 UTC, ronso0 commented
> And I got a crash while I was trying to load a random track to autodj

Not related to this PR as it changes skin files only.
Please post those issues to lib-redesign branch or to respective zulip chat.

2018-06-20 10:28 UTC, ronso0 commented
@nopeppermint 
Due to the conflicts I just rebased to jmigual-lib-redesign, so it shouldn't make any difference.

2018-06-20 22:07 UTC, nopeppermint commented
@ronso0  nice ! 
there might be more minor fix but in general it looks good on all skins under Linux Mint x64

one thing I see compared with branch 2.1, the title of the currently selected widget (library, autodj... ) needs a lot of vertical space.

![compare_2 1_2 2](https://user-images.githubusercontent.com/3403218/41686540-bbaf6f28-74e4-11e8-803a-69698b31cde2.png)

I think one's the suggested layout in https://github.com/mixxxdj/mixxx/pull/1117#issuecomment-333279581  is implemented, we need less space as well

> Single library after first start: search box next to bread crumbs (goes below if table width gets too small to show both side by side))

2018-06-23 13:36 UTC, Be-ing commented
There are still some small issues, but those can be fixed later. This branch has enough improvements to be merged now. Thanks @ronso0, and thanks @nopeppermint for review.

2018-06-23 13:36 UTC, merged

2018-06-23 13:45 UTC, Be-ing commented
Minor issues in Tango:
  * The cover art toggle icon feels out of place and IMO wastes space. Couldn't it be moved to the skin settings menu?
  * Although I can use the splitter between the control pane and track table, I don't see it so it would be difficult to discover if I was not looking for it.

2018-06-24 13:01 UTC, ronso0 commented
> The cover art toggle icon feels out of place and IMO wastes space

yeah, this can be removed. I notice I don't use it at all anymore. It was intended as a quick toggle instead of going to the View menu, so IMO it doesn't make sense to have it in Skin Settings.

The splitter graphic shows up when I load now-merged & updated Tango from lib-redesign branch. There were issues after rebasing but it should be fine now.

2018-06-24 13:18 UTC, ronso0 commented
follow-up is #1723