add quantize dependency to tooltips of sync_enable and beatsync
mixxxdj/mixxx pull request #1697
Opened 2018-06-01 08:52 UTC by daschuer

This is a follow up PR to https://github.com/mixxxdj/mixxx/pull/1679 for not breaking string freeze in the 2.1 branch

2018-06-24 20:08 UTC, Be-ing requested changes

2018-06-24 20:08 UTC, Be-ing commented on src/controllers/controlpickermenu.cpp
> +                             tr("Tap to sync (tempo and phase depending on quantize), hold to enable permanent sync"), syncMenu);
"Tap to sync tempo (and phase with quantize enabled)" is a bit clearer

2018-06-24 20:08 UTC, Be-ing commented on src/controllers/controlpickermenu.cpp
> +                             tr("One-time beat sync (tempo and phase depending on quantize)"), syncMenu);
"One-time beat sync tempo (and phase with quantize enabled)"

2018-06-27 23:08 UTC, daschuer commented
Done.

2018-07-06 14:54 UTC, daschuer commented
Merge?

2018-07-06 14:56 UTC, Be-ing commented
Should this go to 2.2 or master?

2018-07-06 14:58 UTC, daschuer commented
To master, because it needs to be translated.

2018-07-06 15:02 UTC, Be-ing commented
Okay

2018-07-06 15:02 UTC, merged