Added mix mode button to Shade
mixxxdj/mixxx pull request #1702
Opened 2018-06-03 22:39 UTC by daschuer

![bildschirmfoto vom 2018-06-04 00 38 14](https://user-images.githubusercontent.com/1777442/40891947-aa2957ee-678f-11e8-8009-5629033f9d10.png)
left "Add Wet to Dry" right "Dry Wet Crossover"

2018-06-04 00:59 UTC, Be-ing requested changes
Interesting idea with the graphics. However, the crossing lines for D/W mode look like the letter "X" to me, which suggests that something is being blocked or disabled.

2018-06-04 00:59 UTC, Be-ing commented on res/skins/Shade/deck_effect.xml
> +			    <TooltipId></TooltipId>
EffectUnit_mix_mode

2018-06-07 17:48 UTC, daschuer commented
OK, tooltips are in place. 
I have played a bit with the X, but everything melds into noise when lowering the size. 
I am actually pleased with the current bitmap. Even when someone thinks there is something disables, he may click on it and understands the hopefully the intention. Dry signal is blocked ...

2018-06-07 19:59 UTC, Be-ing commented
This branch now has unrelated commits. Please rebase it on master.

2018-06-07 20:01 UTC, Be-ing commented
> when someone thinks there is something disables, he may click on it and understands the hopefully the intention. Dry signal is blocked ...

I don't understand what you mean by blocking the dry signal. Could you explain?

2018-06-07 20:34 UTC, daschuer commented
Nothing important. In case you turn fully right, dry signal is blocked. 
Rebased.

2018-06-07 20:38 UTC, Be-ing commented
I have an idea for a graphic to represent D/W mode: a simple horizontal bar with gradient between different colors on each end. What do you think?

2018-06-07 20:42 UTC, daschuer commented
How will the D+W mode look than? If we do a gradient the same way, it will be hard to see the difference.
D+W will just be darker on the right, because of more dry signal.

2018-06-07 20:46 UTC, ronso0 commented
I think the initial icons are okay, but not knowing what they are about I'd think they are descriptive graphics for the knob above but not buttons.
the crossing lines are 
would they still fit in there when they have a border, after moving the knobs & labels a few pixels up?

2018-06-07 20:47 UTC, ronso0 commented
I would introduce gradients in Shade. If you think the liens aren't clear enough flat triangles could work IMO

2018-06-07 21:04 UTC, daschuer commented
Yes we can add a border. Currently the match with the invert and metknob linking buttons, which have also no border: I think both should look similar: 
![bildschirmfoto vom 2018-06-07 22-54-02](https://user-images.githubusercontent.com/1777442/41125826-e91cbcfc-6aa5-11e8-97c4-9eb098f7f207.png)

2018-06-07 21:04 UTC, daschuer commented
![d w](https://user-images.githubusercontent.com/1777442/41126209-19698fba-6aa7-11e8-8744-43e3079dfbb9.png)
![bildschirmfoto vom 2018-06-07 22-54-02](https://user-images.githubusercontent.com/1777442/41126239-29d722ea-6aa7-11e8-8bbf-ac9c89469378.png)

2018-06-07 21:05 UTC, daschuer commented
The border less version looks more elegant though.

2018-06-07 21:14 UTC, Be-ing commented
> How will the D+W mode look than? If we do a gradient the same way, it will be hard to see the difference.
D+W will just be darker on the right, because of more dry signal.

Almost the same as the current D+W icon, but I think it would help if the horizontal bar representing the dry signal was the same height as the maximum height of the triangle representing the wet signal.

2018-06-07 21:15 UTC, Be-ing commented
@ronso0 I think a gradient is a good symbolic representation of crossfading between two signals.

2018-06-07 21:19 UTC, Be-ing commented
> flat triangles could work

A symbol like `><` implies there is nothing in the middle. A symbol like `<>` implies there is nothing at the sides. What may work would be a long rectangle with the diagonal dividing two colors on top and bottom.

2018-06-07 21:29 UTC, daschuer commented
It e put the dry signal on the top, both graphics follow the view of the crossfader curve in preferences. 
That should work IMHO.

2018-06-07 21:46 UTC, Be-ing commented
What do you think of my sketch for the D/W icon?

2018-06-07 22:07 UTC, daschuer commented
![image](https://user-images.githubusercontent.com/1777442/41128794-9483aa20-6aaf-11e8-89a4-4889efc603af.png)
![image](https://user-images.githubusercontent.com/1777442/41128862-e6484686-6aaf-11e8-9fe4-a58ccadacd5d.png)

2018-06-07 22:08 UTC, daschuer commented
> What do you think of my sketch for the D/W icon?

The D+W icon does not work that way.

2018-06-07 22:19 UTC, Be-ing commented
Right, I was suggesting that sketch for the D/W icon, not D+W.

2018-06-07 22:35 UTC, Be-ing commented
No, the crossed lines do not convey what the D/W mode does.

2018-06-07 22:42 UTC, daschuer commented
On the right you have more wet and less dry. In the middle you have the same level for both. It works for me in the same way the fader curve visualization works. So it is at least now wrong. If you switch the buttons, you van now also see that the dry signal is increased on the right end. Exactly that happens with the sound.

2018-06-07 22:52 UTC, Be-ing commented
I think the crossed lines for D/W look too much like an icon indicating that something is disabled or an error to convey what it does.

2018-06-08 06:08 UTC, daschuer commented
I think it is finally a matter of taste.
It works for me quite good and as I understand it also for Ronso0. We have no better alternative yet. Feel free to propose alternatives for the other skins. 

If space is sufficient, the D/W|D+W seems to ba a good alternative.

2018-06-08 11:10 UTC, Be-ing commented
You still have not responded to my [proposal for D/W](https://github.com/mixxxdj/mixxx/pull/1702#issuecomment-395570216).

2018-06-08 13:55 UTC, daschuer commented
How will D+W look compatef to you proposal? We need to consider both at once.

2018-06-08 14:33 UTC, Be-ing commented
You have already asked and I [already answered](https://github.com/mixxxdj/mixxx/pull/1702#issuecomment-395567340).

2018-06-08 15:28 UTC, daschuer commented
This was you answer to the gradent D/W button. This old idea does IMHO not match your new design.

2018-06-11 20:57 UTC, Be-ing commented
> This old idea does IMHO not match your new design.

I don't know what you mean. What doesn't match what?

I have realized there is a UX problem with only using an icon to identify the states of this switch. How can we teach users the names of the different states? If we refer to "D/W" and "D+W" in the tooltip but the icons are just abstract graphical representations of the concepts, users won't know what the tooltip is talking about. Any ideas to overcome this?

2018-06-11 21:18 UTC, daschuer commented
> I don't know what you mean. What doesn't match what?

You have not yet proposed two matching buttons. My latest proposal can be read the same way for both buttons and has a nice animation when changing the state. 

I have no issue with this: X id probably the best association for "Crossfade" that we can use. See:
![image](https://user-images.githubusercontent.com/1777442/41128794-9483aa20-6aaf-11e8-89a4-4889efc603af.png) D/W mode: Mix knob crossfades between dry and wet

![image](https://user-images.githubusercontent.com/1777442/41128862-e6484686-6aaf-11e8-9fe4-a58ccadacd5d.png) D+W mode: Mix knob adds wet to dry. Use this to change only the effected (wet) signal with EQ and filter effects.

2018-06-11 21:25 UTC, Be-ing commented
I described my [idea for the D+W icon](https://github.com/mixxxdj/mixxx/pull/1702#issuecomment-395567340) above. The original icon in the first commit was better than the current one IMO. The current one should at least be reflected horizontally so the wider side of the triangle is on the right. I think it looks a little odd to put the triangle below the straight line, but whether it's above or below doesn't really change the meaning.

I don't think I've ever seen an "X" icon in a GUI mean anything other than "error" or "close". I think it's a good symbol for crossfading.

2018-06-11 21:54 UTC, daschuer commented
> I described my idea for the D+W icon above.

I have already stated that I think this old idea does not match your new design. Please propose a mock-up for both buttons.

2018-06-13 14:37 UTC, ronso0 commented
Again, I think the both icons do work as intended.
The only remark I have: because the icon is so tiny there's an illusion that makes the flat X look a bit like this (exaggerated)
![ex_1](https://user-images.githubusercontent.com/5934199/41357900-797baabc-6f27-11e8-9133-1a7241376ca9.png)
Try to add a short vertical section in the source svg where those two lines cross to make it look as intended (a bit like those tricks used when creating fonts/letters):
![ex_2](https://user-images.githubusercontent.com/5934199/41358022-c5f64bcc-6f27-11e8-979a-017969b4462c.png)

2018-06-13 14:38 UTC, ronso0 commented
I think I'll use similiar icons for Tango. They are more compact than text labels.

2018-06-13 14:43 UTC, Be-ing commented
Please do not use anything that looks like an X to signify something that is not an error or problem.

2018-07-02 20:40 UTC, Be-ing commented
Ping. Thoughts about the above proposal?

2018-07-02 22:29 UTC, ronso0 commented
>  Thoughts about the above proposal?

The space below the Mix knob is like 7x24 px. I don't see how icons you proposed should fit..

2018-07-06 14:07 UTC, daschuer commented
![bildschirmfoto vom 2018-07-06 16 05 20](https://user-images.githubusercontent.com/1777442/42383125-9ef0449e-8136-11e8-9060-deecedfc19ed.png)

ready

2018-07-06 14:42 UTC, Be-ing commented
This still looks like an "X"...

2018-07-06 14:49 UTC, daschuer commented
But you see the waveform, right? We simply have no better proposal jet, so can't we just merge it and wait if we get real user complains about the X.

2018-07-06 15:11 UTC, Be-ing commented
I don't understand what the waveform has to do with this. These icons are meaningless in the context of the tooltip too. No one will look at these icons and know that they correspond to states called "D+W" and "D/W". Can we simply use the "D+W" and "D/W" text for now?

2018-07-06 15:40 UTC, Be-ing commented
Can't you put a border around the button to show it is a button instead of just a text label?

2018-07-06 15:45 UTC, daschuer commented
I have actually tried first to use an original shade button. But it is too big. These bars are already established as buttons. So we can just reuse the routing linking from knobs. But the current solution works for me much better. I can see here the mixing behaviour. By the way much better that only see a + vs / but it is a matter of taste. (like the whole skin by the way)

2018-07-10 19:59 UTC, daschuer commented
Done! Thank you for the buttons.

2018-08-02 14:27 UTC, Be-ing commented
Following discussion in #1748 to adopt these designs and change the mix mode tooltip, I think this is okay to merge. The mix mode icons somehow still look blurry even though they are SVGs, but that's also the case for the whole skin so I don't think that should hold up merging this PR.

2018-08-02 14:28 UTC, merged