Support IRC, AIM, ICQ in shoutcast broadcasts
mixxxdj/mixxx pull request #1731
Opened 2018-06-29 16:12 UTC by qiubit

https://bugs.launchpad.net/mixxx/+bug/724225

2018-06-29 17:13 UTC, qiubit commented
https://travis-ci.org/mixxxdj/mixxx/jobs/398317936 failed due to not recent enough version of libshout. Anything I can do about it? I suppose doing something like apt-get update && apt-get upgrade on worker could fix it (Mac build works).

2018-06-29 20:53 UTC, uklotzde commented
Please use version guards to ensure backwards compatibility, e.g. like we do for for TagLib, FFmpeg, .... The targeted Ubuntu LTS release often contains outdated library versions that we still need to support.

Upgrading shared libraries only on the build server is useless. Please consider the consequences when finally distributing this piece of software.

2018-06-29 22:52 UTC, qiubit commented
Hm, OK I'll research those version guards, never seen that technique earlier, so I don't even know what it is.

Out of curiosity (sorry if the quesion is stupid, I've never dealt with distribution issues) - isn't it the case that in "distributed" versions of Mixxx libraries are linked statically, so outdated shared libraries aren't an issue? For example, when examining Serato on MacOS with `otool -L` it seems that all "non-OS" libraries are contained in bundle (like Qt, libpulse, libusb, ...) that is installed with the application. Isn't it the case also for Mixxx?

2018-06-29 22:54 UTC, daschuer requested changes
Thank you for your fist PR. To merge it, we need your permission. Please sign:
https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done.


This is a relative minimal change. It would be find for me to slip in 2.2 freeze is scheduled tomorrow, right?

2018-06-29 22:54 UTC, daschuer commented on src/preferences/broadcastprofile.cpp
> +    m_streamIRC = QString(value);
The construct is redundant here.

2018-06-29 22:54 UTC, daschuer commented on src/preferences/broadcastprofile.cpp
> +    m_streamIRC = QString();
Use clear() to avoid construction of a new QString object.

2018-06-29 22:54 UTC, daschuer commented on src/preferences/broadcastprofile.cpp
> +    m_streamIRC = QString(value);
Change other places as well.

2018-06-30 06:33 UTC, daschuer requested changes
I have added ideas for a version guard. 

Can you also add a screenshot of the preferences?

2018-06-30 06:33 UTC, daschuer commented on src/engine/sidechain/shoutconnection.cpp
> +    if (shout_set_meta(m_pShout, SHOUT_META_IRC, baStreamIRC.constData()) != SHOUTERR_SUCCESS) {
#ifdef SHOUT_META_IRC

2018-06-30 06:33 UTC, daschuer commented on src/engine/sidechain/shoutconnection.cpp
> +    if (shout_set_meta(m_pShout, SHOUT_META_AIM, baStreamAIM.constData()) != SHOUTERR_SUCCESS) {
#ifdef SHOUT_META_AIM

2018-06-30 06:33 UTC, daschuer commented on src/engine/sidechain/shoutconnection.cpp
> +    if (shout_set_meta(m_pShout, SHOUT_META_ICQ, baStreamICQ.constData()) != SHOUTERR_SUCCESS) {
#ifdef SHOUT_META_ICQ

2018-06-30 06:33 UTC, daschuer commented on src/preferences/dialog/dlgprefbroadcast.cpp
> +    stream_IRC->setText(profile->getStreamIRC());
#ifndef SHOUT_META_IRC 
   stream_IRC->setVisible(false);

2018-06-30 06:33 UTC, daschuer commented on src/preferences/dialog/dlgprefbroadcast.cpp
> +    stream_IRC->setText(profile->getStreamIRC());
the same below.

2018-06-30 20:51 UTC, qiubit commented
Added version guard.

Here are some screenshots:

Version guard on
![mixxx-guard-on](https://i.imgur.com/oA71XY6.png)

Version guard off
![mixxx-guard-off](https://i.imgur.com/Wpo8s7V.png)

Headers emitted by icecast stream with settings above
![mixxx-shoutcast-headers](https://i.imgur.com/eI8ymXX.png)

2018-07-01 04:40 UTC, daschuer commented
LGTM, Thank you very much!
I think the Matadata group box should be aligned at the top. I will do this after merge.

2018-07-01 04:40 UTC, merged