Library-layout fix GUI lag
mixxxdj/mixxx pull request #1740
Opened 2018-07-05 18:34 UTC by jmigual

Fix bug re-introduced in #1714 

However there's a problem when adding tracks as the signal `tracksAdded(QSet<TrackId>)` from `TrackDAO` does not provide all the ids for the new added tracks and only a small subsample. 

Does anyone have an idea of why this may happen? Am I using the proper signal to see if new tracks have been added?

2018-07-06 06:40 UTC, jmigual commented
The build fails because it does not find the method `intersects` from `QSet`. Which version of Qt 5 are we using for POSIX builds? Qt 5.6 already has this method in its documentation.

2018-07-06 16:52 UTC, Be-ing commented
> The build fails because it does not find the method intersects from QSet. Which version of Qt 5 are we using for POSIX builds? Qt 5.6 already has this method in its documentation.

It looks like Travis is using an ancient version of Ubuntu stuck on Qt 5.2. Edit .travis.yml to update it. 

Travis' macOS builds are using Qt 5.11. I am not sure why those are failing, but it is not related to this PR. I attempted to fix that in #1722.

2018-07-06 17:13 UTC, Be-ing requested changes
Thank you for continuing to work on this.

Please move all SQL code into a separate class. There should be *zero* SQL in GUI classes. Refer to #1304 for an example.

> However there's a problem when adding tracks as the signal tracksAdded(QSet<TrackId>) from TrackDAO does not provide all the ids for the new added tracks and only a small subsample.

I can confirm that adding tracks to the tree is not working. I tried rescanning my library to add new tracks. While they appeared in the track table, they did not appear in the tree.

2018-07-06 22:09 UTC, Be-ing commented
> Ubuntu Trusty, supported until April 2019 has Qt5.2.

Supported by Canonical, which is a company that pays people to continue to backport critical fixes to old packages. Applications have zero obligation to ensure their new versions work on old operating systems. Qt 5.2 was released in December 2013. Following the logic that new versions of Mixxx must support the oldest OS supported by Canonical, Mixxx cannot use new Qt features until 6 years after they have been released! I find that ridiculous. We should be thinking about Qt6 at this point.

2018-07-06 22:38 UTC, Be-ing commented
From [Ubuntu's LTS policy](https://wiki.ubuntu.com/LTS):
> we define the LTS to be: 
Enterprise Focused: We are targeting server and multiple desktop installations, where the average user is moderately risk averse.
...
clearly state that it is not:
A Feature-Based Release: We will focus on hardening functionality of existing features, versus introducing new ones
Cutting Edge

This is the opposite of new Mixxx releases, which are focused on providing new features for use on personal laptops.

2018-07-07 06:48 UTC, daschuer commented
In the history of Mixxx we have always supported all supported Ubuntu version if possible with reasonable effort.
Here we are talking about just a few lines wrapping code, no reason to break Xenial for this, which is still the most used distribution.
I agree, that we can breake this strategy for really hard to solve issues.

2018-07-07 08:30 UTC, jmigual commented on src/library/treeitem.cpp
> +TreeItem*TreeItem::insertChild(int row, const QString& label, const QVariant& data) {
I am amazed that this does compile in fact. I will check it again and "fix" it just to avoid possible problems.

2018-07-07 08:36 UTC, jmigual commented
> Please move all SQL code into a separate class. There should be zero SQL in GUI classes. Refer to #1304 for an example.

Ok, I will move the code as soon as I can work on it again (until August)

Regarding the Qt issue I think that we should discuss it in the mailing list or Zulip and decide in a Qt version for the next release. 
Can't we just deploy a different Qt version in Ubuntu with our binaries?

2018-07-07 08:36 UTC, jmigual commented on src/library/treeitem.h
> -        count = getTrackCount();
Oh sorry I won't do it again

2018-07-07 13:58 UTC, daschuer commented
> Can't we just deploy a different Qt version in Ubuntu with our binaries?

This might be get ripped off by the package maintainer. Here It is IMHO straight forward to backport the Qt 5.6 function. No need to ditch Xenial compatibility here.

2018-07-07 15:14 UTC, Be-ing commented
Zulip discussion: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/minimum.20requirements.20policy

> In the history of Mixxx we have always supported all supported Ubuntu version if possible with reasonable effort.

And here we are publishing our first Qt5 release as upstream is starting to plan for Qt6.

> Ok, I will move the code as soon as I can work on it again (until August)

Okay thank you. I recognize that will take a lot of work. It doesn't necessarily have to be done in this pull request. We'll never get database transactions out of the GUI thread or move to QML with such tight coupling of GUI classes and SQL code.

>  Can't we just deploy a different Qt version in Ubuntu with our binaries?

Statically linking a small library may be reasonable, but Qt is huge.

2018-07-09 18:40 UTC, uklotzde commented
Did you know that LibraryScanner hosts its own instance of TrackDAO in a separate thread? It forwards added tracks one by one to the main TrackDAO via databaseTrackAdded(). Unfortunately these tracks do not result in any tracksAdded() signal from the main TrackDAO, as far as I understand.

2018-08-31 17:01 UTC, nikmartin commented
FYI, because of this PR I built https://github.com/nikmartin/mixxxLibraryBuilder to build a large library of very small tagged, valid mp3 files to test this branch with. A 1,000,000 mp3 library is only .5gb

2021-04-02 13:10 UTC, Holzhaus commented
The minimum requirements issue should have fixed itself by now. This this PR still relevant or should we close this?

2021-04-02 19:57 UTC, ronso0 commented
The target branch is stale and unmergable IIRC due to major perfomrmance issues.
Can be closed IMO.

2021-04-02 19:57 UTC, ronso0 commented
The target branch is stale and unmergable IIRC due to major perfomrmance issues.
Can be closed IMO.

2021-04-02 19:58 UTC, closed without merging