Behringer CMD-MM1 Rework
mixxxdj/mixxx pull request #1744
Opened 2018-07-07 12:34 UTC by Swiftb0y

I rewrote the entire Mapping for better maintainability, readability and performance (marginally).
I removed some features which I turned out to be useless in the old mapping, but it is mostly the same.
It still features the customizability from the old mapping, eg you can still toggle between deck- and fx-channels, different knob assignments, deck sequence and fader assignment (volume/rate/super1).
Some of the core methods of the components framework got overwritten to support the multiple layers the original mapping had as well.
Furthermore, some components have almost no / duplicate functionality (like the middlebutton, the encoderbutton, and layer2 of the 1&2-buttons (similar to layer2 of the fxchannels)). Suggestions would be very appreciated.

2018-08-02 13:57 UTC, Be-ing commented
Thank you for working on this and sorry for the long time with no response. I'll review this next week (I'll be travelling this weekend). Feel free to leave a comment to remind me if I haven't gotten to it.

2018-08-20 17:37 UTC, Swiftb0y commented
@Be-ing 
just reminding you about this PR ;)

2018-08-30 05:52 UTC, Be-ing commented
FYI, I haven't forgotten about this, but I'm focusing on getting the build environments and build servers working for 2.2 beta.

2018-09-07 02:03 UTC, Be-ing commented
Thanks for putting in so much work just to clean up the code. :) This looks better organized at first glance. The way you set up rotating through layers is interesting. I'm wondering if you could use more descriptive names than just integers for the layers. Also, it would be helpful to use more descriptive names than "buttonINT" for the Components. I'll take a more thorough look tomorrow.

2018-09-07 11:07 UTC, Swiftb0y commented
I have thought about about using normal/shift/ctrl/shiftctrl as layer names but just numbering seamed easier. (It also enables me to easily call the method. ([L36](https://github.com/mixxxdj/mixxx/blob/37ab3e42f97bea8abde120bf6038ada7b3592d17/res/controllers/Behringer-CMD-MM1-scripts.js#L36))). The ButtonINT convention might not seem intuitive until you look at the [controller](https://static.bax-shop.de/image/product/39584/78802/3f67f493/Behringer_CMD-MM-1-front.jpg). The "naming convention" I went for was actually buttonLABEL. So buttonCue, button1, button2, make sense. I'll add a comment about that in the code.

2018-10-08 00:06 UTC, Be-ing requested changes
Sorry again for the delay reviewing this. Overall this looks quite good. I was able to understand the code pretty clearly. The biggest thing I am still unclear about is how the numbered layers correspond to the different buttons. If I understand correctly:
1: default
2: shift
3: ctrl
4: shift + ctrl
Is that right?

2018-10-08 18:59 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
The issue might have come from the typo of `length`, I'll to try to test if that resolves the issue in the next couple of days.

2018-10-08 19:25 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +    mask: 1 << 0,
for the sake of consistency...

2018-10-08 19:35 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +      this.inKey="mix_mode";
No it isn't. But I have to update it anyway in the near future (eg. switching from 3D renderings to vectorgraphics for easier editing).

2018-10-08 19:37 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +      // this.speed is controlled by the libraryButton
No. This is an artifact of a previous design choice. I'll update the comment.

2018-10-08 19:59 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +        if (value>42&&value<=84) {
I designed the mapping to extend the missing functionality of the Launchpad and one of the features I really missed were a fader to quickly change the tempo (which is difficult when you are only able to control the rate by button presses). This is sort of a hack and doesn't make much sense but I use it quite often so I think it deserves to stay.

2018-10-09 14:36 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
It didn't resolve the Issue. I wrote to their technical support. They usually take some time to respond but they were able to help me in a similar inquiry before.

2018-10-09 15:14 UTC, Swiftb0y commented
> 1: default
2: shift
3: ctrl
4: shift + ctrl
Is that right?

Yes, exactly.
Btw. Should I worry about that CodeFactor issue?  I most of the warnings only come from the fact that I used the whole function signature (even though I didn't use most of the arguments) for consistency's sake.

2018-10-09 17:41 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +        this.output(theDeck.binaryChannel&this.mask);
I understand what you are saying but this function is only the input method while the controller is in layer4. The before function in line 49 will set reset the the input method when entering any other layer. So I'm actually outputting the current channel assignment (not the crossfader orientation but the actual Deck/Channel (within mixxx) the controllerChannel is controlling) to the user.

2018-10-09 17:42 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +        if (value>42&&value<=84) {
Exactly.

2018-10-09 17:44 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +    mask: 1 << 0,
Same as above. Its just for consistency.

2018-10-10 22:33 UTC, Be-ing commented
>>    1: default
>>    2: shift
>>    3: ctrl
>>    4: shift + ctrl
>>    Is that right?

> Yes, exactly.

Okay, thanks for clarifying. Please either explain this in a comment or use the button names instead of numbers for the different layers.

2018-10-20 22:39 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +    mask: 1 << 1,
I know but I don't necessarily want to wait for that PR... (especially since it seems kind of abandoned right now)

2018-10-20 22:41 UTC, Be-ing commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +    mask: 1 << 1,
Yeah, I didn't mean to imply this PR should wait for that. Just giving you a heads up that this will be nicer in the future :)

2018-10-20 22:55 UTC, merged

2018-10-20 22:58 UTC, Be-ing commented
Thanks again for your patience with this PR. Now that you've gone through the experience of rewriting a mapping using Components, your input in future discussions about how to improve the controller mapping system would be appreciated!

2018-10-20 23:10 UTC, Swiftb0y commented
Of course. I'd be grateful to help and improve Mixxx where ever I can.

2018-10-23 19:00 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
Update: They said that it is not possible to control the Controller via SysEx. So I guess there is no Midi dump feature as well.

2018-10-23 19:02 UTC, Be-ing commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
That does not imply there is no MIDI dump feature. Hercules controllers use a regular 3 byte MIDI message to request a MIDI dump.

2018-10-23 19:08 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
Well, I asked them more or less explicitly about a MIDI dump feature and their response was:
> Dear Nikolaus, Regarding your inquiry: SysEx on the CMD-MM1.
My apologies for the delayed response. Unfortunately, it is not possible to control the CMD-MM1 via Sysex messages. Thank you for your patience.

So I either they don't want to explicitly state that their is/isn't such a feature, or their just isn't one...

2018-10-23 19:32 UTC, Be-ing commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
That response doesn't necessarily mean there isn't a MIDI dump feature. I imagine the customer support person who answered your email just asked an engineer about sysex messages without describing why.

2018-10-23 19:36 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
Weill, I mentioned the dump feature as an example but you could be right. I could try to fuzz the controller and see if anything happens.

2018-10-23 19:37 UTC, Swiftb0y commented on res/controllers/Behringer-CMD-MM1-scripts.js
> +  // Doesn't return anything. The controller might not be serato certified.
On second thought: They have a utility to change the midi channel of the controller, so there must be a way to configure the controller somehow (either via sysex or regular midi).