Added Clementine Lib Connection
mixxxdj/mixxx pull request #1764
Opened 2018-07-25 13:57 UTC by julled

Added a connection to the clementine player playlists. Is an adaption of the #1738 patch for this branch. 

If the Track of the Clementine Playlist is already in Mixxx trackcollection, the bpm is read from there. That feature is not yet in #1738.

2018-07-25 20:20 UTC, daschuer requested changes
Thank you for the work. 

I have just tested it and it works. It is great to see my Clementine playlists im Mixxx  :-)   

The breadcrumb over the track table is not updated. 
There is also a general issue of all library features that a 
"Show all" knot is missing.

2018-07-25 20:35 UTC, julled commented on src/library/features/clementine/clementinefeature.cpp
> +    return ":/images/library/ic_library_clementine.png";
No, i did not miss it, i tried to make a logo, but wasnt able to get the same style. I hope someone who did the other logos will do it...

2018-07-25 20:36 UTC, julled commented
Pushed some tabs->spaces patch.
When do you think this will go to the master branch?

2018-07-25 20:40 UTC, daschuer commented
After the 2.2 release in September. We can merge this to the library redesign branch whenever it is ready.

2018-07-25 21:03 UTC, daschuer commented
Here it is: 
![ic_library_clementine](https://user-images.githubusercontent.com/1777442/43227328-b3944fda-905e-11e8-9e63-862d95316427.png)

2018-07-25 21:08 UTC, julled commented
Cool thx, will add that and do another bugfix...

2018-07-25 21:23 UTC, julled commented
@daschuer did you try to use that logo? If i try to use it, strangly it doesnt show up. Other logo files work.

2018-07-25 21:33 UTC, julled commented
Nice that was it, thx.

2018-07-25 21:36 UTC, julled commented
I think i am done, thx again for your help and your work on mixxx in general!
I am happy i was able to contribute a feature which i always missed...

2018-07-25 22:06 UTC, julled commented
fixed

2018-07-28 19:09 UTC, daschuer commented
Thank you. We are getting close. Now the breadcrumb works, but it does not show the selected play list like the other external library features. 

Do you have interest to fix the missing "Show all" entry for all external library features? 

After merge, I will put your name into the contributor list into the about box. Is it OK to use your real name there?

2018-07-29 12:06 UTC, julled commented
Yes i could do that, but i am confused about the current implementation about that feature for the other players. If you activate at the specific player-connector the "Show All" is activated, but if you activate a specific playlist in that player-connector, there is no way back to "Show All". The only way to get there is to activate another player-connector and then go back. 
Shouldnt be there a specific eye-catching marked entry in the list window for each player-connector for the "show all"?
In the old UI there was the tree-view which made it easy to differentiate between different lists of the connectors.

2018-07-29 14:58 UTC, daschuer commented
Yes, the current implementation of the external libraries is somehow halve baked.
I think the best way is to add a topmost artificial "show all" playlist.

I think we can merge this if the playlist name I shown. This way it is head up with the others. 

The "show all" feature can become a new pull request.

2018-07-30 10:41 UTC, julled commented
Okey, then i would leave it like it is.

2019-06-20 06:11 UTC, julled commented
Hi, is it still possible that this might go to the master branch? Would be sad if not :(

2019-10-08 00:03 UTC, Holzhaus commented
@daschuer ping

2019-10-17 21:03 UTC, daschuer commented
It is really bad that this has stalled. Unfortunately 2.3 is around the corner and I like to not delay it because of this PR. We can merge it into 2.4.

2019-10-19 11:56 UTC, julled commented
Hurray, thank you :)
Will have 2.4 the lib redesigned?
Do you need some additional work? I dont have a mac to get the Travis mac compilation right.

2020-09-09 20:23 UTC, Holzhaus requested changes
Please pull latest master into this branch, I hope we can finally get this merged.

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementinedbconnection.cpp
> +                entry.duration=int(duration/1000000000);
```suggestion
                entry.duration = static_cast<int>(duration / 1000000000);
```

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementinedbconnection.cpp
> +                entry.artist = "Unknown";
```suggestion
                entry.artist = QStringLiteral("[unknown]");
```

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementinedbconnection.h
> +#define CLEMENTINEDBCONNECTION_H
Use #pragma once instead of oldschool include guards

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementinefeature.cpp
> +    return "ClementineFeature";
Please make this a `const QString kSettingsName` in the anonymous namespace

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementinefeature.h
> +#define CLEMENTINEFEATURE_H
```suggestion
#pragma once
```

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementinefeature.h
> +#endif // CLEMENTINEFEATURE_H
```suggestion
```

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementineplaylistmodel.h
> +
```suggestion
#pragma once

```

2020-09-09 20:23 UTC, Holzhaus commented on src/library/features/clementine/clementineplaylistmodel.h
> +#endif // ClementinePLAYLISTMODEL_H
```suggestion
```

2020-09-10 18:36 UTC, julled commented
> Please pull latest master into this branch, I hope we can finally get this merged.

thx for the suggestions, i will do these changes in the next weeks

2020-09-10 20:17 UTC, uklotzde commented
Unfortunately, this PR has been rebased on the *library redesign* branch according to our request. But that branch is dead. The serious performance issues were unknown back then.

Please rebase your branch again on *master* and then target *master*.

2020-09-10 20:20 UTC, julled commented
Okay, i will try that.

2020-10-13 23:15 UTC, julled commented
I continued the work on this for a PR to master in #3173 .

2020-10-13 23:15 UTC, closed without merging