2.1.2 release PR
mixxxdj/mixxx pull request #1776
Opened 2018-08-11 05:11 UTC by daschuer

These should be the commits towards a release.
Is anything missing?

2018-08-11 14:40 UTC, Be-ing commented
#1768 is missing. If 2.1.2 is released without that, I will not spend any effort supporting users with any resultant bugs in 2.1.2.

2018-08-11 18:13 UTC, Pegasus-RPG commented
@Be-ing That's fine. Daniel and I will worry about any such bugs. @daschuer Have we actually made sure new strings were pushed to Transifex? I.e. have any translations actually been changed since 2.1.0?

2018-08-11 21:28 UTC, daschuer commented
I have only fetched strings from Transiflex. 

You are right, that we also have to push the strings. However this will only have an effect for 2.1.3 if we release this as it is.

2018-08-12 21:12 UTC, uklotzde commented
The change set of this PR looks suspicious. It reverts the recent iTunes import fixes!?

2018-08-13 02:31 UTC, Be-ing requested changes

2018-08-13 02:31 UTC, Be-ing commented on CHANGELOG
> +* Don't allways quantize hot ques, a 2.1.1 regression lp1777429
two typos: "Don't always quantize hotcues"

2018-08-13 02:31 UTC, Be-ing commented on CHANGELOG
> +* store No EQ and Filter persistantly lp1780479
persistently

2018-08-13 17:52 UTC, Pegasus-RPG commented
Every time we do a release of any sort (major, minor, bugfix, beta, alpha) we need to push the strings.

2018-08-16 00:10 UTC, sblaisot commented
You also need to update windows installer translations:
https://github.com/mixxxdj/mixxx/blob/master/build/wix/Localization/README-Translations.md

2018-08-16 21:48 UTC, sblaisot commented
ok, I see there is no new translation for windows installer, so nothing to update.

@daschuer can you add windows installer translation update to the Todo list for the next time please?

2018-08-16 23:26 UTC, daschuer commented
Typos fixed, ready for merge and release?

2018-08-16 23:49 UTC, sblaisot commented
> Do we have a guide how to push and pull installer translations?

You have the link 2 comments above

2018-08-17 16:57 UTC, daschuer commented
@Be-ing can we merge this now?

2018-08-17 17:14 UTC, Be-ing commented
I think it's a bad idea without #1768, but okay.

2018-08-17 20:54 UTC, daschuer commented
Thank you.

2018-08-17 20:54 UTC, merged