Portable install
mixxxdj/mixxx pull request #1780
Opened 2018-08-15 23:37 UTC by sblaisot

This PR add a portable mode to Mixxx (lp:1731689).

If a folder named `settings` is detected next to Mixxx executable, then Mixxx runs in portable mode:
- this folder will be used as settingsPath instead of standard settings folder (as if `--settingsPath ./settings` has been passed to Mixxx)
- No attempt will be made to migrate old settings from standard folders to avoid any interaction outside Mixxx directory

This way, settings works exactly the same way as resources, using folder next to executable if found.

I also added a `makeportable` target to scons producing a portable archive using 7-zip and configured appveyor to produce portable archives and store them as artifact.

2018-08-16 00:07 UTC, sblaisot commented
I should probably add CHANGELOG, README and LICENCE in the archive. Will add that tomorrow.

2018-08-16 06:34 UTC, daschuer commented
Nice Idea. I hope I will find time to test this soon.

 Is such magic a standard behaviour among other windows Apps?

Is there anything else to do? I think the use case is to install Mixxx an a jump drive along with all the tracks. Does it work flavlessly when the drive letter changes?

2018-08-16 07:42 UTC, sblaisot commented
AFAIK there is no standard behaviour about portable apps. often, this is done by a launchscript which prepare the configuration before launching and cleanup after closing the application.

I did this that way for settingsPath because we already had that logic for RessourcePath (with another use-case but similar intent).

We currently don't handle relative tracks so this will be a problem when changing drive letter. Il will try ti address this later in another PR.

2018-08-16 20:50 UTC, sblaisot commented
> I think the use case is to install Mixxx an a jump drive along with all the tracks. Does it work flavlessly when the drive letter changes?

Maybe we can handle that by replacing the `"[Playlist]", "Directory"` configkey whet Mixxx is detects a portable execution to point to a "tracks" subdir near the Mixxx executable if it exists.
But doing this will prevent a user to be prompted at first launch to select a Music directory.
We should then explain to portable users how to add another library folder if he wants.
Seems doable, though.

2018-08-16 20:52 UTC, sblaisot commented
> Neat, thanks for working on this. I am wondering if maybe we should use a more descriptive magic directory name than "settings" like maybe "mixxx-settings".

Yes, this is possible ;)

> I could imagine a user putting unrelated files and directories in the same folder as the Mixxx executable and accidentally deleting or renaming a directory simply called "settings" because they do not know what it is.

I see a far bigger risk with the `res` sudbirectory (but this one can also be changed to `mixxx-res` if we want, but also with the `plugins` dir and we have no control on the name of that directory I'm afraid.

2018-08-16 21:30 UTC, Pegasus-RPG commented
Not trying to bike-shed here, but maybe it's better to have a dir called 'portable' then 'settings' and 'resources' in it to keep things neater and more obvious? (That also future-proofs it.)

2018-08-16 21:32 UTC, sblaisot commented
> maybe it's better to have a dir called 'portable' then 'settings' and 'resources' in it

I was thinking about that also. I will try that also.

2018-08-16 22:04 UTC, daschuer commented
> I am wondering if maybe we should use a  more descriptive magic directory name than "settings" like maybe  "mixxx-settings". I could imagine a user putting unrelated files and  directories in the same folder as the Mixxx executable and accidentally  deleting or renaming a directory simply called "settings" because they  do not know what it is.

If we want to protect against this, all additional folders needs the mixxx prefix. If we cannot effort this, I would vote for the original folder names without prefix.

Sometimes it happens to me that I extract a zip achive accidentally to my download folder without a subfolder. This way, I have the exe, various dlls and ini files among other downloaded files, makeing it hard to undo the mistake . 
I think we can save us for this by using a mixxx folder and just adding a single short cut outside this folder. 

@Be-ing does this also help in your use case?

2018-08-16 22:21 UTC, Pegasus-RPG requested changes

2018-08-16 22:27 UTC, sblaisot commented on src/SConscript
> +    os.system('7z a ../{} {}'.format(archive_name, directory_name))
7-zip is smart enough. But if we want to make sure, I can add `-tzip`

```
-t{Type}: Set type of archive
```

Not sure it is a good idea to make an installer for a portable application ;)

2018-08-16 22:37 UTC, Pegasus-RPG commented on src/SConscript
> +    os.system('7z a ../{} {}'.format(archive_name, directory_name))
Oh, no, not an installer. An SFX just runs a little application asking where they want to extract the files to.

2018-08-16 22:38 UTC, Pegasus-RPG commented on src/SConscript
> +    os.system('7z a ../{} {}'.format(archive_name, directory_name))
And if it's smart enough, then just leave it, incase we decide to change the format in the future, we only have to do it in one place.

2018-08-16 22:45 UTC, sblaisot commented on src/SConscript
> +    os.system('7z a ../{} {}'.format(archive_name, directory_name))
It is possible to make a self-extracting archive with a nice GUI under windows with

```
7z a mixxx.exe -sfx7z.sfx mixxx-2.2.0-alpha-pre-portable_install-git6548-release-x64
```

But I need to test it under linux and MacOSX to verify it is cross-platform

2018-08-16 23:04 UTC, sblaisot commented on src/preferences/upgrade.cpp
>  #ifdef __WINDOWS__
done

2018-08-16 23:04 UTC, sblaisot commented on src/preferences/upgrade.cpp
>  #ifdef __WINDOWS__
done

2018-08-16 23:07 UTC, sblaisot commented on src/SConscript
> +    os.system('7z a ../{} {}'.format(archive_name, directory_name))
just putting this here for future reference : https://netbeansscribbles.wordpress.com/2015/01/30/creating-a-self-extracting-7zip-archive-multi-platform/

2018-08-17 09:35 UTC, sblaisot commented
ok, first portable version available for test here: https://ci.appveyor.com/project/mixxxdj/mixxx/build/master-4951/job/0u9msvalom50m489/artifacts
(windows, 64 bits)

2018-08-17 17:25 UTC, Be-ing commented
>  I think we can save us for this by using a mixxx folder and just adding a single short cut outside this folder.

Yes, I like this idea. Perhaps instead of checking for special directory names in the same directory as the executable, we can check for the executable being in a special directory called "mixxx" or "mixxx-portable". If the executable is in that special directory, look for "settings" and "res" in that directory too.

> I think the use case is to install Mixxx an a jump drive along with all the tracks. Does it work flavlessly when the drive letter changes?

I think we need to solve this for this PR to be really useful. It might be better to do that in another PR.

It would be awesome if we could get this to work with an AppImage on Linux and if it works on macOS. Ideally a user could put their music files on a USB drive and have a "mixxx-portable" folder with the Windows exe, macOS .app, and Linux AppImage as a backup in case their laptop fails at a gig. This would be a lot easier to maintain than a live distro just for Mixxx.

2018-08-17 19:49 UTC, sblaisot commented
> we can check for the executable being in a special directory called "mixxx" or "mixxx-portable".

Going that way, I prefer to check wether the executable itself is called mixxx-portable or not.

>> I think the use case is to install Mixxx an a jump drive along with all the tracks. Does it work flavlessly when the drive letter changes?

> I think we need to solve this for this PR to be really useful. It might be better to do that in another PR.

I agreee this should be solved, but I prefer to work on it in another PR. This is not trivial at first look.

> It would be awesome if we could get this to work with an AppImage on Linux and if it works on macOS. 

Did you notice this PR is OS-agnostic and produces a portable archive for linux and macOSX as well ?
Just `scons makeportable`. 

That said, portable archive are less usable on linux because
1. we don't build statically so the system running Mixxx should have all dependencies installed
2. even if we build statically, we always depend on glibc version which can be different between distributions.
I don't know about macOSX on this subject.

2018-08-17 21:49 UTC, Be-ing commented
> Going that way, I prefer to check wether the executable itself is called mixxx-portable or not.

I think that's a better idea. Changing program behavior with the name of the executable is occasionally used by other programs for example BusyBox. On the other hand I do not know of any program that relies on special directory names.

> Did you notice this PR is OS-agnostic and produces a portable archive for linux and macOSX as well ?

I did not notice, thank you for clarifying.

> That said, portable archive are less usable on linux because
>    we don't build statically on linux so the system running Mixxx should have all dependencies installed
>    even if we build statically, we always depend on glibc version which can be different between distributions.

Those can both be resolved by packaging an AppImage built on an old distro.

2018-08-19 21:04 UTC, sblaisot commented on src/SConscript
> +    print("==== Mixxx Post-Build Checks ====")
Done

2018-08-19 21:06 UTC, sblaisot commented
> Those can both be resolved by packaging an AppImage built on an old distro.

Yes but that's beyond the scope of this PR ;)

I will take a look on portable behaviour based on executable name

2018-08-20 20:38 UTC, sblaisot commented
ok, with last commit, Mixxx switch to portable mode if the executable itself is called `mixxx-portable` (case insensitive and without extension) or if the `--portable` switch is used on command-line.

When in portable mode, it uses by default `mixxx-settings` and `mixxx-resources` as settings an resources directories respectively. These can be overwriten with standard `--settingsPath` and `--resourcePath`

PR description updated

2018-08-20 21:48 UTC, sblaisot commented
Argh, it doesn't work because QApplication is not even instanciated when parsing command line args so I can't use `QCoreApplication::applicationFilePath` to get Mixxx executable name :(

All I get is `QCoreApplication::applicationFilePath: Please instantiate the QApplication object first`

I need to find another way to get Mixxx executable name...

2018-08-21 07:08 UTC, sblaisot commented
Leaving this here for reference:
* http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qcoreapplication.cpp#n2227
* https://github.com/mixxxdj/mixxx/blob/master/src/main.cpp#L85-L100

2018-10-14 20:45 UTC, radusuciu commented
Could you instantiate a dummy QCoreApplication just to get access to that method? Or access directly from the args variable?

2019-09-29 22:39 UTC, Symbian9 commented
> > Those can both be resolved by packaging an AppImage built on an old distro.
>
> Yes but that's beyond the scope of this PR ;)

But has you plans to make *AppImage* builds? I really want it use portable *Mixxx* on Linux.

2021-01-01 17:26 UTC, closed without merging