allow for overlapping beatlooprolls
mixxxdj/mixxx pull request #1812
Opened 2018-09-19 18:02 UTC by iamcodemaker

This is necessary if multiple beatlooproll keys are pressed on a controller. Previously, Mixxx would stop the loop roll if any keys were released. Now it tracks all active rolls and will activate the last active one that is still active (button still down) instead of deactivating all rolls. Additionally, if a loop roll is active, activating another beat loop roll will start the loop from the start of the current loop, instead the current play position.

I believe this loop roll behavior is more intuitive and natural.

2018-09-19 20:33 UTC, daschuer commented
Thank you for the Pull request.
Do we have a Launchpad bug for it?

2018-09-19 21:20 UTC, daschuer requested changes
Works good, I have only some minor comments. 
Thank you.

2018-09-19 22:38 UTC, iamcodemaker commented on src/engine/loopingcontrol.cpp
> +    m_activeLoopRolls.push(pBeatLoopControl);
Yes. I'll make that change.

2018-09-19 22:40 UTC, iamcodemaker commented on src/engine/loopingcontrol.cpp
> +    m_activeLoopRolls.removeAll(pBeatLoopControl);
Will update. In theory there should only be one of each beat loop in here max. Actually thinking about it, if a controller had two ways to activate a loop roll we might end up with duplicates. So looping here is necessary.

2018-09-19 23:16 UTC, iamcodemaker commented on src/engine/loopingcontrol.cpp
> +    m_activeLoopRolls.push(pBeatLoopControl);
If we store `double`s in here, are we going to have any issues comparing them using `==`? I don't understand floats well enough to say. The values should be exact though, so my gut says this is fine.

2018-09-19 23:32 UTC, iamcodemaker commented on src/engine/loopingcontrol.cpp
> +    m_activeLoopRolls.removeAll(pBeatLoopControl);
Made the removal loop O(n) (though the stack will always be so small it won't matter). It is slightly more complex now though.

2018-09-19 23:34 UTC, ronso0 commented
Ooouh, sounds interesting!! I got used to the way it works right now, but your idea makes sense. Didn't test this yet.


Is this the right place to ask for taking a look at [lp:1721881 beatloop shouldn't alter beatloop size in spinbox](https://bugs.launchpad.net/mixxx/+bug/1721881) ?


Also, just yesterday I wished I could transfrom a **rolling** beatlopp into a 'regular' one, to resize it and move it. I got stucked when thinking about the controller implementation...

2018-09-19 23:35 UTC, rryan commented
Thanks! To make sure we dont break this in the future could you please add some unit tests?
src/test/looping_control_test.cpp

2018-09-19 23:43 UTC, iamcodemaker commented
Not sure if there is a launchpad bug for it, I didn't check. I'll work on some tests.

2018-09-20 06:15 UTC, daschuer commented
@rons0 transforming a loop, in a way that you can release you finger and the loop keeps looping?
Thats a valid use case. Can you file a bug that we can consider details there?

2018-09-20 12:30 UTC, ronso0 commented
[lp:1793520 transform a rolling beatloop into a 'static' loop](https://bugs.launchpad.net/mixxx/+bug/1793520)

2018-09-25 19:53 UTC, daschuer approved these changes

2018-09-25 19:57 UTC, daschuer commented
The Travis failure is unrelated.
LGTM Thank you very much.

2018-09-25 19:57 UTC, merged