Fix deprecation warning for libupower
mixxxdj/mixxx pull request #1917
Opened 2018-11-24 08:45 UTC by uklotzde

A simple fix to prevent a potential memory leak:
https://gitlab.freedesktop.org/upower/upower/issues/14

2018-11-24 09:50 UTC, daschuer requested changes
Did we do the mentioned mistake from the linked issue when calling
g_ptr_array_free(devices, TRUE);
blow?
Do we need to special case the code there as well?
From our code it looks like both get devices functions are 1:1 exchangeable. But in this case there would be no reason to introduce a second version cluttering the public API.

2018-11-24 09:50 UTC, daschuer commented on src/util/battery/batterylinux.cpp
> +    // See also: https://gitlab.freedesktop.org/upower/upower/issues/14
I think it is better to drop some words about the differences here. One time the free function is set and one time not.

2018-11-24 09:51 UTC, daschuer commented
Thanks for taking cate 😀

2018-11-24 10:17 UTC, uklotzde commented
Indeed, with the old version we actually have a memory leak.

2018-11-24 10:33 UTC, uklotzde commented
Good catch. I was just too lazy to dig deeper. Memory leak should be fixed now by borrowing a line of code from the patch.

2018-11-26 19:21 UTC, daschuer approved these changes
LGTM, Thank you.

2018-11-26 19:21 UTC, merged