Fix build on Ubuntu caused by incorrect order of libraries
mixxxdj/mixxx pull request #1926
Opened 2018-11-29 23:00 UTC by ninomp

This fixes https://bugs.launchpad.net/mixxx/+bug/1804411

2018-11-30 00:12 UTC, ninomp commented
Should I squash these two commits into one?

2018-11-30 07:10 UTC, daschuer commented
I don't mind in this case. Normally you should not rewrite the history in a pending PR.

2018-11-30 07:14 UTC, daschuer commented
Is the 2.1 branch also effected?
If yes, we should reabse (and squash) it to it.

2018-12-18 01:09 UTC, ninomp commented
@daschuer Hmm, if we remove `conf.CheckLib(['dl', 'libdl'])'` from `configure()`, scons will no longer check if this library is available/installed during its configuration step.

2018-12-24 12:21 UTC, daschuer commented
Please check if the original issue was caused by a double -lvamp-hostsdk 
fixed in:
https://github.com/mixxxdj/mixxx/pull/1959

2018-12-24 12:22 UTC, daschuer requested changes
conf.CheckLib(['dl', 'libdl']) already adds -ldl.
The double -ldl should be fixed before merge.

2018-12-24 15:19 UTC, nopeppermint commented
I can confirm that this fix error https://bugs.launchpad.net/mixxx/+bug/1804411 on Linux Mint 19 x64

But if I remove the line suggested by @daschuer in  #1959 I get the following error:
```
ValueError: list.remove(x): x not in list:
  File "/home/stefan/mixxx_develop/mixxx/SConstruct", line 101:
    duplicate=0, exports=['build'])
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/home/stefan/mixxx_develop/mixxx/vamp-plugins/SConscript", line 62:
    env['LIBS'].remove('vamp-hostsdk')
```

but If I remove     ` env['LIBS'].remove('vamp-hostsdk')`  on line 62 in the file `/mixxx/vamp-plugins/SConscript` I get other errors:

```lin64_build/libmixxx.a(vamppluginadapter.o): In Funktion »mixxx::(anonymous namespace)::getPluginLoaderLocked()«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vamppluginadapter.cpp:149: Warnung: undefinierter Verweis auf »_VampHost::Vamp::HostExt::PluginLoader::getInstance()«
lin64_build/libmixxx.a(vamppluginadapter.o): In Funktion »mixxx::VampPluginAdapter::listPlugins[abi:cxx11]()«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vamppluginadapter.cpp:184: Warnung: undefinierter Verweis auf »_VampHost::Vamp::HostExt::PluginLoader::listPlugins[abi:cxx11]()«
lin64_build/libmixxx.a(vamppluginadapter.o): In Funktion »mixxx::VampPluginAdapter::composePluginKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vamppluginadapter.cpp:198: Warnung: undefinierter Verweis auf »_VampHost::Vamp::HostExt::PluginLoader::composePluginKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)«
lin64_build/libmixxx.a(vamppluginadapter.o): In Funktion »mixxx::VampPluginAdapter::loadPlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, int)«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vamppluginadapter.cpp:165: Warnung: undefinierter Verweis auf »_VampHost::Vamp::HostExt::PluginLoader::loadPlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, int)«
lin64_build/libmixxx.a(vampanalyzer.o): In Funktion »VampAnalyzer::Init(QString, QString, int, int, bool)«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vampanalyzer.cpp:60: Warnung: undefinierter Verweis auf »_VampHost::Vamp::PluginHostAdapter::getPluginPath[abi:cxx11]()«
lin64_build/libmixxx.a(vampanalyzer.o): In Funktion »VampAnalyzer::GetInitFramesVector()«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vampanalyzer.cpp:247: Warnung: undefinierter Verweis auf »_VampHost::Vamp::RealTime::realTime2Frame(_VampHost::Vamp::RealTime const&, unsigned int)«
lin64_build/libmixxx.a(vampanalyzer.o): In Funktion »VampAnalyzer::GetEndFramesVector()«:
/home/stefan/mixxx_develop/mixxx/lib/vamp/vamp-sdk/RealTime.h:92: Warnung: undefinierter Verweis auf »_VampHost::Vamp::RealTime::RealTime(int, int)«
lin64_build/libmixxx.a(vampanalyzer.o): In Funktion »VampAnalyzer::GetEndFramesVector()«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vampanalyzer.cpp:263: Warnung: undefinierter Verweis auf »_VampHost::Vamp::RealTime::realTime2Frame(_VampHost::Vamp::RealTime const&, unsigned int)«
lin64_build/libmixxx.a(vampanalyzer.o): In Funktion »VampAnalyzer::Process(float const*, int)«:
/home/stefan/mixxx_develop/mixxx/src/analyzer/vamp/vampanalyzer.cpp:175: Warnung: undefinierter Verweis auf »_VampHost::Vamp::RealTime::frame2RealTime(long, unsigned int)«
collect2: error: ld returned 1 exit status
scons: *** [lin64_build/mixxx] Error 1
scons: building terminated because of errors.
```
so there might be more to do..

2018-12-24 16:53 UTC, nopeppermint commented
thanks!
now compiling current master with this pr on top is working again on Linux Mint 19 x64

2018-12-24 17:01 UTC, ninomp commented
OK I have managed to resolve duplicates. They were caused by having two VAMP SDKs: one installed on system and the other bundled with Mixxx. I have tested this only on my Linux Mint 18.3 system, on which Mixxx is always taking the bundled VAMP SDK. Can you test this on Linux Mint 19 as well as other distros?

2018-12-24 17:04 UTC, ninomp commented
@nopeppermint Glad to hear it :smile:

2018-12-25 07:10 UTC, daschuer commented
Greate, no it is fine, Thank you. I think just need to comment why we need a special treatment here.

2018-12-25 20:38 UTC, daschuer commented
Thank you, for your patience.  LGTM.

2018-12-25 20:38 UTC, daschuer approved these changes

2018-12-25 20:39 UTC, merged

2018-12-25 21:38 UTC, ninomp commented
Thank you for merging.