Exclude Transifex (.ts/.qm) and WiX (.po) l10n files from merging (locally)
mixxxdj/mixxx pull request #1984
Opened 2019-01-05 22:43 UTC by uklotzde

As discussed on [Zulip](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Translations.20on.20transifex/near/154472443)

Please verify if this is the correct way to simplify merging between different releases, e.g. from 2.1 to 2.2.

2019-01-09 07:18 UTC, uklotzde commented
Anyone? I would like to re-sync our release and development branches. This PR just states and documents how to resolve the merge conflicts with translations now and for the future.

2019-01-09 12:19 UTC, daschuer requested changes

2019-01-09 12:19 UTC, daschuer commented on .gitattributes
> +# directory to enable automatic merge resolution:
I think we should add here some more explanations. How about that.
... to register the shell command "true" as merge driver "ours" that does just nothing during a git merge.

2019-01-11 15:00 UTC, daschuer commented on .gitattributes
> +# directory to enable automatic merge resolution:
Ping! 
This command does not enable automatic merge resolution.
It sets a shell script that is used for all merge=ours files.
In this case the script "true" dies not touch anything, just returns successful.

2019-01-12 13:07 UTC, daschuer commented
LGTM, thank you.

2019-01-12 13:07 UTC, merged

2019-01-12 14:53 UTC, uklotzde commented
I've added a note to the [Wiki page](https://mixxx.org/wiki/doku.php/internationalization)