Improve error handling for Musicbrainz lookups
mixxxdj/mixxx pull request #1997
Opened 2019-01-13 22:13 UTC by daschuer

This PR exposed the error messages received from the web services to the user. 
It fixes some wrong fall back messages that are currently displayed instead.

2019-01-13 22:33 UTC, daschuer commented on src/library/dlgtagfetcher.cpp
> +    connect(&m_TagFetcher, SIGNAL(networkError(int, QString, QString, int)),
Yes right, I will do. I did this original on top of 2.1 but than I noticed how this has grown beyond a small bug fix.

2019-01-17 22:03 UTC, daschuer commented
Notes addressed.

2019-01-19 17:30 UTC, uklotzde commented on src/musicbrainz/musicbrainzclient.cpp
> +             "MusicBrainz", message, 0));
Passing 0 is not intuitive. Does a default parameter for signals work in Qt5? Otherwise use a constant with a concise name.

2019-01-19 17:31 UTC, uklotzde requested changes
Minor issues

2019-01-19 22:50 UTC, daschuer commented
Done

2019-01-20 23:01 UTC, uklotzde requested changes
A compiler warning about unused code needs to be fixed

2019-01-20 23:01 UTC, uklotzde commented on src/musicbrainz/tagfetcher.cpp
> +    for (const auto& ptrack: qAsConst(m_tracks)) {
During the local build I noticed that `ptrack` is unused and this loop effectively is useless??? Emitting the signal just once should be sufficient.

Not your fault, but now it's time to fix this before we stumble over it once again!

2019-01-24 21:19 UTC, daschuer commented
Done

2019-01-28 19:35 UTC, uklotzde commented
The VS build failed with a timeout. LGTM.

2019-01-28 19:35 UTC, merged

2019-01-28 19:41 UTC, uklotzde commented
Thank you for maintaining and improving code in addition to fixing a bug, Daniel!