added release and zulip badget
mixxxdj/mixxx pull request #2000
Opened 2019-01-19 16:51 UTC by daschuer

2019-01-19 17:18 UTC, uklotzde commented on README.md
> +[![GitHub release](https://img.shields.io/github/release/mixxxdj/mixxx.svg)](https://github.com/mixxxdj/mixxx/releases/latest)
Please use https://img.shields.io/github/tag/mixxxdj/mixxx.svg = _GitHub tag (latest SemVer)_ for selecting the most recent version. Selecting releases by date is confusing and may alternate between different release branches. Currently it is showing 2.1.6.

2019-01-19 17:32 UTC, uklotzde requested changes
Wrong release badge

2019-01-19 21:49 UTC, daschuer commented
OK works now. Thank you for the hint. 
I have not managed to link to the tag, so now it links to our downloads page.
This is IMHO more reasonable anyway.

2019-01-19 21:51 UTC, daschuer commented
Yippie, I have got #2000 :tada:

2019-01-20 22:34 UTC, rryan commented
> Yippie, I have got #2000 🎉

And you had #1000 too. Lucky!

2019-01-20 22:38 UTC, rryan commented
> @Be-ing has the honor of #1000

Doh, I mis-read the top-line. You merged it.

2019-01-20 22:45 UTC, uklotzde approved these changes

2019-01-20 22:46 UTC, merged