Round display value in library table to whole number
mixxxdj/mixxx pull request #2001
Opened 2019-01-20 17:02 UTC by benis

This was discussed a while ago on Zulip. This PR rounds the BPM column in the library so that it only shows whole values. The tooltip will still show the value to 3 d.p., and the actual value is obviously unaffected.

Before:
<img width="817" alt="screenshot 2019-01-20 at 16 53 30" src="https://user-images.githubusercontent.com/36423450/51442400-1efc3380-1cd4-11e9-8d96-fd71afcbc603.png">

After:
<img width="828" alt="screenshot 2019-01-20 at 16 53 59" src="https://user-images.githubusercontent.com/36423450/51442396-10ae1780-1cd4-11e9-9b4d-4b513305a9f8.png">

The only snag I can think of is that users unfamiliar with Mixxx might be caught out by the fact that [Mixxx's BPM detection doesn't always correctly identify tracks that are at whole BPMs](https://bugs.launchpad.net/mixxx/+bug/1796262/comments/7). This might mask some cases where the analyzed BPM value isn't quite right, which could have some knock-on effects for bpm sync.

2019-01-20 18:48 UTC, daschuer commented
Which issue does the PR solve?

2019-01-20 18:49 UTC, daschuer requested changes
I don't think that this will work for all users. 
Is it worth to clutter the preferences with this?

2019-01-20 19:01 UTC, benis commented
> Which issue does the PR solve?

I was thinking of [this comment](https://mixxx.zulipchat.com/#narrow/stream/109122-general/topic/BPM.20sorting/near/134933613) in particular which a number of people agreed with. I realise it's not the solution to all issues with bpm handling.

> Is it worth to clutter the preferences with this?

I wouldn't say so, no. I think it would better not to implement it than to have to include a preference option.

2019-01-20 19:33 UTC, ronso0 commented
> This might mask some cases where the analyzed BPM value isn't quite right, which could have some knock-on effects for bpm sync.

I think it would help to append special character(s) in this case to indicate there are decimals.
Maybe as simple as `124..`, `124*` or `124~`. The decimals are visible in the decks so IMO this format could be the default, with a Preferences option to return to current display with all decimals visible.

2019-01-20 19:42 UTC, benis commented
> > This might mask some cases where the analyzed BPM value isn't quite right, which could have some knock-on effects for bpm sync.
> 
> I think it would help to append special character(s) in this case to indicate there are decimals.
> Maybe as simple as `124..`, `124*` or `124~`. The decimals are visible in the decks so IMO this format could be the default, with a Preferences option to return to current display with all decimals visible.

I thought about this too, but I felt that adding a non-numeric character would just clutter the field again. But if the idea is popular and the general consensus is that `124~` is better than `124.321` for example then I don't see why not.

If there was going to be a Preferences option, I'd want to have the choice between:
* Show all decimals
* Show rounded numbers with indicator (eg `124~`)
* Show plain rounded numbers

2019-01-20 19:57 UTC, daschuer commented
For me this PR alone does not make any sense. The real issue is the BPM grouping.

2019-01-20 20:00 UTC, daschuer commented
Three decimal places are useless though. Maybe we can go for one or two.

2019-01-20 20:13 UTC, benis commented
I agree 2dp would be an improvement. If I made changes for that and pushed to this PR, would you still want to discuss further? If so we may as well get some further opinions now.

2019-01-20 21:31 UTC, daschuer commented
That will work for me without a preferences option. 
We may also consider to add a .00 to the full BPM values to tidy up the column even more. 

Consideration:
If we consider the normal rate slider range of 8% and a single precision rate slider and a average 120 BPM track, one slider tick is 0,08 BPM. This means the user can only control one decimal place in this case. A high precision slider can control 0,0006 though. 

@ronso0 what do you think.

2019-01-21 19:50 UTC, benis commented
This is how forced 2 d.p. looks. Thoughts? It would be nice if the decimal points aligned, I don't know if Qt has that capability or not but I would guess it does.

<img width="253" alt="screenshot 2019-01-21 at 19 48 43" src="https://user-images.githubusercontent.com/36423450/51495827-96ee5a80-1db5-11e9-9eb0-3a23d4241e80.png">

2019-01-21 22:43 UTC, daschuer commented
I think a delegate can do this, like in https://github.com/mixxxdj/mixxx/pull/2002. 
This will also allow to set the numbers of decimals by the columns width.

2019-01-23 19:31 UTC, benis commented
> I think a delegate can do this, like in # 2002.
> This will also allow to set the numbers of decimals by the columns width.

It will be slightly more tricky. There's already a bpm delegate that handles drawing the bpm lock etc, so I'll need to make it work around/with that. It would be good to get it working though, I'd be happy to use column width to set the decimal places.

2019-01-26 19:43 UTC, benis commented
I'll close this until I have something that needs review, so as not to add to the clutter of open PRs.

2019-01-26 20:33 UTC, ronso0 commented
> I'll close this until I have something that needs review, so as not to add to the clutter of open PRs.

just leave it open as it's on a good way I think.
if the PR is not updated for a while even after a team member sends a reminder it'll get a `stalled` tag

2019-01-26 20:40 UTC, ronso0 commented
> That will work for me without a preferences option.
> We may also consider to add a .00 to the full BPM values to tidy up the column even more.
> 

...and try to align the decimals point in all column fileds.

> Consideration:
> If we consider the normal rate slider range of 8% and a single precision rate slider and a average 120 BPM track, one slider tick is 0,08 BPM. This means the user can only control one decimal place in this case. A high precision slider can control 0,0006 though.
> 
> @ronso0 what do you think.

Users may have high-precision sliders but they usually don't have high-precision hands :)
And IF a DJ has high-precision ears to notice 0.01 BPM offsets they wouldn't rely on BPM display at all for beatmatching. That's just what I noticed when watching DJs experienced with vinyl when they play with digital gear.
having more than 3 decimals would be helpful -if at all- in the decks' rate section, but not in the library IMO.

2019-01-26 22:41 UTC, daschuer commented
So you vote is for one or two decimal places?

It is ok for me to merge this and do the decimal point allignment in a later PR.

2019-01-26 23:03 UTC, ronso0 commented
> So you vote is for one or two decimal places?

IMO one decimal is enough for the library: we can see BPM is not an integer, the rest happpens in the decks.

2019-01-27 08:43 UTC, daschuer commented
@benis Ok, can you change it to one decimal place and the we are ready to merge. Thanks.

2019-01-27 16:50 UTC, benis commented
Ok. For now do you care whether the number always has the decimal place or not? It's actually harder to display a number with 'up to' 1 d.p. than it is to just force 1 d.p.

You can use `'f'` to set the number of decimal places or `'g'` to set the number of significant figures, so using `f` would always give you `xxx.y`, but using `g` would give you (for example) `xxx` or `xx.y` depending on whether the bpm was >= 100 or < 100. So having the decimal place be optional is actually more work than just always displaying it.

2019-01-27 17:02 UTC, uklotzde commented
Personally I would prefer a format with a fixed number of decimal places. This is much easier to recognize. A single decimal place is a perfect compromise between readability and precision.

2019-01-27 17:05 UTC, benis commented
Sounds good to me. I think that's better in the case of numbers such as 121.04 anyway - without the decimal place this would just display as `121` which I think would be _slightly_ misleading.

2019-01-27 17:10 UTC, ronso0 commented
I know this is out of scope for this PR but here's how I'd find the BPM column really useful, and it might be tricky if we use fonts with variable width (non-monospace fonts):
```
123
110.0
 97
 98.3
160
156
```
Slightly shrinking the column would result in
```
123
110.
 97
 98.
160
156
```
which allows to identify fast & slow tracks quickly, and also gives a hint when the BPM has decimals

2019-01-27 17:11 UTC, benis commented
This is how it looks:
<img width="195" alt="screenshot 2019-01-27 at 17 07 29" src="https://user-images.githubusercontent.com/36423450/51804227-0d77d600-2256-11e9-9f7e-b1c3caab20aa.png">

I'm tempted to modify this slightly so that zero values are just left blank. Thoughts?

2019-01-27 18:36 UTC, uklotzde commented
I didn't follow the discussions. But if we use a fixed number of decimal places then the column should be right-aligned as is common for displaying numeric values.

The alignment helps when playing mixed music with a wide range of tempos between 50 and 190 bpm. Usually I sort my genre/style/mood/phase crates by bpm, because this is the (technical) starting point for figuring out a next track that might fit. So for my personal workflow the number-style alignment is a nice-to-have feature.

2019-01-27 19:19 UTC, benis commented
Yeah, right-align would be a good choice to combine with this PR. I don't know if it can be done without having to rework the bpm delegate a fair bit, but I'll have a look.

2019-01-28 09:37 UTC, poelzi commented
For the music I play, the decimal point is a good indicator that the bpm detection failed. Nearly all songs with decimal points are wrongly detected tracks, It helps me not accidental play a track not matching. For me, 2 decimal points would nicely indicate that.

2019-01-28 13:41 UTC, benis commented
I'm wondering if it would be an idea to use an elide that's condition-based and only kicks in with narrower column widths. Currently, as soon as the elide kicks in you lose two characters, which is kind of a pain.

If it were possible to do a conditional elide, you could do something like this:

Value|Wide display|Medium display|Narrow display|Very narrow display
-|-|-|-|-
**123**|123.00|123|123|12…
**123.04**|123.04|123.0|123…|12…

I think this would be a pretty good way of accommodating several different preferences.

2019-02-06 22:14 UTC, benis commented
Replacing '0' values with a dash is a good look, imo:

<img width="553" alt="screenshot 2019-02-06 at 22 13 06" src="https://user-images.githubusercontent.com/36423450/52377328-70d6e480-2a5c-11e9-8108-5231c20c2ff5.png">

2019-02-07 07:05 UTC, daschuer commented
I like the dash version.
I think this is already merge-able, right?
Should I merge this now or wait for the dash?

2019-02-07 12:06 UTC, benis commented
Well.

I took that screenshot above after making an experimental change to `bpmdelegate` as part of a separate change. As far as this PR is concerned though, I figure it makes more sense to do the change to a dash in `basesqltablemodel` at line ~678 where the other changes have been made and there's already some formatting of the number happening.

However, for some reason I can't get this to work:

```cpp
value = value.toDouble();
value = 0.0 ? "-" : QString("%1").arg(value.toDouble(), 0, 'f', 1);
```
It won't evaluate to true, so it keeps displaying 0.0 for zero values. I suspect it's something simple, I've tried replacing 0.0 with just `0` and `0.` but neither works.

I appreciate it's a small detail so if there's not an obvious answer you could just merge this as is.

2019-02-07 12:45 UTC, benis commented
Oh dear, fun with Git -_-

2019-02-07 12:50 UTC, benis commented
Right then! Ready to merge :)

2019-02-07 19:51 UTC, daschuer commented
LGTM, Thank you.

2019-02-07 19:51 UTC, merged

2019-02-21 14:31 UTC, LindyBalboa commented
Hi, I just recompiled and I would like to say I'm not a fan of trailing zeros on integer values. I don't do any inter-track mixing so I don't need to be any more precise than integer BPMs. As it stands, this shows a useless xxx.0 for my whole library. I think I would be in favor of a config option to set the number of decimals displayed.

2019-02-21 14:51 UTC, ywwg commented
I have tracks that definitely need at least 2 decimal points of detail -- I assume this is just rounding the display?  If I edit the bpm value will I see all the significant figures?

2019-02-21 16:41 UTC, daschuer commented
Correct.

2019-02-21 19:54 UTC, benis commented
I agree about the decimal places on integer values. The thing I'm working on currently would deal with that:

<img width="269" alt="screenshot 2019-02-21 at 19 53 08" src="https://user-images.githubusercontent.com/36423450/53197537-57b06500-3612-11e9-8069-c8bed37b236f.png">

2019-02-22 08:41 UTC, LindyBalboa commented
It is not so urgent to me personally to have a fix in master. Your change was so atomic I can easily revert the commit. I'm just happy to hear that you are working further on it with this in mind.