Work around performance issue with Qt 5.12 and PreviewButtonDelegate.
mixxxdj/mixxx pull request #2003
Opened 2019-01-22 01:54 UTC by rryan

[Launchpad Bug #1812763](https://bugs.launchpad.net/mixxx/+bug/1812763).

After upgrading to Qt 5.12, Mixxx idle CPU usage is high (99%) on
macOS. Profiling shows LibraryPreviewDelegate::paintItem as one of the hottest
functions. It appears to be related to calling QPushButton::setGeometry for each
row of the library. My workaround relies on the fact that we only need the
QPushButton size to be correct, not its position.

On macOS 10.13.6, CPU usage drops from 99% to 50% with this change
(and with #1994, idle usage drops to 15%).

2019-01-22 01:58 UTC, rryan commented
> Be-ing changed the base branch from master to 2.2 2 minutes ago
Doh. Thanks.

2019-01-22 16:39 UTC, rryan commented
I removed the workaround added for [lp:1776555](https://bugs.launchpad.net/mixxx/+bug/1776555) but I'm not sure if that was necessary to fix the issue. In general I'm wary of us messing around with QWidget internals (which I believe `WA_WState_Visible` is an internal attribute for state tracking).

2019-01-23 17:20 UTC, daschuer reviewed
Thank you. I have added only some minor comments.
Regarding the Qt5.2 crash fix, I will test if I can reproduce the issue with this branch on Trusty maybe you have fixed it as well.
Else we need to know which is the first version of Qt that has fixed the root cause.
Hopefully we can remove it anyway because Trusty will EOL soon.

2019-01-23 17:20 UTC, daschuer commented on src/library/previewbuttondelegate.cpp
> +    QPushButton* btn = new LibraryPreviewButton(parent);
You can use here make_parented

2019-01-23 17:20 UTC, daschuer commented on src/library/previewbuttondelegate.h
> +    ~LibraryPreviewButton() = default;
Isn't this redundand?

2019-01-23 21:54 UTC, daschuer commented
With this branch, I am not able to crash Mixxx on Trusty like lp:1776555 
Unfortunately the preview button size is jumping around, not following always the column width.
This is a regression from the 2.2 branch.

2019-01-23 21:56 UTC, daschuer requested changes
Does this resize issue also happens on your device?

2019-01-28 02:18 UTC, rryan commented
> With this branch, I am not able to crash Mixxx on Trusty like lp:1776555

Great, thanks for checking.

> Unfortunately the preview button size is jumping around, not following always the column width.
> This is a regression from the 2.2 branch.
> Does this resize issue also happens on your device?

No :( it works for me -- the delegate is always drawn at the right width when I resize the column.

2019-01-28 02:21 UTC, rryan commented on src/library/previewbuttondelegate.h
> +    ~LibraryPreviewButton() = default;
Removed.

2019-01-29 22:59 UTC, daschuer commented
If I resize the column far more than needed, the size cycling with the coloum width.
I have re-added the 
m_pButton->setAttribute(Qt::WA_WState_Visible);
hack, the problem happens less often.
But it is still there at some width.

2019-01-30 17:54 UTC, daschuer commented
I have tried to debug the resizing issue, but it seems to happen inside the image style code.
Than I have tested 2.1.7 and it suffers the same issue. So it is no regression here, we can merge it.
LGTM.

Thank you.

2019-01-30 17:54 UTC, merged