numark mixtrack 3: don't change FX level when moving beatgrid
mixxxdj/mixxx pull request #2057
Opened 2019-03-18 08:04 UTC by mimbert

controller mapping bugfix for Numark Mixtrack Pro 3: when moving the beatgrid forward or backward with TAP + FX level, it has the buggy side effect of changing the FX level. This commit fixes that.

2019-04-12 09:29 UTC, uklotzde commented
Should the fix be included in 2.2.1? Then please change the target branch of this PR.

2019-04-12 09:41 UTC, mimbert commented
The fix is to be included asap, so i guess yes it should be in 2.2.1. I changed the target branch to 2.2
Thanks for noticing this

2019-04-12 09:43 UTC, mimbert commented
But now there's a huge number of conflicts, maybe I should rather create another merge request from scratch, based on branch 2.2 ?

2019-04-12 10:19 UTC, uklotzde commented
Rebasing your local branch on the latest 2.2 should work. Then do a force push and change the target branch afterwards. Creating a new PR would be the last resort.

2019-04-12 10:22 UTC, uklotzde commented
You can re-write and force push your local branch in any way as long as you keep its name. PRs are bound to the URL, i.e. the branch name.

2019-04-17 07:36 UTC, uklotzde commented
Simply changing the target branch doesn't work:
- Rename this branch locally
- Create a new 'numark-mixtrack-pro-3' branch originating from 2.2
- Cherry-pick your commit
- Force push to GitHub
- Change the target of this PR from master to 2.2

2019-04-17 07:37 UTC, uklotzde requested changes
Needs to be rebuild upon and retargeted to 2.2

2019-04-17 07:58 UTC, uklotzde commented
We also need the permission to distribute your changes by signing the [Mixxx contributor agreement](https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ).

2019-04-17 22:38 UTC, Be-ing commented
Considering this has gotten a :+1: from @radusuciu who has this controller, LGTM.

2019-04-17 22:50 UTC, radusuciu commented
> 
> 
> Considering this has gotten a 👍 from @radusuciu who has this controller, LGTM.

FYI I no longer have this controller, but the change is minor and it's relatively easy to see the consequence.

2019-04-19 23:49 UTC, daschuer commented
Thank you!

2019-04-19 23:49 UTC, merged

2019-04-20 00:02 UTC, daschuer commented
And cherry-picked to 2.2 https://github.com/mixxxdj/mixxx/commit/ad334585fb86dc6afd4b263a968f1579b4385d67

2019-04-20 15:49 UTC, daschuer commented
This bug sound quite similar: https://bugs.launchpad.net/bugs/1825659 are they related?

2019-04-24 15:25 UTC, hypsinom commented
hello I made some change before him. But I don't make commits yet. 
https://www.mixxx.org/forums/viewtopic.php?f=7&t=7286&start=310#p40876