Gl es detect
mixxxdj/mixxx pull request #2088
Opened 2019-04-23 19:26 UTC by daschuer

This is an attempt to fix the blank GL Status reported here: 
https://bugs.launchpad.net/mixxx/+bug/1825461

2019-04-24 20:00 UTC, uklotzde commented
Should we remove all the remaining obsolete QT_VERSION_CHECK guards up to and including Qt 5.2 in a separate PR? I noticed that there are many of them that unnecessarily clutter the code.

2019-04-24 20:59 UTC, daschuer commented
> Should we remove all the remaining obsolete QT_VERSION_CHECK guards up to and including Qt 5.2 in a separate PR? I noticed that there are many of them that unnecessarily clutter the code.

Yes, probably along with the string based connect() calls. The later hurts me much more.

2019-04-25 06:10 UTC, daschuer commented
Ok, it is working. My virtualized Windows 10 is now reporting OpenGL ES 2.0. All GL and GLS waveforms are removed from the combobox.

I guess it is because I have messed arround with Qt fall back renderers. Or something.

2019-04-25 06:15 UTC, daschuer commented
Interestingly spinnies and Qt waveforms are  working in this state. 
So it is not correct to hide the Qt waveforms  now.

2019-04-25 15:19 UTC, uklotzde commented
LGTM, although I'm not able to actually test it. Ready to merge?

2019-04-25 22:51 UTC, daschuer commented
Not ready, Qt5 requires at least OpenGL 2.1 or OpenGL ES 2.0. I will update the versions check accordingly.

2019-04-26 22:44 UTC, daschuer commented
Now the GL detection should match QTs ideas of using GL in QT5. 
It also fixes a crasher related to spinnies: https://bugs.launchpad.net/mixxx/+bug/1798858

2019-04-26 22:59 UTC, daschuer commented
Maybe it fixes also the cash reported in https://bugs.launchpad.net/mixxx/+bug/1341036

2019-04-26 23:28 UTC, daschuer commented
This PR is also a base for GL ES waveforms: 
https://bugs.launchpad.net/mixxx/+bug/1316402

2019-04-27 07:22 UTC, uklotzde commented on src/waveform/waveformwidgetfactory.cpp
> +            useOpenGles =  GLVSyncTestWidget::useOpenGles();
Copy&Paste error?

2019-04-29 05:51 UTC, daschuer commented
This one has the regression that there are no waveforms at all if you start Mixxx with: 
mixxx --developer 
on windows 10. 
Without the developer flag everything is fine.

2019-05-01 16:24 UTC, daschuer commented
OK, the initialization of the VSyncThread was timing sensitive. This is now fixed. 
Hopefully that fixes https://bugs.launchpad.net/mixxx/+bug/1824620 as well.

2019-05-02 20:01 UTC, uklotzde commented
Is this ready? I'm slightly confused by the two parallel PRs. Shouldn't the other be marked as WiP until this has been merged both into 2.2 and master?

2019-05-02 20:17 UTC, uklotzde commented
Travis fails: QOpenGLFunctions::glGetString() was introduced in Qt 5.3!

2019-05-02 20:17 UTC, uklotzde requested changes
Requires Qt 5.3

2019-05-02 22:07 UTC, uklotzde approved these changes

2019-05-02 22:09 UTC, uklotzde commented
LGTM. AppVeyor CI build is expected to succeed.

2019-05-02 22:10 UTC, merged