Qt4 Cleanup
mixxxdj/mixxx pull request #2099
Opened 2019-05-02 18:17 UTC by uklotzde

A set of trivial changes that delete all obsolete Qt4 code.

The commits have been splitted for easy review:
-  Explicit checks for any Qt 4.x version
- Checks for Qt version < 5.0, i.e. effectively also for any 4.x version
- Checks for Qt version >= 5.0, i.e. the inverse of the previous checks

Emerging merge conflicts should be trivial to resolve, e.g. #2088.

2019-05-02 19:09 UTC, daschuer commented on src/main.cpp
>      // Support utf-8 for all translation strings. Not supported in Qt 5.
I think this is a left over comment.

2019-05-02 19:26 UTC, daschuer requested changes
Thank you, I have added some comment. This this is for master and #2088 for 2.2.1 IMHO we should merge the later first. 
I don't mind to merge this to 2.2.1 as well by the way.

2019-05-02 19:26 UTC, daschuer commented on src/preferences/dialog/dlgprefinterface.cpp
> -#if QT_VERSION < QT_VERSION_CHECK(5, 0, 0)
I think we can reuse parts of that later ... mmm what does this mean here.

2019-05-02 19:26 UTC, daschuer commented on src/waveform/vsyncthread.cpp
>      glw->swapBuffers();
This melds down to one glw->swapBuffers();
It is also part of https://github.com/mixxxdj/mixxx/pull/2088 waiting for merge. 
Can we merge this merge it first and revert this here?

2019-05-02 19:26 UTC, daschuer commented on src/waveform/vsyncthread.h
> -#if defined(__APPLE__)
the comment above applies also here.

2019-05-02 19:26 UTC, daschuer commented on src/waveform/waveformwidgetfactory.cpp
> -#if QT_VERSION >= QT_VERSION_CHECK(4, 7, 0)
conflicting with #2088

2019-05-02 19:49 UTC, uklotzde commented
I will rebase this PR after merging #2088

2019-05-05 12:58 UTC, daschuer approved these changes

2019-05-05 12:59 UTC, daschuer commented
Thank you for taking care. LGTM

2019-05-05 12:59 UTC, merged