Add files via upload
mixxxdj/mixxx pull request #2104
Opened 2019-05-07 13:37 UTC by DJPhatso

Initial release of MIDI configuration files for Hercules DJControl Inpulse 200

2019-06-12 08:47 UTC, uklotzde commented
Ready for merge? Code is readable, Wiki page exists.

2019-10-23 13:49 UTC, Holzhaus requested changes

2019-10-23 13:49 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +//  - See how to preselect efffects for a rack
effects

2019-10-23 13:49 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +
IMHO you went a bit overboard with all that newlines throughout the script, but that's just a preference.

2019-10-23 13:49 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +    }
Why the curly brackets? Is there supposed to be some if condition that is missing?

2019-10-23 13:49 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +    }
same (brackets)

2019-10-23 13:49 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +DJCi200.scratchButtonStateDB = true;
A more descriptive name like `scratchButtonEnabledDA` would be nice.

2019-10-23 13:49 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +};
Please add a newline at end of file. Most editors do this automatically, which would pollute patch diffs later on. So better at it now ;-)

2019-10-23 13:49 UTC, Holzhaus commented on Hercules_DJControl_Inpulse_200.midi.xml
> +</MixxxMIDIPreset>
Please add a newline at the end of the file.

2019-10-23 13:49 UTC, Holzhaus commented on Hercules_DJControl_Inpulse_200.midi.xml
> +
These aren't comments but XML text nodes. Mixxx' mapping XML parser might currently allow this, but please use actual XML comments here (`<!-- foobar -->`).

2019-10-23 13:54 UTC, Be-ing commented
@Holzhaus thanks for jumping in here. @DJPhatso I apologize for putting off reviewing your pull requests (as well as some other controller mappings) for so long. I have some time now and will go through them. Feel free to leave a comment to remind us that you're waiting on a review if it's been a long time with no activity.

2019-10-23 14:24 UTC, DJPhatso commented
Hi guys,

You might want to hold off reviewing for the moment. Following all the changes and code cleanup made by @kerrickstaley for the DJControl Starlight mapping (which has been approved), I've just started applying the same changes to the Inpulse 200 & 300 mappings.

2020-01-15 14:02 UTC, DJPhatso commented
Mapping files for Hercules DJControl Inpulse 200

Changes to v1.2

Code cleanup.
Changes to v1.1

Fix seek-to-start and cue-master behavior.
Tweak scratch, seek, and bend behavior (User settigns).
Controller knob/slider values are queried on startup, so MIXXX is synced.
Fixed vinyl button behavior the first time it's pressed.



v1.0 : Original forum release

2020-01-20 22:10 UTC, Holzhaus commented
Hi, can you rebase on 2.2? This could also be part of the 2.2.4 release.

2020-06-20 00:44 UTC, Holzhaus requested changes

2020-06-20 00:44 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +////////////////////////////////////////////////////////////////////////
Please remove the JSHint config, this conflicts with eslint that we're using now.

2020-06-20 00:44 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +//function DJCi200() {}
Please remove this line

2020-06-20 00:44 UTC, Holzhaus commented on Hercules-DJControl-Inpulse-200-script.js
> +
I think a single newline suffices here (and also in other parts of the mapping).

2020-06-22 15:12 UTC, DJPhatso commented
I thought I had closed this one already. 
#2542 was started and completed and already been merged.

2020-06-22 15:12 UTC, closed without merging