Fix battery tooltip text when minutesLeft is unknown
mixxxdj/mixxx pull request #2160
Opened 2019-06-12 12:56 UTC by rrrapha

Currently, the tooltip says "Time until charged: 0" or "Time left: 0" when the time is actually unknown.

The change makes all versions of the util return `-1` if `minutesLeft` is unknown.
In src/widget/wbattery.cpp, we have:
```
if (minutesLeft == -1) {
    setBaseTooltip(tr("Time until charged unknown."));
}
```

(minutesLeft can be 0 if the time is less than an minute)

Note that upower returns `0` for unknown:
https://upower.freedesktop.org/docs/Device.html#Device:TimeToEmpty
Windows uses `-1`:
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/ns-winbase-_system_power_status
On OSX, the property is optional and not set when unknown (i guess).

2019-06-13 20:02 UTC, daschuer requested changes
Thank you for the changes. It looks already good for me. 
I have left some some minor comments to improve the code quality. They apply in the same way to the code of all OSs.

2019-06-15 10:59 UTC, rrrapha commented on src/util/battery/batterywindows.cpp
> +    m_iMinutesLeft = -1;
Can we do this later, in a separate pull request?
Fixing this correctly for all OSs is a big change..

2019-06-15 11:10 UTC, rrrapha commented on src/util/battery/batterywindows.cpp
> +    int seconds_left;
done

2019-06-15 11:11 UTC, rrrapha commented on src/util/battery/batterymac.cpp
> +    m_iMinutesLeft = -1;
I've done this in the latest commit (I hope I didn't misunderstand ;)

2019-06-15 12:02 UTC, daschuer commented on src/util/battery/batterywindows.cpp
> +    m_iMinutesLeft = -1;
OK.

2019-06-15 12:02 UTC, daschuer approved these changes

2019-06-15 12:03 UTC, merged