Fix import of relative file paths from playlists
mixxxdj/mixxx pull request #2203
Opened 2019-07-14 14:41 UTC by uklotzde

https://bugs.launchpad.net/mixxx/+bug/1836243

Tests added and updated.

2019-07-22 06:07 UTC, uklotzde commented
No interest in getting reported bugs fixed??

2019-07-22 17:18 UTC, daschuer requested changes
Ups, this was fallen off my priority list.

2019-07-22 22:05 UTC, uklotzde commented on src/library/parser.cpp
> +    auto filePath = QString(playlistEntry).replace('\\', '/');
Out of the scope of this PR. I won't change any file path parsing functions.

2019-07-22 22:10 UTC, daschuer commented on src/library/parser.cpp
> +    auto filePath = QString(playlistEntry).replace('\\', '/');
OK.

2019-07-22 22:49 UTC, uklotzde commented on src/library/parser.cpp
> +std::pair<TrackFile, bool> Parser::playlistEntryToTrackFile(
I found a simpler solution that doesn't intermingle different aspects.

2019-07-22 23:44 UTC, Be-ing commented
Does this affect 2.2?

2019-07-23 05:27 UTC, uklotzde commented
It affects 2.2. But it would require a backport and I'm not keen on doing this twice for a functionality that I personally don't need. Another reason for aiming to release 2.3.0 of only to prevent exhausting contributors ;)

2019-07-23 06:33 UTC, daschuer commented
LGTM, and successfully tested. Thank you.

2019-07-23 06:33 UTC, merged