Initialize the global thread pool only once on application startup
mixxxdj/mixxx pull request #2222
Opened 2019-08-06 06:18 UTC by uklotzde

Found this bad practice while reviewing PR #2119. The custom reconfiguration code needs to be removed from PR #2119, too!

The global thread pool should work as expected even when using only 1 worker thread. Those threads are independent of the main thread and they are not expected to block each other if one doesn't introduce any deadlock or livelock situations.

2019-08-06 06:47 UTC, daschuer requested changes
Did you verify the comment about virtual box? Does it still work, set to 1?
I guess the related comment is still valid and should be kept.

If there is simply no thread in that pool in this case how can it work anyway?
I think the thread pool is used to limit the number of idle thread as well. See:
https://doc.qt.io/qt-5/qthreadpool.html#releaseThread

Do all thread pool use release idleThreads?

I think we have a deeper conceptual issue here. Can we fix this by setting a minimum of four?

2019-08-06 20:12 UTC, uklotzde commented
No issues when setting explicitly to 1. The old comment doesn't make any sense to me.

2019-08-06 20:13 UTC, uklotzde commented
The behavior should be independent of the physical number of cores. That abstraction is handled by the OS.

2019-08-06 20:28 UTC, uklotzde commented
Threads are temporarily borrowed from the pool by `QtConcurrent::run()`. Ensuring that the scheduled functions finish timely and don't get stuck cannot be guaranteed by increasing the number of idle threads. This problem cannot be solved by any framework or wrapper.

2019-08-18 18:27 UTC, JosepMaJAZ commented
Indeed, looks like the comment mixed "processor threads" with "process threads". 

It mostly looks ok to me. I just don't know why you added that DEBUG_ASSERT.

2019-08-18 21:35 UTC, daschuer commented
See the description here: 
https://doc.qt.io/qt-5/qtconcurrent.html#run
https://doc.qt.io/qt-5/qthreadpool.html#details
https://doc.qt.io/qt-5/qthreadpool.html#start

The thread pool has nothing to do with the OS capability of creating threads. 
The issue is on windows where we have only processes, which are quite expensive to create. To get the same performance on Windows like on Linux, Qt creates a number of suspended threads for us. 
As I understand that they are working like semaphores or like a box with three cookies.

If you have only one cookie in the box and you call QtConcurrent::run() two times, the first function is executed and the second function is added on a queue  and executed when the first function is finished. 

If we now reduce the number of threads to 1 and we schedule a function that never returns, no other function is taken from the queue. Even if the thread with the function is suspended, now new function is scheduled, because the thread object is still in use with the function and not returned to the pool. 
It is stuck here: https://github.com/qt/qtbase/blob/53d62b8fcbb639bd625777c8f1c01764445fb1c4/src/corelib/thread/qthreadpool.cpp#L99

That's why I think removing QThreadPool::globalInstance()->setMaxThreadCount(4); can be a regression.

2019-08-18 21:46 UTC, uklotzde commented
If one thread never returns that would be a serious programming error, no matter how many threads are reserved.

Allocating many more threads than the number of cores could cause performance issues.

I'm tired of arguing and will insert in any number you tell me to do.

2019-08-18 21:48 UTC, uklotzde commented
The debug assert just verifies that the comment is actually valid and the assumptions are true.

2019-08-18 21:56 UTC, uklotzde commented
The Qt guys will have checked that their thread pool even works when only a single core is available. I trust them more to select sensible defaults for a wide variety of use cases than "Tobias has decided" in a situation I'm not able to verify. And I don't see any reason why our use case should be special. Do you?

2019-08-18 22:17 UTC, daschuer commented
> I'm tired of arguing and will insert in any number you tell me to do.

4

> If one thread never returns that would be a serious programming error, no matter how many threads are reserved.

This comment is a strong indicator for me that we have such an issue: 
https://github.com/mixxxdj/mixxx/blob/ae34b12b133af4fc9ea831355a00845638a5357e/src/library/rhythmbox/rhythmboxfeature.cpp#L121

Even without such an issue we have for example a thread for music brains lookup. If this is suspended waiting for a network timeout, no cover art can be read from the HD. 

Without a detailed review of the threading, I think we should not reduce the threads in the pool. 
Increasing it to the number of cores is OK though. 

> The Qt guys will have checked that their thread pool even works when only a single core is available. 

I trust them as well, the tread pool will work reliable. We have the issue that we use the same thread pool everywhere and on a single core a single function that is suspended for some reason will suspend the whole thread pool here https://github.com/qt/qtbase/blob/53d62b8fcbb639bd625777c8f1c01764445fb1c4/src/corelib/thread/qthreadpool.cpp#L99

> I trust them more to select sensible defaults for a wide variety of use cases than "Tobias has decided" in a situation I'm not able to verify. And I don't see any reason why our use case should be special. Do you?

Yes, the global thread pool creates a unwanted looking across all modules using the global thread pool.
The number 4 lints the problem a bit. But I must admit it is also only a ugly workaround. The root issue needs to be solved one day. Maybe individual thread pools for every feature. ... This will have a performance overhead of creating a lot more idle threads on start-up which are full weight processes under windows though ...

2019-08-19 06:25 UTC, daschuer requested changes

2019-08-19 06:25 UTC, daschuer commented on src/mixxxapplication.cpp
> +    QThreadPool::globalInstance().setMaxThreadCount(
QThreadPool::globalInstance()->setMaxThreadCount()

2019-08-19 15:07 UTC, daschuer approved these changes

2019-08-19 15:08 UTC, daschuer commented
LGTM. Thank you. A good step in a direction to improve the situation one day.

2019-08-19 15:08 UTC, merged