Analysis: Adjust audio stream length/range if inaccurate or on errors
mixxxdj/mixxx pull request #2252
Opened 2019-08-31 15:05 UTC by uklotzde

An inaccurate (too long) audio stream length is not uncommon, especially when decoding MP3 with FFmpeg. This also happens when decoding corrupt files.

We already adjust the readable length in `CachingReaderWorker`, but this is insufficient! It has to be done directly in `AudioSource`. Otherwise separate consumers of audio data like the analysis that directly access `AudioSource` don't benefit from this adjustment and error handling.

I detected this issue when trying to fix an analysis bug that caused a warning and skipped the final, partial chunk of data. This is fixed by the second commit, taking the now correctly adjusted audio source length into account.

2019-09-01 12:21 UTC, daschuer commented
I have not digged deeply into this, but I am afraid we have now a race condition, because different threads are write accessing m_frameIndexRange. Can this happen?

2019-09-01 12:22 UTC, daschuer reviewed
.

2019-09-01 12:22 UTC, daschuer requested changes
.

2019-09-01 12:24 UTC, uklotzde commented
No race conditions. Each AudioSource instance is always accessed from a single thread only. Remember that all our decoders are not designed to be thread safe!

2019-09-16 06:41 UTC, uklotzde commented
Rebase on master to resolve merge conflicts.

2019-09-22 09:05 UTC, uklotzde commented
@daschuer I don't see any meaningful comments why this has been marked as *rejected*?

2019-10-04 22:40 UTC, daschuer requested changes

2019-10-04 22:40 UTC, daschuer commented on src/analyzer/analyzerthread.cpp
> +            // Only the final chunk should be incomplete
Is this comment correct? I think not, because even the final chunk is clammed by the total length.

2019-10-04 22:40 UTC, daschuer commented on src/engine/cachingreader/cachingreaderworker.cpp
> -    m_readableFrameIndexRange = mixxx::IndexRange();
Why can we still remove this? Maybe we cannot anymore because of a new assertion the cachingreader.c (not verified)

2019-10-04 22:40 UTC, daschuer commented on src/sources/audiosource.cpp
> +        return readable;
Can we  still distinguish a encoding issue from metadata issues? The calling code expect that, but I do not understand how.

2019-10-05 11:21 UTC, uklotzde commented
@daschuer Very helpful input! The code has hopefully become simpler and more robust now.

2019-10-05 19:17 UTC, uklotzde commented
I have re-tested with my collection of corrupt files, also switching between different decoders (FFmpeg and others).

Now all debug assertions are fixed and Mixxx emits silence after the first decoding errors as expected. When seeking back into the valid part of those files playback continues without hiccups.

2019-10-08 05:12 UTC, daschuer commented
Thank you. Looks and works good.

2019-10-08 05:13 UTC, merged

2019-10-08 05:18 UTC, daschuer commented
It could be interesting to play a file, that is just written to HD. Currently playback is stopped at one point. This can be useful to implement a buffered Aux input. Can you estimate how hard this would be?