Track metadata: Minor fixes
mixxxdj/mixxx pull request #2270
Opened 2019-09-07 10:20 UTC by uklotzde

The next tiny steps to catch up with my aoide-related extensions and fixes, more to follow:

**ID3v2**
Restrict parsing of ID3v2 tags to version 2.3 and 2.4. We are not able to support version 2.2 that uses different character encodings and frames. This check was previously missing and could cause unexpected behavior. In this case, only the common default tags like _artist_, _title_, ... will be parsed.

**Missing files**
Missing files triggered a debug assertion when trying to write modified metadata. Fixed.

2019-09-15 22:05 UTC, daschuer requested changes

2019-09-15 22:25 UTC, uklotzde commented on src/track/trackmetadatataglib.cpp
> +                                     .toLatin1();
QString: The whole log message is enclosed in double quotes

2019-09-15 23:52 UTC, daschuer commented on src/track/trackmetadatataglib.cpp
> +                                     .toLatin1();
The Latin1 sting is immediately converted to QString() in QDebug

2019-09-16 17:29 UTC, uklotzde commented on src/track/trackmetadatataglib.cpp
> +        return; // abort
Thanks for the hint about the regression. It turns out that we are at least able to support importing/exporting some basic tags for ID3v2.2 through TagLib. Only extended information in text frames is excluded.

2019-09-16 17:30 UTC, uklotzde commented on src/track/trackmetadatataglib.cpp
> +                                     .toLatin1();
QDebug::noquote() does the trick

2019-09-16 17:31 UTC, uklotzde commented on src/track/trackmetadatataglib.cpp
> +bool checkID3v2HeaderVersion(const TagLib::ID3v2::Header& header) {
The function name should not reveal or repeat internal details. I've added comments, links to references, and more informative logging messages.

2019-09-17 09:10 UTC, daschuer commented
Thank you. LGTM

2019-09-17 09:10 UTC, merged