[WiP - aoide Prerequisite] Extension points for external library sync
mixxxdj/mixxx pull request #2285
Opened 2019-09-17 15:13 UTC by uklotzde

- Moves all functions that are required for synchronizing music libraries up into `Library`, both functions and slots. Comments indicate where new code will be added.
- Changes some parameters if required, e.g. from `TrackId` to `TrackRef`
- `TrackDAO::databaseTracksMoved` has been replaced by `TrackDAO::databaseTracksReplaced` with slightly different and more useful parameters. Please don't start discussing the usage of `QPair`, that's just a negligible detail ;)

2019-09-20 18:12 UTC, daschuer commented
Did you also consider online Libraries like Spotify as ExteralTrackCollection?

2019-09-20 20:41 UTC, daschuer requested changes
Some comments. Thank you for the work.

2019-09-20 20:41 UTC, daschuer commented on src/library/library.cpp
> +    if (!m_externalTrackCollections.isEmpty()) {
This can also become  an early exit.

2019-09-20 22:27 UTC, uklotzde commented on src/library/dao/trackdao.cpp
> +        stmt = stmt.arg(idList.join(","));
This follows the exact same pattern that is used everywhere else in this file for id lists in SQL queries. I will not change this to keep it consistent.

2019-09-20 22:28 UTC, uklotzde commented on src/library/library.cpp
> +                    externalTrackCollection->saveTrack(*pTrack, ExternalTrackCollection::ChangeHint::Modified);
Only by convention. The external track collection is not supposed to touch any files that are used by Mixxx. Period.

2019-09-20 22:38 UTC, uklotzde commented
> Did you also consider online Libraries like Spotify as ExteralTrackCollection?

`ExternalTrackCollection` only contains functions that propagate changes **from** Mixxx **to** the external collection, i.e. write-only. This is a different use case. Documentation is still missing, will follow eventually.

The interface is designed to cover only my use case and to keep the changes to a minimum. It is an adapter that serves as an *anti-corruption layer* between the new and the old world.  I'm not able to repair the internal track management that is wildly scattered among `Library`, `TrackCollection`, `TrackDAO`, and the `LibraryScanner` without clear responsibilities and layers of abstractions. The goal was to make the integration work without breaking anything.

2019-09-20 23:05 UTC, uklotzde commented on src/library/trackcollection.cpp
> +    m_trackDao.databaseTracksReplaced(std::move(replacedTrackRefs));
I agree, this needs to be reconsidered. I just adapted the code technically to keep it working.

`TrackCollection` delegates back to `TrackDAO` not for updating the database but just to dispatch some notifications. It somehow works, but I refuse to touch this brittle design.

2019-09-28 22:30 UTC, daschuer commented
OK, Thank you. LGTM

2019-09-28 22:31 UTC, merged