Fix ConfigObject warnings and issues
mixxxdj/mixxx pull request #2324
Opened 2019-10-19 11:12 UTC by uklotzde

- Fix GCC 9 warnings
- Inline pass-through constructors
- Add virtual destructor to ConfigValue
- Define both operator == and !=
- Delete unused functions
- Add TODO to fix the error-prone design of ConfigValueKbd

2019-10-19 13:23 UTC, Be-ing commented
I have changed the target branch to master. Unless there is some bug that impacts users that you have identified, I do not think this warrants changing the stable branch. Cleaning up code is not a good reason to risk regressions on a stable branch.

2019-10-20 08:17 UTC, uklotzde commented
@Be-ing Agreed.

2019-10-21 19:13 UTC, daschuer commented on src/preferences/configobject.cpp
> +ConfigValueKbd::ConfigValueKbd(QKeySequence keys)
QKeySequence

2019-10-21 20:54 UTC, daschuer requested changes

2019-10-22 15:27 UTC, daschuer commented
LGTM. Thank you. The build errors are unrelated.

2019-10-22 15:28 UTC, merged