Fix relocating moved tracks in external collections
mixxxdj/mixxx pull request #2404
Opened 2019-12-17 22:31 UTC by uklotzde

The update of moved tracks in external collections didn't work as expected. Only the aoide was affected affected. The *old id* of the old track and the *new location* of the new track need to be merged into a new `TrackRef` that identifies the relocated track.

This bug was mainly caused by using a `QPair` instead of a custom class. The class `RelocatedTrack` now encapsulates all the information with appropriate accessor functions and lots of assertions to check consistency. I also added checks to verify that Track::getTrackAdded() is valid for tracks in the library. This was the first indicator for the wrong behavior.

Note 1: Relinking library directories in Mixxx still requires to rescan the library manually. This should be fixed independently. Another bug is that the track table view is not updated with the new location after rescanning. This might also affect BaseTrackCache, I didn't check.

Note 2: During testing duplicate tracks appeared in aoide. This is a different issue that I need to check.

2020-01-12 22:12 UTC, uklotzde commented
Rebased on master since no comments received and only a single commit.

2020-02-04 21:12 UTC, daschuer requested changes
I had expected that after using Relink in Library preferences all tracks will come back without scanning the library. This is not the case. Is this a bug? 

* create folder 1 with one track
* start Mixxx add the folder in the library preferences 
* Play the track 
* quit Mixxx 
* rename the folder to 2
* start Mixxx go to the library preferences  
* Relink folder 1 to 2 
* try to play the track 
* ... Missing 
* Rescan Library track is back

2020-02-04 22:00 UTC, uklotzde commented
> I had expected that after using Relink in Library preferences all tracks will come back without scanning the library. This is not the case. Is this a bug?
> 
>     * create folder 1 with one track
> 
>     * start Mixxx add the folder in the library preferences
> 
>     * Play the track
> 
>     * quit Mixxx
> 
>     * rename the folder to 2
> 
>     * start Mixxx go to the library preferences
> 
>     * Relink folder 1 to 2
> 
>     * try to play the track
> 
>     * ... Missing
> 
>     * Rescan Library track is back

This is a known bug that I discovered while fixing another bug. I was sure that I have already reported it, but I haven't found it yet. Out of scope, will not be fixed in this PR.

2020-02-05 20:39 UTC, uklotzde commented
> > I had expected that after using Relink in Library preferences all tracks will come back without scanning the library. This is not the case. Is this a bug?
> > ```
> > * create folder 1 with one track
> > 
> > * start Mixxx add the folder in the library preferences
> > 
> > * Play the track
> > 
> > * quit Mixxx
> > 
> > * rename the folder to 2
> > 
> > * start Mixxx go to the library preferences
> > 
> > * Relink folder 1 to 2
> > 
> > * try to play the track
> > 
> > * ... Missing
> > 
> > * Rescan Library track is back
> > ```
> 
> This is a known bug that I discovered while fixing another bug. I was sure that I have already reported it, but I haven't found it yet. Out of scope, will not be fixed in this PR.

Ups, I mentioned it right here in this PR, see above *Note 1* :see_no_evil: We should create a bug report.

2020-02-07 17:56 UTC, uklotzde commented
Rescan after relinking: https://bugs.launchpad.net/mixxx/+bug/1862396

2020-02-08 09:19 UTC, uklotzde commented on src/library/relocatedtrack.h
> +    TrackRef mergedTrackRef() const {
updatedTrackRef() might better reflect the naming at the call side?

2020-02-11 20:08 UTC, daschuer approved these changes

2020-02-11 20:08 UTC, daschuer commented
LGTM, Thank you.

2020-02-11 20:08 UTC, merged