Store default recording format after "Resore Defaults", fixing lp1857806
mixxxdj/mixxx pull request #2414
Opened 2019-12-29 11:53 UTC by daschuer

2019-12-29 18:45 UTC, daschuer commented
strange: clang fails with (master merged, rebased later) 
```
In file included from src/sources/soundsourcewv.cpp:4:
src/sources/soundsourcewv.h:9:14: error: typedef redefinition with different types ('void' vs 'struct WavpackContext')
typedef void WavpackContext;
             ^
/usr/local/include/wavpack/wavpack.h:283:31: note: previous definition is here
typedef struct WavpackContext WavpackContext;
```

2019-12-29 19:07 UTC, daschuer commented
possible fix is here: https://github.com/mixxxdj/mixxx/pull/2416

2020-01-06 12:48 UTC, uklotzde commented
Please add an entry to the change log to closely keep track of bug fixes.

2020-01-08 20:43 UTC, daschuer commented
Done.

2020-01-12 22:08 UTC, uklotzde requested changes

2020-01-12 22:08 UTC, uklotzde commented on CHANGELOG
> +* Store default recording format after "Resore Defaults" lp:1857806 #2414
typo

2020-01-12 22:43 UTC, daschuer commented
Ups .. I have amended the last commit.

2020-01-17 22:53 UTC, daschuer commented
merge?

2020-02-03 21:24 UTC, uklotzde commented
Sorry for the delay. We have far too many open PRs.

LGTM. Thank you.

2020-02-03 21:26 UTC, merged