Fix assertion when quantize a cue point near the end
mixxxdj/mixxx pull request #2421
Opened 2020-01-01 20:02 UTC by daschuer

This fixes the false positive assertion:

```
Critical [Main]: DEBUG ASSERT: "cuePos <= total" in function double CueControl::quantizeCuePoint(double, CueControl::QuantizeMode) at /tmp/mixxx/src/engine/controls/cuecontrol.cpp:1641
```

2020-01-02 12:35 UTC, uklotzde requested changes
Just some typos

2020-01-02 12:35 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +    // Note: currentPos can be passed the end of the track, in the padded
type: "past"

2020-01-02 12:35 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +    // Note: closestBeat can be an interpolated beat passed the end of the track,
typo: "past"

2020-01-05 01:52 UTC, daschuer commented
Done, Thank you for review.

2020-01-05 10:09 UTC, Holzhaus commented on src/engine/controls/cuecontrol.cpp
> +    // Note: currentPos can be paset the end of the track, in the padded
```suggestion
    // Note: currentPos can be past the end of the track, in the padded
```

2020-01-05 21:08 UTC, daschuer commented
Ups, it was probably too late yesterday. I have amend the last faulty commit .

2020-01-06 12:27 UTC, uklotzde commented
LGTM. Thanks for fixing this issue.

2020-01-06 12:29 UTC, merged