Soundless joyMIDI: Mapping for joyMIDI
mixxxdj/mixxx pull request #2425
Opened 2020-01-06 06:25 UTC by bcc6

Hi, this mapping support portable MIDI controller joyMIDI. Thanks

2020-01-14 16:53 UTC, Holzhaus commented
Hi, is this mapping using new features that are not present in the 2.2? If not, can you rebase on 2.2?

2020-01-15 08:26 UTC, bcc6 commented
> Hi, is this mapping using new features that are not present in the 2.2? If not, can you rebase on 2.2?

Already merge v2.2

2020-01-15 08:50 UTC, uklotzde commented
Merging 2.2 is the wrong direction. Please rebase your commits *onto* 2.2 instead.

2020-01-15 10:31 UTC, bcc6 commented
Sorry, can tell me how to do.

2020-01-15 10:39 UTC, Holzhaus commented
Just run this command:
```bash
$ git rebase -i 2.2
```

This will then open a text editor. Delete all lines *except* the one that says:

```
pick <commitid> Soundless joyMIDI: Mapping for joyMIDI
```

Then save and close the file.

2020-01-15 10:47 UTC, uklotzde commented
Or use `git rebase -onto`. The result must only contain your own commits, not anything else.

2020-01-15 13:51 UTC, bcc6 commented
Finally, done.

2020-01-15 16:17 UTC, uklotzde commented
But now the CI builds seem to be out of sync, even though the corresponding configuration files have not been modified in any of the commits. Not sure if we need to close this PR and open a new one?

2020-01-16 01:25 UTC, bcc6 commented
Any suggestion ?

2020-01-16 01:32 UTC, Holzhaus commented
I don't think a new PR is necessary. The only relevant "CI" for controller mappings is the CodeFactor linter, and I can just run eslint locally instead.

I'll review this mapping tomorrow.

2020-01-16 18:02 UTC, Holzhaus requested changes
Thanks for contributing a mapping for this unusual little controller! I had a look at the Wiki page and the mapping looks well thought out and should make good use of the buttons available.

As I don't have the controller myself, I can't test it, but I trust that you tested the mapping thorougly. I found few minor issues, but apart from that the mapping looks good to me.

@Be-ing Do you also want to take a look?

2020-01-16 18:02 UTC, Holzhaus commented on res/controllers/Soundless_joyMIDI_scripts.js
> +        }
No need for an else case here. You could even reduce the indentation level, by using something like this:

```js
if (value <= 0) {
    // release
    return;
}
```

2020-01-16 18:02 UTC, Holzhaus commented on res/controllers/Soundless_joyMIDI_scripts.js
> +                        engine.beginTimer(1000, "joyMIDI.syncTimerHandler('" + group + "')", true);
Please pass a function as second argument, not a string.

2020-01-17 09:40 UTC, bcc6 commented on res/controllers/Soundless_joyMIDI_scripts.js
> +        engine.beginTimer(scratchDisableTime, "joyMIDI.ScratchTimerHandler('" +deck+ "','" +group+ "')", true);
Thanks for reply. 
Refer to the following links, these examples use string :
https://www.mixxx.org/wiki/doku.php/script_timers
https://github.com/mixxxdj/mixxx/blob/master/res/controllers/Hercules-DJControl-Compact-scripts.js  (Line 70)
Don't know what do u mean that using an actual function.

2020-01-17 10:31 UTC, Holzhaus commented on res/controllers/Soundless_joyMIDI_scripts.js
> +        engine.beginTimer(scratchDisableTime, "joyMIDI.ScratchTimerHandler('" +deck+ "','" +group+ "')", true);
Here's an example:
https://github.com/mixxxdj/mixxx/blob/master/res/controllers/Roland_DJ-505-scripts.js#L186

2020-01-19 23:59 UTC, Holzhaus requested changes
Thanks! We're almost there. There are still some eslint issues that are fixed by https://github.com/bcc6/mixxx/pull/1. Please merge the PR and fix the description in the XML, then we can merge IMO.

2020-01-19 23:59 UTC, Holzhaus commented on res/controllers/Soundless_joyMIDI.midi.xml
> +        <description>Soundless protable MIDI controller 2020-01-17</description>
```suggestion
        <description>Soundless Portable MIDI Controller</description>
```

2020-01-20 19:14 UTC, Holzhaus commented
@bcc6 Thanks!

2020-01-20 19:14 UTC, merged