Prevent pushbuttons with 'blocked' controls getting stuck pressed
mixxxdj/mixxx pull request #2460
Opened 2020-01-21 10:31 UTC by ronso0

When a disallowed click is performed, like enabling Passthrough, VinylControl or TalkOver with no respective device set up, the button release is not registered because modal message boxes block interaction with Mixxx main window, and the button is 'pressed' only after the message is closed and remains so. Noticed with Shade (colored button) and LateNight (3D effect).
* click Passthrough button
* `group,passthrough` is set `1`
* message pops up, blocks release event, `group,passthrough` is forced `0`
* close popup
* button is set 'pressed', no further control update

Solution:
* set the 'pressed' property before setting any control (which could enforce a popup)
* allow `onConnectedControlChanged` to update the 'pressed' property also for pushbutton with more than one state 

I didn't discover a regression, yet, so I'm curious why this limitation was installed in the first place.?

Maybe we could also use a special pushbutton widget or a different control connection for those buttons that checks if setting the control is allowed to be toggled before actually doing it, which would also prevent disallowed Passthrough stopping playing decks).
But IMO the fix proposed here is the easiest way to resolve this issue.

2020-01-21 10:32 UTC, ronso0 commented on src/widget/wpushbutton.cpp
> +    m_bPressed = (dValue == 1.0);
>= 1 ?

2020-02-02 17:24 UTC, daschuer requested changes
This has the issue, when I press the play button and hold it until the track is at end, the m_bPressed state is lost. This does not happen with the master build

2020-02-02 17:24 UTC, daschuer commented on src/widget/wpushbutton.cpp
> -    if (m_iNoStates == 1) {
This code is only a workaround for one state buttons where the pressed state matches the value.

2020-02-02 21:21 UTC, daschuer commented
It looks like this is a known bug: 
https://bugreports.qt.io/browse/QTBUG-50051

2020-02-02 21:25 UTC, daschuer commented
I have found a alternative solution here: 
https://github.com/ronso0/mixxx/pull/6

2020-02-05 07:28 UTC, daschuer commented
Can one confirm that this is working on Windows as well?
I am afraid to ask for MacOs ..:-/ to not block this PR.

2020-02-05 07:29 UTC, daschuer commented
Ci issues are unrelated.

2020-03-04 23:34 UTC, daschuer commented
Let's merge this. We can test it during alpha and beta phase on the other OSs.

2020-03-04 23:35 UTC, merged