lp1861431: Fix debug assertion for invalid crate names
mixxxdj/mixxx pull request #2477
Opened 2020-02-01 09:45 UTC by uklotzde

- Fixed debug assertion for existing, invalid crate names in the database, i.e. with leading/trailing whitespaces
- Simplified the code for editing crate name (...won't fix the duplication)

2020-02-01 21:06 UTC, daschuer commented
This conflicts locally. 
KONFLIKT (Inhalt): Merge-Konflikt in src/util/db/dbnamedentity.h
I have no idea why github is still satisfied.

2020-02-01 22:05 UTC, daschuer requested changes
Thank you. I have added some comments.

2020-02-01 22:05 UTC, daschuer commented on src/util/db/dbnamedentity.h
> +inline QString parseEntityName(const QString& name) {
i do not understand the function name. Can't we directly use trimmed()

2020-02-02 14:08 UTC, uklotzde commented
CI failures are unrelated

2020-02-02 14:39 UTC, daschuer approved these changes

2020-02-02 14:40 UTC, daschuer commented
Thank you. LGTM.

2020-02-02 14:40 UTC, merged