Rekordbox RGB hotcue colors
mixxxdj/mixxx pull request #2555
Opened 2020-03-17 00:20 UTC by ehendrikd

Stores Rekordbox RGB hotcue colors. Following on from #2520

2020-03-17 07:03 UTC, Holzhaus requested changes

2020-03-17 07:03 UTC, Holzhaus commented on src/library/rekordbox/rekordboxfeature.cpp
> +    pCue->setColor(*mixxx::RgbColor::fromQColor(QColor(colorRed, colorGreen, colorBlue)));
pCue->setColor(mixxx::RgbColor(qRgb(colorRed, colorGreen, colorBlue)));

2020-03-19 12:07 UTC, Holzhaus commented on src/library/rekordbox/rekordboxfeature.cpp
>      int colorBlue;
Can these members become a single `mixxx::RgbColor` or `mixxx::RgbColor::optional`?

2020-03-19 23:21 UTC, Holzhaus requested changes

2020-03-19 23:21 UTC, Holzhaus commented on src/library/rekordbox/rekordboxfeature.cpp
> +    if (color != mixxx::RgbColor::nullopt()) {
```suggestion
    if (color) {
```

2020-03-20 13:08 UTC, uklotzde commented
@Holzhaus LGTM

2020-03-20 13:19 UTC, Holzhaus commented
Alright, let's merge this :D Thank you very much, @ehendrikd!

2020-03-20 13:19 UTC, merged