Fix race-condition in multi-threaded analysis
mixxxdj/mixxx pull request #2763
Opened 2020-05-08 14:21 UTC by uklotzde

This fixes a race condition in the multi-threaded analysis where some worker threads might get stuck forever by not resuming after they received a next track for analysis.

The public method was lacking a mutex lock!

I found this by adding more detailed log messages. Those changes could later be merged to master.

2020-05-08 16:37 UTC, uklotzde commented
Ready. Worker thread needs to be woken up unconditionally to avoid race conditions.

2020-05-08 19:44 UTC, uklotzde commented
Force pushed a type fix in comment

2020-05-08 20:09 UTC, daschuer commented
Unfortunately, I am not able to wrap my head around it in a short time. 

It might work now, but I would prefer a fix that can be easily followed.  
The source of confusion it the the combined function of m_suspend. 
It transports the suspend and the wake command and holds the state in the same time. 
I think it would be better two have two or three values, one for each function.

Do you think it will work to improve the situation. I am unsure. 
If you like I can poke around to verify my idea.

2020-05-08 21:09 UTC, uklotzde commented
This is easiest fix I can come up with.

m_suspend is just a simple flag. The only issue was the race condition between notify_on() and wait().

1. Worker thread invokes m_sleepWaitCond.wait()
2. Other thread invokes m_sleepWaitCond.notify_one(), but no thread is waiting
3. Worker thread blocks on m_sleepWaitCond forever and doesn't receive the notification

This is now documented in WorkerThread::wake().

2020-05-08 21:10 UTC, uklotzde commented
The logs clearly showed that one thread got assigned a track for analysis but then never started the analysis and got stuck.

2020-05-08 21:14 UTC, uklotzde commented
If anyone has a better idea, feel free to rewrite everything. I hope I don't need to touch this again, just fixing my own mistakes.

2020-05-09 08:55 UTC, uklotzde commented
The compare_exchange_strong() became obsolete and can be replaced by simply calling store(). The current value doesn't matter and the worker thread only reads this value.

2020-05-09 22:04 UTC, Be-ing commented
This is an annoying bug, but no need to hold back the beta release for it.

2020-05-09 23:47 UTC, daschuer requested changes
It took me a while to understand that there are two types of suspend. 
On is an external suspend call, the other is the FetchWorkResult::Suspend.
It would be nice to not call the suspend() function from intern and set the flag directly to make it obvious that there are two control flows setting the suspend flag().  

The next source of confusion is the overloaded sleepWhileSuspended() function, 
I think it would helpful to give them different names. something like: 
sleepIfSuspended() 
sleepNow(); 
or such. 

I assume that the same thread is in charge to call suspend()  an resume() from external. 

The internal suspend() call destroys this deterministic. 

Let's assume a FetchWorkResult::Suspend is scheduled as a final task.
Than the scheduler receives new tasks and calls resume() this sets immediately suspend to falls (was already false) than it calls wake() and sleeps until the FetchWorkResult::Suspend is found. 
This calls suspend() and sets suspend to true, falls asleap, and is waked by the waiting wake call. 
It falls immediately asleep again because suspend is still true. 
FetchWorkResult::Suspend wins. 
If FetchWorkResult::Suspend is found a bit earlier, resume () wins. 

Who should win?

2020-05-09 23:51 UTC, daschuer commented
Only WorkerThreadScheduler makes use of FetchWorkResult::Suspend;
Can we dispose it and use FetchWorkResult::Idle istead? 
Than the only one thread has write access to m_suspend.

2020-05-10 07:45 UTC, uklotzde commented on src/util/workerthread.cpp
> +    std::unique_lock<std::mutex> locked(m_sleepMutex);
The mutex is only  locked for a very short time.

2020-05-10 08:07 UTC, uklotzde commented
I have removed all the unused and potentially dangerous result options from tryFetchWorkItems()/FetchWorkResult.

2020-05-10 09:07 UTC, daschuer commented on src/util/workerthread.cpp
> +    std::unique_lock<std::mutex> locked(m_sleepMutex);
Ah, now I see, I was concerned about this lock 
https://github.com/mixxxdj/mixxx/blob/d0ca0e55b20b784d67fa7883ce580c16edb5e529/src/util/workerthread.cpp#L141

2020-05-10 09:09 UTC, daschuer approved these changes

2020-05-10 09:10 UTC, daschuer commented
Much better, Thank you. LGTM, waiting for CI.

2020-05-10 10:30 UTC, merged