Fix crash in ControllerEngine::gracefulShutdown()
mixxxdj/mixxx pull request #2767
Opened 2020-05-09 11:21 UTC by uklotzde

This fixes crash caused by invalid iterator usage when shutting down Mixxx while a controller is connected.

But afterwards Mixxx still crashes when exiting the *Controller* thread:
```
Debug [Controller]: Deleting USB Bulk devices...
Debug [Controller]: Deleting HID devices...
[Thread 0x7ffec3fff700 (LWP 22012) exited]
malloc_consolidate(): invalid chunk size

Thread 34 "Controller" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffee2ffd700 (LWP 22006)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff3623895 in __GI_abort () at abort.c:79
#2  0x00007ffff367e8c7 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff378fe1d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff3685dec in malloc_printerr (str=str@entry=0x7ffff37920a0 "malloc_consolidate(): invalid chunk size") at malloc.c:5347
#4  0x00007ffff3686cb8 in malloc_consolidate (av=av@entry=0x7ffff37c19e0 <main_arena>) at malloc.c:4477
#5  0x00007ffff3687460 in _int_free (av=0x7ffff37c19e0 <main_arena>, p=0x17057f0, have_lock=<optimized out>) at malloc.c:4400
#6  0x00007ffff63fb5bb in magazine_cache_push_magazine () at /lib64/libglib-2.0.so.0
#7  0x00007ffff63fb6cf in private_thread_memory_cleanup () at /lib64/libglib-2.0.so.0
#8  0x00007ffff37d1251 in __nptl_deallocate_tsd () at pthread_create.c:301
#9  __nptl_deallocate_tsd () at pthread_create.c:250
#10 0x00007ffff37d1445 in start_thread (arg=<optimized out>) at pthread_create.c:488
#11 0x00007ffff36ff9d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

2020-05-09 21:37 UTC, daschuer requested changes
Thank you for the fix. 

Only one minor comment.

2020-05-09 21:37 UTC, daschuer commented on src/controllers/controllerengine.cpp
> +    for (auto it = m_controlCache.begin(); it != m_controlCache.end(); /*see loop body*/) {
Cpp has while loops fore situation where the iteration is done in the loop body.

2020-05-09 21:38 UTC, Be-ing commented
Is this a regression in 2.3? Does it also apply to the 2.2 branch? I have not noticed this bug.

2020-05-09 22:05 UTC, Be-ing commented
I cannot reproduce this bug, so I am removing the "beta blocker" tag. Of course we should still fix this promptly, but I don't think there's a need to keep pushing back the beta even further.

2020-05-10 08:09 UTC, uklotzde commented
The iteration was plain wrong already in 2.2. Not sure when this undefined behavior actually caused an error. It might depend on both the Qt and compiler version.

2020-05-10 08:19 UTC, uklotzde commented
Iterators become dangling after removing/erasing items:
https://doc.qt.io/qt-5/qhash-iterator.html

2020-05-10 08:56 UTC, daschuer approved these changes

2020-05-10 08:56 UTC, daschuer commented
LGTM, waiting for CI. Thank you.

2020-05-10 10:21 UTC, merged