Master sync: disable explicit mode
mixxxdj/mixxx pull request #2769
Opened 2020-05-09 17:18 UTC by ywwg

This restores the sync_master CO behavior to what it did in 2.2 so that users won't stumble onto explicit master mode. Since that mode still has a lot of bugs we don't want to expose it just yet.

2020-05-09 21:30 UTC, daschuer requested changes
Please rebase to 2.3

I thought this would be a small impact PR that only redirects the mapped control object to enable sync. 

This PR is quiet big, and required more testing. 

Did you consider, the proposed small impact fix?

2020-05-09 23:51 UTC, ywwg commented
rebased

2020-05-09 23:52 UTC, ywwg commented
oh hm lemme try again

2020-05-09 23:53 UTC, ywwg commented
ok good

2020-05-09 23:53 UTC, ywwg commented
this is a small patch, I'm not sure what you mean by big impact

2020-05-12 22:13 UTC, daschuer commented
> this is a small patch, I'm not sure what you mean by big impact

Yes, I can see now without the unintended master changes.

2020-05-12 22:14 UTC, daschuer approved these changes

2020-05-12 22:14 UTC, daschuer commented
LGTM, Thank you.

2020-05-12 22:14 UTC, merged