Rename scripts/ directory to tools/
mixxxdj/mixxx pull request #2778
Opened 2020-05-10 22:28 UTC by Holzhaus

We also have a "script" directory (without the "s"), which makes it confusing
and harder to select the correct directory with shell completion.

The "tools" name fits better, since the directory contains tools that are/were
helpful during mixxx development (these tools are all scripts - but that
is of secondary importance and also coincidence).

2020-05-10 22:29 UTC, Be-ing commented
Looks good to me. I'll wait to merge in case anyone objects.

2020-05-11 06:04 UTC, daschuer requested changes
Please remove the lp_to_github files before the renaming, to keep this PR small and get rid of some unused legacy.

2020-05-11 06:04 UTC, daschuer commented on tools/lp_to_github/community.txt
> +git bzr import lp:~ulatekh/mixxx/mingw
This one can be removed.

2020-05-12 11:02 UTC, Holzhaus commented on tools/lp_to_github/community.txt
> +git bzr import lp:~ulatekh/mixxx/mingw
Done.

2020-05-12 16:21 UTC, daschuer requested changes
https://github.com/Holzhaus/mixxx/blob/f3a15cb1358ae9b06dc3f8bd057f239bc8a7acdd/tools/generate_sample_functions.py#L54

Needs to point to the new path.

And also 
src/engine/channelmixer_autogen.cpp:L6
src/test/enginebuffertest.cpp:L17
src/test/signalpathtest.h:L141
src/util/sample_autogen.h:L5

2020-05-12 21:56 UTC, daschuer approved these changes

2020-05-12 21:56 UTC, daschuer commented
Thank you. LGTM.

2020-05-12 21:58 UTC, daschuer commented
We may argue if this is really a 2.3 thing. 
But since it does not effect the binary, I go ahead and merge it. 
In future let's target refactoring to master.

2020-05-12 21:58 UTC, merged