Mapping for Numark iDJ Live II
mixxxdj/mixxx pull request #2818
Opened 2020-05-24 16:46 UTC by nkorth

I wrote up a wiki page too: https://mixxx.org/wiki/doku.php/numark_idj_live_ii

Since I've never actually used another DJ controller, I'm not super confident about the scratch parameters. It feels reasonable to me, and I'm pretty sure I at least got the resolution right.

2020-05-25 10:11 UTC, Swiftb0y requested changes
Looks good so far, though I don't think the search accumulator behavior is a good feature. You could simplify the code drastically, if you instead you just speed up the jogwheel while in search mode instead of beatjumping.

2020-05-25 10:15 UTC, Swiftb0y commented
For future reference, you should not develop in the master branch but instead create a feature branch for your mapping and then develop within that.
Also make sure you linted the js:
https://www.mixxx.org/wiki/doku.php/contributing_mappings#automated_code_checking_linting

2020-05-25 15:22 UTC, nkorth commented on res/controllers/Numark iDJ Live II.midi.xml
> +<MixxxControllerPreset mixxxVersion="" schemaVersion="1">
Version 2.2.3. Does that mean I should put "2.2.3+" there, or no?

2020-05-25 15:28 UTC, nkorth commented
> I don't think the search accumulator behavior is a good feature.
Fair enough, it's just something I personally like. Do you have an example of a mapping I could imitate for a search mode? (I was looking at the Ion Discover DJ mapping, but I don't think it's a very good one. It just pitch bends when scratch mode is off, even when paused.)

2020-05-25 15:48 UTC, Be-ing commented
It is common for controller mappings to use shift + jog wheel turn to seek quickly.

2020-05-25 16:01 UTC, Be-ing commented
Could you map the sync button LED to `sync_enabled`?

2020-05-25 17:30 UTC, nkorth commented
Updated with more normal search mode

> Could you map the sync button LED to `sync_enabled`?

fixed

2020-06-05 11:37 UTC, Holzhaus commented
@nkorth Can you update the text about the sync LEDs on the wiki page?

Also, please rebase this PR on 2.2 or 2.3: https://mixxx.org/wiki/doku.php/using_git#targeting_another_base_branch
Otherwise it will only be included in the 2.4 release, so you'd have to wait at least until end of this year...

2020-06-07 06:50 UTC, nkorth commented
Github pull requests confuse me. I rebased it in [a new branch here](https://github.com/nkorth/mixxx/tree/idjl2_controller), do I have to create a whole new pull request in order to use that branch? Do I have to clobber nkorth:master with the contents of mixxx:2.3?

2020-06-07 16:05 UTC, Holzhaus commented
> Github pull requests confuse me. I rebased it in [a new branch here](https://github.com/nkorth/mixxx/tree/idjl2_controller), do I have to create a whole new pull request in order to use that branch? Do I have to clobber nkorth:master with the contents of mixxx:2.3?

Generally, you should work in feature branches and never commit to master. Now that you already opened this PR and used your master branch for it, let's just continue using it and not open a new PR:
```bash
# Switch to the source branch for this PR
git checkout master
# Create a copy of the current branch for backup purposes
git branch -c idjl2-master-backup
# Set the state of the current branch to the rebased version
git reset --hard idjl2_controller
# Push the changes to this PR
git push -f origin master
```

2020-06-13 00:28 UTC, nkorth commented
Done.

2020-06-13 10:56 UTC, Holzhaus approved these changes
LGTM.

2020-06-13 17:46 UTC, Holzhaus commented
Before we merge your code into Mixxx, please sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ). In a nutshell, this gives us permission to distribute your code under the GPL as well as in the Mac App Store which has some terms incompatible with the GPL.

2020-06-13 18:09 UTC, Holzhaus commented
Also, can you add an entry to CHANGELOG.md?

2020-06-14 18:00 UTC, nkorth commented
```
qt.qpa.screen: QXcbConnection: Could not connect to display :99.0
Could not connect to any X display.
```
I assume this is a flaky test and not the result of my change?

2020-06-19 23:02 UTC, Holzhaus commented
LGTM, thank you!

2020-06-19 23:03 UTC, merged