New Behringer-CMD-PL-1 controller
mixxxdj/mixxx pull request #2842
Opened 2020-06-04 03:36 UTC by yledoare

2020-06-04 13:02 UTC, Holzhaus requested changes
Thank you for contributing!

Would you please [sign our contributor agreement form](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) for this and all future contributions?

Please add a wiki page for this controller and document the mapping there. That will allow us to review this properly. Also, please rebase onto the 2.2 or 2.3 branch and change the target branch of this PR to that branch: https://mixxx.org/wiki/doku.php/using_git#targeting_another_base_branch

2020-06-04 13:02 UTC, Holzhaus commented on res/controllers/Behringer CMD PL-1.midi.xml
> +            <control> <group>[Channel1]</group> <key>play</key> <description>Play</description> <status>0x90</status> <midino>0x23</midino> <options> <switch/> </options> </control>
Please split these lines and indent them properly, like this:

```suggestion
            <control>
                <group>[Channel1]</group>
                <key>play</key>
                <description>Play</description>
                <status>0x90</status>
                <midino>0x23</midino>
                <options>
                    <switch/>
                </options>
            </control>
```

2020-09-21 20:11 UTC, Holzhaus commented
Ping @yledoare.

2020-09-22 05:34 UTC, yledoare commented
> Ping @yledoare.

Hello @Holzhaus , I will try to do it this week !

2020-10-03 08:19 UTC, yledoare commented
Done : https://github.com/mixxxdj/mixxx/pull/3147

2020-10-03 09:07 UTC, closed without merging