Fix line-length tool not coercing to string correctly
mixxxdj/mixxx pull request #2856
Opened 2020-06-10 18:12 UTC by ywwg

Fixes issues with errors like 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 7492120: invalid start byte`

2020-06-11 00:35 UTC, daschuer requested changes
Unfortunately this does not fully fix the issue. 
str()  prints the souce code representation of a byte array. 
In https://github.com/ywwg/mixxx/pull/8 I have changed this to utf8 encoding with the replacement character �
The original issue itself is from a library using the latin1 ©

2020-06-11 02:19 UTC, ywwg commented
merged replacement change

2020-06-11 02:19 UTC, ywwg commented
we should backport this to HEAD as well

2020-06-12 07:38 UTC, daschuer approved these changes

2020-06-12 07:38 UTC, merged