EngineMaster: mix mics into master before processing headphones
mixxxdj/mixxx pull request #2968
Opened 2020-07-26 20:22 UTC by Be-ing

Before, using the master/PFL crossfade knob to listen to the
master mix on the headphone output would not include the
microphones.

Reported on the forum:
https://mixxx.discourse.group/t/4-channel-soundcard-master-on-headphone-missing-microphone/19697

2020-07-27 00:12 UTC, daschuer requested changes
This will break the feature to not hear your own voice during announcements that are played to master as well. 
If it turns out to decouple the headphones from the booth settings, we need a separate option to not break the use case for other users. 
At least his is not a 2.2 fix.

2020-07-27 00:15 UTC, Be-ing commented
> This will break the feature to not hear your own voice during announcements that are played to master as well.

I do not understand the use case for this. If the user really doesn't want to hear their voice in headphones, turn the cue/mix knob fully towards PFL. But the user on the forum expected turning the cue/mix knob to the master side of the knob to play exactly the same as the master output, which includes the mics. IMO this user's expectation is reasonable.

2020-07-27 00:26 UTC, daschuer commented
> I do not understand the use case for this. 

Hearing the own voice can be disturbing if it has a long delay. 

> If the user really doesn't want to hear their voice in headphones, turn the cue/mix knob fully towards PFL. 

Not really, because the user wants to hear the master and not the PFL channel. 

> But the user on the forum expected turning the cue/mix knob to the master side of the knob to play exactly the same as the master output, which includes the mics. IMO this user's expectation is reasonable.

That's why we have the master + booth option. Booth is he equivalent to master in the headphone mix.

2020-07-27 17:25 UTC, Holzhaus commented
> But the user on the forum expected turning the cue/mix knob to the master side of the knob to play exactly the same as the master output, which includes the mics. IMO this user's expectation is reasonable.

I agree.

> That's why we have the master + booth option. Booth is he equivalent to master in the headphone mix.

Why isn't master the equivalent to master in the headphone mix? This is confusing.

2020-07-28 07:25 UTC, daschuer commented
>>  Hearing the own voice can be disturbing if it has a long delay.

> In this case the user should use the direct monitoring mode.

Yes, that is recommended, but that is a hardware feature.

2020-07-28 07:38 UTC, daschuer commented
>> That's why we have the master + booth option. Booth is he equivalent to master in the headphone mix.

> Why isn't master the equivalent to master in the headphone mix? This is confusing.

Yes, that is part of the legacy. Original, we had no booth output and a flag to remove the microphone from the master mix.

Now we have a booth channel, wich plays master back to the DJ. It has become the equivalent to the master played back via the headphones.

I guess the user issue is solved by enabling the talkover mix for booth.

The issue we need to solve us a naming issue. I suggest to fix this in 2.4 along with the master rename.

We have three outputs:
* Booth 
* Main
* Headphones

And two mixes:
* Monitoring mix 
* Audience mix

The monitoring mix is the one played though booth and headphones.

The best need to be improved.

Alternative we may introduce an additional setting that switches from the original state to the state proposed in this branch.

2020-07-28 15:48 UTC, Be-ing commented
> The monitoring mix is the one played though booth and headphones.

This is incorrect. The audience mix is played to the booth output.

I do like the suggested terminology of "monitoring mix" and "audience mix" to decouple these from the hardware outputs.

2020-07-28 17:40 UTC, daschuer commented
> This is incorrect. The audience mix is played to the booth output.

You mean correct, right? 

There is no doubt that the audience mix is played to master. Even in the broadcast use case it would be "correct" to not listen to master in you living room, but booth. 

But I guess we should continue to allow to listen the monitor Mixxx through master for legacy reasons.

2020-07-29 14:37 UTC, Be-ing commented
> You mean correct, right?

No. Booth = master. All that is different is they have separate gain knobs. You are conflating separate topics. The booth output is irrelevant to this discussion. The topic is the mics going to the audience mix in the headphone output. This should respect the mic monitor mode option, which it doesn't currently.

2020-07-29 14:47 UTC, daschuer commented
No, booth = master in headphones.
Both into the DJs ears and not to the audience.

That's why we have the different microphone mix options.
And that's why this is a non-issue since it can be fixed by the Preferences option without this PR.

2020-07-29 14:55 UTC, Be-ing commented
>  And that's why this is a non-issue since it can be fixed by the Preferences option without this PR.

No, it can't. That's why this PR exists.

2020-07-29 21:39 UTC, daschuer commented
A, now I understand. I must admit that I have not tested it before.

The issue is that the microphone is never mixed into the headphone. It should be mixed in in case of "Microphone Monitor Mode" = "Main and booth outputs"

2020-07-29 21:43 UTC, daschuer commented
This is not what this PR does.
The swap need to be done in the MASTER_AND_BOOTH case.

2020-07-29 21:47 UTC, daschuer requested changes

2020-07-29 21:47 UTC, daschuer commented on src/engine/enginemaster.cpp
> +            }
Please revert this.

2020-07-29 21:47 UTC, daschuer commented on src/engine/enginemaster.cpp
> -
Please revert this.

2021-11-20 00:39 UTC, Be-ing commented
This simple bug fix is still ready to merge as it was 1.5 years ago.

2021-11-20 15:29 UTC, Be-ing commented
I don't know why pre-commit is complaining about JavaScript files that are not touched by this PR, but it's not relevant.

2021-11-30 16:41 UTC, closed without merging