tools: Add clang tidy
mixxxdj/mixxx pull request #2975
Opened 2020-07-30 12:15 UTC by xerus2000

This way, whenever you commit, clang-tidy will modernize some indisputable things in the changed lines, which avoids work in reviews. Originally started with modernize-use-nullptr (replace NULL with nullptr), I now also added modernize-use-auto, which automatically uses auto if the type would be duplicated otherwise (i.e. when constructing an object) - but we can remove that if it is debatable.

Note that it currently only works after a compilation, since it needs the compile_commands.json which is generated by cmake. A check for that is in progress.

I didn't talk this over beforehand because I myself will use it anyways.

For now it is meshed into line_length.py because it laid a lot of necessary groundwork.
If you want to accept this, we should consider renaming it or splitting it up.

2020-07-30 22:28 UTC, daschuer requested changes
Thank you for this PR. 
I like the idea. 

And yes, we should not merge it like it is. 
We should split it into separate checks, that we are able to disable it individually if required.

2020-07-31 07:09 UTC, xerus2000 commented
One unfortunate thing is that clang-tidy essentially parses the code with all dependencies, so it is quite slow.

I guess we'll be extracting out the common part of finding changed files, which then makes replacing git-clang-format very easy as well.

2020-07-31 09:58 UTC, daschuer commented
Yes, that's fine. 
I even don't mind if we duplicate the changes code.
We just need two independent tasks in Pre-commit hook.

2020-08-01 11:02 UTC, Holzhaus commented
@daschuer @xerus2000 Have a look at #2982.

2020-08-01 11:03 UTC, closed without merging