Use low priority in library analyze queue
mixxxdj/mixxx pull request #2986
Opened 2020-08-03 20:47 UTC by poelzi

The TrackAnalysisScheduler for the library analyze queue uses all CPU cores
which speeds up analysis a lot. Unfortunately those threads fight
heavy with the rest of mixxx when decks are running.
The new LowPriority AnalyzerMode schedules the analyzer thread in QThread::LowPriority
and therefor the other threads more CPU time.
No more skipping audio and super laggy GUI.

2020-08-03 20:58 UTC, uklotzde requested changes

2020-08-03 20:58 UTC, uklotzde commented on src/analyzer/trackanalysisscheduler.cpp
> +                << QThread::idealThreadCount()
Mentioning the ideal thread count doesn't matter here after a specific number of worker threads has been requested. Please note that we already start 2 different schedulers with different numbers of worker threads.

Printing the ideal thread count at this point is confusing.

2020-08-03 21:06 UTC, uklotzde commented
Does this work as intended with the default scheduling strategy on Linux? If not it at least doesn't make it worse.

This PR should target 2.3 instead of master.

2020-08-04 16:42 UTC, uklotzde commented on src/util/workerthread.h
> +    QThread::Priority m_priority;
immutable member -> const

2020-08-04 16:42 UTC, uklotzde commented on src/util/workerthread.cpp
> +        const QThread::Priority priority)
wrong signature

2020-08-04 19:42 UTC, poelzi commented
New pull request for 2.3:
https://github.com/mixxxdj/mixxx/pull/2993

2020-08-04 19:59 UTC, Holzhaus commented
You don't nee to open a new PR, just rebase and force push to this branch and change the target branch by clicking the edit button next to the PR title.

2020-08-04 21:14 UTC, uklotzde commented
Please don't open conflicting PRs. I already commented on both, wasted effort and confusing.

2020-08-06 12:02 UTC, uklotzde commented
Superseded by #2993

2020-08-06 12:02 UTC, closed without merging