CMakeLists.txt: Set Debug Assertions to fatal in debug builds
mixxxdj/mixxx pull request #2987
Opened 2020-08-03 21:36 UTC by xerus2000

For debug runs, assertion failures should be fatal by default.

2020-08-07 14:53 UTC, uklotzde commented
Sounds reasonable and the cleanup is also an improvement. @Holzhaus Any thoughts?

2020-08-21 12:55 UTC, Holzhaus requested changes

2020-11-04 09:35 UTC, poelzi commented
I'm against this change. I always run debug builds cause it's easier to debug if I encounter a error. Having fatal exception without "--debugAssertBreak" will drive me nuts.

2020-11-04 12:32 UTC, daschuer commented
I agree. Can we close this?

2020-11-04 12:37 UTC, Holzhaus commented
> I'm against this change. I always run debug builds cause it's easier to debug if I encounter a error. Having fatal exception without "--debugAssertBreak" will drive me nuts.

It should still be possible to set `-DDEBUG_ASSERTIONS_FATAL=OFF`, this is just attempting to make it the default for debug builds.

I'm okay with closing this, as it's probably easier to start over than fixing the remaining issues and merge conflicts. Should I file a new PR or is changing the default undesired?

2020-11-04 12:37 UTC, closed without merging