Use Variable for CCX color enforcement
mixxxdj/mixxx pull request #3048
Opened 2020-08-27 21:30 UTC by poelzi

this allows you to use
 > cmake .. -D BUILD_COLORS always
to enforce color output.
Very useful with -G Ninja for color diagnostics.

2020-08-29 14:02 UTC, uklotzde commented
LGTM. @Holzhaus?

2020-08-29 14:36 UTC, Holzhaus approved these changes

2020-08-29 14:36 UTC, Holzhaus commented
Rebase on 2.3 or does merge into master suffice?

2020-08-29 15:44 UTC, uklotzde commented
@poelzi Please rebase. Changing the target doesn't work.

2020-08-30 14:01 UTC, uklotzde requested changes
Requesting rebase.

2020-08-31 06:25 UTC, uklotzde commented
@poelzi Please address review comments for this and your other PRs. Otherwise, we are not able to complete the reviews and merge them.

PS: This is also frustrating for reviewers if comments are ignored and PRs get stalled in a pending state. The list of open pull requests is already much too long! Keeping track of all the open PRs and reviews causes distraction.

2020-08-31 21:59 UTC, poelzi commented
done

2020-09-01 07:37 UTC, uklotzde commented
LGTM. Thank you!

2020-09-01 07:37 UTC, uklotzde approved these changes

2020-09-01 07:37 UTC, merged