pre-commit: Add crate to list of ignored codespell words
mixxxdj/mixxx pull request #3066
Opened 2020-09-02 00:11 UTC by Holzhaus

2020-09-02 01:03 UTC, Be-ing commented
We already have `pInOut`... how long will this list grow? I don't think making our own continually growing list of exceptions is a great approach.

2020-09-02 01:44 UTC, Holzhaus commented
> We already have `pInOut`... how long will this list grow? I don't think making our own continually growing list of exceptions is a great approach.

Moved to another file. Other alternatives are removing the codespell hook or getting rid of the "crate" term in our codebase.

2020-09-02 05:41 UTC, daschuer commented
Does pInOut work in a file?
I have some doubts that it does work now that way but not via -L

2020-09-02 14:03 UTC, Holzhaus commented
> Does pInOut work in a file?
> I have some doubts that it does work now that way but not via -L

The problem is that you need to specify the exact case it occurs in the dict, and then all matches (case-insensitive) will be filtered. So it won't warn if you types `inout` instead of `input`.

I worked around this issue. Now this generates the regex on the fly

2020-09-03 06:41 UTC, daschuer commented
Unfortunately this is still broken 
I have also added the capital "Crate" to the exclude file, but I still get complains: 

src/library/crate/cratefeature2.cpp:250: crate ==> create
src/library/crate/cratefeature2.cpp:309: Crate ==> Create
src/library/crate/cratefeature2.cpp:315: Crate ==> Create
src/library/crate/cratefeature2.cpp:339: crate ==> create
src/library/crate/cratefeature2.cpp:381: crate ==> create
src/library/crate/cratefeature2.cpp:396: crate ==> create
src/library/crate/cratefeature2.cpp:442: crate ==> create
src/library/crate/cratefeature2.cpp:456: crate ==> create
src/library/crate/cratefeature2.cpp:468: crate ==> create
src/library/crate/cratefeature2.cpp:621: crate ==> create
src/library/crate/cratefeature2.cpp:677: crate ==> create

I think the best we can do is to apply the ignore list to the codespell output in the same way we ignore the untouched lines.

2020-09-03 06:42 UTC, daschuer requested changes
Or is there a bug in our code?

2020-09-03 14:21 UTC, Holzhaus commented
> Or is there a bug in our code?

There was, but I figured that filtering the matches afterwards is probably easier and more performant anyway. Please retest.

2020-09-03 17:22 UTC, daschuer requested changes

2020-09-03 17:22 UTC, daschuer commented on .codespellignore
> +pInOut
Since we are now after the regex we need to omit the prefix as well.

2020-09-04 11:14 UTC, daschuer requested changes
I see now log spam: 

crate  {'crate', 'Crate', 'InOut'}
crate  {'crate', 'Crate', 'InOut'}
Crate  {'crate', 'Crate', 'InOut'}
crate  {'crate', 'Crate', 'InOut'}
crate  {'crate', 'Crate', 'InOut'}
Crate  {'crate', 'Crate', 'InOut'}
crate  {'crate', 'Crate', 'InOut'}
crate  {'crate', 'Crate', 'InOut'}

2020-09-04 14:39 UTC, daschuer approved these changes
Thank you. LGTM 
Hopefully this hook does not keep itching

2020-09-04 14:39 UTC, merged