WTrackMenu: Create DlgTrackInfo only on demand
mixxxdj/mixxx pull request #3098
Opened 2020-09-13 23:55 UTC by uklotzde

Many unused instances of DlgTrackInfo are created by WTrackMenu. Noticed after adding a database query to the init code.

TODO(XXX): Initialize WTrackMenu lazily on-demand instead of eagerly.

2020-09-14 06:33 UTC, daschuer commented on src/widget/wtrackmenu.cpp
> +    connect(m_pTrackInfo.get(),
data() Get is new in QT 5.11

2020-09-14 06:46 UTC, daschuer requested changes
Great. This surprisingly fixes also the issue that the dialog does not pop up when opening it for a different track. 
Uu-Applied changes are lost in that case. This was also the case in the original version and I think this is a users fault. 

Just a build failure.

2020-09-14 06:46 UTC, daschuer commented on src/widget/wtrackmenu.cpp
> +                if (m_pTrackInfo.get() == sender()) {
data() Get is new in QT 5.11

2020-09-14 07:22 UTC, uklotzde commented
Also applies top DlgTagFetcher. Unfortunately many merge conflicts, need to force push. When I find some time...

2020-09-15 20:14 UTC, daschuer approved these changes
LGTM, Thank you.

2020-09-15 20:14 UTC, merged