Fix some -Wfloat-conversion warnings (Pt. 2)
mixxxdj/mixxx pull request #3121
Opened 2020-09-24 21:07 UTC by Holzhaus

I split them up for better reviewability.

2020-09-24 21:58 UTC, daschuer commented on src/soundio/soundmanager.cpp
> +                    static_cast<mixxx::audio::SampleRate::value_t>(
this double cast looks odd. Can we add an overload for this type?

2020-09-24 21:59 UTC, daschuer requested changes
Thank you.

2020-09-25 06:52 UTC, daschuer requested changes

2020-09-25 06:52 UTC, daschuer commented on src/audio/types.h
> +    void operator=(const value_t value) {
const value_t&

2020-09-25 11:31 UTC, daschuer approved these changes
LGTM Thank you.

2020-09-25 11:31 UTC, merged

2020-09-25 16:09 UTC, ywwg commented
> I split them up for better reviewability.

thanks!