Fix some -Wfloat-conversion warnings (Pt. 5)
mixxxdj/mixxx pull request #3124
Opened 2020-09-25 15:14 UTC by Holzhaus

We're getting close...

2020-09-25 15:33 UTC, daschuer requested changes
Thanks :-)

2020-09-25 15:33 UTC, daschuer commented on src/effects/builtin/phasereffect.cpp
> +    const auto freqSkip = static_cast<CSAMPLE>(1.0 / periodSamples * 2.0 * M_PI);
use kDoublePi? 
I think this can become float math

2020-09-25 15:33 UTC, daschuer commented on src/effects/builtin/phasereffect.cpp
> +        pState->rightPhase = fmodf(static_cast<float>(pState->rightPhase +
cast just M_PI?

2020-09-25 15:33 UTC, daschuer commented on src/engine/enginemaster.cpp
> +        const auto cf_val = static_cast<CSAMPLE>(m_pHeadMix->get());
static_cast<CSAMPLE_GAIN>

2020-09-25 15:33 UTC, daschuer commented on src/engine/enginemaster.cpp
> +        const auto bal = static_cast<CSAMPLE>(m_pBalance->get());
static_cast<CSAMPLE_GAIN>

2020-09-25 15:33 UTC, daschuer commented on src/engine/enginepregain.cpp
> +    const auto fReplayGain = static_cast<float>(m_pCOReplayGain->get());
static_cast<CSAMPLE_GAIN>

2020-09-25 15:33 UTC, daschuer commented on src/engine/enginepregain.cpp
>      float fReplayGainCorrection;
CSAMPLE_GAIN

2020-09-25 15:33 UTC, daschuer commented on src/engine/enginepregain.cpp
> +                fReplayGainCorrection =
this can become float math

2020-09-25 15:33 UTC, daschuer commented on src/engine/enginepregain.cpp
>          speedGain = math_min(kMaxTotalGainBySpeed / totalGain, speedGain);
this can also become float math

2020-10-09 12:43 UTC, Holzhaus commented
Merge?

2020-10-09 14:23 UTC, daschuer approved these changes
LGTM Thank you. 
waiting for CI

2020-10-12 22:12 UTC, Holzhaus commented
Merge?

2020-10-16 08:24 UTC, merged