Fix some -Wfloat-conversion warnings (Pt. 6)
mixxxdj/mixxx pull request #3125
Opened 2020-09-25 20:36 UTC by Holzhaus

Almost done...

2020-09-25 22:30 UTC, daschuer requested changes
Some comments.

2020-09-25 22:30 UTC, daschuer commented on src/effects/lv2/lv2effectprocessor.cpp
> +        m_params[i] = static_cast<CSAMPLE>(m_parameters[i]->value());
We don't know the use here so casting to float would fit better.

2020-09-25 22:30 UTC, daschuer commented on src/effects/lv2/lv2effectprocessor.cpp
> +            m_params[i] = static_cast<CSAMPLE>(m_parameters[i]->value());
Same here, cast too float.

2020-09-30 10:10 UTC, daschuer commented
This has conflicts now.

2020-10-09 12:56 UTC, Holzhaus commented
The conflicts have been resolved.

2020-10-09 14:21 UTC, daschuer approved these changes
LGTM, Thank you.

2020-10-09 14:22 UTC, daschuer commented
Waiting for CI

2020-10-12 22:12 UTC, Holzhaus commented
Merge?

2020-10-16 08:25 UTC, merged