Externalize forward declarations for Track object
mixxxdj/mixxx pull request #3136
Opened 2020-09-27 23:01 UTC by uklotzde

New file `track_decl.h` with forward declarations and enum definitions for `class Track`.

I picked up this technique from customer projects.

Just a peek of what is actually possible. The majority of #include directives in header files should be replaceable, which in turn will reveal many other missing dependencies like in this PR.

2020-09-27 23:04 UTC, Holzhaus commented
No unnecessary recompiling of large parts of Mixxx if you change `track.h` anymore? Sound good.

2020-09-27 23:19 UTC, uklotzde commented
> No unnecessary recompiling of large parts of Mixxx if you change `track.h` anymore? Sound good.

Exactly. Works for all types that are passed around behind shared or managed pointers. Might even reduce compile times in general, but I don't expect much.

2020-09-28 06:16 UTC, daschuer commented
> No unnecessary recompiling of large parts of Mixxx if you change track.h anymore? Sounds good.

How should this work? The compiler processes finally a giant cpp file with all includes and macros extracted. 
If track_decl.h is includes into track.h the content of this file will not change.

2020-09-28 06:17 UTC, daschuer commented on src/library/externaltrackcollection.h
> +#include "track/track_decl.h"
Here this will grow the cpp file after prepossessor = more compile time.

2020-09-28 06:49 UTC, uklotzde commented
@daschuer So what's your point? I am not willing to start discussions about if a few redundant lines of code in some .cpp files.

I consider this useful and necessary. Otherwise, I will close this PR immediately and we can continue with the old, lazy style of including track.h and some sprinkled forward declarations here and there.

2020-09-28 07:00 UTC, daschuer commented
Ah, now I understand. It is useful everywhere you can replace track.h with track_decl.h

2020-09-28 07:24 UTC, daschuer requested changes
OK, good idea, thank you. 
I have found a few places where just class Track is sufficient or the new include can be removed entirely.

2020-09-28 07:24 UTC, daschuer commented on src/library/externaltrackcollection.h
> -class Track;
here we should keep just the forward declaration.

2020-09-28 07:24 UTC, daschuer commented on src/test/soundproxy_test.cpp
> +#include "track/track.h"
Why was this changed?

2020-09-28 07:24 UTC, daschuer commented on src/track/beatgrid.h
> +#include "track/track_decl.h"
this can become 
class Track;

2020-09-28 07:24 UTC, daschuer commented on src/track/beatmap.h
> +#include "track/track_decl.h"
this can become just 
class Track;

2020-09-28 07:24 UTC, daschuer commented on src/track/cue.h
> -class Track;
please revert.

2020-09-28 07:24 UTC, daschuer commented on src/track/keyfactory.h
> +#include "track/track_decl.h"
this can be removed.

2020-09-28 07:34 UTC, uklotzde commented
I am not going to add forward declarations manually.

2020-09-28 07:34 UTC, closed without merging

2020-09-28 09:03 UTC, daschuer commented
In general I think this PR is a good approach. I have just reviewed where track_decl.h is required because of TrackPointer and where not, that's all.
Please reopen.

2020-09-28 09:17 UTC, uklotzde commented
I tried to improve the developer experience and to avoid handcrafting the code. But I am not a C++ advocate anymore and won't participate in those discussions.

2020-09-28 20:48 UTC, Holzhaus commented
I don't think we need to hand optimize forward declarations. Let's just use `track_decl.h` - the likelyhood that it changes is small (much smaller than the likelyhood that `track.h` changes.

@uklotzde please reopen.

2020-09-28 21:44 UTC, daschuer commented
I am working on a new PR on top of this that uses track_decl.h in all headers that uses TrackPointer()