LateNight tweaks
mixxxdj/mixxx pull request #3145
Opened 2020-10-02 16:13 UTC by ronso0

some small fixes and improvements.

Notable changes:
* more intuitive beatgrid / hotcue shift buttons:
![image](https://user-images.githubusercontent.com/5934199/94945375-deaa0c80-04da-11eb-9783-2fba24ab2836.png)
* ..

2020-10-03 08:37 UTC, JoergAtGithub commented
The buttons are much better to understand now! What do you think about changeing the beatgrid shift buttons from 
![grafik](https://user-images.githubusercontent.com/64457745/94987106-02656500-0564-11eb-90a9-da46f5bdc9e2.png) to 
![grafik](https://user-images.githubusercontent.com/64457745/94987116-127d4480-0564-11eb-92ce-95caeb22fe3f.png)
IMHO this makes it more clear, that the whole beatgrid is affected, because the right edge of the arrow is not on a beat.

2020-10-03 08:58 UTC, JoergAtGithub commented
On a second thought, would it be more clear, to have the base edge of the arrows always on the object to move e.g. 
![grafik](https://user-images.githubusercontent.com/64457745/94987521-4312ad80-0567-11eb-84ea-5377f9ce8028.png)
instead of 
![grafik](https://user-images.githubusercontent.com/64457745/94987505-2a09fc80-0567-11eb-896d-949599b85026.png)

2020-10-03 09:36 UTC, JoergAtGithub commented
And maybe this 
![grafik](https://user-images.githubusercontent.com/64457745/94988265-43617780-056c-11eb-8f47-ee5b2b395bd9.png) instead of 
![grafik](https://user-images.githubusercontent.com/64457745/94988309-8a4f6d00-056c-11eb-8a69-33823797e189.png)

2020-10-04 18:51 UTC, ywwg commented
> On a second thought, would it be more clear, to have the base edge of the arrows always on the object to move e.g.

+1 to both of these suggestions

2020-10-05 17:50 UTC, JoergAtGithub commented
What do you think about the this sketch:
![grafik](https://user-images.githubusercontent.com/64457745/95113923-75790200-0743-11eb-8317-8f4838ebd17a.png)
I changed the following:
-Move Cue Left/Right is now horizontal below Move Beatgrid Left/Right
-The Adjust BPM Up/Down buttons are now vertical (as the pitch fader)
-I added a third beat bar to the Adjust BPM buttons. Now all buttons, that affect the whole beatgrid have 3 beat bars

2020-10-05 18:04 UTC, ronso0 commented
hotcue_shift buttons are optional, it would be confusing of other buttons change their position when shift buttons are shown.
I think beats_slower/_faster is good now, the third bar doesn't add information IMO.

2020-10-09 14:42 UTC, ronso0 commented
I changed the looping & beatjump icons so they differ from the beatgrid icons.
What do you think?
![image](https://user-images.githubusercontent.com/5934199/95597031-6c8f7580-0a4e-11eb-8466-71af6564e821.png)

2020-10-09 19:28 UTC, Holzhaus commented
I like the new loop in/loop out buttons. I'm unsure about the beatjump buttons, because they look a bit like fast forward/rewind, not beatjump. On the other hand, the old buttons looked like skip forward/back buttons and I have no idea what a "beatjump icon" could look like, so I guess the fast forward/rewind symbols fit better than the alternative.

While you're at it, could you have a look at the remaining skin errors?
```
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
[...]
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: WaveformSignalColors::fallBackDefaultColor - Skin does not provide valid signal colors, using default color...
```

2020-10-09 19:38 UTC, JoergAtGithub commented
> I like the new loop in/loop out buttons. I'm unsure about the beatjump buttons, because they look a bit like fast forward/rewind, not beatjump.
I aggree to both, what do you think about this: 
![grafik](https://user-images.githubusercontent.com/64457745/95624864-d112fa80-0a77-11eb-8fbb-7daa4103487e.png)

2020-10-10 06:59 UTC, ronso0 commented
adapting the Shade icons :) Sure!

2020-10-10 07:01 UTC, ronso0 commented
I pushed the icons back a bit, I'm about to finish adding 16 samplers. now it's just about ironing out some glitches in the sin settings.

2020-10-10 09:53 UTC, ronso0 commented
Okay, 16 samplers are in place and toggling works nicely.

I added some extra in-line toggles for deck count, hotcues, Fx units and sampler count.
Skin settings can are a bit more compact (now / before)
![Screenshot_2020-10-10_10-27-56](https://user-images.githubusercontent.com/5934199/95652095-0a3a8180-0aef-11eb-9735-b057d45977cc.png)


New Loop, beatjump & beatgrid icons:
![image](https://user-images.githubusercontent.com/5934199/95652042-95674780-0aee-11eb-9fd4-b5daa8021984.png)

2020-10-10 11:29 UTC, JoergAtGithub commented
Did you consider to use green as color for the active loop button, instead of orange? Than loops in the waveforms and the loop buttons would have the same color:
![grafik](https://user-images.githubusercontent.com/64457745/95653798-ad919380-0afb-11eb-870f-506c194c6e24.png)
IMHO orange looks better, while green would result in functional consistency.

2020-10-10 14:49 UTC, ronso0 commented
Hm, actually I decided to have all toggles in the transport row orange to keep static toggles consitent (in contrast to colored hotcues) and to lower the confusion.
the other way around: what about painting the loop orange? Did you try that?

2020-10-10 17:33 UTC, ronso0 commented
> While you're at it, could you have a look at the remaining skin errors?
> 
> ```
> Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
> [...]
> Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )

The use of `highlight` property works, therefore the warning is pointless. I have WIP branch to add highlight to the base widget.

> Warning [Main]: WaveformSignalColors::fallBackDefaultColor - Skin does not provide valid signal colors, using default color...
> ```

I'll check that!

2020-10-10 17:50 UTC, JoergAtGithub commented
> the other way around: what about painting the loop range and the waveform marker orange? Did you try that?
![grafik](https://user-images.githubusercontent.com/64457745/95661727-cfa60880-0b31-11eb-9770-8cc406a98e02.png)

2020-10-10 17:54 UTC, ronso0 commented
Nice! Never tried that and so I didn't notice the underlying waveform shines through that way.
Other's opinions on that? @Holzhaus @ywwg

2020-10-10 17:55 UTC, JoergAtGithub commented
This is just painted, to get a visual impression

2020-10-10 18:19 UTC, ronso0 commented
hmkay..
[here](https://github.com/mixxxdj/mixxx/blob/master/res/skins/LateNight/skin.xml#L162)'s the place in case you wanna play a bit with it.

2020-10-12 18:23 UTC, ywwg commented
I'm getting a cmake error:

```
CMake Error at CMakeLists.txt:1233 (add_executable):
  Target "mixxx-test" links to target "KeyFinder::KeyFinder" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

2020-10-12 18:23 UTC, ywwg commented
(same error for other build targets)

2020-10-12 18:28 UTC, ronso0 commented
I don't see how this could be related to changes in this PR.
Does building 2.3 work for you?

2020-10-12 18:31 UTC, ronso0 commented
CI succeeds building

2020-10-12 22:10 UTC, Holzhaus commented
@ywwg this happens because you built Mixxx with keyfinder support, then checked out this branch which has probably been forked off before keyfinder support has been added. Just delete your build directory and rebuild, then the issue is gone.

2020-10-12 22:11 UTC, Holzhaus commented
@ronso0 is this ready to review and merge?

2020-10-12 22:16 UTC, ronso0 commented
Yes, I'm confident the entire samplers section works flawlessly now with the Singletons.
Please test!

2020-10-12 22:57 UTC, ywwg commented
This looks good!  Maybe the default should be for the samplers to be collapsed -- they take up a lot of space expanded.

2020-10-12 23:40 UTC, ronso0 commented
> This looks good! Maybe the default should be for the samplers to be collapsed -- they take up a lot of space expanded.

Oh, my bad. I commited the test setup..
Default is 8 minimized samplers.

2020-10-13 09:25 UTC, Holzhaus requested changes
Thank you! All looks good except for the small typo in the qss file (see below).

2020-10-13 09:25 UTC, Holzhaus commented on res/skins/LateNight/style_palemoon.qss
> +    background-color: 2#c454f;
```
Warning [Main]: QCssParser::parseHexColor: Unknown color name '#c454f'
```

2020-10-13 14:09 UTC, ronso0 commented on res/skins/LateNight/style_palemoon.qss
> +    background-color: 2#c454f;
thanks, fixed!

2020-10-15 21:07 UTC, Holzhaus approved these changes
LGTM, thank you!

2020-10-15 21:07 UTC, merged