Librarycontrol: allow [Library],GoToItem press dialog buttons
mixxxdj/mixxx pull request #3199
Opened 2020-10-21 22:00 UTC by ronso0

This enables controllers to close `File not found` dialogs as well as warnings from failed VinylControl, Passthrough, Mic Talkover or Aux play actions.

2020-10-21 22:02 UTC, ronso0 commented
I'll update the [documentation](https://manual.mixxx.org/2.3/en/chapters/advanced_topics.html#mixxx-controls) as soon as this is merged.

2020-10-26 21:13 UTC, uklotzde requested changes

2020-10-26 21:13 UTC, uklotzde commented on src/library/librarycontrol.cpp
> +            focusWindow->type() == static_cast<Qt::WindowType>(Qt::Dialog)) {
Don't use static_cast, test for the flags in the value returned by type(). I suppose we need to check for both Qt::Dialog and Qt::Popup.

2020-10-26 21:15 UTC, uklotzde commented on src/library/librarycontrol.cpp
> +            focusWindow->type() == static_cast<Qt::WindowType>(Qt::Dialog)) {
```
if (focusWindow && (focusWindow->type() & (Qt::Dialog | Qt::Popup))) {
```

2020-10-27 18:03 UTC, ronso0 commented
Ready.

2020-10-30 18:36 UTC, uklotzde approved these changes
Thank you! Sorry for the delay, I am completely lost between all those pending PRs. LGTM

2020-10-30 18:36 UTC, merged