Info about support for database on non USB / SD devices
mixxxdj/mixxx pull request #3211
Opened 2020-10-24 21:47 UTC by fkbreitl

2020-10-24 22:19 UTC, ronso0 reviewed
some suggestions.
Though I'm not a native speaker either ;)

2020-10-24 22:19 UTC, ronso0 commented on src/library/rekordbox/rekordboxfeature.cpp
> +            "Reads databases exported for Pioneer CDJ / XDJ players with the Rekordbox Export mode. <br/>"
```suggestion
            "Reads databases exported for Pioneer CDJ / XDJ players using the Rekordbox Export mode. <br/>"
```

2020-10-24 22:19 UTC, ronso0 commented on src/library/rekordbox/rekordboxfeature.cpp
> +            "Mixxx reads a database from any device that contains the database folders (PIONEER and Contents). <br/>"
```suggestion
            "Mixxx can read a database from any device that contains the database folders (PIONEER and Contents). <br/>"
```

2020-10-25 12:45 UTC, fkbreitl reviewed
fixed pre-commit code style issues

2020-10-25 20:47 UTC, Holzhaus requested changes

2020-10-25 20:47 UTC, Holzhaus commented on src/library/rekordbox/rekordboxfeature.cpp
>              "Preferences > Advanced > Database management. <br/>"
```suggestion
            "Reads databases exported for Pioneer CDJ / XDJ players using "
            "the Rekordbox Export mode.<br/>"
            "Rekordbox can only export to USB or SD devices with a FAT or "
            "HFS file system.<br/>"
            "Mixxx can read a database from any device that contains the "
            "database folders (<tt>PIONEER</tt> and <tt>Contents</tt>).<br/>"
            "Not supported are Rekordbox databases that have been moved to "
            "an external device via<br/>"
            "<i>Preferences > Advanced > Database management</i>.<br/>"
```

2020-10-25 21:19 UTC, Holzhaus approved these changes
LGTM, thank you.

2020-10-26 18:05 UTC, Be-ing commented
Can you rebase this onto the 2.3 branch?

2020-10-26 19:10 UTC, fkbreitl commented
Can I do it on Github? I have no local repository...

2020-10-26 19:11 UTC, Be-ing commented
I don't think so. It's going to be pretty hard to contribute if you're only relying on the GitHub web interface instead of using Git locally.

2020-10-26 19:51 UTC, fkbreitl commented
I have it for other work but didn't think I would need it for changing this little text.

2020-11-03 00:06 UTC, fkbreitl commented
What are the git commands to do this?

2020-11-03 00:20 UTC, Be-ing commented
If you haven't already, [configure the upstream remote as described on the wiki](https://github.com/mixxxdj/mixxx/wiki/using-git#set-up-git). Then
```
git checkout patch-1 # switch to your branch
git rebase -i upstream/2.3
```
This will bring up a big list of commits to rebase. Delete all the commits that aren't yours, then save the file and Git will do the rebase. Then
```
git push --force
```
https://git-scm.com/book/en/v2/Git-Branching-Rebasing
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2020-11-17 20:46 UTC, merged

2020-11-17 20:46 UTC, Be-ing commented
Thank you.