BalanceGroupState: Fix signed/unsigned comparison for armv7hl
mixxxdj/mixxx pull request #3223
Opened 2020-10-26 14:56 UTC by uklotzde

http://koji.rpmfusion.org/koji/getfile?taskID=443532&volume=DEFAULT&name=build.log&offset=-4000

```
CMakeFiles/mixxx-lib.dir/src/effects/builtin/balanceeffect.cpp.o.d -o CMakeFiles/mixxx-lib.dir/src/effects/builtin/balanceeffect.cpp.o -c ../src/effects/builtin/balanceeffect.cpp
../src/effects/builtin/balanceeffect.cpp: In member function 'virtual void BalanceEffect::processChannel(const ChannelHandle&, BalanceGroupState*, const CSAMPLE*, CSAMPLE*, const mixxx::EngineParameters&, EffectEnableState, const GroupFeatureState&)':
../src/effects/builtin/balanceeffect.cpp:132:38: error: comparison of integer expressions of different signedness: 'unsigned int' and 'mixxx::audio::SampleRate::value_t' {aka 'int'} [-Werror=sign-compare]
  132 |     if (pGroupState->m_oldSampleRate != bufferParameters.sampleRate() ||
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

2020-10-26 14:58 UTC, Be-ing commented
LGTM, waiting for CI.

2020-10-26 16:44 UTC, uklotzde commented
I have started a new build with non-fatal warnings to detect any further issues (instead of aborting the build after the first warning):
http://koji.rpmfusion.org/koji/taskinfo?taskID=443567

2020-10-27 06:53 UTC, uklotzde commented
@Be Ready. I have hopefully fixed all warnings that appeared in the build logs.

2020-10-27 08:47 UTC, daschuer requested changes
Thank you.

Does the arm compiler use unsigned char?
That might be dangerous because, because I am sure that our code base is not fully tested with that.

2020-10-27 08:47 UTC, daschuer commented on src/effects/builtin/metronomeeffect.cpp
> +                math_min(static_cast<SINT>(bufferParameters.framesPerBuffer()),
Isn't framesPerBuffer() already SINT? 
At least it schould be.

2020-10-27 10:15 UTC, uklotzde commented
> Thank you.
> 
> Does the arm compiler use unsigned char?
> That might be dangerous because, because I am sure that our code base is not fully tested with that.

Yes, `char` seems to be unsigned for that architecture/compiler and must be explicitly cast to a `signed char` when needed. Only the FAAD2 function signature is affected, casting is safe. Not further issues.

2020-10-27 14:14 UTC, daschuer reviewed
LGTM, thank you.

2020-10-27 14:15 UTC, daschuer approved these changes

2020-10-27 14:15 UTC, merged