Automated header cleanups
mixxxdj/mixxx pull request #3275
Opened 2020-11-07 14:17 UTC by xerus2000

These are all purely automatic (Regex) changes that:
- remove copyright and filename headers (they were inconsistent anyways, and for file creation and authors we have a VCS)
- put `#pragma once` in place everywhere

I split them off from #3013, since that one unhelpfully threw them in with lots of other changes.

I took a lot of care to not delete any potentially useful information, that is why I preserved some comments that might not be ideally formatted or in the correct. However, these are manual edits that I want to avoid in code I don't know. When people touch the files again they will clearly see the information that was put there by the original creators (often a comment on the first line of the file) and can decide whether it can be deleted or where it should be incorporated.

Since this only concerns file headers (and sometimes footers), it won't mess up `git blame` either ;)
But it can save a lot of time from manually doing these things whenever such an old file is encountered.

2020-11-07 15:39 UTC, Holzhaus commented
Can you rebase on 2.3? That should avoid merge conflicts later on.

2020-11-07 19:35 UTC, xerus2000 commented
I just rebased onto main :sweat_smile: I thought that is the branch that non-user-centric changes should go into?

2020-11-07 21:14 UTC, Holzhaus commented
Yes, but this is basically a no-op and I worry about merge conflicts...

2020-11-10 22:41 UTC, xerus2000 commented
Done :+1: not quite a no-op, but nothing mention-worthy

2020-11-12 01:47 UTC, Holzhaus commented
> not quite a no-op, but nothing mention-worthy

What do you mean? I thought this just removed some license/author comments and replace ifdefs with pragma once. What did you change? 

Please don't slip functional changes into "cleanup" PRs. Now I need to read through 5000 LOC to find out what was changed.

2020-11-12 06:57 UTC, daschuer commented
> Please don't slip functional changes into "cleanup" PRs. Now I need to read through 5000 LOC to find out what was changed.

This is the reason we do not want mass refactoring for no reason. I think we have discussed this already in similar PRs from @xerus2000. There is only a minimum benefit is such PRs and it steals reviewer time that can be used for features and real bug fixes. 

Can we just close this?

2020-11-12 10:51 UTC, xerus2000 commented
> > not quite a no-op, but nothing mention-worthy
> 
> What do you mean? I thought this just removed some license/author comments and replace ifdefs with pragma once. What did you change?

I think we misunderstood no-op. I thought you referred to the act of rebasing being a no-op in the sense of there would be no conflicts, but they were a few due to pragma once-conversions in the meantime.

> Please don't slip functional changes into "cleanup" PRs. Now I need to read through 5000 LOC to find out what was changed.

No, I did not "slip in" anything. Nothing changed.

2020-11-12 10:53 UTC, xerus2000 commented
> There is only a minimum benefit is such PRs and it steals reviewer time that can be used for features and real bug fixes.

Integrating this with other changes steals away reviewer and coding time. I used some regexes to get this out of the way once and for all, because doing it by hand on the go became too tedious.

2020-11-12 11:23 UTC, Holzhaus commented
> > > not quite a no-op, but nothing mention-worthy
> > 
> > What do you mean? I thought this just removed some license/author comments and replace ifdefs with pragma once. What did you change?
> 
> I think we misunderstood no-op. I thought you referred to the act of rebasing being a no-op in the sense of there would be no conflicts, but they were a few due to pragma once-conversions in the meantime.
> 
> > Please don't slip functional changes into "cleanup" PRs. Now I need to read through 5000 LOC to find out what was changed.
> 
> No, I did not "slip in" anything. Nothing changed.

OK, I misunderstood. The *PR* is still a functional no-op, but *rebase* was not because there were conflicts. Got it.

2020-11-13 20:36 UTC, xerus2000 commented
It would be good to merge this soon, since (trivial) conflicts arise quickly.

2020-11-14 02:56 UTC, Holzhaus requested changes

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controller.h
>  */
Use `///` and move in front of class.

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controller.cpp
Remove these two lines.

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerenumerator.h
> + */
Use `///` and move directly in front of class.

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllermanager.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllermanager.h
> +// Manages creation/enumeration/deletion of hardware controllers.
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerpresetfilehandler.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerpresetfilehandler.h
> +/// Handles loading and saving of Controller presets.
move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerpresetinfo.h
>  */
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerpresetinfo.cpp
> +/** Implement handling enumeration and parsing of preset info headers
Redundant (see header), please remove.

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerpresetinfoenumerator.cpp
> +// Enumerate list of available controller mapping presets
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/controllerpresetinfoenumerator.h
> +// Enumerate list of available controller mapping presets
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/dlgcontrollerlearning.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/dlgcontrollerlearning.h
> +// The controller mapping learning wizard
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/dlgprefcontroller.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/dlgprefcontroller.h
> +/// Configuration dialog for a single DJ controller
move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/hid/hidcontroller.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/hid/hidcontroller.h
> +// HID controller backend
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/hid/hidcontrollerpreset.cpp
>  /// elements that make it up.
move into header file and put it directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/hss1394controller.h
> +/** HSS1394-based MIDI backend
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/hss1394enumerator.h
> +// This class handles discovery and enumeration of DJ controllers that appear under the HSS1394 cross-platform API.
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/midicontroller.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/midicontroller.h
>  */
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/midicontrollerpreset.cpp
> +/// MIDI Controller Preset
Move this whole comment into the header file (directly in front of class)

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/midicontrollerpresetfilehandler.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/midicontrollerpresetfilehandler.h
> +// Handles loading and saving of MIDI controller presets.
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/midioutputhandler.h
>   */
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/portmidicontroller.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/controllers/midi/portmidicontroller.h
> +/** PortMidi-based MIDI backend
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoder.h
> +// encoder API for mixxx
This comment doesn't add any value, please remove

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderbroadcastsettings.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderbroadcastsettings.h
> +// storage of broadcast settings for the encoders.
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderffmpegcore.h
> +// core code for ffmpeg encoders
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderffmpegmp3.cpp
> +// FFMPEG MP3 encoder for mixxx
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderffmpegmp3.h
> +// FFMPEG MP3 encoder for mixxx
Use `///` and move directly in front of class (and remove "for Mixxx")

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderffmpegvorbis.cpp
> +// FFMPEG OGG/Vorbis encoder for mixxx
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderffmpegvorbis.h
> +// FFMPEG OGG/Vorbis encoder for mixxx
Use `///` and move directly in front of class (and remove "for mixxx")

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderflacsettings.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderflacsettings.h
> +// storage of setting for flac encoder
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodermp3settings.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodermp3settings.h
> +// storage of setting for mp3 encoder
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodersettings.h
> +// Encoder settings interface for encoders.
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodersndfileflac.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodersndfileflac.h
> +// encoder for flac using libsndfile
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodervorbis.cpp
> +// http://svn.xiph.org/trunk/vorbis/examples/encoder_example.c
Remove or move to header file

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodervorbis.h
> +// vorbis encoder for mixxx
Use `///` and move directly in front of class (and remove "for mixxx")

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodervorbissettings.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encodervorbissettings.h
> +// storage of setting for vorbis encoder
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderwave.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderwave.h
> +// wave/aiff "encoder" for mixxx
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderwavesettings.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/encoder/encoderwavesettings.h
> +// storage of setting for wave/aiff encoder
Use `///` and move directly in front of class

2020-11-14 02:56 UTC, Holzhaus commented on src/engine/channels/engineaux.cpp
```suggestion
```

2020-11-14 02:56 UTC, Holzhaus commented on src/engine/channels/engineaux.h
```suggestion
```

2020-11-15 23:20 UTC, xerus2000 commented
> I took a lot of care to not delete any potentially useful information, that is why I preserved some comments that might not be ideally formatted or in the correct. However, these are manual edits that I want to avoid in code I don't know. When people touch the files again they will clearly see the information that was put there by the original creators (often a comment on the first line of the file) and can decide whether it can be deleted or where it should be incorporated.

@Holzhaus I don't want to do any manual edits here

2020-11-16 21:13 UTC, Holzhaus commented
> > I took a lot of care to not delete any potentially useful information, that is why I preserved some comments that might not be ideally formatted or in the correct. However, these are manual edits that I want to avoid in code I don't know. When people touch the files again they will clearly see the information that was put there by the original creators (often a comment on the first line of the file) and can decide whether it can be deleted or where it should be incorporated.
> 
> @Holzhaus I don't want to do any manual edits here

I don't really see the purpose then tbh.

> But it can save a lot of time from manually doing these things whenever such an old file is encountered.

Deleting 10 lines is 3 keystrokes for me (`d9j`). Cleaning up the comments takes a bit longer and would actually benefit during development because doxygen comments are picked up by editors/IDEs.

2020-12-02 20:29 UTC, Holzhaus commented
Closing in favor of https://github.com/mixxxdj/mixxx/pull/3397.

2020-12-02 20:29 UTC, closed without merging