effects: Replace old-style Qt connect() calls
mixxxdj/mixxx pull request #3306
Opened 2020-11-13 20:43 UTC by Holzhaus

2020-11-13 20:46 UTC, Be-ing commented
Please don't make more merge conflicts for #2618 just to make a linter happy.

2020-11-14 09:07 UTC, uklotzde commented
@Be-ing Approval to merge this?

The integration of clazy will push code quality onto a new level and helps to detect issues upfront before manually reviewing PRs. It will save us from a lot of tedious review work and prevent bugs. I am so glad that Jan has started this.

2020-11-14 14:28 UTC, uklotzde commented on src/effects/effectchainslot.h
> +    void slotControlChainSuperParameter(double v, bool force);
Why did you decide keep the default parameter shouldEmit = true in slotChainEffectChanged() although you pass `true` explicitly now? Default parameters in slots should be avoided.

2020-11-14 14:28 UTC, uklotzde requested changes
TODO: Remove default parameter from slotChainEffectChanged()

2020-11-14 14:31 UTC, uklotzde commented
@Be-ing Conflicts with #2618 should be easy to resolve. The removal of default parameters from slots is the only notable exceptions.

2020-11-14 14:37 UTC, Be-ing commented
> TODO: Remove default parameter from slotChainEffectChanged()

Adding TODOs in code that has already been completely rewritten is pointless.

2020-11-14 14:38 UTC, Be-ing commented
> @Be-ing Approval to merge this?

Okay. I'm just grumpy about having to keep resolving merge conflicts.

2020-11-14 15:13 UTC, uklotzde commented
Maybe it is better we resolve those merge conflicts now instead of later whenever we need to merge 2.3 into main?

We need to ensure that no major effect changes are required for 2.3 before merging #2618, including skins. But then I recommend to merge #2618 early for thorough testing!

2020-11-14 15:17 UTC, Be-ing commented
> Maybe it is better we resolve those merge conflicts now instead of later whenever we need to merge 2.3 into main?

I don't understand how that would be possible.

2020-11-14 17:07 UTC, uklotzde approved these changes
LGTM

2020-11-14 18:55 UTC, Holzhaus commented
I could take care of the merge conflicts in #2618, but it already conflicts and I have no idea about the skin conflicts.

2020-11-14 22:01 UTC, uklotzde commented
No need to wait for the redundant SCons build. LGTM

2020-11-14 22:01 UTC, merged