DlgPrefRecord: enable CUE sheet recording by default
mixxxdj/mixxx pull request #3374
Opened 2020-11-26 08:17 UTC by Be-ing

A CUE sheet cannot be created retroactively after making a
recording, so it is better to have it on by default. If a user
does not want them, they can delete the CUE files and turn off
the option easily.

As discussed on Zulip
https://mixxx.zulipchat.com/#narrow/stream/109122-general/topic/Exporting.20a.20Mixcloud-digestable.20playlist

2020-11-26 12:22 UTC, daschuer requested changes
We have the default velue now scattered among the code base. 
Please use a single constant.

2020-11-26 15:39 UTC, Be-ing commented
Okay, done. I will *not* do anymore refactoring of this legacy code. I am only changing this one boolean value; that's it.

This preferences code needs an overhaul so that it is not possible to have the default value inconsistent in different places.

2020-11-26 21:37 UTC, uklotzde approved these changes

2020-11-26 22:27 UTC, uklotzde commented
Unrelated: I see varying test failures on different Windows CI builds. This is strange.

2020-11-27 10:23 UTC, daschuer requested changes
LGTM, Thank you.

2020-11-27 10:26 UTC, daschuer approved these changes

2020-11-27 10:26 UTC, merged