Multi Preview Fix
mixxxdj/mixxx pull request #3382
Opened 2020-11-28 14:39 UTC by daschuer

This fixes an issue when you preview more than one cues at a time. 
In 2.3 the last released button moves the playposition to the associated hot cue position. 
This can't no longer work with cue loops involved. 

I have changed the code that internally only one hot cue can be previewing. 
If you preview one hot-cue and press a second one, the second takes over. The release of the first hot cue is ignored from that point. If it was a loop, looping is disabled.  

This also cleans up looking.

2020-11-28 14:54 UTC, uklotzde commented
You might consider to pick and apply this commit: https://github.com/uklotzde/mixxx/commit/4c2d90f9e12acb49601db6819c964c41ba54e26d

I didn't check if it still applies here and what changes are required. The idea is simple, just keep the code that belongs together at a single place.

2020-11-29 22:40 UTC, daschuer commented
Done.

2020-12-02 22:23 UTC, uklotzde requested changes
Just some minor coding comments. Overall the code seems to be much more readable than before.

I didn't check if everything works as expected. The cue handling is complicated, I have to trust the tests.

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +/// Used for a common tarcking of the previewing Hotcue in m_currentlyPreviewingIndex
typo

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +// This is called from the EngineWokerThread and ends with the initial seek v
typo and left over character

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +        if (!active_hotcues.contains(hotCue)) {
Fix the variable naming along the way?

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +    // Note: We do not mess with ply here, we continue playing or previewing.
typo

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +    // CO's are update loadCuesFromTrack()
missing "in" (multiple times)

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +    if (!pCue) {
This was never checked before. Could this ever become a nullptr? If not then use VERIFY_OR_DEBUG_ASSERT.

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.h
> +    void storePreviewingActivateData() {
The name of the function does not tell me what it is actually doing. What is "activate data"?

2020-12-02 22:23 UTC, uklotzde commented on src/engine/controls/cuecontrol.h
> +    QMutex m_trackMutex;
Place the mutex above the member(s) it protects as a delimiter after the unprotected members.

2020-12-02 22:23 UTC, uklotzde commented on src/library/rekordbox/rekordboxfeature.cpp
> +    if (!pCue) {
if (pCue) { update } else { create }

2020-12-02 22:23 UTC, uklotzde commented on src/mixer/basetrackplayer.cpp
>          if (!pLoopCue) {
if (pLoopCue) { update } else { create }

2020-12-02 22:23 UTC, uklotzde commented on src/track/track.cpp
>      QMutexLocker lock(&m_qMutex);
Move the lock down to the point when it is actually needed. We don't need to protect the global system allocator or the Qt connect functions.

2020-12-10 17:59 UTC, Be-ing commented
To clarify, this fixes a regression in the main branch, correct? If so, it's not relevant for 2.3.

2020-12-10 20:59 UTC, daschuer commented
Yes, merge target main is correct.

2020-12-16 11:53 UTC, daschuer commented
Done

2021-01-05 07:47 UTC, daschuer commented
@uklotzde Is this OK now?

2021-01-05 10:57 UTC, uklotzde approved these changes
Sorry for the delay, didn't notice. LGTM

2021-01-05 10:57 UTC, merged