Deere - Enlarge parameter buttons
mixxxdj/mixxx pull request #3469
Opened 2020-12-19 15:39 UTC by abseits

the existing buttons are very small (4pt height),
with 8pt they are much better visible and usable

2020-12-19 15:48 UTC, Holzhaus commented
Can you include before/after Screenshots? That's helpful when reviewing skin changes.

2020-12-19 16:42 UTC, abseits commented
Hi, here are scrennshots woth 4pt buttons and 8 pt buttons.
![classic parameterButtons 4](https://user-images.githubusercontent.com/75733902/102694447-5d346180-4221-11eb-9716-2f60f0addb2f.jpg)
![classic parameterButtons 8](https://user-images.githubusercontent.com/75733902/102694449-602f5200-4221-11eb-95bb-a5f26ade255b.jpg)

2020-12-19 18:17 UTC, uklotzde commented
I like the slim version better.

Does the wide version consume additional vertical space?

2020-12-20 14:58 UTC, abseits commented
No, there is no additional space nedded. Maybe I should explain my intention:
Due to a very bad corneal opacity I have massive problems with the visibility of these buttons,.
Not only the size - the blue on grey contrast is nearly invisible for me and to pick that buttons with the  mouse is really difficult.
My idea is to create a colorscheme for Deere with very high contrast and enlarged effect buttons, but I couldn´t figure out how to enlarge these buttons in my HiCon scheme only without affecting the classic Deere layout. 
I totally agree, the slim version is more elegant, but the wider one is easier to handle.
As a complete newcomer to Git and Github this simple PR was a first lesson for me to find out how this system works.  
The next step will be a PR with colorschemes for Deere including a revival of the charcoal theme.

2020-12-20 15:04 UTC, Be-ing commented
The height of these seems excessively exaggerated to me. How about a compromise size? Maybe 6 px?

2020-12-20 15:55 UTC, abseits commented
YES ! I immediately tried that -perfect.
Here is a screenshot with 6px parameter buttons in classic deere colors and a preview of my high contrast theme for visual impaired users
![classic 6pt parabtn](https://user-images.githubusercontent.com/75733902/102717673-0cd20800-42e4-11eb-96fc-5a3174e08e65.jpg)
![HiCon 6pt parabtn](https://user-images.githubusercontent.com/75733902/102717674-0fccf880-42e4-11eb-88e6-90ee0da44e70.jpg)

2020-12-20 18:57 UTC, poelzi commented
@abseits i will soon finish my waveform color palette branch, that will you allow to choose better waveform color that fit your need :)

2020-12-21 21:12 UTC, ronso0 commented
@abseits 
Probably you applied the "6px" knob template but you uploaded it to the main source directory. It has to got to res/skins/Deere/effect_parameter_knob.xml instead.
Is that where you have the changes locally? If so, you can stage that change locally with `git add -p` , then `git commit --amend` to attach that change to the initial commit b6d3c8a575054df6379071dff67c648adb196975
Then run `git push -f (your-remote-repo) Deere_HiCon` to force-update the changes and overwrite the state we see here.

Also, right now the active link inversion button has a blue border. Do you mind making that red (plus brighter red for hover) and add that as another commit?

2020-12-21 21:13 UTC, ronso0 commented
For a truely improved scheme for visually impaired users we may think about setting the height of the link button in the style sheet.
But we can discuss that in the actual PR later.

2020-12-21 22:23 UTC, ronso0 requested changes

2020-12-21 22:23 UTC, ronso0 commented on effect_parameter_knob.xml
> +<!DOCTYPE template>
this file is in the wrong place.
please apply the changes to res/skins/Deere/effect_parameter_knob.xml which you initially modified.

2021-01-03 23:40 UTC, uklotzde commented
@ronso0 Commit is fixed. Ready to merge?

2021-01-03 23:41 UTC, uklotzde commented
Rebase on 2.3?

2021-01-04 00:25 UTC, ronso0 commented
@abseits had some issues with rebasing as he is new to git. We worked on some in Zulip 1:1

@abseits : I have picked and rebased your commit. I can push it here and we can merge, but for that to work you need to check the box "Allow edits and access to secrets by maintainers" here in this PR page (somewhere at the top right).

2021-01-10 21:34 UTC, ronso0 commented
LGTM
Thanks @abseits for being such a patient learner :)

2021-01-10 21:36 UTC, merged