Save CUE Sheet text as UTF-8
mixxxdj/mixxx pull request #3496
Opened 2020-12-29 10:47 UTC by albertaparicio

About a year ago I noticed that track and artist names with non-Latin characters are rendered as question marks in the CUE files created by Mixxx when recording a set.

I saw a [bug about this](https://bugs.launchpad.net/mixxx/+bug/1856890) in Launchpad, but it did not look as it had much activity.

Two days ago I recorded a set full of Japanese characters, and the result is a total mess, so I gave a go at making Mixxx save CUE files in UTF-8 instead of Latin1.

I have built the code with the patch I am submitting, and the resulting CUE file has been saved in UTF-8 with all names intact.

If you (Mixxx developers) think this patch is suitable for inclusion in Mixxx and will not break anything else, please do merge it. I think many will find it of use.

I am not a C++ developer by any means, I just looked for the code that deals with CUE sheets and edited it.

2020-12-29 10:54 UTC, albertaparicio commented
I see the pre-commit check failed because of code style. However, when I check my code, it is exactly like the one in the `main` branch, with the different function calls

If someone could point me to how can I fix this code style issue I would be grateful

2020-12-29 11:13 UTC, daschuer commented
This log contains a patch you can apply:
https://github.com/mixxxdj/mixxx/commit/6b2d3e5d1319abc3a78c1cf552749ea2ebf90eb3/checks/1621333795/logs

Or follow the red X below.

For a whole branch you can reformat you changes using git-clang-firmat

Like 
```
git clang-format upstream/main
```

For future contribution it is recommended to install the pre-commit hocks. Than the changes are applied locally.

2020-12-29 12:01 UTC, Holzhaus commented on src/engine/sidechain/enginerecord.cpp
> +                            .arg((double)cueFrame, 2, 'f', 0, '0')
If you touch that line anyway, please remove the C-style cast:

```suggestion
                            .arg(static_cast<double>(cueFrame), 2, 'f', 0, '0')
```

2020-12-29 12:12 UTC, ronso0 commented
Thank you for taking care of this old bug @albertaparicio 

This is a bugfix so it should target the latest 'stable' which is soon-to-be-released 2.3
When the review is finished please change the base branch to 2.3 (PR title > Edit) and rebase. Should be easy.

Also, this s your first commit to Mixxx, right?
Please sign the contributor agreement so we can merge this patch:
https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
Thanks!

2020-12-29 12:12 UTC, Holzhaus commented
Should this go into 2.3? I think that would make sense.

2020-12-29 12:15 UTC, albertaparicio commented
No problem, I will change the base branch to 2.3

In my fork I originally applied this patch to `2.3`, but was not sure if it was the appropriate one, so I sent it to `main`. I will change the base branch after review, no problem

I have signed the contributor agreement. I'm glad I can be of help

2020-12-29 13:15 UTC, uklotzde commented
> No problem, I will change the base branch to 2.3
> 
> In my fork I originally applied this patch to `2.3`, but was not sure if it was the appropriate one, so I sent it to `main`. I will change the base branch after review, no problem
> 
> I have signed the contributor agreement. I'm glad I can be of help

Your `2.3` and `main` branches should always track the corresponding upstream branches. Don't add any custom commits to them. For development *branch off* separate *feature branches* from these *tracking branches*.

2020-12-29 13:17 UTC, uklotzde commented
Keep the branch name `main` for the review until the PR has been merged. Then reset those branches as suggested.

2020-12-29 13:22 UTC, uklotzde commented
Please consider to write an [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) at the beginning of the file for disambiguation.

2020-12-29 14:12 UTC, Holzhaus commented
> Please consider to write an [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) at the beginning of the file for disambiguation.
> 
> http://cue.tools/wiki/CUETools#Known_issues
> > Converting the CUE sheet to UTF-8 BOM (byte order mark) will help CUETools identify the encoding.

Unsure. The UTF-8 standard says: "Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use a BOM or where the BOM is used as a UTF-8 signature."

2020-12-29 14:54 UTC, poelzi commented
I always had more problems with BOM then without. Without bom, the file is at least latin-1 compatible for ascii only tracks. Many programs have problems with BOMs

2020-12-29 15:02 UTC, albertaparicio commented
I have prepared the code to add the BOM at the start of the file. 

I have tested it and looking at the Hexdump of the output CUE sheet I see this:

```
0000000 bbef 50bf 5245 [...]
[...]
```
I believe this is what the BOM should look like, right?

If it is correct and it is decided that it is necessary, I will commit the changes

2020-12-29 15:02 UTC, albertaparicio commented
@uklotzde Regarding branches, maybe I did not express correctly what I have done since forking. Let me detail it:

1. I forked the Mixxx repo
2. I checked out the `2.3` branch and made the changes
3. I was not sure if PR-ing to `2.3` was appropriate, so I cherry-picked the commit into `main`
4. I submitted the PR, with a commit at the HEAD of `main`
5. The rest of the commits in this PR are on top of the `main` branch in my forked repo

When the review is over, what should I change with regards of source and target branches?

2020-12-29 15:08 UTC, uklotzde commented
Always prefer to keep the `2.3.` and `main` branches in your forked repo aligned with the upstream repo:

https://github.com/mixxxdj/mixxx/wiki/Using-Git

2020-12-29 15:10 UTC, uklotzde commented
> I have prepared the code to add the BOM at the start of the file.
> 
> I have tested it and looking at the Hexdump of the output CUE sheet I see this:
> 
> ```
> $ hexdump test.cue
> 0000000 bbef 50bf 5245 [...]
> [...]
> ```
> 
> I believe this is what the BOM should look like, right?
> 
> If it is correct and it is decided that it is necessary, I will commit the changes

Only 3 bytes should be prepended.

2020-12-29 15:15 UTC, uklotzde commented
Non-ASCII files could be ambiguous without the BOM.

Please distinguish between arbitrary text files and CUE files. We should follow the recommendations for CUE files.

2020-12-29 15:22 UTC, albertaparicio commented
> > I have prepared the code to add the BOM at the start of the file.
> > I have tested it and looking at the Hexdump of the output CUE sheet I see this:
> > ```
> > $ hexdump test.cue
> > 0000000 bbef 50bf 5245 [...]
> > [...]
> > ```
> > 
> > 
> > I believe this is what the BOM should look like, right?
> > If it is correct and it is decided that it is necessary, I will commit the changes
> 
> Only 3 bytes should be prepended.

The code I have prepared is this:

```c++
     // Write UTF-8 BOM at the start of the file
     unsigned char bom[] = { 0xEF,0xBB,0xBF };
     m_cueFile.write((char*)bom, sizeof(bom));
```

I am writing bytes 0xEF,0xBB,0xBF in the correct order, I think. I think the order of the bytes in the result not matching exactly the intended order is due to being little endian. If we flip around these first 4 bytes we get: `efbb bf50 [...]` like it should be.

If I have done anything wrong, please do tell me

2020-12-30 01:18 UTC, Be-ing commented
Thank you for taking care of this. Are there programs that won't work with a UTF8 cue sheet? If so, maybe we should implement an option in DlgPrefRecording to choose the encoding. I'd prefer to not add an option if it isn't needed though.

2020-12-30 01:27 UTC, Be-ing commented
```
     // Write UTF-8 BOM at the start of the file
     unsigned char bom[] = { 0xEF,0xBB,0xBF };
     m_cueFile.write((char*)bom, sizeof(bom));
```
Please do not use C arrays or C casts. Make a QByteArray and then use QIODevice::write on the QFile.

2020-12-30 09:34 UTC, albertaparicio commented
@Be-ing I have changed the implementation of the BOM to using a QByteArray, as you suggested. I hope it is correct now

Regarding the option in `DlgPrefRecording` I am afraid that falls out of the scope of my knowledge. I am not familiar with neither C++ programming or Mixxx's codebase. If this option is deemed necessary, I can give it a try, but I will need some help.

2020-12-30 10:18 UTC, uklotzde commented
> @Be-ing I have changed the implementation of the BOM to using a QByteArray, as you suggested. I hope it is correct now
> 
> Regarding the option in `DlgPrefRecording` I am afraid that falls out of the scope of my knowledge. I am not familiar with neither C++ programming or Mixxx's codebase. If this option is deemed necessary, I can give it a try, but I will need some help.

Using a temporary QByteArray is not strictly necessary. A reinterpret_cast instead of a C-style cast would be sufficient.

2020-12-30 10:30 UTC, uklotzde commented
The UTF-8 BOM should be defined as a constant in an anonymous namespace:

```
const char* const kUtf8Bom = "\xef\xbb\xbf";
```

You don't need any casts here. This zero-terminated string should work ootb when passed to QIODevice::write().

2020-12-30 10:48 UTC, albertaparicio commented
@uklotzde I implemented your suggestion

2020-12-30 11:18 UTC, uklotzde commented
I though about suggesting a unit test, but the CUE sheet export is burried deep inside `EngineRecord` which makes it difficult to test. Extracting this functionality is a prerequisite for testing. Not possible now.

2020-12-30 11:47 UTC, albertaparicio commented
@uklotzde If we are done with the review, we can look at rebasing branches and such.

As suggested, I have made a feature branch in my fork, rebased onto the upstream's `2.3` branch with the changes I have been making.

I understand it is the recommended way to do it. What would be the best way to proceed forward with this PR?

2020-12-30 11:57 UTC, uklotzde commented
> @uklotzde If we are done with the review, we can look at rebasing branches and such.
> 
> As suggested, I have made a feature branch in my fork, rebased onto the upstream's `2.3` branch with the changes I have been making.
> 
> I understand it is the recommended way to do it. However, I cannot change the source branch of the PR. What would be the best way to proceed forward?

Keep your `main` branch as is until this PR has been merged.

2020-12-30 12:01 UTC, albertaparicio commented
Understood. If I have to do anything else in the future, please do tell me.

2020-12-30 12:19 UTC, uklotzde commented
BOM is written correctly and recognized by other applications.

Depending on the name of `mixxxdj/mixxx` you need to rebase this branch on `2.3`. The following command assumes that the remote upstream repo is named `upstream`:

```
git rebase --onto upstream/2.3 6b2d3e5d1319abc3a78c1cf552749ea2ebf90eb3^
```

This command reapplies your commits on `2.3`. If you already have a local `2.3` branch that tracks the upstream repo then simply omit the `upstream/` prefix. When successful force push your `main` branch.

For future contributions please get familiar with the Git workflows to avoid confusion.

2020-12-30 13:10 UTC, Holzhaus commented
> Depending on the name of `mixxxdj/mixxx` you need to rebase this branch on `2.3`. The following command assumes that the remote upstream repo is named `upstream`:
> 
> ```
> git rebase --onto upstream/2.3 6b2d3e5d1319abc3a78c1cf552749ea2ebf90eb3^
> ```
> 
> This command reapplies your commits on `2.3`. If you already have a local `2.3` branch that tracks the upstream repo then simply omit the `upstream/` prefix. When successful force push your `main` branch.
> 
> For future contributions please get familiar with the Git workflows to avoid confusion.

I like to point users at our wiki instead of explaining it in my own words, not just because I'm lazy but also because maybe contributors read the other topics too and find them helpful.

For reference: https://github.com/mixxxdj/mixxx/wiki/Using%20Git#targeting-another-base-branch

2020-12-30 13:40 UTC, uklotzde commented on src/engine/sidechain/enginerecord.cpp
> +    const char* const kUtf8Bom = "\xef\xbb\xbf";
Please move this definition into an *anonymous namespace* as requested.

2020-12-30 13:45 UTC, uklotzde requested changes
TODO:
- Define constant in anonymous namespace
- Rebase onto and target 2.3

2020-12-30 14:26 UTC, daschuer requested changes
@albertaparicio Sorry for all the forth and back for such an initial simple PR. 

I have just tested the BOM version on  VLC media player 3.0.8 and it fails to use the BOM version. 

It is:
Latin1: OK
Utf8: OK 
Utf8-BOM: Not OK 

This means we should remove the BOM to generate a universal usable *.cue file. 

There is no point in telling the users that 2.3 cues are no longer usable with VLC player and it is the VLC players fault. 

IMHO we can live with 
"Herbert GrÃ¶nemayer" for players which do expect Latin1. The user than decide if a Latin1 file covers all characters and convert the UTF8 file after recording. The other way around is not possible. 

If we receive bug reports about this, it is an evidence that we need an encoding preferences option. I would go without it until then. 

We can even consider to remove the .cue writing checkbox ...

2020-12-30 14:46 UTC, albertaparicio commented
@daschuer I have removed the BOM as you suggested

@uklotzde The `main` branch in my fork is rebased onto `2.3` from my fork and from the upstream repo. I understand that takes care of your request

2020-12-30 17:05 UTC, uklotzde commented
VLC indeed fails to handle the BOM. Nevertheless, this is a bug in VLC. Adding a BOM for UTF-8 CUE sheets is recommended by various authors.

2020-12-30 17:20 UTC, daschuer commented
Probably not the authors of VLC ...

Uft8 without BOM works for all and is lossless. It is hard to argue not to pick this solution and instead use one that has known issues.

2020-12-30 18:00 UTC, daschuer commented
This is the original spec: 
http://web.archive.org/web/20070221154246/http://www.goldenhawk.com/download/cdrwin.pdf

> Cuesheet files are standard text (ASCII) files

This means adding a BOM will violate the standard because the control structure is broken. 
If we add non ASCII characters in between the quotes (payload), it is IMHO OK because the control structure is still valid.

2021-01-01 09:31 UTC, uklotzde commented
CI failure is unrelated. Thank you for your patience ;) This is what reviews are for. LGTM

2021-01-01 09:31 UTC, uklotzde approved these changes

2021-01-01 09:33 UTC, uklotzde requested changes
@albertaparicio We still need to rebase these changes on 2.3!

2021-01-01 10:58 UTC, albertaparicio commented
I have rebased my changes onto `upstream/2.3`. Should I change the target branch of the PR to `2.3` as well?

2021-01-01 11:06 UTC, Holzhaus commented
> I have rebased my changes onto `upstream/2.3`. Should I change the target branch of the PR to `2.3` as well?

Yes please.

2021-01-01 11:09 UTC, albertaparicio commented
Done

2021-01-01 11:43 UTC, uklotzde approved these changes

2021-01-01 11:44 UTC, merged

2021-01-01 16:18 UTC, Be-ing commented
Thank you for making Mixxx more useful for people playing music in different languages. :)

2021-01-02 17:40 UTC, albertaparicio commented
You are welcome. I am glad I could be of some help 😄