Intro/Outro: Add APIs for detecting if we're in intro/outro
mixxxdj/mixxx pull request #3763
Opened 2021-04-03 17:57 UTC by ywwg

This can be used by Sync Lock to inform Implicit Leader.

(synccontrol gets updates per-buffer on play position, and it can figure out when it has crossed an intro/outro border, and notify the sync engine when that happens)

2021-04-03 18:17 UTC, Holzhaus commented on src/engine/controls/cuecontrol.cpp
> +    const double pos = getSampleOfTrack().current;
Please add units to variable names (e. g. `framePosition` or `positionSamples` or something like that)

2021-04-03 18:17 UTC, Holzhaus commented on src/engine/controls/cuecontrol.h
> +    bool inIntro() const;
`isInIntro`?

2021-04-03 18:17 UTC, Holzhaus commented on src/test/cuecontrol_test.cpp
> +    auto* pCueControl = getCueControl();
```suggestion
    const auto* pCueControl = getCueControl();
```

2021-04-03 18:17 UTC, Holzhaus commented on src/test/cuecontrol_test.cpp
> +    auto pIntro = pTrack->createAndAddCue(
```suggestion
    const auto* pIntro = pTrack->createAndAddCue(
```

2021-04-03 20:27 UTC, Be-ing requested changes
I am very doubtful this is a good idea. Sync must be simple to use. If its behavior depends on where in the track the playhead is, that's one extra state the user can get confused about.

2021-04-03 20:38 UTC, ywwg commented
The other PR is at an impasse, I'm not sure how else to resolve the issue.

2021-04-03 20:44 UTC, ywwg commented
I'm not sure we can guess how confusing / intuitive it is until we test it.

2021-04-16 20:49 UTC, poelzi commented
It is usefull for the autodj as well. Proper segmentation will be the ultimate tool, but for the current state I can imagine a bass swap when the into ends.

2021-05-15 14:39 UTC, ywwg commented
any thoughts on this @daschuer ? do we need it?

2021-06-20 13:08 UTC, daschuer commented
Yes, I think we will need it for all sorts of fancy automated transitions. 
I would welcome if you fix the pending comments and than we can merge it.

2021-07-28 17:24 UTC, closed without merging