Replace recursive QMutexes with QRecursiveMutex
mixxxdj/mixxx pull request #3814
Opened 2021-04-28 21:29 UTC by Holzhaus

Recursive QMutexes have been deprecated since the 5.15.

Fixes warnings like these:

    src/vinylcontrol/vinylcontrolprocessor.cpp: In constructor ‘VinylControlProcessor::VinylControlProcessor(QObject*, UserSettingsPointer)’:
    src/vinylcontrol/vinylcontrolprocessor.cpp:28:32: error: ‘QMutex::QMutex(QMutex::RecursionMode)’ is deprecated: Use QRecursiveMutex instead of a recursive QMutex [-Werror=deprecated-declarations]
       28 |           m_bReloadConfig(false) {
          |                                ^
    In file included from /usr/include/qt/QtCore/QMutex:1,
                     from src/vinylcontrol/vinylcontrolprocessor.h:6,
                     from src/vinylcontrol/vinylcontrolprocessor.cpp:1:
    /usr/include/qt/QtCore/qmutex.h:140:14: note: declared here
      140 |     explicit QMutex(RecursionMode mode);
          |              ^~~~~~

2021-04-28 21:40 UTC, uklotzde requested changes

2021-04-28 21:40 UTC, uklotzde commented on src/engine/controls/cuecontrol.cpp
> +          m_mutex() {
No need to explicitly invoke the default constructor. Also applies to `m_pLoadedTrack()` above.

```
#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)
{
#else
, m_mutex(QMutex::Recursive) {
#endif
```

2021-04-28 21:40 UTC, uklotzde commented on src/util/mutex.h
> +    MMutex()
= default;

2021-04-28 21:40 UTC, uklotzde commented on src/vinylcontrol/vinylcontrolprocessor.cpp
> +#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)
Only `QT_VERSION < QT_VERSION_CHECK(5, 14, 0)` is required, no else.

2021-04-30 10:22 UTC, Holzhaus commented
Merge? Currently I need to pull it into every branch I test to be able to build with `-DWARNINGS_FATAL=ON`.

2021-04-30 13:35 UTC, uklotzde approved these changes
Sorry for the delay, busy times. LGTM

2021-04-30 13:35 UTC, merged