Cmake gitinfo without reconfig
mixxxdj/mixxx pull request #3841
Opened 2021-05-07 11:54 UTC by Holzhaus

Based on #3831.

Hopefully replaces #3837 #3822 #3259 #3832.

This should avoid reconfiguration due to git state changes reliably:
- All git info stuff removed from CMakeLists.txt
- Add build time, this always runs a script that configures a file with the git version info as a build job. That file is then included by the source code. This means that the build system can figure out if it needs to rebuild/relink and we don't have any unnecessary rebuilds/reconfigurations.
- For CPack, the git information is retrieved *at CPack time*, not at configuration time. This also ensure that the git info is always up to date.

2021-05-07 15:04 UTC, daschuer commented
I am gad we are getting close, thank you. What a work for this tiny flag, not used for DJ-ing :-/ .. but at least interesting to lean cmake ...

2021-05-07 15:28 UTC, daschuer requested changes
The big solution ... Thank you. 
I have left some comments.

2021-05-07 15:41 UTC, Holzhaus commented on CMakeLists.txt
>    set(MIXXX_FILEVERSION "${CMAKE_PROJECT_VERSION_MAJOR},${CMAKE_PROJECT_VERSION_MINOR},${CMAKE_PROJECT_VERSION_PATCH}")
Why? It's the third component of "2.3.0": https://cmake.org/cmake/help/latest/command/project.html#options

2021-05-07 16:01 UTC, Holzhaus commented
> Uhhh bad ....
> 
> This fails with ninja. Ninja does not recalculate files during build. All files that changes during the build must be added with DEPENDS directives. Some of these do not work for VisualStudio.

I cannot reproduce this, it works fine here:

```
$ ninja
[2/6] Update git version information in gitinfo.h
Git describe: 2.3-beta-3890-g836d68bcce
Git worktree modified: no
Git branch: cmake-gitinfo-without-reconfig
Git commit date: 2021-05-07T17:48:21+02:00
Git commit year: 2021
Git commit count: 8173
$ printf "\n" >> ../res/schema.xml
$ ninja
[2/10] Update git version information in gitinfo.h
Git describe: 2.3-beta-3890-g836d68bcce-modified
Git worktree modified: yes
Git branch: cmake-gitinfo-without-reconfig
Git commit date: 2021-05-07T17:48:21+02:00
Git commit year: 2021
Git commit count: 8173
[10/10] Linking CXX executable mixxx-test
```

2021-05-07 16:13 UTC, Holzhaus commented on src/gitinfo.h.in
> +#cmakedefine GIT_DIRTY
No, this file is also used from `mixxx.rc.include.template` which isn't C/CPP. And I think configuring header files is much cleaner than cpp files. Performance wise I doubt this makes a difference.

2021-05-07 16:13 UTC, Holzhaus commented on CMakeLists.txt
> +  add_dependencies(mixxx mixxx-gitinfo)
> This will speed up recompiling even more?

How so?

2021-05-07 16:14 UTC, Holzhaus commented on packaging/CPackConfig.cmake
> +set(CPACK_DEBIAN_GIT_DESCRIBE "${GIT_DESCRIBE}")
I hopefully fixed it now. But I can't test (no debian system).

2021-05-07 21:56 UTC, daschuer commented
It does not rebuild, mixxx when the git work there becomes dirty due to a file that not triggers a rebuild anyway.

2021-05-07 22:43 UTC, Holzhaus commented
> Ninja does not rebuild, mixxx when the git work there becomes dirty due to a file that not triggers a rebuild anyway.

Cannot reproduce this, works for me:

```
$ ninja
[2/6] Update git version information in gitinfo.h
Git describe: 2.3-beta-3897-ga01f34ec79
Git worktree modified: no
Git branch: cmake-gitinfo-without-reconfig
Git commit date: 2021-05-07T18:15:51+02:00
Git commit year: 2021
Git commit count: 8176
$ printf "\n" >> ../res/controllers/Roland_DJ-505-scripts.js
$ ninja
[2/6] Update git version information in gitinfo.h
Git describe: 2.3-beta-3897-ga01f34ec79-modified
Git worktree modified: yes
Git branch: cmake-gitinfo-without-reconfig
Git commit date: 2021-05-07T18:15:51+02:00
Git commit year: 2021
Git commit count: 8176
[6/6] Linking CXX executable mixxx
$ ninja --version
1.10.2
```

In any case, I think this PR improves the current situation.

2021-05-08 08:32 UTC, daschuer commented
I can no longer confirm the ninja build issues.

2021-05-08 08:53 UTC, daschuer commented on CMakeLists.txt
> +  add_dependencies(mixxx mixxx-gitinfo)
I can take care after merge.

2021-05-08 08:56 UTC, Holzhaus commented
Maybe the worktree was already dirty. In that case, if you change something else, too, it stays dirty and won't recompile unnecessarily.

2021-05-08 09:01 UTC, daschuer approved these changes
Thank you for this effort. It works now.

2021-05-08 09:03 UTC, merged