Try to fix arm test failures Lp1927859
mixxxdj/mixxx pull request #3869
Opened 2021-05-15 23:08 UTC by daschuer

This is the attempt to fix the arm test failures. 
They are probably cause by a div by zero operation using 0.0 rate_ratio. 
In addition this fixes doubtful code around the seek queue. Now the position and the type are stored as a single atomic which guarantees that they will always belong together.

2021-05-16 09:54 UTC, uklotzde requested changes
Thank you, this seems to be the right direction. Some technical comments.

Please mention how you tested the new code. Did you build without -ffast-math? I suggest to temporarily disable fast-math in the CI builds for both vanilla 2.3 and the PR, then compare the results and add the information to this PR. Expected result: Vanilla 2.3 should fail while this PR passes.

2021-05-16 09:54 UTC, uklotzde commented on src/engine/controls/bpmcontrol.cpp
> +    if (dThisRateRatio == 0.0) {
Please move this early return to the earliest point where a decision could be made and avoid calculating values that are not used. This is confusing and suggests that the preceding operations might have intended side effects which is fortunately not the case here.

2021-05-16 09:54 UTC, uklotzde commented on src/engine/enginebuffer.cpp
> +    struct QueuedSeek queuedSeek = {newpos, seekType};
More idiomatic C++:
const auto queuedSeek = QueuedSeek{newpos, seekType};

The temporary only introduces redundant noise, I would prefer:
m_queuedSeek.setValue(QueuedSeek{newpos, seekType});

2021-05-16 09:54 UTC, uklotzde commented on src/engine/enginebuffer.cpp
> +    struct QueuedSeek queuedSeek = m_queuedSeek.getValue();
The extra struct/enum keyword are not needed in C++ (multiple occurrences). Instead better use const here.

2021-05-16 09:54 UTC, uklotzde commented on src/engine/enginebuffer.cpp
> +    queuedSeek = {-1, SEEK_NONE};
This special value probably deserves a constant.

2021-05-16 09:54 UTC, uklotzde commented on src/engine/enginebuffer.cpp
> +    bool isSeekQueued = queuedSeek.seekType != SEEK_NONE;
This temporary obscures the actual control flow and behavior.

2021-05-16 20:48 UTC, daschuer commented
OK, comments are resolved and an issue reverting https://github.com/mixxxdj/mixxx/commit/4fd805d2f265b9cd6e32c2948e446b70b0af5df5 is also fixed. 
I can confirm that the tests are working locally without -ffastmath. 
I don't think that it is necessary to prove it with the CI, because that is unrelated to the original issue, fixing arm builds.

2021-05-16 20:52 UTC, uklotzde approved these changes
~~Any updates on the test results?~~ Ok

2021-05-16 22:48 UTC, uklotzde commented
Thank you very much! LGTM

2021-05-16 22:48 UTC, merged

2021-05-16 23:37 UTC, daschuer commented
I can confirm the issue is solved on Launchpad.
https://launchpadlibrarian.net/539068432/buildlog_ubuntu-bionic-armhf.mixxx_2.3.0~beta1~4000~g3125a4e426-1~bionic_BUILDING.txt.gz
Thank you very much @uklotzde and @geraldog for your help.

2021-05-16 23:44 UTC, geraldog commented
Thanks, @daschuer ! One more step closer to 2.3 release!

2021-05-17 16:59 UTC, uklotzde commented
@daschuer Some merge conflicts with main. You probably know best how to resolve them.