Preview resize
mixxxdj/mixxx pull request #3926
Opened 2021-05-29 20:28 UTC by ywwg

2021-05-29 22:01 UTC, ronso0 requested changes

2021-05-29 22:01 UTC, ronso0 commented on src/skin/skinloader.cpp
>      preview.load(":/images/skin_preview_placeholder.png");
```suggestion
    if (preview.isNull()) {
        preview.load(":/images/skin_preview_placeholder.png");
    }
    preview = preview.scaled(QSize(640, 360), Qt::KeepAspectRatio, Qt::SmoothTransformation);
```
..to include the placeholder.
if we then create all previews with a ratio of 16:9 all options below have a fixed position.

2021-05-29 22:31 UTC, ronso0 commented
we should re-create all skin previews when this is merged. Right now they're blurry already due to odd resizing from minimal skin size to 445 x 250 px.
we can take the new, yet to be made 4k screenshots from the website and scale the down to 1920px
https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/2.2E3.20planning.3A.20https.3A.2F.2Fgithub.2Ecom.2Fmixxxdj.2Fmixxx.2Fprojects.2F2/near/240724451

2021-05-30 02:22 UTC, ywwg commented
Yes I like that idea

2021-05-31 14:22 UTC, ronso0 commented on src/skin/skinloader.cpp
>      preview.load(":/images/skin_preview_placeholder.png");
ping

2021-05-31 15:32 UTC, ywwg commented
good to merge?

2021-05-31 15:40 UTC, ronso0 commented
let's wait for CI..

2021-05-31 16:42 UTC, ronso0 commented
LGTM, thank you!

2021-05-31 17:02 UTC, merged

2021-06-04 01:23 UTC, ronso0 commented
Unfotunately the previews are blurry when Mixxx is scaled uo, even when using integer values.
fixed with #3941