Skins, waveforms: remove I-beam from in/outro markers to equalize marker size
mixxxdj/mixxx pull request #3989
Opened 2021-06-13 15:14 UTC by ronso0

![Screenshot_2021-06-13_17-11-02](https://user-images.githubusercontent.com/5934199/121813073-d067df00-cc6a-11eb-8b98-46b129b4d035.png)
![Screenshot_2021-06-13_17-11-07](https://user-images.githubusercontent.com/5934199/121813075-d1007580-cc6a-11eb-97a4-01ada14ac6e9.png)
![Screenshot_2021-06-13_17-11-13](https://user-images.githubusercontent.com/5934199/121813076-d1007580-cc6a-11eb-92e3-d0757217072e.png)
![Screenshot_2021-06-13_17-11-20](https://user-images.githubusercontent.com/5934199/121813078-d1990c00-cc6a-11eb-9355-0588c959a659.png)

2021-06-13 22:30 UTC, daschuer requested changes
I am afraid this alown is not sufficient. In PaleMoon it works so nice, because the label is also shifted in a way that the position marker takes the role of the I-Beam. Can we do that for all?

2021-06-13 22:46 UTC, ronso0 commented
Sure. But I'll do that only for the in/outro markers -- I assume there were reason to choose the marker positions in Deere and Shade...

2021-06-14 07:36 UTC, daschuer commented
Looks nice now. The windows build error is related. Thank you.

2021-06-14 07:36 UTC, daschuer approved these changes

2021-06-14 07:36 UTC, merged