CueControl: Use mixxx::audio::FramePos internally
mixxxdj/mixxx pull request #4081
Opened 2021-07-07 23:59 UTC by Holzhaus

2021-07-09 09:02 UTC, uklotzde requested changes
That was heavy. Found only one leftover debugging statement.

@daschuer Please double check

2021-07-09 10:54 UTC, Holzhaus commented on src/engine/controls/cuecontrol.cpp
> +    qWarning() << m_pCuePoint->get();
b8e4da11ac9400a9615f37ac29e272ba6aac039d

2021-07-09 10:54 UTC, Holzhaus commented on src/engine/controls/cuecontrol.cpp
> +    const auto cuePoint =
2b559050c95f4b3e7d5c7404459b2d4c2eb563c6

2021-07-09 10:55 UTC, Holzhaus commented
> That was heavy.

Yeah sorry. Maybe I should have migrated the individual methods in separate commits/PRs.

2021-07-09 11:23 UTC, uklotzde approved these changes

2021-07-09 15:21 UTC, daschuer commented
LGTM. 
I think that deserves also a manual tests.
Did you give it a try already? I can test tonight.

2021-07-10 12:17 UTC, uklotzde commented
@daschuer Ping. This is the last pending PR before the final cleanup.

2021-07-11 05:04 UTC, daschuer approved these changes
I did a brief test and everything still works. Thank you.

2021-07-11 05:05 UTC, merged