Fix build issues and more on FreeBSD
mixxxdj/mixxx pull request #4111
Opened 2021-07-17 18:36 UTC by jacardenasm

mixxx was update to 2.3 on FreeBSD but I applied some patches to fix some issues

2021-07-17 18:41 UTC, Be-ing commented
Thanks for this! Can you do an interactive rebase on the 2.3 branch and make the commit messages more descriptive?

Where does the __FREEBSD__ define come from? Our CMake scripts don't define it. Is that always defined when compiling on FreeBSD?

2021-07-17 18:42 UTC, Be-ing commented on src/util/versionstore.cpp
> +    QString base = QStringLiteral("FreeBSD");
extra spaces at the end of the line

2021-07-17 18:45 UTC, Be-ing commented
Maybe we could use `#ifdef __UNIX__` instead to make this more general?

2021-07-17 18:47 UTC, Be-ing commented
Let's use `__BSD__` instead. We already have that set by the build system:
```
elseif(UNIX)
  if(APPLE)
    target_compile_definitions(mixxx-lib PUBLIC __APPLE__)
  else()
    target_compile_definitions(mixxx-lib PUBLIC __UNIX__)
    if(CMAKE_SYSTEM_NAME STREQUAL Linux)
      target_compile_definitions(mixxx-lib PUBLIC __LINUX__)
    elseif(CMAKE_SYSTEM_NAME MATCHES "^.*BSD$")
      target_compile_definitions(mixxx-lib PUBLIC __BSD__)
    endif()
  endif()
endif()
```

2021-07-17 18:53 UTC, Be-ing commented on cmake/modules/FindLibUSB.cmake
> +endif()
I think this should work without any special casing for BSD:
```
  NAMES usb-1.0 usb
```

2021-07-17 21:37 UTC, uklotzde requested changes
The proposed changes have to be applied upstream. We are not going to maintain custom patches for 3rd party libs.

2021-07-17 21:38 UTC, Be-ing commented
@uklotzde I do not understand your comment. This does not change third party dependencies.

2021-07-17 21:39 UTC, Be-ing commented
Oh do you mean the hack for SPSCQue? IIRC upstream already decided they didn't want that so we decided to keep it in Mixxx.

2021-07-17 21:54 UTC, uklotzde commented
I have noticed changes in lib for SPSC and Kaitai Struct. If you need to apply patches for FreeBSD you have to do this during packaging. Otherwise please submit the changes upstream.

The PR is not reviewable until it is properly rebased.

2021-07-17 21:57 UTC, uklotzde commented
If it only modifies a custom patch of us it is acceptable. I didn't verify this.

2021-07-17 21:59 UTC, uklotzde commented
Disclaimer: I am not able to properly review PRs during the next days. I'll try to check occasionally for updates.

2021-07-17 22:27 UTC, Be-ing commented
The change to Kaitai Struct should be sent upstream.

2021-07-17 22:39 UTC, Be-ing commented
I would prefer the patch for Kaitai Struct to stay in the FreeBSD port until that's merged upstream.

2021-07-20 01:02 UTC, Be-ing commented
I redid these changes except the one for the Kaitai Struct file on the 2.3 branch in #4122, #4123, and #4124. Please submit the fix for Kaitai Struct upstream. In the meantime you can keep using that patch in the FreeBSD port. Thanks for bringing these issue to our attention.

2021-07-20 01:02 UTC, closed without merging