Fix version detection in Findhidapi.cmake
mixxxdj/mixxx pull request #4215
Opened 2021-08-17 09:05 UTC by daschuer

The first commit is the bug fix, taken from  #4200, the second commit is for the improved messages.

2021-08-17 12:15 UTC, Be-ing requested changes
This doesn't fix the incorrect #include path which was fixed already in #4200.

2021-08-17 12:38 UTC, Be-ing requested changes
This has a misleading error message in case hidapi is too old:
```
 -- Found hidapi: /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so  
-- Found libhidapi version < 0.10.0
-- Linking internal libhidapi 0.10.1 statically
```
`Found libhidapi version < 0.10.0` is misleading. We require 0.10.1.

2021-08-17 12:40 UTC, Be-ing requested changes

2021-08-17 12:40 UTC, Be-ing commented on CMakeLists.txt
> +    message(STATUS "Linking internal libhidapi 0.10.1 statically")
This is error prone. I do not anticipate that anyone would remember to update this line when updating the vendored library.

2021-08-17 13:34 UTC, daschuer commented
> This doesn't fix the incorrect #include path which was fixed already in #4200.

For my understanding that was a regression by #4300 itself.

2021-08-17 13:35 UTC, Be-ing commented
No, the Mixxx code has been wrong. #4200 fixes it.

2021-08-17 13:43 UTC, daschuer commented
> No, the Mixxx code has been wrong. #4200 fixes it.

Please explain how it has worked since than?

2021-08-17 13:45 UTC, Be-ing commented
It worked because the build system fudged the include paths by treating `/usr/include/hidapi` as the include path. It does not do this for any other library; hidapi should not be an exception.

2021-08-17 14:22 UTC, daschuer commented
OK, all findings are resolved, merge?

2021-08-17 14:36 UTC, Be-ing commented
I don't care which of this or #4200 gets merged. They both do the same thing.

2021-08-17 15:03 UTC, uklotzde commented
I'm slightly in favor of merging #4200, because it is simpler and the error message is comprehensible for me. The special case handling is restricted to Findhidapi.cmake and does not creep into CMakeLists.txt.

2021-08-17 15:10 UTC, daschuer commented
OK, here the full fix as discussed as second option. 
 
Now a it utilizes PC_hidapi_VERSION and falls back reading the header if the PC file is not available. 
The error message is generated using FindPackageHandleStandardArgs() correctly with the default error message. 

In case of Ubuntu Bionic it prints now: 

```
-- Could NOT find hidapi: Found unsuitable version "0.8.0-rc1", but required is at least "0.10.1" (found /usr/lib/x86_64-linux-gnu/libhidapi-libusb.so)
-- Linking internal libhidapi statically
```

2021-08-17 17:43 UTC, Be-ing commented
I was not aware of the VERSION_VAR parameter of FindPackageHandleStandardArgs. That is the best solution.

2021-08-17 17:43 UTC, merged

2021-08-18 06:23 UTC, daschuer commented
@Be-ing: 
We have the policy to use merge commits! 
It looks like you have changed you habit recently. #4172 #4121 #4163 #4058
Please use merge commits in future to not information like the relationship of commit messages to change in the code.