Allow to remove tracks by pressing Delete key
mixxxdj/mixxx pull request #4330
Opened 2021-09-28 00:16 UTC by ninomp

This PR is trying to fix a highly requested feature: ability to delete/remove tracks by pressing Delete key on the keyboard.

I have pointed this to 2.3, feel free to re-point to main if you think this should not go to stable branch.

This fixes:
- https://bugs.launchpad.net/mixxx/+bug/1227676
- https://bugs.launchpad.net/mixxx/+bug/1851457
- https://bugs.launchpad.net/mixxx/+bug/1856402
- https://bugs.launchpad.net/mixxx/+bug/1944565

2021-09-28 00:25 UTC, Be-ing commented
This is a new feature. It should definitely go to the main branch, not the stable branch.

2021-09-28 00:26 UTC, ronso0 commented
: )

2021-09-28 00:27 UTC, ninomp commented
OK I will rebase.

2021-09-28 19:48 UTC, uklotzde requested changes
This seems to be a straightforward and easy extension. Unfortunately, we cannot add it without a command history and undo support.

Situation: You want to quickly start a new search or simply delete the existing search query. Therefore you press *Ctrl+A* followed by *Del*. Unfortunately, you didn't notice that the track table was focused instead of the search edit field. Now your carefully crafted playlist or crate is gone, forever. No chance to restore it if you don't have a database backup.

2021-09-28 20:12 UTC, ronso0 commented
I think a confirm dialog could prevent that, incl. a checkbox `[  ] Remember decision for this session".

2021-09-28 21:07 UTC, foss- commented
Please keep in mind that for macOS laptop keyboards or compact external keyboards there is no del key. `⌘Backspace` is what Apple uses in music app as keyboard shortcut to open the delete dialog.

And yes, a confirmation dialog is a requirement for any delete operation.

2021-10-02 12:13 UTC, ronso0 commented
@uklotzde 
Do you think a warning dialog is sufficient to prevent purging playlists?
Maybe if we don't add the [  ] Remember decision for this session` checkbox?
UX would be
* select tracks
* hit `Del`
* hit `Enter`

I think requiring `Enter` is okay because it wouldn't affect the remove workflow much since `Del` and `Enter` are close on the keyboard.

Besides: how do you imagine the Undo history to be implemented?

2021-10-02 12:36 UTC, ronso0 commented on src/widget/wtracktableview.cpp
> +                pTrackModel->removeTracks(indices);
```suggestion
                const auto plibraryTableModel = static_cast<LibraryTableModel*>(pTrackModel);
                if (plibraryTableModel) {
                    // Hide tracks if this is the main library table
                    // confirmation dialog
                    pTrackModel->hideTracks(indices);
                } else {
                    // Else remove the tracks from playlist/crate
                    // confirmation dialog
                    pTrackModel->removeTracks(indices);
                }
```

2021-10-02 12:36 UTC, ronso0 commented
Idea to extend this feature:
in **Tracks** `Del` would **hide** tracks (incl. the same warning dialog I mentioned above), though I'd appreciate the "Remember decision.." checkbox then because hiding tracks can be reverted.

2021-10-03 00:03 UTC, ronso0 commented
@ninomp Please take a look at a2e53733375ae3d4070071c716b9edf2407f3eeb, that's an easy way to show the shortcut in the menu to make it more discoverable.

2021-10-03 15:43 UTC, ronso0 commented
Also, if we want to avoid merge conflicts I could cherry-pick this commit into #4347 and take care of the dialogs and stuff.

2021-10-04 17:33 UTC, ninomp commented
@ronso0 Sorry for delay. I'll try to finish this PR soon(ish), so it could be merged and then you can continue with your PR. Does this work for you?

2021-10-04 19:15 UTC, ronso0 commented
Sure, I just noticed that now that I have everything sorted out it would be super easy to incorporate your changes into my PR, as well as taking care of the dialogs.
But if you're still motivated and have time to finish it soonish I won't interfere further, except reviewing, of course ; )

2021-10-07 12:02 UTC, ronso0 requested changes

2021-10-09 22:02 UTC, uklotzde commented
For safety we need at least a confirmation dialog that allows to disable subsequent confirmations for the current session.

2021-10-10 08:37 UTC, uklotzde commented
> > For safety we need at least a confirmation dialog that allows to disable subsequent confirmations for the current session.
> 
> I think a simple confirmation dialog suffices. An option to disable subsequent confirmations may be added later on if deemed necessary.

Then a simple message box instead of a custom dialog would be sufficient. I thought about this, too. Ok, then let's start with this minimum solution.

2021-10-18 11:19 UTC, uklotzde requested changes

2021-10-18 11:30 UTC, ronso0 requested changes

2021-10-19 16:20 UTC, ninomp commented
This is ready.

2021-10-19 18:55 UTC, ronso0 approved these changes

2021-10-19 20:32 UTC, ronso0 commented
Squash into one commit to keep the git history clean?

2021-10-19 21:31 UTC, uklotzde requested changes

2021-10-19 22:10 UTC, ninomp commented
This is again ready.

2021-10-20 22:57 UTC, uklotzde approved these changes
Thank you! LGTM

2021-10-20 22:58 UTC, merged

2021-12-23 00:48 UTC, ninomp commented
@foss- Could you test #4577 to check whether it solves the minor issue on macOS you reported?