Beatloop: add control to start beatloop while keeping start point.
mixxxdj/mixxx pull request #4491
Opened 2021-10-29 15:34 UTC by quirxmode

Current controller scripts have no option to enable a beatloop without simultaneously setting the loop-in point to the current playback position. This PR adds a control to start a beatloop, keeping a previously set loop-in position. This is especially useful for implementing a more accurate mapping of controllers like the DDJ-400. A long-press of the loop-in button emits another midi signal which is intended for setting up an instant 4-beat loop.

2021-10-29 15:48 UTC, Be-ing requested changes
I do not think we should add this. The existing `beatloop_activate` ControlObject should be changed instead. This is implemented in #4328.

2021-10-30 08:59 UTC, quirxmode commented
I don't want to be a pest, but `reloop_toggle` checks whether the loop-out point is set, and if it is not, it does nothing.
On the DDJ-400, the workflow is
- When pressing loop-in, the loop-in point is set
- while holding the button, after 1 second, the controller emits another midi message, upon which a 4-beat-loop is enabled. The loop-in point is perserved.

I do not see any way to implement this behavior currently.
If you have a vision how the engine could provide this functionality I can provide a PR that implements it. Granted my current solution might not be than elegant.

2021-10-30 09:41 UTC, Be-ing commented
That may be able to be implemented already in JS with a hack setting `loop_out` a calculated offset from `loop_in`... but why? What benefit does that add? Copying other DJ software exactly is not a design goal of Mixxx. I strongly discourage relying on long presses in controller mappings because it is really easy to accidentally do the wrong action in a time-sensitive context while also paying attention to manipulating other controls.

2021-10-30 09:50 UTC, Be-ing commented
Looking at the [documentation for the DDJ-400 mapping](https://manual.mixxx.org/2.3/en/hardware/controllers/pioneer_ddj_400.html#deck-sections-p-6), it is already possible to set a 4 beat loop by adjusting beatloop_size and pressing the `ACTIVATE LOOP` button... so what is the need for this new ControlObject? How would it be better than the existing mapping?

2021-10-30 09:52 UTC, Be-ing commented on src/engine/controls/loopingcontrol.cpp
> +            [=](double value){slotBeatLoop(value, true);}, Qt::DirectConnection);
This should use the value of `beatloop_size`, not this new ControlObject.

2021-10-30 09:52 UTC, Be-ing commented on src/engine/controls/loopingcontrol.cpp
> +    m_pCOBeatLoopKeepLoopIn = new ControlObject(ConfigKey(group, "beatloop_keep_loopin"), false);
```suggestion
    m_pCOBeatLoopKeepLoopIn = new ControlPushButton(ConfigKey(group, "beatloop_keep_loopin"), false);
```

2021-10-31 18:36 UTC, ronso0 commented
one aspect to consider for mappings:
if longpress of `IN/4BEAT` should indeed always set a 4-beat loop (and not use the deck's individual beatloop size), the longpress duration should be adjusted so that it's shorter than 4 beats for a reasonable BPM range.
otherwise longpress is registered _after_ 4 beats have passed and when the playhead then jumps back to loop_in it'll likely be off beat.

2021-11-01 20:11 UTC, quirxmode commented
>the longpress duration should be adjusted

Maybe there is a misunderstanding - the longpress emits another midi message. It is not something done in the mapping via javascript.
The longpress-duration is hardcoded in the DDJ-400's firmware. It is ~1 second so that should be short enough for anything up to 240bpm. I am pretty sure Pioneer engineers thought of that when they chose the delay to be 1s.

2021-11-01 22:22 UTC, daschuer commented on src/engine/controls/loopingcontrol.cpp
> +    m_pCOBeatLoopKeepLoopIn = new ControlPushButton(ConfigKey(group, "beatloop_keep_loopin"));
```suggestion
    m_pCOBeatLoopKeepLoopIn = new ControlPushButton(ConfigKey(group, "beatloop_keep_loop_in"));
```
To match the "loop_in" control.

2021-11-01 22:33 UTC, daschuer commented
I wonder if this can become the default behavior of "beatloop_activate"

In case a user sets the loop_in position and presses "beatloop_activate" before the possible loop_out point (loop_in + beatloop size) has passed, it feels quite natural. What else could be expected than. 
At least ignoring the just set loop_in feels wrong in this case.   

Once the loop_in is out of sight and activating a beat loop at loop_in will jump back, the current behavior with the loop in at the current play position feels correct.

2021-11-02 21:17 UTC, ronso0 commented
> > the longpress duration should be adjusted
> 
> Maybe there is a misunderstanding - the longpress emits another midi message. It is not something done in the mapping via javascript. The longpress-duration is hardcoded in the DDJ-400's firmware. It is ~1 second so that should be short enough for anything up to 240bpm. I am pretty sure Pioneer engineers thought of that when they chose the delay to be 1s.

Thanks for the explanation and doing the math for me : )

2021-11-02 21:42 UTC, ronso0 commented
> I wonder if this can become the default behavior of "beatloop_activate"
> 
> In case a user sets the loop_in position and presses "beatloop_activate" before the possible loop_out point (loop_in + beatloop size) has passed, it feels quite natural. What else could be expected than. At least ignoring the just set loop_in feels wrong in this case.
> 
> Once the loop_in is out of sight and activating a beat loop at loop_in will jump back, the current behavior with the loop in at the current play position feels correct.

I agree.
For maximum transparency/predictability the following UX tweaks come to mind, though they might be overkill:
(cumbersome to implement, and with a small potential for confusion)
* set `loop_in`
* = for preview an **inactive** loop is set from `loop_in` + `beatloop_size`
* `beatloop_activate` would simply enable that loop
* manually setting `loop_out` would work, too
* once the play positions passed the proposed `loop_out` without the loop being activated, the preview loop would be removed (unset `loop_out`)

2021-11-02 22:15 UTC, daschuer commented
I have just played with it and if we make the preview a real disabled loop, it surprisingly works well. A disabled loop is a kind of preview anyway. 

We have no other way to drop a loop during playback, without immediately enabling it. This would work than as well. 

I think we should use for the long press reloop_toggle, because it never sets a new loop in, which is undesired here, in case you are too late.

2021-11-03 02:12 UTC, Be-ing commented
I'm still not getting the point of this new ControlObject nor the other ideas proposed.

> We have no other way to drop a loop during playback, without immediately enabling it.

Can you elaborate why that is useful?

2021-11-03 10:24 UTC, daschuer commented
You hear a nice section suitable for a beat loop during a later transition. 

Currently you can drop a hot cue while playing.
When you like to enable the loop later you can recall the hot cue and press immediately bratloop_enabled. By luck the loop_in is placed near the hot cue. 

With the proposed feature you can just drop the loop in, adjust the loop size via the beatloop size box and enable the loop later. I don't know away to achieve this currently.

2021-11-03 12:57 UTC, Be-ing commented
Thank you for explaining that. I don't think there is a way to do that currently. Creating a loop while the track is playing without enabling it is not something I've ever thought that I wanted, but that makes sense how it could be useful. However, that's tangential to this PR. I still do not understand how the proposed code changes would be beneficial.

2021-11-03 13:02 UTC, Holzhaus commented
There is a way to do that already: https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[ChannelN]-hotcue_X_gotoandloop

2021-11-03 13:03 UTC, Holzhaus commented
This is used for the CUE LOOP mode implemented by the Roland DJ-505 mapping.

2021-11-09 21:36 UTC, daschuer commented
What is the way forward here. Do we agree that the solution outlined by @ronso0 and me is a good way forward? 
* loop-In sets a disabled beat loop 
* The second midi telegram of DDJ-400 can than be mapped to reloop_toggle

This enables the feature instantly for all, because loop-in and reloop is available on many controllers and in all skins. 
I don't think that this will interfere with any other workflow. 

@quirxmode does this solve your original issue as well? 

If we can commit to that here, do you have interest to create it as a new PR? It should be not too complex.

2021-11-10 10:27 UTC, ronso0 commented
> I don't think that this will interfere with any other workflow.

The only situation I can imagine is
* have an very high beatloop size, e.g. 128
* set loop_in
* forget about it :raised_eyebrow: 
* later, when the loop_in is out of sight, hit `beatloop_activate`
* surprise!

Showing the loop immediately when pressing loop_in would avoid the surprise.

2021-11-10 10:57 UTC, daschuer commented
That's why I have proposed to keep `beatloop_activate` unchanged.
This should still always creat a beatloop at the play position.

The new feature shall use loop_in + reloop_toggle

2021-11-10 11:48 UTC, ronso0 commented
okay, I missed that when reading

> * loop-In sets a disabled beat loop
> * The second midi telegram of DDJ-400 can than be mapped to reloop_toggle

and leave `beatloop_activate` unchanged.

:+1:

2021-11-10 14:56 UTC, Be-ing commented
> The new feature shall use loop_in + reloop_toggle

`loop_in` and `reloop_toggle` already exist so I'm unclear what you are suggesting.

I do not agree that this MIDI message that the DDJ 400 sends with a long press needs to be mapped. This new idea to create a new loop without immediately enabling it is interesting and could be done in a different PR after closing this.

2021-11-10 15:02 UTC, Be-ing commented
Do you mean that you propose that `loop_in` creates a disabled loop with a size taken from `beatloop_size`? I don't think `loop_in` and `loop_out` should use `beatloop_size`; their purpose is for manually setting loop boundaries.

2021-11-10 15:07 UTC, daschuer commented
Yes that the proposal. The original use-case for setting the loop boundaries is not affected in any ways.

2021-11-10 15:39 UTC, Be-ing commented
> The original use-case for setting the loop boundaries is not affected in any ways.

This isn't entirely accurate because there would be a deactivated loop shown on the waveforms which could be surprising and confusing. However this might be an acceptable tradeoff. I think it would need to implemented and tested to judge that.

2021-11-11 20:13 UTC, quirxmode commented
Controllers might require a different API than what the UI needs. The current loop controls are very much tailored towards mapping to buttons in the UI. The "problem" with controllers like the DDJ-400 is that they do things that users normally do not, such as splitting the actions of setting the loop-in point, beatloop size and beatloop activation into two discrete ones that happen at different times.
It should be possible to provide an API that is flexible enough for both without breaking either. If there is a better PR I will gladly test it.

2025-03-12 21:09 UTC, acolombier commented
Hey @quirxmode , I will make this PR a draft as it seems there is still a little bit of work to get this feature ready. Feel free to mark it ready again if you get a chance to complete or close it in case you have lost interest in getting this over the finish line

2025-03-12 22:56 UTC, quirxmode commented
We can close this.

2025-03-12 22:56 UTC, closed without merging