Tango: style Quick Effect selector
mixxxdj/mixxx pull request #4503
Opened 2021-11-06 21:43 UTC by ronso0

based on #4501

![image](https://user-images.githubusercontent.com/5934199/140624698-15295507-1194-472c-86eb-e2c4fee80702.png)

2021-11-07 02:01 UTC, daschuer requested changes
Please rebase this to main. Without a rebase we see rebased commits from the already merged PRs twice in the history.

2021-11-07 02:01 UTC, daschuer commented
The rest looks good.

2021-11-07 11:38 UTC, ronso0 commented
> Please rebase this to main. Without a rebase we see rebased commits from the already merged PRs twice in the history.

That's how I planned to do it.
I wonder why the log doesn't have duplicate commits after merging the LateNight fx PR.

2021-11-07 13:11 UTC, Be-ing requested changes
The removal of the border and making the background identical to the surroundings makes it hard to tell that the comboboxes are comboboxes.

2021-11-07 13:12 UTC, daschuer commented
> I wonder why the log doesn't have duplicate commits after merging the LateNight fx PR.

These commits where identical, inclusive their history. Here they are almost identical, with a different commit hash.

2021-11-07 13:12 UTC, daschuer approved these changes

2021-11-07 13:23 UTC, Be-ing commented on res/skins/Tango/style.qss
> +      color: #aaa;
Please revert this.

2021-11-07 16:14 UTC, Swiftb0y commented
IMO its still visible that the effect name is a clickable combobox because of the "down-arrowhead" next to the name. 
Removing the border to remove visual clutter makes sense here.

2021-11-07 16:21 UTC, Holzhaus commented
> The removal of the border and making the background identical to the surroundings makes it hard to tell that the comboboxes are comboboxes. This PR is a step backwards IMO. Can you explain why you think these changes are an improvement?

I think it mainly saves screen space that would otherwise be used by margins/pasding/borders. I'm also torn on this, because I think it space-efficient and looks good, but on the other hand it's less easy to discover. Maybe we can consider adding borders and reducing font size instead.

2021-11-07 16:24 UTC, Swiftb0y commented
If we talk about discoverability, I think thats fine too. It's not an essential feature that you need to see understand and instantly (like the playbutton for example). Its not like its deeply buried in menus (unless we hide it using a skin or preference option, which is not good idea IMO).

2021-11-07 16:59 UTC, Be-ing commented
I agree that it isn't crucial that this is super easy to discover and even with this change it isn't too hard to discover, but still, this makes it harder to discover and I don't think there was a problem with the styling before.

2021-11-07 18:44 UTC, Swiftb0y commented
I guess its a personal taste call, and I prefer this. Should we decide via a quick poll?

2021-11-07 18:46 UTC, Be-ing commented
I would like to hear @ronso0's motivation for this change before jumping to a vote.

2021-11-07 19:06 UTC, ronso0 commented
My motivation for this plain effect selector
* with borders it's the inner padding + border + margin to the EQs and bottom container border would make the entire mixer 'much' taller and the decks would grow unnecessarily -- especially in Tango which is meant to be as compact as possible
* it has the same drop-down arrow indicating a combobox as the effect selector, the AutoDJ mode selector and the search box, as well as a hover effect, thus I consider it discoverable
* I do not expect the majority of users to change this frequently, if at all, thus styling it more like an informative label makes much more sense than adding the visual clutter of a fully decorated combobox

2021-11-14 00:03 UTC, Be-ing requested changes
There is less room for text with this branch. Here is main:
![image](https://user-images.githubusercontent.com/9455094/141662537-d8adbc3e-0bf4-4b1a-a68b-b2994b94306b.png)

This branch:
![image](https://user-images.githubusercontent.com/9455094/141662546-cada9a3d-01ea-4e0e-8d20-6533f62d44af.png)

2021-11-14 12:30 UTC, ronso0 commented
The previous implementation was quick and dirty and always added extra row to the deck.
It was okay for testing but I'm not going to premanently change the layout that much just to have a large quick effect selector.

Though, I can try to squeeze out a few more pixels for the selector.

2021-11-20 00:19 UTC, ronso0 commented
![image](https://user-images.githubusercontent.com/5934199/142706397-885ec855-d0ae-4540-bc16-56972543ab7d.png)

Note: the screenshot was made with #4532

2021-11-20 00:22 UTC, ronso0 commented
marked as draft because it looks like I broke the fx units. I'll remove the extra tweaks and add the chain preset button styling asap.

2021-11-20 00:24 UTC, Be-ing commented
I wouldn't be opposed to that last screenshot, though I still prefer how it is currently in the main branch.

2021-11-30 00:40 UTC, ronso0 commented
![image](https://user-images.githubusercontent.com/5934199/143964791-d500f56d-7118-44e7-b1ef-9baef8a6b48c.png)

Ready.

2021-11-30 00:43 UTC, ronso0 commented
In another PR I'll make the fx unit menu more discoverable (WEffectChainPresetButton), the arrow was just a quick shot, too. I used the gear icon (skin settings) for that in LateNight and it makes more sense than the down arrow.

2021-12-01 10:22 UTC, Swiftb0y commented
Why did you put the PFL button the same height as the dropdown? Wouldn't it make more sense to make the vumeter shorter to put the pfl button horizontally aligned with the filter and gain knob so there is more space for the text in dropdown?

2021-12-02 23:45 UTC, ronso0 commented
Yes, that would look better for that one configuration.
But it has some consequences and requires more elaborate changes to keep the skin consistent (trying to keep my initial design intact).
* channel VUs are aligned with the main VU (shrink the main VU, too?)
* with EQ knobs hidden the Vol slider and VU should expand to available height. The VU pixmap are designed pixel-perfect so we'd need two VU meters per deck? Or have one version center vertically?

Tbh I'm not motivated to work on that right now. The Deere implementation is still overdue, LateNight still needs the chain menu button...

2021-12-02 23:46 UTC, ronso0 commented
That said, I'd like to merge this now and me or anyone else may propose improvements later on.

2021-12-03 09:28 UTC, Swiftb0y commented
Thanks for the explanation. Sure we can merge.

2021-12-03 10:40 UTC, ronso0 commented
@Be-ing already agreed to the new implementationearlier so I don't think we need to wait for his formal approval.

2021-12-03 11:36 UTC, Swiftb0y commented
He also recently announced to abstain from contributing to mixxx for the foreseeable future, I don't think he'll care to review/approve this PR because of that.

2021-12-10 23:59 UTC, ronso0 commented
_pa-ping..._

2021-12-11 01:59 UTC, Holzhaus commented
Alright, shall we merge then?

2021-12-11 11:02 UTC, Swiftb0y approved these changes
Thanks :+1:

2021-12-11 11:02 UTC, merged