Improve documentation comments
mixxxdj/mixxx pull request #4530
Opened 2021-11-18 09:51 UTC by xeruf

Please don't create an epic fuss and let conflicts pile up. These changes were done while I worked on the Macros feature and capture insights and code quality improvements that would have to be done either way at some point.

2021-11-22 00:00 UTC, Holzhaus requested changes
Thanks, the doxygen-style comments are definitely useful. I left some comments.

2021-11-23 15:10 UTC, xeruf commented on src/track/track.h
> -    // Get sample rate
It being about the _number_ of channels is only deductible from seeing the signature or the docs
But I can of course also adjust it.

2021-11-23 15:11 UTC, xeruf commented on src/recording/recordingmanagerbase.cpp
> +void RecordingManagerBase::slotSetRecording(bool record) {
Right, recently I was advised to prefer squashing so I didn't bother

2021-11-23 15:11 UTC, Holzhaus commented on src/track/track.h
> -    // Get sample rate
Ah right, that makes sense.

2021-11-23 15:13 UTC, xeruf commented on src/track/track.cpp
> +void Track::analysisFinished() {
The benefit is the grouping of related methods and sometimes ordering alignment to the header file, making it much easier to find your way around a file.

2021-11-23 15:15 UTC, xeruf commented on src/track/track.h
> -    // Returns the bitrate as a string
I would expect "320", if that is not so it should be documented yeah.

2022-01-01 23:07 UTC, Holzhaus commented on src/recording/recordingmanagerbase.cpp
> +void RecordingManagerBase::slotSetRecording(bool record) {
I don't know who said that but squashing/amending only makes sense for commits working on the same topic, not unrelated commits. We do prefer squashing for stuff like controller mappings where people have a bunch of commits with useless commit messages like "update mapping", but not in other cases.

2024-05-26 21:44 UTC, ronso0 commented
Stale since 2022, many conflicts, **xeruf** vanished after GSoC, closing this.

2024-05-26 21:44 UTC, closed without merging