WTrackMenu: Add ability to select loaded track in library
mixxxdj/mixxx pull request #4688
Opened 2022-02-27 01:42 UTC by ninomp

2022-02-27 19:58 UTC, daschuer commented
Nice. Thank you.

2022-03-03 13:17 UTC, Russe commented
This is a very nice feature, thank you.
I tested this PR with Utbuntu and it works like a charm.

One questions, do you think it's also possible to mark or highlight (not select) loaded tracks automatically in library?
This could be an additional feature.

2022-03-06 17:51 UTC, uklotzde approved these changes
One minor nitpick, otherwise fine.

2022-03-06 17:51 UTC, uklotzde commented on src/widget/wtracktableview.h
> +    void slotSelectTrack(const TrackId& trackId) {
Please move the implementation into the .cpp file. I suggest to define only trivial, single-line functions inline.

2022-03-16 07:46 UTC, daschuer commented
Thank you for the feature. It works OK. 
Can you also scroll to the selected track if it is already selected. 
It would be also nice, if the current would be selected in case you have searched a similar track. 
The feature dos not work in case AutoDJ is selected. In this case the cover art is shown regardless of the track in in the AutoDJ List or not.
My expectation was that this feature works for the currently selected library table. Helpfull to see the current track in the context of the others in a crate or library.

2022-03-16 07:49 UTC, daschuer requested changes

2022-03-16 07:49 UTC, daschuer commented on src/widget/wtracktableview.cpp
> +    setCurrentTrackId(trackId);
I think here is a check missing if the track is in that Table at all.

2022-04-24 08:44 UTC, ronso0 commented
@ninomp Please reword the last two commits to provide meaningful messages, rebase onto the commit before [b80c7b3](https://github.com/mixxxdj/mixxx/pull/4688/commits/b80c7b3354c1cfdffce294230a97108807a5dc7f) and force-push (no one has reviewed them so far so it should be okay)

2022-04-24 13:24 UTC, ronso0 commented
> @ninomp Please reword the last two commits to provide meaningful messages, rebase onto the commit before [b80c7b3](https://github.com/mixxxdj/mixxx/pull/4688/commits/b80c7b3354c1cfdffce294230a97108807a5dc7f) and force-push (no one has reviewed them so far so it should be okay)

Sorry I didn't notice those were merges from main. Why didn't you use the usual `merge upstream/main`?

2022-05-02 10:43 UTC, ronso0 requested changes

2022-05-02 10:43 UTC, ronso0 commented on src/widget/wtrackproperty.cpp
> +        WTrackMenu::Feature::SelectInLibrary;
This also needs to be added to WTrackWidgetGroup, used for the track color bar in the decks

2022-05-02 10:43 UTC, ronso0 commented on src/widget/wtracktableview.cpp
> +    setSelectedTracks({trackId});
```suggestion
    if (setCurrentTrackId(trackId, 0, true)) {
        setSelectedTracks({trackId});
    }
```

2022-05-02 11:25 UTC, ronso0 requested changes

2022-05-02 11:25 UTC, ronso0 commented on src/library/library.cpp
> +    connect(this, &Library::selectTrack, pTrackTableView, &WTrackTableView::slotSelectTrack);
for readability, please break this line like the surrounding connections.

2022-05-02 23:48 UTC, ronso0 commented
re @daschuer's observation
> The feature dos not work in case AutoDJ is selected. In this case the cover art is shown regardless of the track in in the AutoDJ List or not.

This happens when clicking _any_ sidebar root item (feature root), except Tracks and History.
With those, the table model is simply not "shown" when the view is selected, so the `selectTrack` request goes to the previously selected WTrackTableView. Btw that also clears the previous track selection there :|

@ninomp
Since I messed with the library a few times already I was curious and took a look.
For features where the root view has a track view (AutoDJ, Analyze, Recording), I managed to fix it by adding `emit showTrackModel( [trackModel] );` to `[Feature]::activate`. If you mind that approach take a look at 8cfd397773
For other root views _without_ a tracks table (Crates, Playlists, Browse, some external libraries?), no idea..

Maybe the `selectTrack` signal should rather be connected in `Library::addFeature`, and then each feature needs a `slotSelectTrack` slot? Maybe also make use of `WLibrary::getActiveView()`, or add `bool `WLibrary::isCurrentViewTracksTable()`? Possible, if features store the WLibrary pointer in `feature::bindLibraryWidget`.
https://github.com/mixxxdj/mixxx/blob/6f8676073e1689a1cc749a701d909570d0cafb0e/src/widget/wlibrary.cpp#L91-L93

Sorry, I'm aware this may be overwhelming since your current minimal approach is actually beautifully simple and seemed to work fine, too.

one more thing... :grimacing: 
I'd actually expect the "Select track" action to be greyed out if the current library view is not a WTrackTableView, though it is probably complete overkill to make the decks' track menu aware of the tracks table (if possible at all).

2022-05-16 04:55 UTC, daschuer commented
https://github.com/mixxxdj/mixxx/pull/4740 has been merged, so this can be closed. @ninomp Thank you for starting this nice feature.

2022-05-16 04:55 UTC, closed without merging