Spinback fix
mixxxdj/mixxx pull request #4708
Opened 2022-03-29 21:30 UTC by ronso0

2022-03-29 21:31 UTC, ronso0 commented
still draft because I'd like to keep the debug output 87c23c210004d531f8c425bd27de59248f2e8af6 until review is finished.

2022-03-30 10:48 UTC, ronso0 commented
Also: merging this to `main` requires manual editing since there are conflicts with renamed and moved files ( + clang-format, no actual behaviour or syntax changes).
Please ping me before merging so I can make sure I have time to merge to main !!

2022-03-30 22:01 UTC, daschuer reviewed
Some more comments. I hope I will find time for a manual test soon.

2022-03-30 22:29 UTC, ronso0 commented
> Some more comments. I hope I will find time for a manual test soon.

I am testing with the GUI and a MIDI Through mapping that uses callbacks of toggles on deck 2:
https://gist.github.com/ronso0/70bc239c14c1de491dbb87dc303a789f
Eject = init brake
Repeat = init spinback
Slip mode = init softstart

2022-03-30 22:36 UTC, ronso0 commented
Thanks, I pushed th small fixes.

2022-04-03 19:50 UTC, daschuer commented
I have tested it and I think it works like desired. 
So I think it is ready to polish for merge. 

I must admit hat I have never used the backspin effect before and I think it is implemented unnaturally. 
My expectation was that it sound like pushing a vinyl backward with a sharp acceleration an a spin down phase afterwards. Something like demonstrated here: https://www.youtube.com/watch?v=dzEJoSkwvnI at 0:20 
Is this a topic of this PR?

2022-04-03 20:38 UTC, ronso0 commented
Exactly, that's how a backspin is supposed to sound like.
I am sure it was initially implemented like this (I simply doubt someone would implement it in such a weird way as it is now), so I suspect something broke since then, but I didn't figure out _when_ with a quick git search.

Actually I think some of the debug output is quite helpful, so I'll remove some of it and put the helpful part behind #ifdef SCRATCH_DEBUG 
Okay?

2022-04-03 20:39 UTC, ronso0 commented
Thanks for testing btw, appreciated!

2022-04-04 05:21 UTC, daschuer commented
Yes OK, thank you.

2022-04-04 05:23 UTC, daschuer commented
I will file a bug for the implementation issue. Maybe we find a GSoC contributor taking care with @ywwg.

2022-04-04 05:32 UTC, daschuer commented
https://bugs.launchpad.net/mixxx/+bug/1967715

2022-04-05 22:40 UTC, ronso0 commented
Last commit disables the debug output in real-time code.
Ready for merge.

2022-04-06 06:43 UTC, daschuer requested changes

2022-04-06 06:43 UTC, daschuer commented on src/controllers/controllerengine.cpp
> +    qDebug() << ".";
Her is a leftover

2022-04-06 08:04 UTC, ronso0 commented on src/controllers/controllerengine.cpp
> +    qDebug() << ".";
whoops, fixed.

2022-04-06 09:31 UTC, daschuer approved these changes
Thank you. LGTM

2022-04-06 09:32 UTC, merged