MacOs warnigs fix
mixxxdj/mixxx pull request #4732
Opened 2022-04-23 11:22 UTC by daschuer

This fixes some warnings that are shown when building for MacOS. See commit messages.

2022-04-26 16:51 UTC, uklotzde requested changes

2022-04-26 20:22 UTC, daschuer commented on lib/libshout-idjc/src/shout.c
> +                    if (strncasecmp(upgrade, "Content-Length: ", 16) == 0)
Upstream has already fixed this. They are on Version 2.4.4, but we are sucked with 2.4.1.

2022-04-26 20:27 UTC, daschuer commented
Done.

2022-04-27 09:41 UTC, uklotzde approved these changes
Changes seem reasonable. Thank you! LGTM

2022-04-27 09:41 UTC, merged