CHANGELOG: Add a raw version with all PRs towards Mixxx 2.4
mixxxdj/mixxx pull request #4840
Opened 2022-07-05 06:03 UTC by daschuer

This is an important step towards the long overdue 2.4 release. We have already integrated ~800 PRs .. Thank you all for this hard work. 

The rendered Changelog looks like this: 
https://github.com/daschuer/mixxx/blob/9cfe9e4d0f8eacafc4c82be87a352e48c3ad167b/CHANGELOG.md

I like to keep this full list as a commit for later reference, documenting our next meld down step. 
So please have a look. 

The next step would be cut out a 2.4 branch. I am still very much in favor or a 6 month release cycle to stop wining about a view very last PRs that should become part of a certain release and than delay all the other 800 by another six month or such.  

Let's now also collect PRs that should still go to 2.4 at the 2.4 Milestone:
https://github.com/mixxxdj/mixxx/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.4.0

2022-07-05 07:30 UTC, ronso0 commented on CHANGELOG.md
> +* Track Properties: Show 'date added' as local time [#4838](https://github.com/mixxxdj/mixxx/pull/4838) [lp:1980658](https://bugs.launchpad.net/mixxx/+bug/1980658)
this went into 2.3

2022-07-05 07:35 UTC, ronso0 commented
+ Implement Un-eject to reload the previous track [4868](https://github.com/mixxxdj/mixxx/pull/4668)

2022-07-05 07:38 UTC, ronso0 commented on CHANGELOG.md
> +* Pot support for arbitrary maximums in 7-/14-bit handlers from controller scripts[#4495](https://github.com/mixxxdj/mixxx/pull/4495)
```suggestion
* add support to Potmeters to  handler arbitrary maximums in 7-/14-bit from controller scripts [#4495](https://github.com/mixxxdj/mixxx/pull/4495)
```

2022-07-05 07:40 UTC, ronso0 commented on CHANGELOG.md
> +* Shade: Fix library sidebar splitter glitch [#4828](https://github.com/mixxxdj/mixxx/pull/4828) [lp:1979823](https://bugs.launchpad.net/mixxx/+bug/1979823)
this was backported to 2.3.4 #4808

2022-07-05 07:44 UTC, ronso0 commented on CHANGELOG.md
> +* Waveform: Avoid visual glitch with ranges < 1 px [#4804](https://github.com/mixxxdj/mixxx/pull/4804)
went into 2.3.4

2022-07-05 08:02 UTC, ronso0 commented on CHANGELOG.md
> +* LateNight: add effect chain menu button [#4593](https://github.com/mixxxdj/mixxx/pull/4593)
```suggestion
* add new Quick Effect selector and effect chain buttons [#4501](https://github.com/mixxxdj/mixxx/pull/4501) [#4502](https://github.com/mixxxdj/mixxx/pull/4502) [#4503](https://github.com/mixxxdj/mixxx/pull/4503) [#4590](https://github.com/mixxxdj/mixxx/pull/4590)  [#4593](https://github.com/mixxxdj/mixxx/pull/4593)
```

2022-07-05 08:03 UTC, ronso0 commented on CHANGELOG.md
> +  [#4833](https://github.com/mixxxdj/mixxx/pull/4833) [lp:1980078](https://bugs.launchpad.net/mixxx/+bug/1980078)
indentation here & above

2022-07-06 05:59 UTC, daschuer commented on CHANGELOG.md
> +  [#4771](https://github.com/mixxxdj/mixxx/pull/4771)
I am unclear what is the issue here. Is it solved already?

2022-07-06 06:01 UTC, daschuer commented
I have moved all 2.3.4 changes to https://github.com/mixxxdj/mixxx/pull/4842

2022-07-18 16:51 UTC, daschuer commented
This is now rebased on top of current main including the unrelease 2.3.4 changelog.

2022-07-19 05:14 UTC, daschuer commented
@ronso0 this should now also be up to date.

2022-07-20 21:18 UTC, ronso0 commented on CHANGELOG.md
> +* Add a track context menu for looking up track metadata at Discogs, Soundcoud an LastFM [#4772](https://github.com/mixxxdj/mixxx/pull/4772) [#4836](https://github.com/mixxxdj/mixxx/pull/4836)
```suggestion
* Add a track context menu for looking up track metadata at Discogs, Soundcoud and LastFM [#4772](https://github.com/mixxxdj/mixxx/pull/4772) [#4836](https://github.com/mixxxdj/mixxx/pull/4836)
```

2022-07-20 21:25 UTC, ronso0 commented on CHANGELOG.md
> +  [#4771](https://github.com/mixxxdj/mixxx/pull/4771)
I guess it doesn't matter, just noticed it

2022-08-03 22:50 UTC, daschuer commented
Anyone else want that want to take a look?

2022-08-04 09:42 UTC, ronso0 requested changes
Thank you for doing this tedious job!

Some typos and other minor remarks.
Note I only checked Changelog.md, someone else may do the final check that meatinfo.xml matches

2022-08-04 09:42 UTC, ronso0 commented on CHANGELOG.md
> +* Add a track context menu for looking up track metadata at Discogs, Soundcoud and LastFM [#4772](https://github.com/mixxxdj/mixxx/pull/4772) [#4836](https://github.com/mixxxdj/mixxx/pull/4836)
```suggestion
* Track Menu: Add action to select loaded track in library [#4740](https://github.com/mixxxdj/mixxx/pull/4740)
* Track Menu: Add menu for Analyze and Reanlyze [#4806](https://github.com/mixxxdj/mixxx/pull/4806)
* Track Menu: Add menu for looking up track metadata at Discogs, Soundcoud and LastFM [#4772](https://github.com/mixxxdj/mixxx/pull/4772) [#4836](https://github.com/mixxxdj/mixxx/pull/4836)
```

2022-08-04 09:42 UTC, ronso0 commented on CHANGELOG.md
> +  [#4589](https://github.com/mixxxdj/mixxx/pull/4589)
#4589 shouldn't this be in the **Audio Engine** category?

2022-08-04 09:42 UTC, ronso0 commented on CHANGELOG.md
> +* Allow to reset loops via "[ChannelN], loop_remove" control object [#4802](https://github.com/mixxxdj/mixxx/pull/4802) [lp:1978507](https://bugs.launchpad.net/mixxx/+bug/1978507)
This should go to below the other **Track Menu** entries, though just to improve discoverability?
Or we add it twice: the track menu action to **Library** and the control here?

2022-08-04 09:42 UTC, ronso0 commented on CHANGELOG.md
> +* Fix crashe when using midi.sendShortMsg and platform vnc [#4635](https://github.com/mixxxdj/mixxx/pull/4635)
```suggestion
* Fix crash when using `midi.sendShortMsg` and platform vnc [#4635](https://github.com/mixxxdj/mixxx/pull/4635)
```

2022-08-04 09:42 UTC, ronso0 commented on CHANGELOG.md
> +* Fix crash when starting without a valid skin directory [#4575](https://github.com/mixxxdj/mixxx/pull/4575) [1934560](https://bugs.launchpad.net/mixxx/+bug/1934560)
```suggestion
* Fix crash when starting without a valid skin directory [#4575](https://github.com/mixxxdj/mixxx/pull/4575) [lp:1934560](https://bugs.launchpad.net/mixxx/+bug/1934560)
```

2022-08-04 09:48 UTC, ronso0 requested changes
entries that need to be moved to **2.4**

2022-08-04 09:48 UTC, ronso0 commented on CHANGELOG.md
> +* Fix exporting m3u files with tracks and special characters by using the URL format [#4752](https://github.com/mixxxdj/mixxx/pull/4752)
how did this end up in the 2.1.6 changelog? : )

2022-08-04 09:48 UTC, ronso0 commented on CHANGELOG.md
> +* ID3v2 parsing: Improve log warnings [#4610](https://github.com/mixxxdj/mixxx/pull/4610)
also move to **2.4**

2022-08-04 12:23 UTC, Swiftb0y commented
> Note I only checked Changelog.md, someone else may do the final check that meatinfo.xml matches

Not necessary IMO. The metainfo.xml is generated automatically from the changelog.

2022-08-04 22:04 UTC, daschuer commented
Done

2022-08-04 22:20 UTC, ronso0 commented
There are some issues left
https://github.com/mixxxdj/mixxx/pull/4840#pullrequestreview-1061560881

2022-08-05 09:25 UTC, ronso0 commented
Thank you :tada:

2022-08-05 09:26 UTC, ronso0 approved these changes

2022-08-05 09:26 UTC, merged

2022-08-05 12:15 UTC, daschuer commented
Thank you very much for your thoughtful review!