Fix reset of bpm and key when (re-)importing track metadata
mixxxdj/mixxx pull request #4875
Opened 2022-08-02 21:11 UTC by uklotzde

Resetting the bpm and key didn't work at all because of some special case handling for these fields. The comments in the code explain the reasoning when resetting those fields is desired.

Could be tested by setting `[Library] SyncTrackMetadataExport 1` in `mixxx.cfg` manually. The default behavior should be unaffected.

2022-08-02 23:15 UTC, Swiftb0y approved these changes
lgtm. :shrug:

2022-08-03 09:01 UTC, daschuer requested changes
Normally purchased files do not have BPM, Key and Replaygain set. 

So without exporting the Mixxx medadate to the file enabled, these fields are always empty.

The original use case: 
https://mixxx.discourse.group/t/cannot-update-blank-tag-in-mixxx/25348 
Is to remove the "composer" tag from all files using a third Party tool and reimport the File tags.

The user can now set the hidden Prefernces option and Mass-Import all files.

Results: All Beat Grid / Key and Replaygain infos are deleted as well. 
In case of Beat Grid he may have luck and have locked the value before. 

My guess is that this is not desired. 

Do you have an idea how to improve the situation?

2022-08-03 09:46 UTC, uklotzde commented on src/track/track.cpp
> +        if (!m_pBeats ||
No value is better than a wrong value.

2022-08-03 09:48 UTC, uklotzde commented
The current behavior is inconsistent. Deleting those tags will render the file out of sync with the database. That's undesired.

Btw, replay gain is reset as expected. Why not bpm and key? How about all other non-string fields? Were to start and were to stop with the exceptions? Users will expect that resetting works consistently for all fields.

2022-08-03 09:56 UTC, uklotzde commented on src/track/track.cpp
> +        if (!m_pBeats ||
When file tags are synchronized the bpm values will match. The internal value is not affected by a re-import unless a user has intentionally deleted or modified the file tag.

**case b**: Resetting the internal bpm if it differs by a certain amount (e.g. >= 0.5 bpm) from the imported value would be another option. Again, no value is better than a wrong value.

2022-08-03 13:16 UTC, daschuer commented
> When file tags are synchronized the bpm values will match.

In that case the outline approach will work. Unfortunately this is not the default. 
I don't see the use case that a user deletes the exported BPM value form the track files. Do you? 
If not, this case is IMHO not relevant here.

The relevant case for me is that a user manages the metadata in a third party tool and Bulk Re-Imports the changes to Mixxx from time to time. 

In that case I can imagine users expect that deleted textual fields like "composer" or especially "comments" are also deleted, but they I don't want that the beat grid is destroyed or it is required to reanalyse key and ReplayGain. 

I think the question that distinguishes these data if they are mandatory for Mixxx or not.  
* BPM / Key / Replaygain are required and when they were deleted, features are also missing. 
* Artist and Title, it is also kind of mandatory, here Mixxx uses the info from the file name when empty.

Oher values are normally empty, more like decoration that is available or not. Here it is expected that they are empty. 

Proposal: 
* Get rid of the hidden parameter and use the outlined behaviour as default 

Will this work for all? 
If not, we may introduce an exposed config option, or a case by case checkbox. 

I think we should also ask the original reporter ... 

What do you think? 

Another topic are explicit empty values.
I can imagine that in some tools are able to set values explicit to empty. 
Mixxx does it, right?  Not sure if it is feasible for regular users to deal with it.
If so we may configure to Import explicit emty values as empty, but not import missing values.     

What do you think.

2022-08-03 14:10 UTC, uklotzde commented
Then I prefer to maintain those patches in a private fork. If anyone is willing to come up with a whole new concept than please do so.

2022-08-03 14:10 UTC, closed without merging

2022-08-03 15:20 UTC, Swiftb0y commented
I don't understand the problem here. Does mixxx keep the info in the DB synced with the File tags?

2022-08-03 16:23 UTC, daschuer commented
It is an opt in feature to write the metadata to the file. Mixxx does not read the file tags again after the initial import. 

When the feature is enabled the issue is actually minor. 

When the option is kept on default, There is a high risk that the user loosed all analysis during a mass re-import of the file tags. That 

The original use-case and requested feature was that a user has cleared the "composer" tag in a third party tool and expect to see it cleared in Mixxx after re-import. 
Uwe introduced a hidden feature for this. 

In main we have now the inconsistency that the BPM is showed cleared, but it is kept. This PR actually clears the BPM, instead of fix the visual issue. 

The proposed solution is outlined above with a couple of questions we need to clarify.

2022-08-03 16:32 UTC, uklotzde commented
> It is an opt in feature to write the metadata to the file. Mixxx does not read the file tags again after the initial import.

That's incorrect. Opt-ing in to synchronization is now bidirectional, i.e. metadata is implicitly re-imported from file tags if the file has been modified according to the time stamp. This affects all newly imported or re-imported files.

2022-08-03 16:38 UTC, uklotzde commented
> In main we have now the inconsistency that the BPM is showed cleared, but it is kept. This PR actually clears the BPM, instead of fix the visual issue.

Both the original bpm and key are preserved both in the database and visually without this PR on re-import. Unlike all other metadata including the replay gain. This is inconsistent.

2022-08-03 16:42 UTC, uklotzde commented
Inconsistencies should be fixed first before introducing more new features on top of a new (and still hidden) feature.

2022-08-03 17:16 UTC, Swiftb0y commented
Right. So I see two options here: Either we enable the bidirectional metadata synchronization by default now or we merge this PR and put a disclaimer in the manual that a re-import of metadata will clear everything thats not present in the file tags (including everything that depends on it, such as the beatgrid) and the user has to be aware of that. IMO everything else is just a hack that will make the import/export behavior of mixxx seem even less predictable (due to the inconsistencies).

2022-08-03 17:46 UTC, uklotzde commented
> Right. So I see two options here: Either we enable the bidirectional metadata synchronization

Why? Manually re-importing metadata is independent of the synchronization setting and works as expected and as before.

2022-08-03 19:08 UTC, daschuer commented
> Starting with a consistent behavior that only contains the bare minimum of special case handling is the way to go.

It does not make sense to start a new PR for a feature without clarify the requirements and use cases. The discussion is required before dive into more code. 

So let's move the discussion away from abstract "inconsistency" to real use-case and requirements we have. 

Can you have a look to my questions and ideas above? 

My hope is that we find a way of operation that works for all, without a preference option. 

What are your use-case?

2022-08-03 21:18 UTC, Swiftb0y commented
> Why? Manually re-importing metadata is independent of the synchronization setting and works as expected and as before.

Well, IIUC the point @daschuer is trying to make is that if a track has a BPM set in mixxx but not in the filetags, then simply re-importing the track would wipe the bpm in mixxx (with this PR and the overwrite behavior enabled). So if we export the BPM to the file tags beforehand, a re-import would avoid clearing the bpm in mixxx. 
So the synchronization would work around the problematic behavior this PR would introduce.

2022-08-03 21:27 UTC, uklotzde commented
I prefer to leave all future metadata improvements to someone else.

2022-08-03 21:36 UTC, Swiftb0y commented
Mhmm. I would've tried to adopt the branch if you didn't delete it...

2022-08-03 22:45 UTC, uklotzde commented
I am tired and exhausted of these derailing discussions.

2022-08-03 23:25 UTC, Holzhaus commented
> Mhmm. I would've tried to adopt the branch if you didn't delete it...

It's just a single commit. You can append `.patch` to the URL to get a patch that can be applied using `git am`:

```sh
$ curl -OL https://github.com/mixxxdj/mixxx/commit/15414f502e39ac3f0831c325481d8abe581af668.patch
$ git am < 15414f502e39ac3f0831c325481d8abe581af668.patch
```