cautils&fileinfo: compBaseName add for cart update
mixxxdj/mixxx pull request #4909
Opened 2022-08-22 10:37 UTC by fatihemreyildiz

This PR aims to solve this bug mentioned on [Launchpad](https://bugs.launchpad.net/mixxx/+bug/1985843).

This simply fixes to wrong cover art update if the names has more than one "." dot. I
track.1.mp3
track.2.mp3
track.3.mp3
track.4.jpg
track.5.jpg
 
If track.1-track.2-track.3's cover arts updated via "Reload from file/folder" it updates it with track.4.jpg. 

With this change, it looks for the complete full name, so track.1.mp3 won't be updated with track.4.jpg. 

But with that change, this can change the old behavior, if the files named as;
track.1.mp3.jpg
track.1.mp3
updating wouldn't not update the cover art, to not change the behavior of old updating, there is an another block added. If complete full name is not working, this will look for file name of the track `"track.1.mp3"` and complete name of the cover art `"track.1.mp3".jpg`

2022-08-22 13:24 UTC, daschuer commented
Thank you. This looks like a bug fix for 2.3.

2022-08-22 13:29 UTC, fatihemreyildiz commented
Yes, that is happening in 2.3 :+1:

2022-08-22 13:44 UTC, daschuer requested changes
One missing line.

Can you rebase this on 2.3 than. Thank you.

2022-08-22 13:44 UTC, daschuer commented on src/library/coverartutils.cpp
> +                bestInfo = &file;
```suggestion
                bestType = TRACK_BASENAME;
                bestInfo = &file;
```

2022-08-22 14:03 UTC, fatihemreyildiz commented on src/library/coverartutils.cpp
> +                bestInfo = &file;
I've added the missing line.

2022-08-22 14:40 UTC, daschuer approved these changes
LGTM

2022-08-22 14:40 UTC, daschuer commented
Does anyone else want to have a look?

2022-08-23 17:31 UTC, daschuer commented
Thank you!

2022-08-23 17:31 UTC, merged

2022-08-23 20:19 UTC, daschuer commented
Ups, this is now broken in the 2.3 branch: https://github.com/mixxxdj/mixxx/runs/7979410003
I did not realize that the CI was still testing the main merge after changing the merge target. 
I will push a fix directly to 2.3

2022-08-23 20:33 UTC, daschuer commented
https://github.com/mixxxdj/mixxx/commit/517d7a64a51d439be309f6fcbcd73cce4820075e

2022-08-23 21:16 UTC, fatihemreyildiz commented
Thank you for taking care. 

I guess the file `trackfile.h` in 2.3 branch, changed to `fileinfo.h` in main branch right? I was trying to fix it and added the completeBaseName in `file.h` in main branch and while re-basing to 2.3 there was no `fileinfo.h` so I deleted completeBaseName, and compiled successfully. 

I just didn't get it why it failed. I hope I didn't do something missing-wrong.