Refactor MixxxMainWindow.
mixxxdj/mixxx pull request #941
Opened 2016-05-04 21:18 UTC by rryan

NOTE: This is a work in progress. I'll be rebasing this as I go until
it's ready for review. I'm looking for early feedback on the approach.

Splits MixxxMainWindow into two pieces: Core and WMainWindow.

This will allow us to iterate on new frontends that do not make use of
QtWidgets / QtGui (such as an Android or iOS port) and generally
enforces a cleaner separation between Mixxx services (provided by
individual manager classes) and the Mixxx UI.

This is also a step towards refactoring the bootup process (which
prompted us to add a loading" launch screen because it's so
slow). With a cleaner concept of "phases" of bootup (construction,
initialize, configure, finalize, destruction) we can start the UI
after construction/initialization and delay the longer tasks
(e.g. connecting audio devices and controllers) or push them onto a
different thread.

Ideally all manager classes and Core will remain buildable with the
QtWidgets module disabled.

2016-05-05 01:47 UTC, rryan commented
This is step 2 (step 1 was WMainMenuBar) on a long-term refactor journey for me. I wrote down some of the goals in this design doc:
http://mixxx.org/wiki/doku.php/mixxx_init_refactor

2016-05-05 19:05 UTC, daschuer commented
I have just read the linked document and I like the underlying ideas. The multi-threading approach will help to utilize the n-cores of recent CPUs. 

However, I think it is not a good idea to present the GUI before Mixxx is ready to used. 
This is one of the annoyances (old) Windows compared to Linux, Windows predicts to be ready, but you cannot use it util the HDD has stopped seeking. 

An other general thought is: Multitheading increased the complexity significant. If you aim to reduce the complexity this might be a bad deal. But we will see, when it comes to the implementation.

2016-05-05 19:09 UTC, daschuer commented on src/main.cpp
> +    {
// scope for core

2016-05-05 19:10 UTC, daschuer commented on src/main.cpp
> +        {
// scope forWMainWindow

2016-05-05 19:23 UTC, daschuer commented on src/library/autodj/autodjfeature.cpp
> +        this, m_pConfig, pPlayerManager, m_iAutoDJPlaylistId, m_pTrackCollection);
indent

2016-05-05 19:27 UTC, daschuer commented on src/widget/wmainwindow.cpp
> +            "default skin cannot be loaded see <b>mixxx</b> trace for more information.");
indent

2016-05-05 19:44 UTC, daschuer commented
OK, I assume there where nothing changed in the business logic, only moving functions around, right?  I have only added some minor nits. 

The other main issue is the release schedule. We have already published a release date for Mixxx 2.1
for February 2016. The current master version contains a lot of improvements worth a soon release without any further additions. So we should brake out a 2.1 branch and announce the beta phase now. 

( _The alpha seams to be blocked by the broken windows build server though 
@Pegasus-RPG: how is your progress? 
I have played with https://www.appveyor.com/ , will it be an alternative?_  )

These planed refactorings will not have a user impact, but have some degree of regression risk. 
So the should go to a master. The same is true for the GSOC projects.

2016-05-06 17:28 UTC, rryan commented on src/library/autodj/autodjfeature.cpp
> +        this, m_pConfig, pPlayerManager, m_iAutoDJPlaylistId, m_pTrackCollection);
Fixed
/me can't wait until we use clang-format so we can stop wasting time on this.

2016-05-06 17:28 UTC, rryan commented on src/widget/wmainwindow.cpp
> +            "default skin cannot be loaded see <b>mixxx</b> trace for more information.");
Fixed

2016-05-06 17:28 UTC, rryan commented on src/main.cpp
> +        {
done

2016-05-06 17:28 UTC, rryan commented on src/main.cpp
> +    {
Done -- though this seems a bit obvious, no?

2016-05-06 17:29 UTC, rryan commented
> OK, I assume there where nothing changed in the business logic, only moving functions around, right? I have only added some minor nits.

Yep, that's right.

2016-05-06 18:06 UTC, rryan commented
> The other main issue is the release schedule. We have already published a release date for Mixxx 2.1
> for February 2016. The current master version contains a lot of improvements worth a soon release without any further additions. So we should brake out a 2.1 branch and announce the beta phase now.

I agree this shouldn't go in 2.1.

2017-12-27 22:38 UTC, Be-ing commented
@rryan are you interested in picking this up again? Now would be the time to do it. Our startup time has gotten really bad.

2018-04-18 04:07 UTC, Be-ing commented
This pull request has not been updated in years so I am closing it to reduce the clutter of open PRs. If you solve the merge conflicts and would like to have it merged in the future, please reopen it. However, considering how many merge conflicts there are, it may be easier to start over from the current master branch.

2018-04-18 04:11 UTC, rryan commented
> @rryan are you interested in picking this up again? Now would be the time to do it. Our startup time has gotten really bad.

Yea, I am. I'll re-open when/if I get to it though.

2018-09-17 22:28 UTC, rryan commented
Re-based against master, tests are passing on macOS and no shared_ptr leaks occur.

2018-09-17 22:31 UTC, Be-ing commented
Thanks for picking up work on this again!

2018-09-18 00:08 UTC, Be-ing commented
I think there will be a few small merge conflicts between this and #1705, but it looks like they will be easy to resolve.

2018-10-02 03:29 UTC, rryan commented
> I think there will be a few small merge conflicts between this and #1705, but it looks like they will be easy to resolve.

Yea, I tried to make this minimally invasive w.r.t. any changes made to the effects system or library.

2018-10-08 02:40 UTC, Be-ing requested changes
Thanks for starting to clean this up!

2018-10-08 02:40 UTC, Be-ing commented on src/main.cpp
> +            WMainWindow window(app, core);
This introduces a regression. No GUI is shown for about 3 seconds, then when the main window is first shown, the loading progress bar is already over half way.

2018-11-21 00:13 UTC, Be-ing commented on src/main.cpp
> +            WMainWindow window(app, core);
Ping. I propose moving the construction of services in the CoreServices class from the constructor to a new method that would get called by WMainWindow. Then have CoreServices emit a signal after each service is started that triggers a progress bar update in WMainWindow.

2018-11-21 00:14 UTC, Be-ing commented
I would like to merge this relatively soon before more merge conflicts develop.

2018-12-27 23:32 UTC, Be-ing commented
@rryan will you have time to continue this soon? If not I might pick it up.

2018-12-28 22:02 UTC, rryan commented
> @rryan will you have time to continue this soon? If not I might pick it up.

Yea, it's on my list after #926.

2020-12-15 15:31 UTC, Be-ing commented
Superceeded by #3446

2020-12-15 15:31 UTC, closed without merging